### ISSUE TITLE
Editorial badges do not support dark mode

### ISSUE THREAD

**Issue by cemms1** [guardian/dotcom-rendering#10021]
Example article https://www.theguardian.com/world/2024/jan/02/tuesday-briefing-red-sea-crisis-middle-east-conflict?dcr=apps where the editorial badge for the First Edition series (https://assets.guim.co.uk/images/badges/4df269f6581a038e125c11a320e886d2/newsletter-badge.svg) does not look right in dark mode.

_Desktop viewports:_
|  Dark  |  Light |
| ------ | ------ |
| <img width="357" alt="image" src="https://github.com/guardian/dotcom-rendering/assets/43961396/5e557d77-9dbf-4ad9-bbbe-ab3cf994e766"> | <img width="344" alt="Screenshot 2024-01-02 at 11 13 24" src="https://github.com/guardian/dotcom-rendering/assets/43961396/f5c5a50f-3d9f-4284-82ab-f589e134333f"> |

_Mobile viewports:_
|  Dark  |  Light |
| ------ | ------ |
| <img width="656" alt="Screenshot 2024-01-02 at 11 11 27" src="https://github.com/guardian/dotcom-rendering/assets/43961396/8ddd4d4b-146b-4a11-8a9b-bcebc678fc3f"> | <img width="658" alt="image" src="https://github.com/guardian/dotcom-rendering/assets/43961396/c7884726-6861-4471-9d2c-148c2e7b4d44"> |

**Comment by paperboyo** [comment]
FWIW, once I got annoyed by pixelisation on that one, so created this SVG hoping it could replace the PNG. Was told it’s used in 120 places, so not a small job. But if ever one would want to make it dark mode-compatible, maybe it will be of some use?
https://uploads.guim.co.uk/2023/11/02/Newsletters_titlepiece.svg

**Comment by JamieB-gu** [comment]
We should hide these from apps articles until a) they have support for dark mode, or b) we decide to deprecate badges altogether.

**Comment by georgeblahblah** [comment]
Closing in favour of #10254
