### ISSUE TITLE
Release DCR Lightbox to PROD

### ISSUE THREAD

**Issue by mxdvl** [guardian/dotcom-rendering#10102]
Let’s release Lightbox with a gradual rollout, as per the original plan.

```[tasklist]
### Rollout
- [ ] https://github.com/guardian/dotcom-rendering/pull/10090
- [ ] guardian/frontend#26799
- [ ] https://github.com/guardian/dotcom-rendering/issues/10328
```

**Comment by shesah** [comment]
Waiting on D&I for CWV data and any core metrics

**Comment by JamieB-gu** [comment]
The PROD release is done 🥳, @mxdvl to move remaining tasks onto a "post-PROD" epic.
