### ISSUE TITLE
DCAR: iPad ads are not in the correct position

### ISSUE THREAD

**Issue by abeddow91** [guardian/dotcom-rendering#10105]
When lightbox got accidentally released to apps, it was reported that ads on ipads were not in the correct position and were being positioned off screen. 

We suspect this is fixed by the lightbox change being reverted but we should double check this.

Previously, this was easily, consistently replicable on a simulator so we should be able to test it is now fixed in the same environment.
```[tasklist]
### Tasks
- [ ] Ads not centred on android - could be related? - screenshot below
```

![Image](https://github.com/guardian/dotcom-rendering/assets/1229808/bdcae029-3dd6-4c76-85f6-83036ce6eff4)

**Comment by abeddow91** [comment]
Following the lightbox fix, the ads are now appearing in the correct positions on tablet.

**Comment by alinaboghiu** [comment]
Session booked for Mon 12th

**Comment by JamieB-gu** [comment]
We're working with Commercial Dev to solve this, and starting by giving them an introduction to working with DCAR within the native app.

**Comment by JamieB-gu** [comment]
Commercial Dev are doing this.
