### ISSUE TITLE
Running storybook locally produces warnings `Unexpected usage of "storyName" in "{Story Name}". Please use "name" instead.`

### ISSUE THREAD

**Issue by georgeblahblah** [guardian/dotcom-rendering#10202]
Running DCR's `make storybook-dev` produces warnings in the format:  `Unexpected usage of "storyName" in "{Story Name}". Please use "name" instead.`

Look into whether these need fixing or supressing.

**Comment by domlander** [comment]
These warnings are no longer being produced
