### ISSUE TITLE
[Bug]: `@guardian/identity-auth` peer dependency mismatch

### ISSUE THREAD

**Issue by mxdvl** [guardian/dotcom-rendering#10205]
### What happened?

There are a number of peer dependency mismatches in DCR for `@guardian/identity-auth` & `@guardian/identity-auth-frontend`.

```sh
# …
├─┬ @guardian/identity-auth 1.1.0
│ ├── ✕ unmet peer @guardian/libs@^15.0.0: found 16.0.0
│ └── ✕ unmet peer typescript@~5.1.3: found 5.3.3
└─┬ @guardian/identity-auth-frontend 1.0.0
  ├── ✕ unmet peer @guardian/libs@^15.0.0: found 16.0.0
  └── ✕ unmet peer typescript@~5.1.3: found 5.3.3
# …
```

> [!TIP]
> You can check this yourself by running `pnpm install --resolution-only`

@guardian/identity please could you update this package to use versions that are compatible with this repo?

### What is the impact?

This will soon become a blocker as we want to enforce met peer dependencies in this repo

**Comment by coldlink** [comment]
Commercial: https://github.com/guardian/commercial/pull/1236
Frontend: https://github.com/guardian/frontend/pull/26855
DCR: https://github.com/guardian/dotcom-rendering/pull/10402

**Comment by coldlink** [comment]
Have upgraded and merged them in!
