### ISSUE TITLE
[Bug]: `@guardian/commercial` peer dependency mismatch

### ISSUE THREAD

**Issue by mxdvl** [guardian/dotcom-rendering#10204]
### What happened?

There are a number of peer dependency mismatches in DCR for `@guardian/commercial`. Excerpt from `pnpm i --resolution-only`:

```sh
# …
├─┬ @guardian/commercial 11.32.1
│ ├── ✕ unmet peer @guardian/libs@^15.6.4: found 16.0.0
│ ├── ✕ unmet peer @guardian/source-foundations@^13.0.0: found 14.1.2
│ ├── ✕ unmet peer @guardian/ab-core@^5.0.0: found 7.0.1
│ ├── ✕ unmet peer @guardian/core-web-vitals@^5.1.0: found 6.0.0
│ └─┬ prebid.js 8.24.0
│   └─┬ @guardian/libs 15.7.1
│     └── ✕ unmet peer typescript@~5.1.3: found 5.3.3
# …
```

> [!TIP]
> You can check this yourself by running `pnpm install --resolution-only`

@guardian/commercial-dev please could you update this package to use versions that are compatible with this repo?

### What is the impact?

This will soon become a blocker as we want to enforce met peer dependencies in this repo

**Comment by Jakeii** [comment]
Noted, will get this sorted out!

**Comment by i-hardy** [comment]
We'll be tackling the prebid dependency separately; the others should be fixed by https://github.com/guardian/frontend/pull/26819 and https://github.com/guardian/dotcom-rendering/pull/10243
