### ISSUE TITLE
Light Background For Interactive Atoms In Dark Mode

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#10212]
We may want to use a light background for interactive atoms in dark mode, similar to what was done for chart atoms in #9976.

We should also see if we can surface the platform to the interactive atom, so developers can apply dark mode styles only on apps.

## Example

https://www.theguardian.com/us-news/2024/jan/12/us-elections-2024-calendar-key-events

![dark-mode-interactive-atom](https://github.com/guardian/dotcom-rendering/assets/53781962/80723ebb-5b61-4f2e-bde5-f138aada4d40)

**Comment by mxdvl** [comment]
🏳️

**Comment by georgeblahblah** [comment]
I think adding a blanket white background across all interactive atoms could cause problems for atoms which target dark mode correctly.

**Comment by JamieB-gu** [comment]
> I think adding a blanket white background across all interactive atoms could cause problems for atoms which target dark mode correctly.

I think this may be ok if it's what the templates do? Any interactive atom that does support dark mode should already be expecting a light background to work from?
