### ISSUE TITLE
No duplicated state in `FirstCommentWelcome`

### ISSUE THREAD

**Issue by mxdvl** [guardian/dotcom-rendering#10224]
Lift all duplicated state and callbacks from `FirstCommentWelcome`:

https://github.com/guardian/dotcom-rendering/blob/6b1c27d42c6019a7423c75fa322d6fce794da23d/dotcom-rendering/src/components/Discussion/FirstCommentWelcome.tsx#L63-L64

**Comment by georgeblahblah** [comment]
I think `userName` does not need to be lifted! It's very local to this component.
