### ISSUE TITLE
`fixed/medium/slow-VII` Stretching Images

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#10237]
This container may stretch the images of cards in the second row when not enough cards are present to fill the container.

Should be visible in the last two cards when 5 cards are present rather than the required 7.

Possibly related to #8885.

**Comment by JamieB-gu** [comment]
It's proving difficult to replicate this. CP are going to attempt to create it on a test front.

**Comment by alinaboghiu** [comment]
@JamieB-gu to hand over to @georgeblahblah

**Comment by paperboyo** [comment]
Well, this is a long-standing issue: we request images sized for the expected number of stories. Ideally we would be always requesting them at the size they are used (nevermind if the assumption about number of stories is correct). It may be super-hard to fix, so may well warrant closing, I don’t know. just wanted to mention. I created example [here](https://preview.gutools.co.uk/training-site-2#headlines-(fixed-slow-7)).

<img width="1567" alt="image" src="https://github.com/guardian/dotcom-rendering/assets/6032869/bdf8a6b4-b18d-47b9-94fe-03ba1623890f">

Biden and Haley cards are 460px, Biden image is requested correctly at `width=460`, but Haley one is requested at `width=220`
