### ISSUE TITLE
Investigate Gracenote widget support

### ISSUE THREAD

**Issue by georgeblahblah** [guardian/dotcom-rendering#10285]
[More details in this thread.](https://groups.google.com/a/guardian.co.uk/g/dotcom.platform/c/Xc1TfoasjZY)

We should investigate support interactive elements/embeds pulling data from Gracenote ahead of the Paris olympics.

Check that:

- requests to Gracenote APIs succeed (not blocked by CORS etc)
- 3rd party cookies dropped by the element are treated appropriately

**Comment by ioannakok** [comment]
Closing this as we have investigated. If needed we will merge this: https://github.com/guardian/fastly-edge-cache/pull/1045/
