### ISSUE TITLE
Callouts: Communicate file size upload limit to readers

### ISSUE THREAD

**Issue by georgeblahblah** [guardian/dotcom-rendering#10313]
[Original chat thread](https://chat.google.com/room/AAAAG9rU0m0/QLYg39mO9gY/QLYg39mO9gY?cls=10).

Some callouts allow readers to upload files. There is a maximum file size of ~<6mb because the [service which accepts submissions](https://github.com/guardian/formstack-submitter-ts) is deployed as a Lambda. We should communicate this limit to readers.

**Comment by alinaboghiu** [comment]
@benwuersching to see if there are existing designs for this and confirm the text we want to add

**Comment by benwuersching** [comment]
It is very simple. We can use the secondary text field. We just need to agree on the copy. I'm attaching a quick mockup to show what I mean.

![max file size](https://github.com/guardian/dotcom-rendering/assets/23035818/a0ac3b14-ec15-4808-80c1-99590a0dd39a)
