### ISSUE TITLE
Some images are ignored

### ISSUE THREAD

**Issue by mxdvl** [guardian/dotcom-rendering#10322]
https://www.theguardian.com/games/2024/jan/20/strange-sweaty-sociable-early-days-of-gaming-in-pictures#img-6

Should be the following image:

<img width="375" alt="image" src="https://github.com/guardian/dotcom-rendering/assets/76776/0175dbc8-6b92-49c0-83e3-ed7fe9d8d2b9">

**Comment by mxdvl** [comment]
Could it be due to `isWideEnough` checks being inconsistent in `ImageComponent` and `MultiImageComponent`?

**Comment by paperboyo** [comment]
Looks like it’s not `half-width` only. [Here](https://www.theguardian.com/artanddesign/2024/jan/30/resilience-and-bravery-in-ukraine-photobrussels-festival-2024), two are ignored, the first one a `showcase`.

**Comment by paperboyo** [comment]
Testing on CODE, this fixes half of the problem: image order is no longer upset by rogue ones, so you never end up getting a wrong when entering Lightbox. Yay!

Unfortunately, still, exactly the same images from two examples above:
- do not display Lightbox icon and hover behaviour
- are not clickable
- cannot be seen in Lightbox when navigating from other images

So they are still completely missed for a mysterious, dark reason. Non-yay.

In total: half-yay!

There is also a regression, in [here](https://m.code.dev-theguardian.com/artanddesign/2024/jan/30/resilience-and-bravery-in-ukraine-photobrussels-festival-2024) (but not in [another](https://m.code.dev-theguardian.com/games/2024/jan/20/strange-sweaty-sociable-early-days-of-gaming-in-pictures) piece), clicking on Main media does nothing. It works correctly in PROD.
