### ISSUE TITLE
Implement Discussion API On Android

### ISSUE THREAD

**Issue by alinaboghiu** [guardian/dotcom-rendering#10325]
```[tasklist]
### Tasks
- [ ] Implement comment
- [ ] Implement reply
- [ ] https://github.com/guardian/dotcom-rendering/issues/10738
- [ ] Implement addUsername
- [ ] #10654
```

**Comment by JamieB-gu** [comment]
The Android team may pick this up once we've defined the Bridget API.

**Comment by ioannakok** [comment]
We spoke with @robksmith and the plan for this is:

1. WebX is going to put together a draft PR in Bridget - this will outline the api calls required. See #10544. We can alter this together as we see fit.  

2. When we are happy with it Android developers will start implementing / re-using discussion modules in the Android code base.

**Comment by ioannakok** [comment]
Draft PR for Bridget API for discussion: https://github.com/guardian/bridget/pull/111

**Comment by georgeblahblah** [comment]
Closing thanks to huge amounts of great work from @EnochHankombo92 !!!
