### ISSUE TITLE
Review Results Of Second Deeply Read Test

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#10348]
Launched in #8807.

**Comment by mxdvl** [comment]
The test should be turned off today

**Comment by alinaboghiu** [comment]
Test turned off today - will wait for data at the end of this week

**Comment by alinaboghiu** [comment]
@benwuersching says to go with adding "learn more" as a text link at the end of the subheading description

**Comment by benwuersching** [comment]
Here's the design for it. 

![Group 1](https://github.com/guardian/dotcom-rendering/assets/23035818/2a1bc7c2-072c-41e4-a046-c598573d3bf7)
