### ISSUE TITLE
Chromatic flakey snapshot: `LightboxLayout: Without Caption`

### ISSUE THREAD

**Issue by cemms1** [guardian/dotcom-rendering#10509]
The `LightboxLayout: Without Caption` story is not showing the intended view i.e. shows caption when it should be hiding the caption

E.g. https://www.chromatic.com/test?appId=63e251470cfbe61776b0ef19&id=65c26dc8c85999ef16e2bd86
![image](https://github.com/guardian/dotcom-rendering/assets/43961396/5756acbd-4a53-464b-be71-02cbe947bfe9)

We should investigate why this is happening and try to provide a Chromatic snapshot which accurately describes what it should look like

**Comment by paperboyo** [comment]
Worth noting the state ot this sidebar is kept in localstorage, so probs easy to force it to whatevs we want?

**Comment by alinaboghiu** [comment]
We should use this ticket to look more broadly at reducing flaky chromatic diffs. I will create a separate ticket this is just to remind me to do it.

**Comment by domlander** [comment]
PR: https://github.com/guardian/dotcom-rendering/pull/11086

**Comment by domlander** [comment]
Current set of flaky snapshots on `main`. All Chromatic stories were run for this test: https://www.chromatic.com/build?appId=63e251470cfbe61776b0ef19&number=7769
