### ISSUE TITLE
[Tag Pages] Pagination missing on `/all` URLs

### ISSUE THREAD

**Issue by cemms1** [guardian/dotcom-rendering#10556]
Pagination missing on `/all` tag pages

Example URL: https://www.theguardian.com/sport/all

Should look like the following screenshot:
![image](https://github.com/guardian/dotcom-rendering/assets/43961396/ce28a96e-887e-4f13-a10e-3a5fcc53ddca)

**Comment by alinaboghiu** [comment]
This will be because we never implemented /all: https://github.com/guardian/dotcom-rendering/issues/8321

**Comment by ioannakok** [comment]
Specifically, it's the /all.json route that's [missing](https://github.com/guardian/frontend/blob/main/applications/conf/routes#L93). Once we add it, these will stop returning 404: https://www.theguardian.com/sport/all.json?dcr

And then we have to add the pagination data for /all pages to the DCR model. Atm we're only sending pagination data for regular tag pages (e.g. https://www.theguardian.com/politics/michaelgove.json?dcr). In regular tag pages pagination comes from [`Tag`](https://github.com/guardian/frontend/blob/main/common/app/model/Tag.scala#L181-L184) 

<img width="400" alt="Screenshot 2024-03-14 at 15 54 09" src="https://github.com/guardian/dotcom-rendering/assets/19683595/6d274688-a099-48e7-8924-bac9e19fbef8"><br>

In /all pages pagination comes from [`Metadata`](https://github.com/guardian/frontend/blob/main/common/app/model/meta.scala#L323)

<img width="800" alt="Screenshot 2024-03-14 at 15 54 09" src="https://github.com/guardian/dotcom-rendering/assets/19683595/ca2b47ad-8d39-4a95-accf-c8cc1d5052bf">

**Comment by abeddow91** [comment]
```[tasklist]
### Tasks
- [ ] Add all.json route to Frontend 
- [ ] Add all.json route to Platform router
- [ ]  pass pagination from frontend to DCR
- [ ] 
```
