### ISSUE TITLE
Update MAPI filter to allow live blogs in beta

### ISSUE THREAD

**Issue by cemms1** [guardian/dotcom-rendering#10573]
Update the `getBetaDcrSupport` method in `DcrSupportUtils.scala` in MAPI. The `isLiveBlog` method from `ContentApi.scala` may be useful for this, as a replacement for the changes made in #12017.

**Note:** Make sure we continue to exclude sportblogs from this filter. See #7396 for more information.

**Comment by domlander** [comment]
Blocked by [12313 - Support all elements that can appear in liveblogs](https://github.com/guardian/dotcom-rendering/issues/12313)

**Comment by JamieB-gu** [comment]
@domlander @DanielCliftonGuardian @arelra we should make sure we specify in MAPI that liveblogs require the same min Bridget version as media atoms, so that if a media atom gets added to the liveblog the app can handle it.
