### ISSUE TITLE
Hide duration on small video card

### ISSUE THREAD

**Issue by cemms1** [guardian/dotcom-rendering#10607]
Duration pill takes up a lot of space on the video thumbnail in the following screenshot:

![image](https://github.com/guardian/dotcom-rendering/assets/43961396/6609b448-9e08-417e-8a2d-9485f2201c93)

We should consider removing the timestamp on these small thumbnails.

Additionally, we should consider removing the "hour" part of the timestamp if the video is shorter than one hour (which most of them are)

ie `hh:mm:ss` becomes `mm:ss`

This will align the design better with apps

**Comment by paperboyo** [comment]
I think it may be roken only for some containers (paletted ones?). Compare [this](https://preview.gutools.co.uk/training-site-2#headlines-(dynamic-fast)) (correct) and [that](https://preview.gutools.co.uk/training-site-2#headlines-(dynamic/package)) (broken).

**Comment by abeddow91** [comment]
closing as this was resolved by https://github.com/guardian/dotcom-rendering/pull/11038
