### ISSUE TITLE
Enable recommendations-only discussion in DCAR

### ISSUE THREAD

**Issue by mxdvl** [guardian/dotcom-rendering#10618]
Once we’ve released [read-only discussions](https://github.com/guardian/dotcom-rendering/issues/10565), we can focus discussions that are closed, but still open for recommendation.

This will mean we need to implement the Bridget method for [`recommend`](https://github.com/guardian/bridget/blob/22d1f223e808a077348b9a430cd162e6a409c9a8/thrift/native.thrift#L125), but do not yet have to implement every method.

```[tasklist]
### Tasks
- [ ] https://github.com/guardian/dotcom-rendering/issues/10639
- [ ] https://github.com/guardian/dotcom-rendering/issues/10654
```

**Comment by JamieB-gu** [comment]
Tracked by #10326 and #10325
