### ISSUE TITLE
Horizontal rule in`SlotBodyEnd` stretches out the page on mobile web

### ISSUE THREAD

**Issue by ioannakok** [guardian/dotcom-rendering#10613]
<img src="https://github.com/guardian/dotcom-rendering/assets/19683595/df6ef427-bcb4-4fb9-a045-3208a2786b38" alt="image" width="300" height="auto">

<br><br>

https://github.com/guardian/dotcom-rendering/blob/12028af86406b03cb5c3cd6127285d92d518c318/dotcom-rendering/src/components/SlotBodyEnd.importable.tsx

**Comment by alinaboghiu** [comment]
We think this is no longer an issue
