### ISSUE TITLE
Issue with sponsorship badging

### ISSUE THREAD

**Issue by ioannakok** [guardian/dotcom-rendering#10684]
Reported by CP in: https://groups.google.com/a/guardian.co.uk/g/dotcom.platform/c/bOQoXkmKP-I

This series doesn't have the [theguardian.org](http://theguardian.org/) sponsorship badging, even though it should as it is part of the global development section: https://www.theguardian.com/global-development/series/a-common-condition

Badging should be appearing as it is on this series: https://www.theguardian.com/global-development/series/rights-and-freedom

Lily from CP mentions:

> I looked into this and tried adding the 'a common condition' tag onto the global development sponsorship in tag manager, and I got this:

![Image](https://github.com/guardian/dotcom-rendering/assets/19683595/33f3eb7b-c0fb-4b4a-9408-43a5147b1d56)

> So I looked at that Helmsley sponsorship and can see it is expired:

![Image](https://github.com/guardian/dotcom-rendering/assets/19683595/e3bb120c-6bbf-4adf-aadd-4162ddba0b6e)

> We wondered if this could be blocking [theguardian.org](http://theguardian.org/) sponsorship badging even though it is expired?
> We might be wrong, but cannot spot another reason for it not appearing.

**Comment by shesah** [comment]
@ioannakok could you please confirm if this is a platform bug or tools?
