### ISSUE TITLE
Update the filter in MAPI to support read only Discussion in PROD

### ISSUE THREAD

**Issue by abeddow91** [guardian/dotcom-rendering#10734]
We currently have read only discussions in BETA

Once we implement reportAbuse (https://github.com/guardian/dotcom-rendering/issues/10738 and https://github.com/guardian/dotcom-rendering/issues/10737) we can release read only discussions to PROD

**Comment by mxdvl** [comment]
Fixed by https://github.com/guardian/mobile-apps-api/pull/3014
