### ISSUE TITLE
Make sure we have consent when using storage for discussion in apps

### ISSUE THREAD

**Issue by abeddow91** [guardian/dotcom-rendering#10735]

**Comment by abeddow91** [comment]
Currently, ios does not offer users the option to set preferences which means there is no need to store on the device. One option would be to follow this pattern and hide preferences on app.

**Comment by alinaboghiu** [comment]
To check with data privacy (data.privacy@guardian.co.uk) but we think we don't have any PII

**Comment by abeddow91** [comment]
Waiting to hear back from data privacy that this does not require consent
