### ISSUE TITLE
Replace start-server-and-test with an internal solution

### ISSUE THREAD

**Issue by abeddow91** [guardian/dotcom-rendering#10980]
Playwright uses `start-server-and-test`. This is the only use case and could be replaced by a script.

**Comment by arelra** [comment]
I think we can get Playwright to do this: https://playwright.dev/docs/test-webserver

I'll take this ticket as it's related to some other tidy up I want to do with the local setup of Playwright

**Comment by arelra** [comment]
Completed by: https://github.com/guardian/dotcom-rendering/pull/11022
