### ISSUE TITLE
Add canonical url to front pages

### ISSUE THREAD

**Issue by alinaboghiu** [guardian/dotcom-rendering#11036]
Possibly during the migration we forgot to set a canonical url on front pages? 

**DCR**
view-source:https://www.theguardian.com/uk?dcr=true

**Frontend**
view-source:https://www.theguardian.com/uk?dcr=false

This ticket is to add it back in to DCR pages

**Comment by arelra** [comment]
Closed by:
https://github.com/guardian/frontend/pull/27060
#11189
