### ISSUE TITLE
Additional subheading styling post design feedback

### ISSUE THREAD

**Issue by cemms1** [guardian/dotcom-rendering#11051]
### Remove surplus space from above some `h2` elements

Remove the `padding-top` from all subheadings (`h2` elements) when an `h2` does not follow a `p` / `TextBlockComponent`. This is because the spacing looks too big between an image for example and a following subheading e.g. in this article https://www.theguardian.com/stage/2024/mar/01/the-best-theatre-to-stream-this-month-peaky-blinders-prima-facie-and-more

### Handle consecutive `h2` elements

Due to the lack of `h3` elements available in composer, we have some non-semantic uses of `h2` which can look a little strange with the new subheading styling coming in with the article format design updates.

For **Immersive** **soft tone** tags (with bold weight) only, the following adjacent (second, third etc.) h2 always switches to a **Light weight**. This is not user controlled but automatic. The following article showcases why: https://www.theguardian.com/books/2019/sep/21/best-books-of-the-21st-century

**Comment by alinaboghiu** [comment]
Closing this as we decided to allow immersive articles to have regular font weight and respect strong tags coming in from Composer
