### ISSUE TITLE
Contributors page: A-Z index not updating

### ISSUE THREAD

**Issue by ioannakok** [guardian/dotcom-rendering#11188]
Raised by CP: https://groups.google.com/a/guardian.co.uk/g/dotcom.platform/c/1UwVVYRPGdI

> We are auditing this page with the digi eds and noticed that the A-Z index at the top is not updating with new (or even quite old!) writers: 
https://www.theguardian.com/index/contributors
A random example: [Torsten Bell ](https://www.theguardian.com/profile/torsten-bell)is not appearing under T or B, nor are several other writers.

**Comment by ioannakok** [comment]
This PR has some documentation on how this page works:

* https://github.com/guardian/frontend/pull/25176

Might be useful

**Comment by alinaboghiu** [comment]
Looks like Torsten Bell has now appeared, perhaps it was caching or they didn't have any content published yet? 

TODO: reply to original thread
