### ISSUE TITLE
Scrolling causing text to resize on mobile

### ISSUE THREAD

**Issue by DanielCliftonGuardian** [guardian/dotcom-rendering#11284]
Scrolling causing text to resize on mobile
iPhone 8 running Safari in iOS 16.6.1. 

Email thread: https://mail.google.com/mail/u/0/?q=amp+code#inbox/FMfcgzGxStqZFQKrjdWqZWSMXVzPCCXr

**Comment by alinaboghiu** [comment]
@mxdvl managed to recreate but we think it was short lived

**Comment by mxdvl** [comment]
Caught the culprit, it’s an explicit width set on an ad container by our opt-out advertising:

<img width="871" alt="image" src="https://github.com/guardian/dotcom-rendering/assets/76776/d05eeb3a-e6bf-415b-8be6-a4720f10a652">
