### ISSUE TITLE
Investigate highlighting breadth of journalism to US users

### ISSUE THREAD

**Issue by abeddow91** [guardian/dotcom-rendering#11330]
## What is the task
The US have suggested they highlighting the breadth of The Guardian's journalism in the US might improve next clicks. 

We need to speak with Tom Johnson and the US team to understand what this means in practice (ie what kind of component / how they wish to achieve this) and how we might best test and measure it.

## Questions to consider
- Can we do this just for US users?
- Could we then also target based on certain referrers 
      - Do we need to use Braze with an epic for this?
      - Could we add epics to articles

**Comment by shesah** [comment]
[Link to meeting notes](https://docs.google.com/document/d/1iM7j_1f4A096osZrIZCIsXsHknnLGN5INXGI_IcYvhY/edit)

Next Steps:

WebX to speak to [Marcus Peabody](mailto:marcus.peabody@guardian.co.uk) in the US about any possible designs he has already done on this

WebX to work with UX to look at possible placement of component on the page

US team to brainstorm ideas around possible wording for the component

WebX/[Anthony Mangeri](mailto:anthony.mangeri@theguardian.com) to create list of possible measures of success of this testing

**Comment by ashishpuliyel** [comment]
At the risk of solutionising, the US could just use the merch-high slot and ad-serve whatever they want. And ad-served stuff can be geo-targeted, or even (_I think_) targeted to first-time visitors.
