### ISSUE TITLE
Effect of DCR Tag Pages on ad revenue

### ISSUE THREAD

**Issue by alinaboghiu** [guardian/dotcom-rendering#11352]
Get data from D&I Commercial.

There is a small % of tag pages (e.g. [contributors index](https://www.theguardian.com/index/contributors)) that have a high frequency of fronts-banner ads due to the small height of each section. Ensure that these pages perform similarly.

**Comment by ashishpuliyel** [comment]
There was no significant impact on revenue from this change. There an increase in impressions per-pageview.

> There was a very minor 0.03% increase in programmatic revenue per 1000 page views. This came alongside a 6.4% increase in impressions per page views.
