### ISSUE TITLE
Tear down "legacy" DCR stack

### ISSUE THREAD

**Issue by georgeblahblah** [guardian/dotcom-rendering#11422]
Since spinning up dedicated stacks for different purposes in #9955 we should tear down the legacy stack:

https://github.com/guardian/dotcom-rendering/blob/bb185ff4ee533358f3317cb858742d17717b8a3c/dotcom-rendering/cdk/bin/cdk.ts#L14-L29

This should be replaced with a new stack which handles miscellaneous requests like the email newsletters page.

**Comment by JamieB-gu** [comment]
Step one, moving the traffic, here: https://github.com/guardian/frontend/pull/27467

Will need to see if #10498 re-occurs before tearing down the old stack.
