### ISSUE TITLE
Tune `facia-rendering` And `tag-page-rendering`

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#11441]
Previously we had a single stack for rendering fronts and tag pages: `facia-rendering`. In #11421 we created a new stack, `tag-page-rendering`, and sent all tag page traffic to that. We did not change the size (number of instances) or scaling policy of the `facia-rendering` stack, and we created the new `tag-page-rendering` stack using exactly the same rules.

As a result, both stacks now have different traffic patterns to what those rules were optimised for. `facia-rendering` now serves only fronts traffic, and `tag-page-rendering` serves only tag page traffic.

Therefore we should tune the size and the scaling policy of both stacks to suit their new traffic patterns. This will likely at least mean reducing the minimum number of instances for both.

**Comment by alinaboghiu** [comment]
We should pull this into our next health sprint in June
