### ISSUE TITLE
Star ratings are missing from onward journey carousels

### ISSUE THREAD

**Issue by abeddow91** [guardian/dotcom-rendering#11465]
Star ratings are missing from onward journey carousels. This might be an intentional design decision.  If it was not, then these must have been missed in the migration and should be added back as per designs.

**Comment by abeddow91** [comment]
@HarryFischer has been messaged about this to find out if these should appear or not.

**Comment by mxdvl** [comment]
Awaiting on visual’s designs for the look of this.

**Comment by HarryFischer** [comment]
Can we just copy what we do on Fronts? Sizing should be the same. I won't have time to supply designs before Elections are over
