### ISSUE TITLE
Body text becomes big after a bit of scrolling

### ISSUE THREAD

**Issue by ioannakok** [guardian/dotcom-rendering#11486]
This is an issue in the app.

https://groups.google.com/a/guardian.co.uk/g/dotcom.platform/c/z94cHMVItTs/m/yxjFxVcXAgAJ

https://github.com/guardian/dotcom-rendering/assets/19683595/49b23b17-e560-456d-b291-3bbe2c0bd003

**Comment by mxdvl** [comment]
Fixed by #11503
