### ISSUE TITLE
New rich links for election interactive page

### ISSUE THREAD

**Issue by alinaboghiu** [guardian/dotcom-rendering#11504]
Visuals team asked for help with general election tracker page (interactive). 

Figma link: https://www.figma.com/design/KUY6ZVRdDEY0O2t0ECCE8d/UK-General-Election-2024-%E2%80%94-Designs?node-id=0-1&t=IE86khFb49OYC57b-0

Can we support the new rich link designs in this Figma file by using the existing Composer rich links? 

![Image](https://github.com/guardian/dotcom-rendering/assets/1229808/134ab059-c0e3-4889-abc1-181dc17ffc85)

**Comment by alinaboghiu** [comment]
We think the Visuals team can style the rich links in an interactive article by using the interactive atom functionality. Not much webX can help with in this case. 

@CDicksonG to set up a chat with visuals to give them some pointers as to how they might achieve this

**Comment by shesah** [comment]
Harry is building this so we will close it.
