### ISSUE TITLE
New design for mobile spider diagram

### ISSUE THREAD

**Issue by shesah** [guardian/dotcom-rendering#11546]
https://www.figma.com/design/rytX3LgJ6v7u0Em5D3y5PM/Euros-2024-spider?node-id=0-1&t=gWEYw0dYOD3QCrER-1

Merge the following two:

<img width="993" alt="image" src="https://github.com/guardian/dotcom-rendering/assets/76776/a82ee369-ce47-49af-853f-02b76a0bb497">

<img width="605" alt="image" src="https://github.com/guardian/dotcom-rendering/assets/76776/c4817cff-629d-46f8-a063-e63792043e75">

**Comment by mxdvl** [comment]
Until we get dedicated time from moving the rendering of these diagrams out of the Twirl templates, we will not update these designs.
