### ISSUE TITLE
Quick Guide Embed broken

### ISSUE THREAD

**Issue by domlander** [guardian/dotcom-rendering#11654]
There is a report that the show/hide buttons in the Quick Guide embed not functioning correctly. See video below.

Device: iPhone 14
Browser: Chrome

https://github.com/guardian/dotcom-rendering/assets/9574885/187f1e0a-7e6e-4de0-9a1f-72386c9394aa

Reported by Alessia Amitrano in the WebX chat: https://chat.google.com/room/AAAAG9rU0m0/FXZTuP1B4BY/FXZTuP1B4BY?cls=10

**Comment by domlander** [comment]
There is a report that the show/hide buttons in the Quick Guide embed not functioning correctly. See video below.

Device: iPhone 14
Browser: Chrome

https://github.com/guardian/dotcom-rendering/assets/9574885/187f1e0a-7e6e-4de0-9a1f-72386c9394aa

Reported by Alessia Amitrano in the WebX chat: https://chat.google.com/room/AAAAG9rU0m0/FXZTuP1B4BY/FXZTuP1B4BY?cls=10

**Comment by domlander** [comment]
I was unable to reproduce this bug on Chrome on MacOS

**Comment by shesah** [comment]
Anna has also tried and failed to reproduce it. However we can try with BrowserStack to see if we can reproduce - if not let's close the ticket

**Comment by abeddow91** [comment]
closing as this is not reproducable
