### ISSUE TITLE
Sudoku's listed on incorrect day on tag page

### ISSUE THREAD

**Issue by domlander** [guardian/dotcom-rendering#11676]
On the [Sudoku tag page](https://www.theguardian.com/lifeandstyle/series/sudoku), all puzzles are appearing as being released on the day before they were actually released. They are off by one day.

![image](https://github.com/guardian/dotcom-rendering/assets/9574885/fda5e22f-00c6-4cb8-91e4-2c087c474ff8)

Max Duval: For developers: this is likely due to the [use of UTC dates on the backend](https://github.com/guardian/dotcom-rendering/blob/8209f09d27d48b6f68e9e740893d73d49f502f93/dotcom-rendering/src/model/groupTrailsByDates.ts#L99), rather than inferring the date from the time zone

Reply to this thread once complete: https://mail.google.com/mail/u/0/#all/FMfcgzQVxHZZrMhqmcMFsLdGqVQGgbjv

**Comment by domlander** [comment]
Sudoku's are still listed on the incorrect day (it works fine when running locally, but not on PROD or CODE)

https://www.theguardian.com/lifeandstyle/series/sudoku

<img width="1453" alt="image" src="https://github.com/guardian/dotcom-rendering/assets/9574885/b2224a9b-b26b-4d7d-bed0-9546cb7ebdfa">

**Comment by mxdvl** [comment]
Fixed by #11851
