### ISSUE TITLE
George is leaving 😭😭😭

### ISSUE THREAD

**Issue by alinaboghiu** [guardian/dotcom-rendering#11687]
This is a major issue. Likely cannot be fixed. 

More seriously **this is George's leaving card**! 

If you'd like to leave a goodbye message for George please add a comment below

**Comment by paperboyo** [comment]
PLEASE FIX THIS ISSUE YET!!!!1110NE11

It’s utterly unacceptable such a major bug slipped through your seemingly rigorous process, especially under recently enacted zero-bug policy. What kind of engineers are you if you can’t even make people not fly planes?! My seven month old gold fish, who died last week, can deal with issues much faster! Totally unacceptable. That does it. We are switching to Logo, at least it’s got a turtle. I love turtles. My whole world stands on their giant shoulders.

Thank you George!

**Comment by ashishpuliyel** [comment]
I can replicate. This is a MAJOR annoyance. I've not even been using this project long, but he was a really useful feature of the team! Could someone please look into this, urgently?

Steps to Reproduce:
- Read the leaving email from George
- Witness the emotional outpouring in the replies.

Expected Result:
- He changes his mind. He's staying. 
 
Actual Result:
- Still leaving!

Severity: **High**

Environment: **Production**

Possible Solutions: Clone George if possible?

**Comment by ashishpuliyel** [comment]
I think we can class this as a migration bug?

**Comment by MaxWalker2010** [comment]
Hi, Georges, I will always value your friendship at the start of my time in P&E (especially remember the Christmas skating trip.) You have always been great to work with. Good luck with everything in the future. Max

**Comment by robksmith** [comment]
Hi George!

It's sad to see you go.

All the best for the future

**Comment by tkgnm** [comment]
I'm also seeing some unexpected behaviour - my entire screen has gone blurry. I can't read anything. Oh wait, it's just the tears in my eyes 😢😢😢

Will miss you loads George! Stay in touch xxxxxx

**Comment by shesah** [comment]
I say this from the bottom of my heart, George, it was really lovely working with you on both MSS and WebEx these last couple of years and I am really excited about your next chapter. Please, please let us know how you get on - would love to hear about your progress.

**Comment by alinaboghiu** [comment]
It was such a treat working with you George, I am devastated. The Software Engineering profession will never quite recover from this loss. The aviation industry is already quietly celebrating. I hope one day to hear your high quality jokes and cynicism on the speakers on some flight to New York.

**Comment by mxdvl** [comment]
_Auf Wiedersehen, George…_

The only thing that compares with the lovely glow I get from pairing with you is going to get an edible treat near the office. You’re always the joyous, composed, funny, composed and thorough colleague – and dare I say friend! No amount of pastries can fill this loss, but you have my word that I will try nonetheless.

**Comment by dblatcher** [comment]
Sorry to see you go - thank you for all your help, support and very patient reviews!

```typescript
describe("theGuardianPE", () => {
  it("should include George", () => {
      expect(theGuardianPE.members.includes(GEORGE).toBe(true)
  }
}

```

**Comment by arelra** [comment]
It's been wonderful working with you George and you're going to be sorely missed. Fully expecting a barrel roll past the office one day!

**Comment by alinaboghiu** [comment]
From Victoria Barrett: <img width="58" alt="Screenshot 2024-07-04 at 14 38 35" src="https://github.com/guardian/dotcom-rendering/assets/1229808/13c32dd3-f83b-4f52-a71b-3d75669709d0" width=80 >
"George I am so very sorry to see you go, I will miss our chats, see you at a festival I hope"

**Comment by ioannakok** [comment]
George! It's sad to see you go but I'm also very happy for your next exciting adventure! It's been a pleasure working with you, I will miss all the knowledge, the calmness and positive energy you bring to the team. Looking forward to enter the pilot cabin next time I see you in the air ✈️ 

All the best,
Ioanna

**Comment by oliverlloyd** [comment]
*Speedbird George, Speedbird George, this is Human Oliver, Human Oliver*
...
*Speedbird George, please say your current position and altitude*
...
*Speedbird George, Human Oliver, I’ve had reports that you are no longer at your last reported position and that your altitude has increased dramatically?*
...
*Speedbird George?*
...
*Speedbird George, Human Oliver, fair winds and safe watch*
