### ISSUE TITLE
Deeply Read Test Analysis

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#11689]
D&I analysis is complete and can be found in this email thread: https://groups.google.com/a/guardian.co.uk/g/dotcom.platform/c/Is5-17vWA0w/m/ZvyINXG0AQAJ

Summary of key results, comparing the two variants `Most Viewed only` to `Most Viewed and Deeply Read`:
- Click-through rate: UP 76% 
- Revenue per 1000 sessions: DOWN 4.21%

**Comment by shesah** [comment]
Speak to commercial and Chris Moran on next steps
