### ISSUE TITLE
Support Identity Team with Discussion Frontend

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#11717]

**Comment by ioannakok** [comment]
This repo is deprecated and is also using deprecated identity functionality: https://github.com/guardian/discussion-frontend

It is responsible for the comment count and sign in / profile avatar info for articles that are still rendered by frontend and have discussion enabled.

<img width="936" alt="image" src="https://github.com/user-attachments/assets/c25e7762-5778-4a55-9d0d-242a9f2582f8">

**Comment by shesah** [comment]
@shesah and @CDicksonG to speak to the I&T team to see which option from above is best.

**Comment by ioannakok** [comment]
From this document by the Identity team: https://docs.google.com/document/d/1ORn7S_vsi5v22fBYa8fQEWMQXr5_WTiChPDr_dDxYFQ/edit

"Each [crossword page](https://www.theguardian.com/crosswords/quick/16909) has a comment section. This section makes two calls to our legacy platform using legacy identity cookies, which are then returned in headers. The two calls originate from:

1. The comment feed
2. The ‘Signed in as…’ component in the left-hand sidebar
"

From our investigation, we think the calls are made only by this section, not by the comment feed.

<img width="936" alt="image" src="https://github.com/user-attachments/assets/c25e7762-5778-4a55-9d0d-242a9f2582f8">

@JamieB-gu do you perhaps know why they're saying one of the calls comes from the comment feed?

**Comment by CDicksonG** [comment]
We will clarify exactly what we need to turn off and then have conversations with the right people in Editorial

**Comment by ioannakok** [comment]
@JamieB-gu and myself clarified today with @pvighi that we only need to turn off the box with the comment count and avatar info highlighted in the screenshots above. This will happen only for articles that are still rendered by frontend, i.e. crosswords, galleries and audio articles.
