### ISSUE TITLE
Tag Page Timestamps Not Respecting Edition

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#11744]
The timestamps are all using GMT/BST, i.e. the UK edition timezone, regardless of edition.

As @mxdvl points out, this is likely caused by a hardcoded edition here:

https://github.com/guardian/dotcom-rendering/blob/b231e65510d2be9391474147e69a0a2fd16eb352/dotcom-rendering/src/components/Card/components/CardAge.tsx#L77

https://github.com/guardian/dotcom-rendering/blob/b231e65510d2be9391474147e69a0a2fd16eb352/dotcom-rendering/src/components/Card/components/CardAge.tsx#L87

**Comment by mxdvl** [comment]
Possibly easier to fix with #11742
