### ISSUE TITLE
Max is leaving 😭😭😭

### ISSUE THREAD

**Issue by alinaboghiu** [guardian/dotcom-rendering#11804]
What I thought was an [isolated issue](https://github.com/guardian/dotcom-rendering/issues/11687) has, devastatingly, reoccured. 

Please leave your leaving messages for Max in a comment below.

**Comment by paperboyo** [comment]
![don’t_1](https://github.com/guardian/dotcom-rendering/assets/6032869/9be12cf2-7cfe-426a-a484-ef942fb6e29a)

**Comment by andrewHEguardian** [comment]
this is so sad 😢 are we sure this is an issue on every browser?

**Comment by MaxWalker2010** [comment]
On the plus side, I won't panic so often when somebody in a demo says: "And now Max is going to share something." But will really miss your ability to see past all the waffle and get to the heart of an issue. Good luck. Max

**Comment by mchv** [comment]
😢 We will miss you Max! 

C'est tellement triste de te voir déjà partir, resterons avec nous ton code et ton sourire, ta culture et tes PR.
Quelques rimes croisées, en hommage au treillis de tes nombreuses contributions assemblées.
Plusieurs héritages, nombreux voyages, de l'architecture et du SVG, alors j'ai choisi de la menuiserie japonaise numérique pour te représenter.

![Max face in Kumiko pattern](https://github.com/user-attachments/assets/4a05196e-ec04-4a7a-828f-1f406d16375a)

**Comment by vlkerag** [comment]
Hi Max, I will miss our lively brainstorming and your pragmatic, solution-oriented approach, as well as your enormous expertise! All the best for your future.

**Comment by michaelclapham** [comment]
😭 This is a serious bug. Max is great at writing web applications without using a bundler, but going so far so to unbundle himself from P&E? This is a step too far. I'll spend the rest of my days on edge trying to compute ways to make Max come back Fastly. Maybe we should bake him a cake in the shape of his favourite animal (A [Deno](https://deno.com/)saur)? Wait, he lived in Japan, maybe he's more of a fan of steamed [Bun](https://bun.sh/)s. It's hopeless, we pine after you, but clearly we're just not your **Type**script. 

Max I learnt so much from you. If it's somehow related to the modern web or typescript, you had bountiful knowledge to share on it. I will miss geeking out about weird web side projects at the pub. Bon voyage! 🚢

**Comment by philmcmahon** [comment]
![noomax](https://github.com/user-attachments/assets/23ce4768-5bb7-489f-8294-b3a786f76b68)

À la prochaine 👋🏻

**Comment by shesah** [comment]
Well buddy, what can I say? it was an absolute pleasure working with you. really was. But as the ol' saying goes all good things come to an end and this chapter has come to a close but a new one will begin for you and I wish you all the best in it. Good luck with everything and hopefully catch you in a drinking establishment in the not-to-distant future.

**Comment by deedeeh** [comment]
It's really sad to see you leaving Max! You have done enormous great work and contributions at the Guardian and definitely you are one engineer to look up to. Your passion and curiosity are priceless ✨

Thank you for the great PR reviews which I am going to miss, also your presentations in the different meetings, commDev-WebX catchups, and sharing your skills and knowledge during our mentorship sessions. If you were staying a little longer at the Guardian I was going to ask to practice French with you 😄 

Bonne chance et à bientôt 👋🏼

**Comment by blishen** [comment]
> 😢 We will miss you Max!
> 
> C'est tellement triste de te voir déjà partir, resterons avec nous ton code et ton sourire, ta culture et tes PR. Quelques rimes croisées, en hommage au treillis de tes nombreuses contributions assemblées. Plusieurs héritages, nombreux voyages, de l'architecture et du SVG, alors j'ai choisi de la menuiserie japonaise numérique pour te représenter.
> 
> ![Max face in Kumiko pattern](https://private-user-images.githubusercontent.com/615085/350964666-4a05196e-ec04-4a7a-828f-1f406d16375a.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3MjY4MzQsIm5iZiI6MTcyMTcyNjUzNCwicGF0aCI6Ii82MTUwODUvMzUwOTY0NjY2LTRhMDUxOTZlLWVjMDQtNGE3YS04MjhmLTFmNDA2ZDE2Mzc1YS5zdmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyM1QwOTIyMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMTFlMzgwNDI3YWRjYjA2NDc5NmVkNWM5MDRmMDczMjE3NDNlYmQ4NDZiZDE3ZDI4ODI0MmJhMzhiOTIwMWQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zTNia2E9g4tg8QKgQXQkAw8k_edVUeJo0dvtep-ktUY)

Monsieur Directeur, not great in dark mode this. Just saying. Max, we'll miss you a great deal, and if there are any of us left, it is an easy place to come back to. Just ask Tony McCrae. xxx

**Comment by itsibitzi** [comment]
Good bye Max!!! Best of luck in the future <3

**Comment by arelra** [comment]
What a legacy you leave Max! There probably isn't a a team in P&E that you haven't helped and raised the bar for. Thanks for all the sterling work and contributions you've made. All the best 💟

**Comment by Amouzle** [comment]
Whilst I'm clinging onto hope that a twist of fate brings you back very soon... Just want to say a massive thank you for everything you've done to better the Guardian, P&E and my own journey here! You're such a joy to work with and learn from! Hope to see you very soon!

**Comment by bryophyta** [comment]
It's very sad to see you go, but I hope you know that your positive influence will live on in the culture (& codebases!) of P&E. I've learned so much from working with you, and I'm really looking forward to hearing what you get up to next!

**Comment by jamesgorrie** [comment]
Max always on maximum when it comes to kindness, innovation, quality, inclusion and all the amazing things, really proving that great places are made of great people!

_**さ**_よなら, au re**V**oir, and **G**ood-bye Max! It's been a true pleasure!on

**Comment by ioannakok** [comment]
Sad to see you go, Max! Your contribution has been massive all around P&E and it's been fun working with you on the same team. I hope you have the best of luck in your new adventure! We'll miss you!

**Comment by aracho1** [comment]
We'll miss you Max! Thank you for mentoring and sharing your knowledge with me and others at the Guardian. Best of luck with your next adventure and please keep in touch!

**Comment by mxdvl** [comment]
It’s been such a blast working with you all. Thanks for helping me grow and share and pair and mess up. Thanks for your candid feedback and your kind words.

- Favour why over how
- Favour feedback over projections
- Favour colleagues over code

_Du fond du cœur, merci et à la prochaine!_

**Comment by Georges-GNM** [comment]
This issue is persisting. Pls reopen
