### ISSUE TITLE
Sprint planning 16th July - 30th July

### ISSUE THREAD

**Issue by shesah** [guardian/dotcom-rendering#11893]
**Previous sprint goal:** 
- Health Sprint

**Where are we on this goal?** 
- Half way there

**What do we need to do this sprint for our OKR work?**
- Have designs ready for the US banner and tag page redesign

**What other work are we able to fit in (remember OKR is the priority work)** 
- Be ready for Olympics
- Improvements to our systems (from incident retro)
- Youtube SDK w/ Ravi (@arelra)

**New sprint goal:**
- Health sprint continued and big events progress (inc. olympics)

**Anybody off?** 
- There some annual leave in the team

**On Rota:**
-  Ashish this week, Ioanna next week then Daniel.

**Comment by ioannakok** [comment]
👋 @shesah can we discuss this ticket in tomorrow's planning? https://github.com/orgs/guardian/projects/88/views/15?filterQuery=retry&pane=issue&itemId=68293958
