### ISSUE TITLE
Olympics Atom: Navigation tabs do not wrap properly on mobile on front

### ISSUE THREAD

**Issue by ioannakok** [guardian/dotcom-rendering#11948]
Reported in WebX chat: https://chat.google.com/room/AAAAG9rU0m0/_p4LYb3dZB0?cls=12

> On all interactive pages, the navigation items in the atom wrap on two lines on mobile. The style is not picked up on the front with the same code. 

### Olympics front on mobile

<img src="https://github.com/user-attachments/assets/719340fe-8808-4d57-abed-ae63cca7a8e9" width="300">

### Should be

<img src="https://github.com/user-attachments/assets/03c055f0-8d6d-4aed-9d13-8361a68800fb" width="300">

Link to the front: https://www.theguardian.com/sport/olympic-games-2024
An interactive where the atom works correctly : https://www.theguardian.com/sport/ng-interactive/2024/jul/19/paris-olympics-2024-live-schedule
and the code that is not pulling through:  https://github.com/guardian/interactives/blob/dffa3d74a00de9aa664b2b37dbfb26b3bd4693d1/atoms/editorial-design/olympics-2024/src/olympics-2024-header/src/client/css/_web.scss#L150

**Comment by shesah** [comment]
Waiting on visuals to make some changes their side
