### ISSUE TITLE
Add the reader revenue epic to blogs

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#12020]
The reader revenue epic is interleaved between blocks on liveblogs and deadblogs. The implementation for apps will be different to web, and powered by Bridget. We can look at AR and the templates to see what to do.

**Comment by domlander** [comment]
Waiting for Supporter Revenue to confirm what's needed: https://chat.google.com/room/AAAAIddGn5w/gQPMlpQDPyE/gQPMlpQDPyE?cls=10

**Comment by domlander** [comment]
Supporter Revenue do not have any epic inbetween liveblog content, so we can proceed with the migration without consideration for this content
