### ISSUE TITLE
My Account dropdown menu obscured in tablet portrait mode

### ISSUE THREAD

**Issue by domlander** [guardian/dotcom-rendering#12090]
Steps to reproduce:
- Log in and go to the home page
- Click "My Account" in the top-left corner

Expected behaviour:
- The dropdown should fit entirely within the viewport

Actual behaviour
- The dropdown is partially within the viewport

![image](https://github.com/user-attachments/assets/0af2df8f-1c2d-45ca-9511-494921bb34af)

**Comment by shesah** [comment]
Looks to be resolved with the changes to the header from FG team
