### ISSUE TITLE
Sign up to newsletter placeholder text overlays user input

### ISSUE THREAD

**Issue by domlander** [guardian/dotcom-rendering#12112]
An iOS live app user has reported that when signing up to a newsletter (The Stakes), the email box is overlaid with the 'Enter your email address' text. I can reproduce and have attached a video. I'm using an iPhone 12 Pro on iOS 17.5.1.

https://groups.google.com/a/guardian.co.uk/g/dotcom.platform/c/K-zhYIAsDjw

https://github.com/user-attachments/assets/0e7adc19-2dad-4475-afd6-9845f28961e4

**Comment by shesah** [comment]
@alinaboghiu this looks like a templates issue
