### ISSUE TITLE
Close Buttons Sometimes Not Working

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#12132]
We've had reports that the close button on the edition-switcher banner is not working in some scenarios. There has also been a report that the close button on the reader revenue (RR) banner is also not working in some cases, which could be related.

The edition switcher issue has occurred on:

- iOS 16.6.1 (Safari 16.6)
- Android 14 (Chrome 127)

The RR banner issue has occurred on:

- Android 12 (Chrome 127)

**Comment by arelra** [comment]
RR banner issue on Android 12, Chrome 127.0.6533.103

**Comment by JamieB-gu** [comment]
This has been reported as fixed.
