### ISSUE TITLE
Contrast problem on sublink to gallery

### ISSUE THREAD

**Issue by ioannakok** [guardian/dotcom-rendering#12169]
Reported from CP: https://groups.google.com/a/guardian.co.uk/g/dotcom.platform/c/UfN_o2A8HEY

> on https://www.theguardian.com/science I tried adding https://www.theguardian.com/science/article/2024/aug/19/what-is-blue-supermoon-when-uk-skies as a sublink of https://www.theguardian.com/science/gallery/2024/aug/20/full-moon-blue-supermoon-sky-august-2024-super-gallery-images-in-pictures and got this

![Image](https://github.com/user-attachments/assets/3b3e8d3a-f5f2-4bcb-93b2-2c597d28c658)

**Comment by shesah** [comment]
@cemms1 is this a FG issue?

**Comment by frederickobrien** [comment]
Haven't been able to replicate this issue and haven't heard further reports so going to close. If it happens again we'll try to jump on it quickly so we can get to the root of what's going wrong.
