### ISSUE TITLE
AWS budget exceeding threshold

### ISSUE THREAD

**Issue by ioannakok** [guardian/dotcom-rendering#12260]
To investigate the emails we're getting from AWS: https://groups.google.com/a/guardian.co.uk/g/dotcom.platform/search?q=AWS%20budgets

**Comment by marjisound** [comment]
Take a look at the comments on individual tasks:

- S3 cost allocation tags:
https://github.com/guardian/dotcom-rendering/issues/12442#issuecomment-2454202521
- AWS EC2 cost:
https://github.com/guardian/dotcom-rendering/issues/12463#issuecomment-2454237683
