### ISSUE TITLE
Support Identity Team With API Calls

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#12365]

**Comment by CDicksonG** [comment]
Ashish is currently looking into this for us

**Comment by SiAdcock** [comment]
This is blocked because the old identity API (pre-Okta, using cookies) still gets hit from pages with pressed interactives. We need to form a plan for pressed interactives going forward as pressing unsupported interactives forever not a sustainable solution.

**Comment by shesah** [comment]
@ashishpuliyel any updates on this card? can we help?

**Comment by shesah** [comment]
@SiAdcock to speak to Paul r in I&T to understand what that team needs and then Calvin to speak to Jonathan H on how we address older interactives

**Comment by SiAdcock** [comment]
From @pvighi:

> I noticed that in DCR there still a flag that you can set to not use Okta.  I'm not sure if changing this setting will already break anything but I have a PR ready to go that would make some calls not work unless the flag is set to use Okta.

> is it a problem with you if we move on with the migration and basically force DCR to have the flag set to Okta, or do you normally remove configuration options before they become "dangerous" ?

> To be honest, I'm not sure that changing the Okta flag would not already break anything

**Comment by SiAdcock** [comment]
Closing in favour of [#13020](https://github.com/guardian/dotcom-rendering/issues/13020)
