### ISSUE TITLE
Set liveblog 'block' Share button behaviour based on platform

### ISSUE THREAD

**Issue by shesah** [guardian/dotcom-rendering#12414]
Is it possible to implement the system share on mobile web only, and have the 'Link copied' functionality implemented for all desktop users? Failing that, would it be possible to add the 'Link copied' functionality alongside the system share on desktop only, either with a second 'Copy link' button next to 'Share' or so that when you click the current 'Share' button you copy the link as well as get the system share dialog? 

https://groups.google.com/a/guardian.co.uk/g/dotcom.platform/c/8hkcV3k6Flw

**Comment by domlander** [comment]
Duplicate of https://github.com/guardian/dotcom-rendering/issues/12411
