### ISSUE TITLE
Decouple Source dev kitchen components from `ArticleFormat`

### ISSUE THREAD

**Issue by jamesmockett** [guardian/dotcom-rendering#12493]
The following Source Development Kitchen components include a `format` prop that relies on the `ArticleFormat` type from `@guardian/libs`:

`QuoteIcon`
`ToggleSwitch`
`EditorialButton`

Source components should not be dependent on `ArticleFormat` as this ties them to DCR whereas they should be reusable anywhere. Additionally, we want to relocate the `ArticleFormat` types from `@guardian/libs` to DCR, but this can't be done whilst there are components that rely on them.

`format` is used by all of these components to apply an appropriate colour scheme based on the selected Pillar. They should be refactored so that a colour scheme or theme can be applied in a more generic way that doesn't rely upon `ArticleFormat`.

### `QuoteIcon`

Doesn't appear to be used anywhere. DCR has it's own local copy so we can probably safely remove the `format` prop entirely.

### `ToggleSwitch`

Used by DCR, manage-frontend and support-frontend, but none of these appear to use `format`. `ArticleFormat` isn't used in any meaningful way—the presence of `format` simply toggles between two alternate colour schemes.

### `EditorialButton`

Used by DCR in single place. `format` is used to theme the button using the selected Pillar.

**Comment by SiAdcock** [comment]
Remove QuoteIcon: https://github.com/guardian/csnx/pull/1730
