### ISSUE TITLE
Ad Misalignment In Apps Liveblogs

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#12605]
Steps to reproduce:

1. Open a liveblog or deadblog
2. Navigate to another page
3. Scroll down to find misaligned ads

This could be caused by the fact that we use a URL fragment to scroll the user to the main content of the liveblog when navigating between pages.

![ad-liveblog](https://github.com/user-attachments/assets/2a66b906-085c-41e5-bac4-8c96425607a1)

**Comment by domlander** [comment]
> This could be caused by the fact that we use a URL fragment to scroll the user to the main content of the liveblog when navigating between pages.

I've tested this and it doesn't look to be the case. Removing the scroll to the main content does not affect the misalignment of the ads.

**Comment by arelra** [comment]
Proposed fix here: https://github.com/guardian/ios-live/pull/8257
