### ISSUE TITLE
Turn off US banner A/B test

### ISSUE THREAD

**Issue by shesah** [guardian/dotcom-rendering#12622]
### AB tests
https://github.com/guardian/frontend/blob/main/static/src/javascripts/projects/common/modules/experiments/tests/usa-expandable-marketing-card.js
https://github.com/guardian/dotcom-rendering/blob/main/dotcom-rendering/src/experiments/tests/usa-expandable-marketing-card.ts

This can be turned off if the following are true:
- It is Tuesday 29th October or later
- D&I (Anthony) have told us that we've reached sample size

**Comment by domlander** [comment]
Anthony (D&I): looks like we have just under a million in each variant. Should be more than enough.

We can now turn off the test

**Comment by domlander** [comment]
The test is turned off. No code change at this point, while we wait for the results and the US to decide whether they would like to use this component.

![Image](https://github.com/user-attachments/assets/853d3767-d995-4cbd-a34b-fab615790a6f)
