### ISSUE TITLE
Crosswords Homepage in a Webview for PressReader

### ISSUE THREAD

**Issue by CDicksonG** [guardian/dotcom-rendering#12665]
**Problem:**
A new Editions product will now be provided by [PressReader](https://www.pressreader.com/). This means that the paper will be delivered to PressReader as a pdf. As a result, user's will lose the interactive crossword player that is built in to the editions app. In order to meet the T&Cs of Editions we need to provide access to the last 30 days of crosswords (available in the previous App). 

**Deadline**
Editorial staff that currently work on the Editions product are being moved off of this team in mid December, so we need to provide an alternative solution by **w/c December 16th**.

**Requirements**
- User can access today's crosswords from within PressReader App
- User can access crosswords for last 30 days
- User is able to play crosswords from within the PressReader App

**Proposed Solution**
The Pressreader App provides a puzzles button where we can open a Guardian hosted page in a webview. The lowest effort solution (that we hope can be achieved in time) is to link that puzzles button to a webview of the crosswords front on our site and let the users navigate to the crossword that they would like.
<img src="https://github.com/user-attachments/assets/a52cd9b0-8eb3-4c55-90fc-150fd5762110" width=30% height=30%>

**Concerns**
How is this going to play with...
- Cookie Banner?
- Support Messaging?
- Ads?
- Navigation?
- Comments?
- etc.?

Can we do anything to minimise the elements on the page available to the users through this webview?

Notes: https://docs.google.com/document/d/1GKjaelUGaPVGDhzOttZMSSx36KV8E81csCd8WSNE_W8

**Comment by domlander** [comment]
I'm looking at creating a front-type page that can be used for PressReader:
- Only has Quick and Cryptic crosswords; other crossword types and crossword articles are filtered out.
- No header, footer, pagination, ads, support messaging, cookie banner
- No links other than each crossword
