### ISSUE TITLE
Key Events Horizontal Scrolling On Android

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#12728]
There is a bug on Android that means it's not possible to scroll horizontally through the key events at the top of liveblogs and deadblogs. This does not affect vertical scrolling through the rest of the article.

The options for fixing this are as follows:

1. Fix the horizontal scrolling issue, which would require investigation by an Android developer.
2. On Android only we could either truncate key events to only the first couple that are visible, or hide the key events section entirely. This is not a long term fix, but rather a temporary one until we can do 1).
3. Redesign the key events section to use buttons to navigate rather than relying on a horizontally scrolling area. This will require discussion with Design.

![Image](https://github.com/user-attachments/assets/86fbe8ef-4b03-4b55-9a5a-2b138ec476d6)

**Comment by JamieB-gu** [comment]
We could consider adding a method to Bridget to deactivate Android scrolling behaviour whenever someone attempts to horizontal scroll on certain elements in an article. There was a similar method available in the templates: https://github.com/guardian/mobile-apps-article-templates/blob/ae6d5dcb28ed5f6eecb4d91fe5375b03ac4a6bd6/ArticleTemplates/assets/js/bootstraps/audio.js#L90-L111

Android are going to investigate whether this would work on their side, and we're going to investigate how and when we would call this method on our side.

**Comment by worldofpablo** [comment]
From memory, some other horizontal-scroll element encountering issues on Android on DCAR:

- Carousels like on https://www.theguardian.com/thefilter/2024/oct/10/best-walking-boots-hiking-men-tried-tested
- Before-after photos (depending on how they're implemented)  

We should retest these if making a fix on the Android end of things for Key Events.

**Comment by marjisound** [comment]
We're currently waiting for the Bridget PR https://github.com/guardian/bridget/pull/172 to be merged so we can update DCR PR https://github.com/guardian/dotcom-rendering/pull/12836 with the new Bridget version and start using the function. @arelra and I are also discussing the Bridget naming for the new service and function with the Android developers.

**Comment by SiAdcock** [comment]
Should this ticket be closed @marjisound ?

**Comment by SiAdcock** [comment]
From @marjisound : Had a catch up with Rob from android, they’re planning to release horizontal scroll to Beta on Tuesday. Though the next android prod release will be on 6th January
