### ISSUE TITLE
Add new crossword endpoint to frontend

### ISSUE THREAD

**Issue by SiAdcock** [guardian/dotcom-rendering#12797]
Create an endpoint in frontend. This will act as the entry point for crosswords from the Guardian Digital Editions app.

This may initially return a dummy page or a 200 response. Having this in place gives us a route for our Fastly service to point to.

![Image](https://github.com/user-attachments/assets/923f48c6-e971-4eb2-81f2-ac92b2a47c60)

**Comment by rowannekabalan** [comment]
https://github.com/guardian/frontend/pull/27591
