### ISSUE TITLE
Design Types

### ISSUE THREAD

**Issue by gtrufitt** [guardian/dotcom-rendering#1362]

**Comment by gtrufitt** [comment]
+1 maybe graphql can help

**Comment by paperboyo** [comment]
![Young_Boy_and_His_Mother_in_an_Artist's_Studio_by_Charles_Rousseau](https://user-images.githubusercontent.com/6032869/128040865-50e852bf-7ccf-498f-a10d-a3c3bef27201.jpg)

**Comment by jamesgorrie** [comment]
No idea what this is
