### ISSUE TITLE
Lighthouse Scores with and without the commercial bundle

### ISSUE THREAD

**Issue by oliverlloyd** [guardian/dotcom-rendering#2210]
## What is this?
Just a snapshot on where we are with our lighthouse scores with and without the commercial bundle. Hopefully this is useful as a comparison when testing any future improvements in this area.

## On desktop

With                                     |  Without
:-------------------------:|:-------------------------:
![](https://user-images.githubusercontent.com/1336821/101492864-2c207b00-395d-11eb-988c-f45afe53dcf1.jpg)  |  ![](https://user-images.githubusercontent.com/1336821/101492869-2cb91180-395d-11eb-9f6b-196cec6abc0a.jpg)

## On mobile

With                                     |  Without
:-------------------------:|:-------------------------:
![](https://user-images.githubusercontent.com/1336821/101492860-2aef4e00-395d-11eb-8952-fb2f1433f71e.jpg)  |  ![](https://user-images.githubusercontent.com/1336821/101492866-2c207b00-395d-11eb-8222-ef092da41288.jpg)

## How was the bundle removed?
Simply by commenting out [the line](https://github.com/guardian/dotcom-rendering/blob/main/src/web/server/document.tsx#L90) to add the script in `document.ts`

```typescript
    const priorityScriptTags = generateScriptTags(
        [
            { src: polyfillIO },
            { src: 'ophan.js', module: true },
            // CAPI.config && { src: CAPI.config.commercialBundleUrl },
            { src: 'sentry.js', module: true },
            { src: 'dynamicImport.js', module: true },
            { src: 'react.js', module: true },
        ].filter(Boolean),
        'defer',
    );
```

**Comment by oliverlloyd** [comment]
## How do I run this test locally?
Clone DCR, then:
- run `make build && make start`
- visit: http://localhost:9000/Article?url=https://www.theguardian.com/world/2020/dec/08/yemeni-woman-makes-epic-eight-month-journey-to-reach-uk

(I recommend not using the default Harry Potter article as the results there don't seem realistic)

### Why do I get a permissions error trying to write log?
Run `sudo chmod 777 /var/logs` (sorry)

**Comment by alinaboghiu** [comment]
@SiAdcock FYI
