### ISSUE TITLE
Developer blog posts aren't responsive

### ISSUE THREAD

**Issue by jamesgorrie** [guardian/dotcom-rendering#4005]
reported by: David Furey
via: chat https://chat.google.com/room/AAAAG9rU0m0/Wdp9ONJNnxA [not public]
on: 15 Feb 2022

> mentioned that our developer blog posts aren't responsive at mobile breakpoints - e.g. https://www.theguardian.com/info/2022/feb/01/creating-pinned-posts-on-our-live-blogs
>
> My guess is that code blocks have a minimum size.  The audience for these pieces is small, but arguably the impact on potential candidates is quite high.

**Comment by mxdvl** [comment]
I think this is only an issue when resizing a page.

As it works with JS disabled, I think this might be due to the Twitter embeds.

**Comment by OllysCoding** [comment]
Closing as the twitter embed resizing bug is a known issue on the site
