### ISSUE TITLE
Showing off our beautiful videos

### ISSUE THREAD

**Issue by jamesgorrie** [guardian/dotcom-rendering#4006]
reported by: Nikhita Chulani
via: email "Re: Immersive video"
on: 15 Feb

> This lovely feature of the [Novak interview on the BBC website](https://www.bbc.co.uk/news/world-60354068) made me want to raise this issue again: is there any chance we could introduce making videos bigger on the website? 
>
> I think it would be brilliant if this is something we could add and I find at least one example a day. I think it could make an article look better and have a great impact. 
>
> Additionally, we have had desk editors tell us they haven't wanted to embed video for the aesthetic alongside immersive images.

**Comment by paperboyo** [comment]
Oooh, a comeback of issues?

Tools should give you `role`s soon-insh. There is [this problem](https://github.com/guardian/frontend/pull/15193#issuecomment-265346621) of poster frame images being one quality only (should be possible even within constraints of `background-image`).

Not sure about videos in Immersive Main media. At least not the atom ones. Playable, short, silent, control-less lopps – yeah.

**Comment by VDuczekW** [comment]
closing as this work will be done by Tools
