### ISSUE TITLE
Question on the roll out of comments

### ISSUE THREAD

**Issue by jamesgorrie** [guardian/dotcom-rendering#4039]
reported by: Lucy
via: chat https://mail.google.com/chat/u/0/#chat/space/AAAAG9rU0m0/GfZTOAKQyx8 (internal)
on: 16 Feb 2022

when DCR rolled out on articles, did anything substantial change in how we display comments?

we've seen a huge drop in the number of clicks to the "read more" comments button

at around the time of the initial roll out

do we possibly display it less now or?

**Comment by OllysCoding** [comment]
@jamesgorrie to follow up

**Comment by jamesgorrie** [comment]
Closing off as I haven't heard back from the people who raised it.
