### ISSUE TITLE
Wide ads served as square ads break layout

### ISSUE THREAD

**Issue by jamesgorrie** [guardian/dotcom-rendering#4041]
Misbehaving advert on DCR liveblog? https://www.theguardian.com/world/live/2022/feb/16/covid-news-live-south-korea-reports-record-number-of-cases-china-tells-hong-kong-to-stabilise-outbreak?dcr=&filterKeyEvents=false

<img width="1456" alt="Screenshot 2022-02-21 at 20 03 29" src="https://user-images.githubusercontent.com/31692/155020265-1fb2b8f3-efc6-451a-bcbe-e4dc310b4182.png">

**Comment by mxdvl** [comment]
Looping in @guardian/commercial-dev for visibility.

**Comment by OllysCoding** [comment]
@jamesgorrie @guardian/commercial-dev to follow up
