### ISSUE TITLE
Links going to the wrong places

### ISSUE THREAD

**Issue by jamesgorrie** [guardian/dotcom-rendering#4042]
reported by: Akash
via: chat https://chat.google.com/room/AAAAG9rU0m0/kiqbu5di_qU (internal)
on: 19 Feb 2022

Hi, I've spotted a bug. The links in the header seem a little wonky:
  - Subscriptions goes to jobs.theguardian.com (rather than subscribe.theguardian.com?)
  - Search jobs goes to profile.theguardian.com

I'm signed in via Google with my @guardian.co.uk account.

Visiting profile.theguardian.com, incorrectly, triggers a new sign-in flow, but I don't think that's related.

The behaviour is seen on pages from all sections, but the URL in the video is https://www.theguardian.com/football/2022/feb/19/west-ham-newcastle-premier-league-match-report

https://user-images.githubusercontent.com/31692/155020863-960d2ebb-cc2c-4430-a6e2-dbf1a8121769.mov

**Comment by OllysCoding** [comment]
@OllysCoding To follow up with Akash

**Comment by OllysCoding** [comment]
This bug appears to affect anyone on the site who has a subscription (which causes the 'subscriptions' link to be added to the page)
