### ISSUE TITLE
embed.ly oembeds are returning `url: ""` for Vimeo embeds

### ISSUE THREAD

**Issue by jamesgorrie** [guardian/dotcom-rendering#4057]
It seems [embed.ly](http://embed.ly/) returns `""` as the `url` in the oembed response for vimeo. This is odd, as you can see a more expected result for youtube.

https://embed.ly/docs/explore/oembed?url=https%3A%2F%2Fvimeo.com%2F539597768
https://embed.ly/docs/explore/oembed?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DW8HVOBzg2pE

Composer uses this response directly, so bubbles down the pipeline to frontend.

We have raised a support ticket with embed.ly.

**Comment by OllysCoding** [comment]
@jamesgorrie to follow up

**Comment by rhiannareechaye** [comment]
@jamesgorrie this looks like it's over a year old so we are putting in the 'to be closed' bucket
