### ISSUE TITLE
Bundle size increased by 400kB (68%)

### ISSUE THREAD

**Issue by DavidLawes** [guardian/dotcom-rendering#4089]
Speedcurve shows that the bundle size shot up by 68%. We should investigate the root cause for this (it's also impacting time to interactive).

**Comment by oliverlloyd** [comment]
This has gone back down again now. This has happened previously and related to a third party script - this could have been the same thing?

**Comment by DavidLawes** [comment]
Thanks - I'd noticed this too, which was why we didn't pick this up (other 'more important' (?) things came along).
