### ISSUE TITLE
Indentation for quotes

### ISSUE THREAD

**Issue by oliverlloyd** [guardian/dotcom-rendering#4156]
DCR
<img width="670" alt="Screenshot 2022-03-03 at 11 45 01" src="https://user-images.githubusercontent.com/1336821/156558553-99801106-a7c5-4ac0-835a-8c73b2f4fc75.png">

Frontend
<img width="564" alt="Screenshot 2022-03-03 at 11 44 29" src="https://user-images.githubusercontent.com/1336821/156558561-e034f846-b248-4ba3-aa1c-12e22d69b74c.png">

**Comment by mxdvl** [comment]
DCR is the one we want, and has been implemented in #4022.

The missing link is maybe something we want to address, but in this is a case of DCR being closer to the design intent.
