### ISSUE TITLE
The chevrons on `Accordion` are not semantically marked up

### ISSUE THREAD

**Issue by oliverlloyd** [guardian/dotcom-rendering#4162]
For accessibility and to be able to show the right pointer on hover we should use a `button` or `a` tag here

![2022-03-03 12 13 12](https://user-images.githubusercontent.com/1336821/156562705-c4bc2d64-2729-4b32-a1fb-3a86c6252287.gif)

**Comment by AshCorr** [comment]
I *think* this shouldn't be an issue as the Icon itself is purely a visual guide and not actually interactive (the <summary> element that "Key Events ^" is wrapped in is the actual interactive part). It seems like screen readers, etc, already have good support for <summary> elements and will tell the user if a section can be collapsed.

Will double check if this is the case though, maybe we might need to add aria-ignore to the icon itself.
