### ISSUE TITLE
Images in rich links

### ISSUE THREAD

**Issue by AshCorr** [guardian/dotcom-rendering#4172]
Decide if we should continue to render images in rich links.

Currently this seems tempermental in Frontend where sometimes it renders images and sometimes it doesn't.

Images can sometimes look [out of](https://m.code.dev-theguardian.com/business/live/2022/feb/11/uk-gdp-december-2021-omicron-recovery-stock-markets-ftse-inflation-fed-business-live) [place](https://www.theguardian.com/football/live/2022/feb/09/manchester-city-v-brentford-tottenham-v-southampton-premier-league-live?page=with:block-62043a678f08b0eb1f62bd9a#block-62043a678f08b0eb1f62bd9a), especially in liveblogs.

Let's decide if we want to continue rendering images and what we can do to improve them

**Comment by oliverlloyd** [comment]
After speaking with @HarryFischer & also @alinaboghiu I'm going to prevent the image on rich links when showing in a blog. This removes the problems that loading images in on the client introduces (CLS, poor quality images, image overload). If we decide later that we want to restore rich link images for all or some rich links we can address the best way to do this at that time
