### ISSUE TITLE
Analysis Card underline

### ISSUE THREAD

**Issue by mxdvl** [guardian/dotcom-rendering#4191]
The line-height of Analysis cards does not match the `background-size` of the underline.

<img width="242" alt="image" src="https://user-images.githubusercontent.com/76776/157001964-18fd2b3d-c329-42c8-99de-422ae0615612.png">

Most recent PR touching these is #4048

**Comment by AshCorr** [comment]
This also seems to be an issue with frontend (screenshot from https://www.theguardian.com/tone/analysis)

<img width="1308" alt="image" src="https://user-images.githubusercontent.com/21217225/164474441-f0cc7c01-9a52-4441-8665-c6875b8f7307.png">

**Comment by AshCorr** [comment]
Going to leave Frontend out of this as this issue will be fixed once the current migration to DCR is done.
