### ISSUE TITLE
Visual Run-Through Of Deadblogs

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#4224]
We'll want to perform a visual run-through of deadblogs to capture any issues before they go out, similar to the process we followed for deadblogs and liveblogs on dotcom.

**Comment by JamieB-gu** [comment]
@VDuczekW shall we organise something for a group of us to do this?

**Comment by VDuczekW** [comment]
@JamieB-gu yes lets - who needs to be involved and how long and i will sort

**Comment by JamieB-gu** [comment]
I suspect it would be good to have:

- The AR bubble: myself, Iain and Mario
- Design/UX: Harry, Priscilla and Ben W
- Dotcom: anyone who wants to come
- Apps: any volunteers - so far: Frankie (@frankie297)
- Mateusz (@paperboyo)
- Marjan? - @marjisound you did a lot of the work on deadblogs, so let us know if you want to come 🙂

I think the Dotcom one was half an hour, so we could make it the same. We can also probably have a doc for people to write up the issues in, as with the Dotcom one.

**Comment by VDuczekW** [comment]
@JamieB-gu set up catch up for tomorrow.

**Comment by marjisound** [comment]
Thanks @JamieB-gu I'd certainly like to join the run through 🙂

**Comment by JamieB-gu** [comment]
We completed this today and gathered a document of possible problems. Next task is to work through and do the following:

- De-duplicate and write up issues for the problems
- Decide which issues are blockers for getting deadblogs out in Beta, and add those to the "Deadblogs Beta Release" milestone
- Put all other issues in the backlog, possibly creating milestones to organise them

**Comment by VDuczekW** [comment]
@JamieB-gu shall i put something in so the de-duping gets done? Like a refinement session where we de-dupe while adding the items in the backlog and label. AR bubble and Harry?

**Comment by JamieB-gu** [comment]
This is done - next steps in #4314.
