### ISSUE TITLE
Change Blockquote Design On Blogs

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#4227]
@HarryFischer recommended that we change the way blockquotes look on blogs to reflect some newer designs. @mxdvl recently implemented this in #4022, so perhaps we can re-use/share some stuff?

**Note:** Harry is this something we should be considering for other article formats too?

## Designs

| Before (AR) | After (Current DCR) |
| - | - |
|  ![pullquote-before](https://user-images.githubusercontent.com/53781962/157737296-b333b171-19c7-42bb-86a6-e9c9fe328835.jpg) | ![pullquote-after](https://user-images.githubusercontent.com/53781962/157737301-39f859b8-758d-4944-bda4-7f2741e78d7b.jpg) |

**Comment by mxdvl** [comment]
The way we achieve this is to make the SVG inline, embedded within the quote itself. In DCR, this is achieved by leveraging the `unwrapHtml` method.

```tsx
<blockquote>
   <p><svg />My Great Quote.</p>
</blockquote>
```
