### ISSUE TITLE
Image Captions - Replace Triangle With Camera

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#4228]
@HarryFischer recommended that we replace the triangle icon that appears in image captions with a camera icon. This change has already been made on DCR so you can see examples of this on most articles on dotcom. The change can be made here:

https://github.com/guardian/dotcom-rendering/blob/35d5d5b6de53a9a7502c92998e95c3c27cd7302a/common-rendering/src/components/figCaption.tsx#L95-L101

**Comment by HarryFischer** [comment]
Also need to make caption font-size 14px
