### ISSUE TITLE
TikTok embeds not working on some browsers

### ISSUE THREAD

**Issue by OllysCoding** [guardian/dotcom-rendering#4232]
Reported by: Matthew Holmes
Browser version(s): Chrome 94.0.4606.81
Chat-link (private): https://chat.google.com/room/AAAAG9rU0m0/ZY-_9IaYrtg

We've receiving reports that the TikTok embed on this article: https://www.theguardian.com/world/2022/mar/11/diana-totok-ukraine-escape-tiktok ([wayback url](https://web.archive.org/web/20220311115835/https://www.theguardian.com/world/2022/mar/11/diana-totok-ukraine-escape-tiktok)) does not work.

Tiktok embed looks like this after accepting the consent overlay
<img width="626" alt="image" src="https://user-images.githubusercontent.com/9575458/157880597-4314f918-48ce-4903-9ef6-5cc6a5d7a6e0.png">

**Comment by rhiannareechaye** [comment]
We are deprioritising this ticket by 'closing a not planned' - this won't delete the ticket and it will be searchable if the issue crops up again. Unfortunately we have over 130 health tickets to address in the web team. With so many tickets we are potentially missing things that are high-impact so we're reorganising the board - if we can get through all our high-impact tickets we can re-open these lower impact ones.

**Comment by rhiannareechaye** [comment]
We are deprioritising this ticket by 'closing a not planned' - this won't delete the ticket and it will be searchable if the issue crops up again. Unfortunately we have over 130 health tickets to address in the web team. With so many tickets we are potentially missing things that are high-impact so we're reorganising the board - if we can get through all our high-impact tickets we can re-open these lower impact ones.
