### ISSUE TITLE
Lines go through byline in AMP article

### ISSUE THREAD

**Issue by OllysCoding** [guardian/dotcom-rendering#4236]
Raised by: Tom Richards
Original Discussion: https://chat.google.com/room/AAAAG9rU0m0/vHLvpxhXdHk (private)
Article: https://amp.theguardian.com/world/commentisfree/2022/mar/09/poland-ukrainians-refugees-history

The horizontal lines should not be going through the text, they should be below the byline (with some space)
<img width="677" alt="image" src="https://user-images.githubusercontent.com/9575458/158155935-ffd7c7eb-8c18-44c9-acd5-5dc8c0cc95bc.png">
<img width="397" alt="image" src="https://user-images.githubusercontent.com/9575458/158156644-c771ca29-87a8-4a14-a253-f7c94ce3918a.png">

**Comment by OllysCoding** [comment]
@HarryFischer if I set the spacing to be the same as we see on the non-amp version; we get something which looks more like: 
<img width="429" alt="image" src="https://user-images.githubusercontent.com/9575458/158207833-ab289305-688c-4587-9226-bcf32d45d11a.png">

I'm not sure if this is _**too**_ much spacing (43px blow the text) ~ what do you think? Also does it look like it needs extra margin on the bottom as well?

**Comment by HarryFischer** [comment]
👍
