### ISSUE TITLE
Flakey Cypress tests failing on TeamCity

### ISSUE THREAD

**Issue by oliverlloyd** [guardian/dotcom-rendering#4264]
Note from Tom W copied from Dotcom channel:

> I've got a couple of cypress failures on the build for my branch here: https://teamcity.gutools.co.uk/buildConfiguration/dotcom_rendering/752383?showRootCauses=false&pluginCoverage=true&expandBuildProblemsSection=true&expandBuildChangesSection=true&showLog=752383_6131_494 (specifically parallel-1/article.e2e.spec.js and parallel-3/article.interactivity.spec). They ran fine in GHA. I'm guessing these are just sporadic failures. Would you just re-run the build and hope they resolve themselves?

**Comment by OllysCoding** [comment]
I don't think this is completely resolved, but I'm closing this card for the time being!
