### ISSUE TITLE
Standard interactive: Immersive images come across small and low res

### ISSUE THREAD

**Issue by VDuczekW** [guardian/dotcom-rendering#4290]
First image in this article is set to immersive in composer.
https://composer.gutools.co.uk/content/61a74e308f08d4d8978b3785
The idea would be to use it full width (max-width 1300px) but the image I am served is quite small and therefor blurry at this size:
https://i.guim.co.uk/img/media/3d70c04e183f3ca2358a2d2345a12004141a0808/0_135_3500_2101/master/3500.jpg?width=620&quality=85&auto=format&fit=max&s=2f6d636994686743d8cac0023dd18627

**Comment by HarryFischer** [comment]
@bryophyta Yep all looks good now
