### ISSUE TITLE
Have monitoring on DNS records for theguardian.com

### ISSUE THREAD

**Issue by VDuczekW** [guardian/dotcom-rendering#4293]
We need a way to alert us if the CNAME record is something else than expected.

Third parties should be investigated before building our own.

See first action here:
https://docs.google.com/document/d/1SI58Kkgh_Gw5eYa-C6V3F5oN9gWfZhtttROB6tinYXQ/edit#heading=h.cq45l71z1e8q - Connect to preview

**Comment by shesah** [comment]
Will not fix/do
