### ISSUE TITLE
Multiple cmp bundles being requested

### ISSUE THREAD

**Issue by VDuczekW** [guardian/dotcom-rendering#4295]
[](https://www.theguardian.com/uk-news/2020/jan/09/prince-harry-meghan-decision)[](https://www.theguardian.com/uk-news/2020/jan/09/prince-harry-meghan-decision)This card is worth checking after App.tsx has been removed - this bug could be a result of using both App.tsx and Islands.

It was noticed on some articles (eg [Prince Harry and Meghan’s decision to 'escape' looks like a carefully laid plan](https://www.theguardian.com/uk-news/2020/jan/09/prince-harry-meghan-decision)) that the cmp bundle was requested multiple times.

Before the change to youtube block components as an Island ([guardian/dotcom-rendering: Pull Request 3887](https://github.com/guardian/dotcom-rendering/pull/3887)) the bundle was requested twice. After the migration the bundle was requested 3 times.

It would be expected that webpack already knows about cmp from the 1st request and reuse it, meaning it shouldn't request it multiple times.

**Comment by VDuczekW** [comment]
see the Trello for previous comments https://trello.com/c/6i91denk/703-move-to-githb-multiple-cmp-bundles-being-requested

**Comment by mxdvl** [comment]
I don’t think this is actually happening: the`cmp.js` file has nothing to do with us!

it comes from https://ced-ns.sascdn.com/diff/js/modules/cmp.js
