### ISSUE TITLE
Main media image missing on specific blog

### ISSUE THREAD

**Issue by MarSavar** [guardian/dotcom-rendering#4296]
Main media image missing on specific blog, e.g. 
https://mobile.guardianapis.com/rendered-items/fashion/live/2015/feb/12/kanye-wests-yeezy-boost-sneaker-launch-live

**Comment by MarSavar** [comment]
Paired with @iainjchambers-guardian and @JamieB-gu on this - it turns out the main media image in that blog does not have a master asset, which is why it's not being displayed. We're currently investigating the reason.

**Comment by JamieB-gu** [comment]
The next steps on this are in #4351. It's a problem on all articles, not just here, so not specifically a blocker for Beta Deadblogs.
