### ISSUE TITLE
Comment permalinks not working

### ISSUE THREAD

**Issue by VDuczekW** [guardian/dotcom-rendering#4297]
Navigate to a profile's comments section page e.g. indigenousbrit's public profile | Identity | The Guardian
Try to navigate to one of the 'view discussion' links e.g. The 20 best recipes for the weekend

The article loads correctly, but does not scroll down to the user's comment.

I wonder if this may be to do with the fact that discussion-rendering is lazy-loaded?

**Comment by VDuczekW** [comment]
is this still needed - was converting Trello https://trello.com/c/HCtFozEA/464-move-to-github-comment-permalinks-not-working but can see this PR attached which is merged https://github.com/guardian/dotcom-rendering/pull/3873 
@oliverlloyd & @mxdvl

**Comment by oliverlloyd** [comment]
That other PR partially fixed this issue but comment permalinks are still broken, sadly 😞

**Comment by VDuczekW** [comment]
@mxdvl & @bryophyta please check and see if this can be linked or closed due to a dupe ticket existing
