### ISSUE TITLE
Write Up Issues From Visual Run-Through

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#4314]
Next step from #4224. We've done the visual run-through and split the resulting issues into two categories:

1. Required for Deadblogs Beta Release
2. Non-blockers for Deadblogs Beta Release

We've created tickets for the first category and moved them into the milestone. We now need to write up the much longer list of issues that can go into the backlog.

**Comment by MarSavar** [comment]
All done :)
