### ISSUE TITLE
Padding between image and caption is too large 

### ISSUE THREAD

**Issue by marsavar** [guardian/dotcom-rendering#4328]
The padding between image and caption is too large / the caption line-height looks too large.

**Comment by JamieB-gu** [comment]
Is this just main media or all images? Is this just blogs or is it all articles?

cc @HarryFischer

**Comment by HarryFischer** [comment]
all AR articles but not main media (these have captions hidden behind the yellow camera circle) @JamieB-gu

**Comment by JamieB-gu** [comment]
Second part done, first part still needs looking at.

**Comment by georgeblahblah** [comment]
Won't do now that we are rendering apps articles in DCR
