### ISSUE TITLE
The tag and headline ascenders should align on wider breakpoints

### ISSUE THREAD

**Issue by MarSavar** [guardian/dotcom-rendering#4332]
On wider breakpoints - where we have leftCol - the tag and headline ascenders should align

**Comment by MarSavar** [comment]
@HarryFischer could you please clarify what ascenders are?
I think we discussed it in the call but my memory is a bit fuzzy 🙈

**Comment by JamieB-gu** [comment]
<dl>
  <dt>Ascenders</dt>
  <dd>The part of a letter than extends above the height of a lowercase <code>x</code> (<code>x-height</code>) in a font.</dd>
  <dt>Descenders</dt>
  <dd>The part of a letter than extends below the baseline of a font (the line on which most letters sit).</dd>
</dl>

For example, the letters `h`, `t`, `f` etc. and most (all?) capitalised letters have ascenders; the letters `y`, `p`, `q` etc. have descenders ("tails").

That's my attempt at explaining it anyway 🙂, @paperboyo can probably give a better explanation/correct anything I've got wrong.

**Comment by JamieB-gu** [comment]
#5852
