### ISSUE TITLE
Tapping on the published time doesn’t give you the first published time

### ISSUE THREAD

**Issue by marsavar** [guardian/dotcom-rendering#4333]
Tapping on the published time doesn’t give you the first published time.
- Maybe consider something similar for last updated at the bottom of blocks
- Timestamp at the button left of the block has a different format from DCR.
    - AR: `Updated: 06.10am 16 Mar 2022 GMT`
    - DCR: `Updated at 6.10am GMT`
- Maybe use the DCR version but show the longer version using a details/summary

**Comment by georgeblahblah** [comment]
Won't do now that we are rendering apps articles in DCR
