### ISSUE TITLE
Missing ‘Live feed’ title and chevron 

### ISSUE THREAD

**Issue by MarSavar** [guardian/dotcom-rendering#4337]
Wider conversations to be had about this feature across platforms.

This is what it looks like on DCR - currently missing in AR.

<img width="495" alt="image" src="https://user-images.githubusercontent.com/57295823/159252664-61b61902-da32-4c31-b692-37cb4125f83b.png">

**Comment by JamieB-gu** [comment]
Is this something we still want @HarryFischer ?

**Comment by HarryFischer** [comment]
I'll check. Can we make sure the Key events can be collapsed though

**Comment by JamieB-gu** [comment]
> Can we make sure the Key events can be collapsed though

Yup, that's done 👍

**Comment by georgeblahblah** [comment]
@HarryFischer I'm happy to take a look at this, but wanted to double check if it's still relevant?

**Comment by HarryFischer** [comment]
@georgeblahblah We can close this ticket - this feature is being phased out on Dotcom. 
See: https://www.theguardian.com/business/live/2022/jul/25/ryanair-covid-19-variants-recovery-oil-recession-markets-dover-disruption-business-live at mobile breakpoint

**Comment by georgeblahblah** [comment]
Thanks @HarryFischer, good to know!
