### ISSUE TITLE
Replace Greenwich Mean Time with GMT

### ISSUE THREAD

**Issue by MarSavar** [guardian/dotcom-rendering#4338]
This is to achieve consistency with DCR.
Also consider other timezones.

AR at the moment:
<img width="239" alt="image" src="https://user-images.githubusercontent.com/57295823/159253381-1c785abe-b699-4284-a7ca-d89a9d72fcfd.png">

**Comment by JamieB-gu** [comment]
This may actually be the result of #4391.

**Comment by georgeblahblah** [comment]
Fixed in #4391
