### ISSUE TITLE
Show pinned icon on posts that are pinned

### ISSUE THREAD

**Issue by oliverlloyd** [guardian/dotcom-rendering#4346]
If a in body post [is pinned](https://www.theguardian.com/politics/live/2022/mar/21/boris-johnson-ukraine-brexit-sajid-javid-coronavirus-uk-politics-latest-updates?page=with:block-6238a48e8f0832c62ade2e90&dcr=false#block-6238a48e8f0832c62ade2e90) it should have an icon highlighting this

<img width="652" alt="Screenshot 2022-03-21 at 16 44 19" src="https://user-images.githubusercontent.com/1336821/159312386-b3a812f7-835d-44b4-bbb0-7deea977c157.png">

note. This screenshot if from Frontend, the date is positioned differently for DCR

**Comment by abeddow91** [comment]
https://github.com/guardian/dotcom-rendering/pull/4368
