### ISSUE TITLE
Apps Are Kicking MAPI URLs Out To Browser/Templates WebView

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#4367]
Articles in the apps are rendered in webviews. Articles, being web-based, often contain links to other content. Currently these links are handled as follows:

| Type Of URL | How it's handled |
| - | - |
| Third-Party | Kicked out to a browser (in-app or system browser) |
| First-Party - theguardian.com | Captured and redirected to app view if possible (articles and fronts/list pages) |
| First-Party - mobile.guardianapis.com (MAPI) | Kicked out to a browser (Android) or webview opens to old templates version (iOS) |

The third category is causing us some problems. For example, in blogs we have relative URLs (MAPI URLs) in key events, block permalinks, pagination buttons etc. Currently, instead of taking the user to a specific block or to the next page they're kicking out to a browser or going to an old templates version.

Is there some way we can keep links to MAPI URLs inside the app/AR webview?

**Comment by michaelclapham** [comment]
On the Android side I think a fix as a part of this bug issue: https://theguardian.atlassian.net/browse/LIVE-3891 might solve the problem on Android (depending on how it's done)

**Comment by JamieB-gu** [comment]
This is currently sitting with the iOS and Android teams, with JIRA tickets to track progress. cc @Reettaphant

**Comment by JamieB-gu** [comment]
@michaelclapham @tahaamini would you say this work is done now?

**Comment by tahaamini** [comment]
on the iOS side yes.

**Comment by michaelclapham** [comment]
Yes this is fixed on the Android side. Except in the unusual case of links where the edition is in the path before the /rendered-items/ https://mobile.guardianapis.com/uk/rendered-items/world/2022/may/17/ufo-briefing-us-congress-military for example gets served up by apps rendering but when you try to launch that in the app it will tell you it's unsupported content.
