### ISSUE TITLE
Add `/Front` endpoint to DCR

### ISSUE THREAD

**Issue by oliverlloyd** [guardian/dotcom-rendering#4410]
- [ ] - DCR exposes the `/Front` endpoint accepting the json for a front
- [x] - DCR returns a dummy page

**Comment by jamesgorrie** [comment]
Would this be a chance to potentially think of breaking the apps into smaller micro-services? Or at least thinking about it for when another requirement of the service comes up?

Potentially having the project look something like:
- dotcom-rendering/fronts
- dotcom-rendering/articles

Where articles is what we have now. 

I know this will need a little upfront work and I don't want to slow the migration. It would also be good to have another requirement before doing this prematurely ([rule of three](https://en.wikipedia.org/wiki/Rule_of_three_(computer_programming))), but it felt like a good time to start talking about it.

**Comment by oliverlloyd** [comment]
> Would this be a chance to potentially think of breaking the apps into smaller micro-services? Or at least thinking about it for when another requirement of the service comes up?
> 
> Potentially having the project look something like:
> 
> * dotcom-rendering/fronts
> * dotcom-rendering/articles
> 
> Where articles is what we have now.
> 
> I know this will need a little upfront work and I don't want to slow the migration. It would also be good to have another requirement before doing this prematurely ([rule of three](https://en.wikipedia.org/wiki/Rule_of_three_(computer_programming))), but it felt like a good time to start talking about it.

In the meeting this morning we saw that there were potentially some common areas between rendering an article and a front but we thought that a good approach would be to move forward with a new rendering stack for Fronts now and then look at where we have common touch points later. 

This doesn't really address the problem of where code should live though and what it should be called. I'd be wary of a brand new root folder but I do think we could consider some sort of re-organisation to rationalise things

**Comment by oliverlloyd** [comment]
Does this problem - need to figure out a place to put things - justify a tool like NX? That's a pretty big hammer...

**Comment by oliverlloyd** [comment]
> Looking at [this PR](https://github.com/guardian/dotcom-rendering/pull/4432/files) though, it seems the rendering is coupled

I think this PR is presenting some dummy code but isn't _exactly_ where what we want to end up? But I'm not sure on that.

**Comment by mxdvl** [comment]
>  […] a new rendering stack for Fronts now […]

I don’t think we wanted to introduce a completely separate stack at this point, but rather a whole different method for generating the HTML. Much like we have different paths for `/KeyEvents` and `/Blocks`, `/Front` can have its own `renderFrontHtml`.

**Comment by mxdvl** [comment]
There’s still nothing hooked up on the `frontend` side to send the appropriate JSON
