### ISSUE TITLE
Create migration dashboard for Fronts

### ISSUE THREAD

**Issue by oliverlloyd** [guardian/dotcom-rendering#4414]

**Comment by jamesgorrie** [comment]
Do we want to, or would we already be measuring our performance metrics?

**Comment by oliverlloyd** [comment]
> Do we want to, or would we already be measuring our performance metrics?

I add https://github.com/guardian/dotcom-rendering/issues/4415 for this 😉

**Comment by oliverlloyd** [comment]
Closed by https://logs.gutools.co.uk/goto/ae184cf0-b0da-11ec-8147-294a9e488936
