### ISSUE TITLE
Create Performance dashboard for Fronts

### ISSUE THREAD

**Issue by oliverlloyd** [guardian/dotcom-rendering#4415]
Ask D&I to create a core web vitals view for Fronts

- [x] Add a front to lighthouse script

**Comment by guyparr** [comment]
Do we know what fronts you want this to include (eg, all fronts/network fronts/pressed fronts etc)? I think you were talking about "pressed" fronts being the priority for the migration, although I don't think we have an easy way of identifying them in the lake. I can probably have a look putting together a list if you guys don't have one.

**Comment by VDuczekW** [comment]
Starting point is to measure the core web vitals @guyparr

**Comment by guyparr** [comment]
Hi Victoria. I shared this a few weeks back, which is a version of the existing CWV dashboard but just for fronts:

https://tableau.gnmremote.com/#/views/DotcomWebVitals-Fronts/Singlefilterview

It can be split and filtered by frontend, DCR, and DCR could render, using the experiences field in pageview.

**Comment by VDuczekW** [comment]
we are using this and are also working on improving https://metrics.gutools.co.uk/d/oi0YcYI4k/web-vitals- this ticket can be marked as done
