### ISSUE TITLE
Subnav: make close icon sticky

### ISSUE THREAD

**Issue by DavidLawes** [guardian/dotcom-rendering#4437]
Until tablet, if the menu is expanded, the menu close icon should stick. Currently we can scroll and the close icon is out of view.

https://user-images.githubusercontent.com/45561419/160574681-028a1c63-a9d2-475d-9eb1-e70203c4e51f.mp4

**Comment by AshCorr** [comment]
Seems like this has been completed already!

**Comment by paperboyo** [comment]
I just **always** try to swipe this menu to close! Just saying…
