### ISSUE TITLE
Issue ID: DAC_Frame_Without_Title6 - Feature: Interactive atom

### ISSUE THREAD

**Issue by VDuczekW** [guardian/dotcom-rendering#4455]
Report Link: https://drive.google.com/file/d/1WXZv1vVNRX9kH8XDmzjtS9LIHQSwTKfS/view
Full list of issues: https://docs.google.com/spreadsheets/d/1vWQtZfD49uq7uNCNELuYN_HcIj-BKiE4t4Hwda3tJaQ/edit#gid=0

**Comment by bryophyta** [comment]
my feeling is that this is a relatively systematic issue, which might merit coordination with other teams to  get a robust solution. I've written up notes for this which I hope to discuss at the next accessibility mobbing day.

**Comment by alinaboghiu** [comment]
fixed by #9981
