### ISSUE TITLE
Issue ID: DAC_Frame_Without_Title7 - Feature: Interactive atom

### ISSUE THREAD

**Issue by VDuczekW** [guardian/dotcom-rendering#4456]
Report Link: https://drive.google.com/file/d/191HsiVHkzD7yqngZNDqHfFI9bnBu4RsF/view
Full list of issues: https://docs.google.com/spreadsheets/d/1vWQtZfD49uq7uNCNELuYN_HcIj-BKiE4t4Hwda3tJaQ/edit#gid=0

**Comment by SiAdcock** [comment]
We don't know the impact of this change and it would be useful to understand this.

**Comment by bryophyta** [comment]
This chart  seems to be `type: contentatom` and `contentAtomTypeData: { atomType: "interactive" }`.

In this particular case there is a `title` attribute in the CAPI response which is not being passed to DCR by Frontend. If the `title` attribute is reliably present in CAPI then we should adjust Frontend to pass the title through to DCR.

**Comment by mxdvl** [comment]
We can see the most recent URLs with `InteractiveAtomBlockElement`s here: https://logs.gutools.co.uk/s/dotcom/goto/86803750-59f6-11ed-9b49-edd97f9389f6

**Comment by mxdvl** [comment]
Fixed by #9979 

<img width="1712" alt="image" src="https://github.com/guardian/dotcom-rendering/assets/76776/7a060c48-0614-4c3c-aa44-130424cb527b">
