### ISSUE TITLE
Issue ID: DAC_Hidden_Links1 - Feature: Discussion

### ISSUE THREAD

**Issue by VDuczekW** [guardian/dotcom-rendering#4457]
Report Link: https://drive.google.com/file/d/1MvbPA5bAFi2bM_OkTAx3BTxzS1Ixrp2u/view
Full Issue list: https://docs.google.com/spreadsheets/d/1vWQtZfD49uq7uNCNELuYN_HcIj-BKiE4t4Hwda3tJaQ/edit#gid=0

**Comment by SiAdcock** [comment]
We have proposed removing this control from frontend. See guardian/frontend#25065
