### ISSUE TITLE
Issue ID: DAC_Magnified_Images1 - Feature: Gallery

### ISSUE THREAD

**Issue by VDuczekW** [guardian/dotcom-rendering#4460]
Report link: https://drive.google.com/file/d/1myaQdkLNCNhmrIoe_BPRwOxvpPxvT7w0/view
Full issue list: https://docs.google.com/spreadsheets/d/1vWQtZfD49uq7uNCNELuYN_HcIj-BKiE4t4Hwda3tJaQ/edit#gid=0

**Comment by AshCorr** [comment]
@OllysCoding we had a brief look at this in our team.

It looks like the new <dialog> element might be the way to go, this article summarises it pretty nicely: https://www.scottohara.me/blog/2019/03/05/open-dialog.html

Dialogs make it a lot easier to have accessible modals by trapping focus in the modal and moving focus to the modal when opened.

**Comment by jamesgorrie** [comment]
We're looking into the activation of the dialogue with Voice Over and Voice Control.

**Comment by jamesgorrie** [comment]
Note on ordering of the DOM with styling:

Using styling to “smartly” order DOM on different breakpoints can cause confusion with how a person would navigate using tabindex e.g. a screenreader.

An example is [here](https://www.theguardian.com/science/gallery/2018/mar/14/the-life-of-stephen-hawking-in-pictures) where the `figcaption` is before the "Expand image" button in the DOM.

This makes sense when the design is left to right:
<img width="1421" alt="Screenshot 2022-06-14 at 11 51 42" src="https://user-images.githubusercontent.com/31692/173561628-24157a8d-e21b-4af1-8f12-9443ec9707f8.png">


But not top to bottom>:
<img width="790" alt="Screenshot 2022-06-14 at 11 52 30" src="https://user-images.githubusercontent.com/31692/173561574-a3ddc2c8-4584-4502-8a10-e410ba6c8899.png">
