### ISSUE TITLE
Don't stick key events when viewport height is less than the key events block

### ISSUE THREAD

**Issue by VDuczekW** [guardian/dotcom-rendering#4467]
Just a small issue with the new design of key events to consider - the height of the key events block is greater than the viewport here, meaning that we don't show all of them - https://www.theguardian.com/politics/live/2021/nov/18/raab-tories-boris-johnson-standards-reform-hs2-rail-uk-politics-live-latest-updates?dcr

<img width="611" alt="image" src="https://user-images.githubusercontent.com/91130034/160854836-747b457c-6189-4f5d-90c7-606364abca53.png">

**Comment by alinaboghiu** [comment]
now using carousel
