### ISSUE TITLE
AR Visual Bug – Rich link image doesn't fit container

### ISSUE THREAD

**Issue by VDuczekW** [guardian/dotcom-rendering#4481]
At wider breakpoints the image here should be wider

<img width="489" alt="image" src="https://user-images.githubusercontent.com/91130034/161069790-9d615105-c4f6-45c7-9b32-957c7e7f34ca.png">

**Comment by JamieB-gu** [comment]
DCR has removed images in rich links on blogs, let's do the same. See #4172 and #4229
