### ISSUE TITLE
twitter handle needs colour logic

### ISSUE THREAD

**Issue by VDuczekW** [guardian/dotcom-rendering#4482]
In this scenario (mobile) is should be white, then grey at wider breakpoints when we introduce the leftColumn

<img width="406" alt="image" src="https://user-images.githubusercontent.com/91130034/161070442-d129426a-f304-4b5c-a93b-cf1520722193.png">

**Comment by jlieb10** [comment]
For rota - please check that this hasn't been done before working on it. It may already have been done and could be closed.

**Comment by HarryFischer** [comment]
I can still see the issue on mobile here: https://www.theguardian.com/politics/live/2022/apr/19/boris-johnson-partygate-covid-lockdown-fine-uk-politics-live
