### ISSUE TITLE
Comments on deadblogs needs leftCol width adjusting

### ISSUE THREAD

**Issue by VDuczekW** [guardian/dotcom-rendering#4488]
It should follow the behaviour of the containers below

<img width="518" alt="image" src="https://user-images.githubusercontent.com/91130034/161094269-14c7c537-2ce7-42a2-a783-b22b8605233b.png">

**Comment by jlieb10** [comment]
For rota - please check that this hasn't been done before working on it. It may already have been done and could be closed.

**Comment by HarryFischer** [comment]
This is still an issue, see here at leftCol: https://www.theguardian.com/politics/live/2022/apr/19/boris-johnson-partygate-covid-lockdown-fine-uk-politics-live
