### ISSUE TITLE
Lift ESLint in the configuration to the root and standardise across projects

### ISSUE THREAD

**Issue by VDuczekW** [guardian/dotcom-rendering#4491]
Common Rendering currently does not have eslint enabled.

Lift and shift the eslint config to root and standardise across projects in the monorepo

**Comment by OllysCoding** [comment]
@jamesgorrie Is this still part of the plan for the monorepo?

**Comment by jlieb10** [comment]
I think this is something we should try to do outside of normal hours, when no one on apps has a particularly old branch taken out, as it's likely to be fairly disruptive

But I agree that it's worth doing. I don't think we should have these two running on divergent or diverging style standards.

**Comment by mxdvl** [comment]
Picking this up again:

- #4933 
- #4934

**Comment by VDuczekW** [comment]
we will not do - taking different approach

**Comment by jamesgorrie** [comment]
New issue: https://github.com/guardian/dotcom-rendering/issues/4935
