### ISSUE TITLE
DCR: Fix date handling for liveblog blocks 'published time'

### ISSUE THREAD

**Issue by OllysCoding** [guardian/dotcom-rendering#4501]
PR #4500 Introduced a hotfix which resolved an issue on DCR where all liveblogs where displaying the 'block published time' in UTC - incorrect both in the UK as of late March & for any users around the world browsing other editions.

This should not be considered the permanent solution. The larger problem is that DCR doesn't contain the necessary logic to determine the correct timestamps itself ~ where timezone specific dates are used in DCR, they (except in the case this PR resolved) use a pre-generated timestamp provided by frontend.

However in the case of this specific PR, the designs called for a time format which wasn't currently provided by frontend, and would potentially break the existing 'standard' frontend has (which is to include the timezone when pre-generating the timestamp), so as a hotfix we are re-formatting the existing frontend string - not ideal.

---

Some time should be spent working with design and considering the architecture of DCR to come up with a more permanent solution.

It is essential this ticket be addressed to maintain the health of dates/times in DCR & its Frontend data source.

**Comment by paperboyo** [comment]
Thx!
Slightly related: https://github.com/guardian/dotcom-rendering/issues/4338 & https://github.com/guardian/dotcom-rendering/issues/4391.
