### ISSUE TITLE
Interview Circular Avatar

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#4515]
When an image is available, add a circular avatar to the `Metadata` component for the journalist. The byline disappears from this component to appear in the headline, as documented in #4514.

An example can be found here on [AR](https://mobile.guardianapis.com/rendered-items/sport/2022/apr/05/welsh-fires-jacob-bethell-my-dream-is-to-play-for-england-in-all-formats) and [Dotcom](https://www.theguardian.com/sport/2022/apr/05/welsh-fires-jacob-bethell-my-dream-is-to-play-for-england-in-all-formats).

Other examples can be found here: https://www.theguardian.com/tone/interview

The same feature can be found on `Design.Feature` pieces.

**Comment by MarSavar** [comment]
Closed by #4627
