### ISSUE TITLE
Interview Dropcap

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#4516]
Add a dropcap to the first paragraph on interview pieces.

An example can be found here on [AR](https://mobile.guardianapis.com/rendered-items/sport/2022/apr/05/welsh-fires-jacob-bethell-my-dream-is-to-play-for-england-in-all-formats) and [Dotcom](https://www.theguardian.com/sport/2022/apr/05/welsh-fires-jacob-bethell-my-dream-is-to-play-for-england-in-all-formats).

Other examples can be found here: https://www.theguardian.com/tone/interview

The same feature can be found on `Design.Feature` pieces.

**Comment by paperboyo** [comment]
Is the logic for when to show a drop cap identical between DCR and AR (it should be)?

**Comment by JamieB-gu** [comment]
I think the rules/designs say that they _should_ be the same, but the actual concrete implementation will be different because DCR and AR don't share much code at the moment. So they should appear the same, but we can't guarantee it won't be different in some cases unintentionally.

**Comment by paperboyo** [comment]
Thx! I meant only the rules of [when to show and when not](https://sites.google.com/a/guardian.co.uk/esd/tips/drop-caps-when-and-how-they-appear), not the actual implementation.

**Comment by JamieB-gu** [comment]
Closing as this is captured better in #4542.
