### ISSUE TITLE
Hide keyevents toggle when no key events

### ISSUE THREAD

**Issue by HarryFischer** [guardian/dotcom-rendering#4523]

**Comment by HarryFischer** [comment]
![image](https://user-images.githubusercontent.com/20658471/162701546-2bf1b5d8-82f1-4e53-9000-1bb2aec407f0.png)

**Comment by jlieb10** [comment]
For rota - please check that this hasn't been done before working on it. It may already have been done and could be closed.

**Comment by HarryFischer** [comment]
Spoke with @alinaboghiu and this is on Journalism team backlog
