### ISSUE TITLE
Look at block byline design

### ISSUE THREAD

**Issue by HarryFischer** [guardian/dotcom-rendering#4525]
Currently too similar to body cop

<img width="772" alt="Screenshot 2022-04-05 at 19 58 02" src="https://user-images.githubusercontent.com/20658471/161831938-18708c42-eaa4-4cbf-8712-7b4abedc848c.png">
y

**Comment by paperboyo** [comment]
Should we just do exactly what we do for articles? Unlinked in italic, linked (to a profile page) – bold? Not sure if it’s easy from a tech perspective or if it’s desired design-wise, but I wonted to make a case for consistency (and extra functionality of linking to author’s bio page).

**Comment by JamieB-gu** [comment]
> linked (to a profile page)

Work to add profile links captured in #5683

**Comment by alinaboghiu** [comment]
duplicate of https://github.com/guardian/dotcom-rendering/issues/10336
