### ISSUE TITLE
Remove 200 years from logo

### ISSUE THREAD

**Issue by jamesgorrie** [guardian/dotcom-rendering#4536]
We should remove "For 200  years" part of the logo 4th May @ 2022 23:59 (or there abouts). We should keep "News website of the year".

Related:

https://github.com/guardian/frontend/pull/24102
https://github.com/guardian/frontend/pull/24104

**Comment by HarryFischer** [comment]
New svg
<svg width="300" height="116" viewBox="0 0 300 116" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M68.131 51.554L73.283 48.879V8.502H69.387L59.87 21.091H58.795L59.402 7.059H100.664L101.26 21.091H100.131L90.806 8.502H86.814V48.794L91.998 51.522V52.891H68.131V51.554ZM105.401 49.77V5.02L101.398 3.428V2.59L115.866 0H117.388V21.175L117.792 20.835C120.997 18.045 125.596 16.25 130.194 16.25C136.529 16.25 139.328 19.817 139.328 26.461V49.771L142.714 51.606V52.966H123.797V51.617L127.192 49.77V26.376C127.192 22.726 125.596 21.26 122.594 21.26C120.592 21.26 118.868 21.887 117.59 22.906V49.823L120.922 51.66V52.955H101.995V51.67L105.401 49.77V49.77ZM153.732 36.025C154.125 43.423 157.447 49.145 165.324 49.145C169.135 49.145 171.839 47.382 174.384 46.045V47.5C172.414 50.186 167.422 53.954 160.47 53.954C148.26 53.954 142.021 47.192 142.021 35.474C142.021 24.021 148.845 16.889 159.874 16.889C170.243 16.889 175.629 22.058 175.629 35.665V36.015H153.732V36.026V36.025ZM153.529 34.327L164.271 33.669C164.271 24.509 162.695 18.427 159.544 18.427C156.201 18.427 153.529 25.485 153.529 34.327ZM0 70.808C0 51.33 12.934 44.399 27.338 44.399C33.448 44.399 39.218 45.376 42.443 46.713L42.72 60.31H41.347L32.894 47.16C31.447 46.544 30.074 46.3 27.54 46.3C19.886 46.3 15.968 55.12 16.085 69.587C16.235 86.888 19.247 94.743 26.273 94.743C28.104 94.743 29.509 94.467 30.489 94.043V75.498L25.847 72.845V71.295H48.267V72.951L43.7 75.499V93.787C39.91 95.263 33.512 96.664 26.763 96.664C10.39 96.664 0 89.096 0 70.808ZM47.478 61.722V60.597L62.553 57.944L64.203 58.082V87.696C64.203 91.262 65.927 92.366 68.812 92.366C70.675 92.366 72.357 91.666 73.698 90.063V63.505L69.568 61.721V60.554L84.642 57.9L86.153 58.038V91.983L90.22 93.681V94.764L75.348 96.59L73.837 96.452V91.994H73.421C70.664 94.531 66.811 96.728 62.127 96.728C54.898 96.728 51.587 92.472 51.587 86.018V63.507L47.478 61.723V61.722ZM142.767 57.88L144.002 58.018V68.982H144.342C145.95 60.947 149.505 57.944 153.838 57.944C154.53 57.944 155.286 58.007 155.701 58.219V69.439C155.009 69.237 153.774 69.163 152.603 69.163C149.165 69.163 146.631 69.778 144.406 70.797V92.472L147.834 94.372V95.772H128.289V94.382L131.813 92.482V62.9L127.682 61.67V60.66L142.767 57.88Z" fill="white"/>
<path d="M180.622 58.804V47.234L176.491 45.791V44.867L191.704 42.076L193.151 42.277V91.963L197.356 93.481V94.765L182.346 96.781L181.175 96.644V92.536H180.835C178.631 94.733 175.597 96.718 170.849 96.718C162.652 96.718 156.669 90.477 156.669 77.708C156.669 64.248 163.621 57.636 174.16 57.636C177.173 57.636 179.451 58.188 180.622 58.804V58.804ZM180.59 90.614V60.917C179.621 60.301 178.929 59.537 176.427 59.622C172.361 59.76 169.849 65.895 169.849 76.806C169.849 86.625 171.658 92.112 177.077 91.932C178.599 91.879 179.834 91.337 180.59 90.616V90.614ZM214.07 57.848L215.379 57.986V92.46L218.818 94.36V95.76H199.273V94.37L202.786 92.47V63.43L198.581 61.785V60.638L214.07 57.847V57.848ZM215.454 48.538C215.454 52.18 212.356 54.918 208.779 54.918C205.064 54.918 202.168 52.169 202.168 48.538C202.168 44.898 205.064 42.085 208.779 42.085C212.356 42.085 215.454 44.898 215.454 48.539V48.538ZM261.453 92.472V63.112L257.322 61.669V60.247L272.332 57.455L273.844 57.593V61.987H274.259C277.495 59.1 282.318 57.253 287.066 57.253C293.602 57.253 296.498 60.343 296.498 67.21V92.408L300 94.36V95.76H280.455V94.37L283.968 92.47V67.9C283.968 64.122 282.318 62.615 279.22 62.615C277.219 62.615 275.579 63.125 274.057 64.249V92.462L277.495 94.362V95.762H257.94V94.372L261.453 92.472V92.472ZM239.768 74.024V69.099C239.768 61.679 238.15 59.249 233.551 59.249C233.008 59.249 232.54 59.312 231.997 59.386L223.811 70.446H222.661V60.269C226.174 59.186 230.571 57.912 236.394 57.912C246.4 57.912 252.223 60.682 252.223 69.036V93.046L255.811 93.99V94.935C254.395 95.815 251.553 96.622 248.434 96.622C243.494 96.622 241.131 95.009 240.045 92.302H239.704C237.607 95.136 234.637 96.75 229.964 96.75C224.013 96.75 219.957 93.045 219.957 86.634C219.957 80.425 223.811 77.06 231.656 75.574L239.768 74.024V74.024ZM239.768 90.614V75.774L237.267 75.977C233.338 76.317 231.923 78.811 231.923 84.341C231.923 90.338 233.881 91.898 236.66 91.898C238.214 91.888 239.098 91.42 239.768 90.614ZM110.202 74.024V69.099C110.202 61.679 108.584 59.249 103.975 59.249C103.432 59.249 102.963 59.312 102.42 59.386L94.234 70.446H93.084V60.269C96.597 59.186 100.994 57.912 106.817 57.912C116.824 57.912 122.647 60.682 122.647 69.036V93.046L126.234 93.99V94.935C124.818 95.815 121.976 96.622 118.857 96.622C113.917 96.622 111.554 95.009 110.468 92.302H110.128C108.031 95.136 105.05 96.75 100.387 96.75C94.437 96.75 90.38 93.045 90.38 86.634C90.38 80.425 94.234 77.06 102.08 75.574L110.202 74.024V74.024ZM110.202 90.614V75.774L107.701 75.977C103.772 76.317 102.357 78.811 102.357 84.341C102.357 90.338 104.315 91.898 107.094 91.898C108.637 91.888 109.521 91.42 110.202 90.614Z" fill="white"/>
<path d="M73.848 100.316H76.094L79.043 105.411C79.969 107.003 81.001 109.359 81.001 109.359H81.055C81.055 109.359 80.895 106.886 80.895 105.22V100.316H82.715V112.023H80.745L77.51 106.355C76.594 104.763 75.55 102.364 75.55 102.364H75.487C75.487 102.364 75.679 104.912 75.679 106.557V112.034H73.859V100.316H73.848V100.316ZM84.6 108.053V107.257C84.6 104.402 86.26 103.085 88.464 103.085C91.019 103.085 92.084 104.402 92.084 107.129V108.212H86.622C86.675 110.165 87.506 110.579 89.177 110.579C90.317 110.579 91.051 110.324 91.796 109.963V111.375C91.21 111.747 90.263 112.192 88.783 112.192C85.93 112.192 84.6 110.738 84.6 108.053ZM86.601 106.832H90.114C90.114 105.081 89.528 104.54 88.432 104.54C87.548 104.54 86.654 104.932 86.601 106.832ZM92.87 103.245H94.904L95.681 106.493C96.021 107.894 96.394 110.59 96.394 110.59H96.458C96.458 110.59 96.831 107.926 97.225 106.493L98.108 103.245H99.865L100.748 106.493C101.121 107.894 101.568 110.59 101.568 110.59H101.632C101.632 110.59 101.994 107.926 102.334 106.493L103.101 103.245H104.879L102.515 112.034H100.525L99.535 108.457C99.162 107.141 98.928 104.784 98.928 104.784H98.864C98.864 104.784 98.651 107.141 98.278 108.457L97.288 112.034H95.255L92.871 103.245H92.87ZM105.752 111.609V110.048C106.487 110.345 107.104 110.579 108.329 110.579C109.5 110.579 109.968 110.239 109.968 109.602C109.968 109.019 109.808 108.743 108.84 108.509L107.882 108.286C106.583 107.979 105.763 107.31 105.763 105.739C105.763 104.115 106.774 103.075 108.935 103.075C110.106 103.075 110.862 103.287 111.426 103.563V105.091C110.926 104.879 110.096 104.656 109.116 104.656C108.126 104.656 107.615 104.985 107.615 105.601C107.615 106.185 107.892 106.429 108.659 106.609L109.617 106.832C111.299 107.225 111.884 107.904 111.884 109.443C111.884 111.248 110.713 112.171 108.573 112.171C107.477 112.171 106.466 111.98 105.752 111.609V111.609ZM116.728 103.245H118.761L119.538 106.493C119.879 107.894 120.251 110.59 120.251 110.59H120.315C120.315 110.59 120.688 107.926 121.082 106.493L121.965 103.245H123.722L124.605 106.493C124.978 107.894 125.425 110.59 125.425 110.59H125.489C125.489 110.59 125.851 107.926 126.191 106.493L126.958 103.245H128.736L126.372 112.034H124.382L123.392 108.457C123.019 107.141 122.785 104.784 122.785 104.784H122.721C122.721 104.784 122.508 107.141 122.135 108.457L121.145 112.034H119.112L116.728 103.245V103.245ZM129.641 108.053V107.257C129.641 104.402 131.301 103.085 133.505 103.085C136.06 103.085 137.124 104.402 137.124 107.129V108.212H131.663C131.716 110.165 132.547 110.579 134.218 110.579C135.357 110.579 136.092 110.324 136.837 109.963V111.375C136.251 111.747 135.304 112.192 133.824 112.192C130.971 112.192 129.641 110.738 129.641 108.053ZM131.642 106.832H135.155C135.155 105.081 134.569 104.54 133.473 104.54C132.589 104.54 131.685 104.932 131.642 106.832V106.832ZM138.71 111.525V99.541H140.669V104.01H140.754C141.372 103.479 142.128 103.086 143.245 103.086C144.842 103.086 146.471 104.01 146.471 107.077V107.788C146.471 110.792 144.991 112.225 142.138 112.225C140.893 112.225 139.52 111.928 138.71 111.525V111.525ZM144.427 108.064V107.247C144.427 105.198 143.778 104.7 142.309 104.7C141.627 104.7 141.01 104.954 140.659 105.135V110.368C140.989 110.527 141.404 110.707 142.234 110.707C143.384 110.707 144.427 110.272 144.427 108.064V108.064ZM147.632 111.609V110.048C148.366 110.345 148.984 110.579 150.208 110.579C151.379 110.579 151.847 110.239 151.847 109.602C151.847 109.019 151.688 108.743 150.73 108.509L149.772 108.286C148.473 107.979 147.653 107.31 147.653 105.739C147.653 104.115 148.664 103.075 150.825 103.075C151.996 103.075 152.752 103.287 153.317 103.563V105.091C152.816 104.879 151.986 104.656 151.006 104.656C150.016 104.656 149.505 104.985 149.505 105.601C149.505 106.185 149.782 106.429 150.549 106.609L151.507 106.832C153.189 107.225 153.774 107.904 153.774 109.443C153.774 111.248 152.603 112.171 150.464 112.171C149.356 112.171 148.345 111.98 147.632 111.609ZM155.253 99.816H157.276V101.684H155.253V99.816ZM155.285 103.244H157.244V112.033H155.285V103.244ZM159.969 109.9V104.784H158.521V103.245H159.969V101.122H161.928V103.245H164.196V104.784H161.928V109.592C161.928 110.356 162.184 110.579 163.025 110.579C163.386 110.579 164.004 110.484 164.313 110.356V111.683C163.951 111.906 163.237 112.14 162.386 112.14C160.917 112.14 159.969 111.588 159.969 109.9V109.9ZM165.313 108.053V107.257C165.313 104.402 166.974 103.085 169.178 103.085C171.733 103.085 172.797 104.402 172.797 107.129V108.212H167.336C167.389 110.165 168.22 110.579 169.891 110.579C171.03 110.579 171.765 110.324 172.51 109.963V111.375C171.924 111.747 170.977 112.192 169.497 112.192C166.644 112.192 165.313 110.738 165.313 108.053ZM167.315 106.832H170.828C170.828 105.081 170.242 104.54 169.146 104.54C168.262 104.54 167.368 104.932 167.315 106.832V106.832ZM178.035 108.053V107.31C178.035 104.55 179.76 103.085 182.07 103.085C184.561 103.085 186.041 104.518 186.041 107.225V107.968C186.041 110.76 184.348 112.192 182.048 112.192C179.526 112.192 178.035 110.738 178.035 108.053V108.053ZM184.007 108.127V107.236C184.007 105.038 183.124 104.593 182.038 104.593C180.814 104.593 180.068 105.357 180.068 107.161V108.074C180.068 110.229 180.963 110.685 182.091 110.685C183.305 110.675 184.007 109.963 184.007 108.127V108.127ZM188.318 104.784H186.881V103.245H188.318V102.162C188.318 100.241 189.489 99.402 191.139 99.402C191.937 99.402 192.544 99.551 192.832 99.71V101.079C192.608 101.016 192.15 100.952 191.661 100.952C190.766 100.952 190.277 101.355 190.277 102.353V103.266H192.374V104.805H190.277V112.044H188.318V104.784V104.784ZM198.496 109.9V104.784H197.048V103.245H198.496V101.122H200.454V103.245H202.722V104.784H200.454V109.592C200.454 110.356 200.71 110.579 201.551 110.579C201.913 110.579 202.53 110.484 202.839 110.356V111.683C202.477 111.906 201.764 112.14 200.912 112.14C199.443 112.14 198.496 111.588 198.496 109.9V109.9ZM204.212 99.541H206.171V104.137H206.256C206.874 103.532 207.906 103.086 208.96 103.086C210.589 103.086 211.409 103.797 211.409 105.506V112.034H209.45V105.994C209.45 105.114 209.173 104.763 208.045 104.763C207.406 104.763 206.672 104.976 206.171 105.23V112.034H204.212V99.541V99.541ZM212.995 108.053V107.257C212.995 104.402 214.655 103.085 216.859 103.085C219.414 103.085 220.478 104.402 220.478 107.129V108.212H215.017C215.07 110.165 215.901 110.579 217.572 110.579C218.711 110.579 219.446 110.324 220.191 109.963V111.375C219.605 111.747 218.658 112.192 217.178 112.192C214.325 112.192 212.995 110.738 212.995 108.053ZM214.996 106.832H218.509C218.509 105.081 217.923 104.54 216.827 104.54C215.933 104.54 215.039 104.932 214.996 106.832V106.832ZM225.609 115.112V113.732C225.833 113.785 226.163 113.817 226.472 113.817C227.249 113.817 227.739 113.509 228.047 112.681L228.356 111.853L225.29 103.245H227.355L228.313 106.1C228.931 107.915 229.325 110.335 229.325 110.335H229.378C229.378 110.335 229.814 107.915 230.4 106.1L231.315 103.245H233.253L229.878 112.989C229.303 114.645 228.473 115.388 226.898 115.388C226.45 115.388 225.865 115.271 225.609 115.112V115.112ZM233.86 108.053V107.257C233.86 104.402 235.521 103.085 237.724 103.085C240.279 103.085 241.344 104.402 241.344 107.129V108.212H235.882C235.936 110.165 236.766 110.579 238.437 110.579C239.576 110.579 240.311 110.324 241.056 109.963V111.375C240.471 111.747 239.523 112.192 238.044 112.192C235.201 112.192 233.86 110.738 233.86 108.053V108.053ZM235.872 106.832H239.385C239.385 105.081 238.799 104.54 237.703 104.54C236.809 104.54 235.914 104.932 235.872 106.832V106.832ZM242.408 109.666C242.408 108.042 243.42 107.278 245.133 107.066L247.092 106.811V106.142C247.092 105.017 246.634 104.731 245.187 104.731C244.356 104.731 243.611 104.858 243.09 104.975V103.563C243.888 103.234 244.835 103.075 245.953 103.075C247.923 103.075 249.051 103.85 249.051 105.707V112.023H247.443L247.284 111.142H247.188C246.783 111.715 246.134 112.182 245.038 112.182C243.473 112.192 242.408 111.375 242.408 109.666V109.666ZM247.082 110.271V108.042L245.57 108.191C244.74 108.276 244.367 108.722 244.367 109.571C244.367 110.42 244.857 110.77 245.623 110.77C246.219 110.781 246.762 110.568 247.082 110.271ZM251.01 103.245H252.883V104.444H252.979C253.416 103.712 254.384 103.118 255.279 103.118C255.523 103.118 255.736 103.15 255.8 103.203V104.986C255.575 104.948 255.347 104.927 255.119 104.922C254.352 104.922 253.511 105.177 252.969 105.527V112.044H251.01V103.245V103.245Z" fill="#FFE500"/>
</svg>

**Comment by abeddow91** [comment]
Thanks @HarryFischer
