### ISSUE TITLE
Stop Relying On Star Rating To Parse `Design.Review`

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#4539]
AR currently mandates that a piece has to have a star rating to be classed as a review:

https://github.com/guardian/dotcom-rendering/blob/09f166c66d56661adab97473e34e9e9a9a42c990/apps-rendering/src/item.ts#L398

Unfortunately it turns out that some review pieces don't include a star rating, but still pick up the rest of the `Design.Review` design treatment: bold, themed headline, avatar picture, light standfirst etc. See the difference here: [AR](https://mobile.guardianapis.com/rendered-items/books/2022/apr/03/in-brief-the-secret-world-of-weather-song-for-the-missing-espana-book-reviews), [Dotcom](https://www.theguardian.com/books/2022/apr/03/in-brief-the-secret-world-of-weather-song-for-the-missing-espana-book-reviews).

We'll want to remove this check and refactor the definition of `Review` to alter the `starRating` field to `Option<number>`:

https://github.com/guardian/dotcom-rendering/blob/09f166c66d56661adab97473e34e9e9a9a42c990/apps-rendering/src/item.ts#L94-L98

**Comment by JamieB-gu** [comment]
@HarryFischer is it correct that pieces should still be classed as "review" and receive all the normal "review" design treatment even if they don't have a star rating?

**Comment by HarryFischer** [comment]
@JamieB-gu Yep I think you're right. Don't always require stars to be a review
