### ISSUE TITLE
Dropcaps

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#4542]
Some pieces, under certain circumstances, have dropcaps that appear on their first paragraph. Dropcaps are a large, capitalised letter that appear as the first letter of a paragraph, and drop below the main baseline of the text. The rules about when they should appear are quite complex, and can be summarised as followed (adapted from the ESD help site):

- The piece must be one of the following `Design`s: `Feature`, `Comment`, `Review`, `Interview`, `Recipe`, `PhotoEssay`
- Alternatively the piece can be set to `Display.Immersive`
- The piece must not be `Theme.Labs`
- The first paragraph must contain at least 200 characters and the first word must be at least three characters long
- A drop cap is not displayed if the first character is an `I` or a punctuation mark (but quotes are capped together with following letter)
- Drop caps are four lines deep

**Note:** I've added this to the "Interview Beta Release" milestone as that's likely to be the first one we complete. It's technically required for a number of other milestones ("Review", "Immersive" etc.), but GitHub doesn't allow an issue to appear under multiple milestones.

cc @paperboyo 

## What Does DCR Do?

This logic is implemented on DCR here:

https://github.com/guardian/dotcom-rendering/blob/09f166c66d56661adab97473e34e9e9a9a42c990/dotcom-rendering/src/web/components/TextBlockComponent.tsx#L230-L236

and there's a component for it here:

https://github.com/guardian/dotcom-rendering/blob/09f166c66d56661adab97473e34e9e9a9a42c990/dotcom-rendering/src/web/components/DropCap.tsx#L49-L56

**Comment by JamieB-gu** [comment]
@ajbreuer @paperboyo what happens if the first element in the body isn't a paragraph? What if it's, for example, a bulleted list or an image or an embed?

Do we show dropcaps on the first paragraph of the page, regardless of how far down the page the first paragraph appears, or do we only show them if the first element in the body is a paragraph?

**Comment by ajbreuer** [comment]
> @ajbreuer @paperboyo what happens if the first element in the body isn't a paragraph? What if it's, for example, a bulleted list or an image or an embed?
> 
> Do we show dropcaps on the first paragraph of the page, regardless of how far down the page the first paragraph appears, or do we only show them if the first element in the body is a paragraph?

Yes, on the tags listed the body text should start with a drop cap, even if it is preceded by another element. 👍

**Comment by mxdvl** [comment]
> * The first paragraph must contain at least 200 characters and **the first word must be at least three characters long**
> * A drop cap is not displayed **if the first character is an `I`** or a punctuation mark (but quotes are capped together with following letter)

Is there any documentation for part of the rules parts I highlighted **in bold**? I could not find any code that implements this. [Frontend][] doesn’t care about a leading `I`.

**Comment by MarSavar** [comment]
AR PRs: #4627 #4674

**Comment by MarSavar** [comment]
> A drop cap is not displayed if the first character is an I or a punctuation mark (but quotes are capped together with following letter)

Before I merge #4694, can anybody confirm whether this means "any word beginning with an I"?
The current rule in that PR excludes anything that begins with an I (e.g. if an interview article begins with the word "Inevitably").

**Comment by paperboyo** [comment]
We just need to come up with some sensible rule and apply it consistently. I guess someone decided `I` (when without opening quote) looks confusing? cc @HarryFischer
