### ISSUE TITLE
Audio Elements

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#4545]
Audio articles use audio elements - elements in the CAPI blocks API with `type: "audio"` - in main media to provide the audio file. We'll need to add support for these in the `MainMedia` component.

An example piece can be found here: [AR](https://mobile.guardianapis.com/rendered-items/news/audio/2022/mar/24/the-siege-of-mariupol-podcast), [Dotcom](https://www.theguardian.com/news/audio/2022/mar/24/the-siege-of-mariupol-podcast)

## Audio Elements vs Audio Atoms

Audio elements are defined as described above. An alternative delivery mechanism for audio files is audio **atoms**. These are defined as elements with `type: "contentatom"` in the CAPI blocks API, and as atoms with `atomType: "audio"` in the CAPI atoms API.

Audio atoms at the moment seem to be used to embed audio files in other articles, as seen here for Today in Focus: [AR](https://mobile.guardianapis.com/rendered-items/world/2022/apr/05/tuesday-briefing-atrocities-ukraine), [Dotcom](https://www.theguardian.com/world/2022/apr/05/tuesday-briefing-atrocities-ukraine)

There's a suggestion that we may want to replace the use of audio elements in audio articles with audio atoms. If this happens we'll want to support audio atoms as main media in audio articles instead.

**Comment by georgeblahblah** [comment]
Won't do now that we are rendering apps articles in DCR
