### ISSUE TITLE
Fronts migration/replatforming

### ISSUE THREAD

**Issue by jamesgorrie** [guardian/dotcom-rendering#4547]
# OKR
**Increase percentage of pressed Fronts supported via DCR from 0% to 100%**

- [Project board](https://github.com/orgs/guardian/projects/12/views/12)
- [Dashboard](https://logs.gutools.co.uk/app/dashboards#/view/4b086ea0-b0d1-11ec-bb1d-31c7d038c7a5)
- [Milestone](https://github.com/guardian/dotcom-rendering/milestone/9)

## Release plan
A front is supported when a set of criteria are met, as seen in [FaciaPicker](https://github.com/guardian/frontend/blob/main/facia/app/services/dotcomrendering/FaciaPicker.scala). This will set "DCR Supports" (`dcrCanRender`) = true. 

We also have [an experiment](https://github.com/guardian/frontend/blob/main/common/app/experiments/Experiments.scala#L28-L35) running for serving supported fronts (currently at 0%).

When a person is in that experiment, and the front is supported, a person will get a DCR front).

## GitHub labels:
- dotcom-rendering: https://github.com/guardian/dotcom-rendering/labels/Fronts%20%3Anewspaper%3A
- frontend: https://github.com/guardian/frontend/labels/Fronts%20%3Anewspaper%3A

## Resources
- [Questions from Alex and design (Internal)](https://docs.google.com/document/d/1XTqrTkiSkJwaRuTYscXenUDHbrr37u5eap9EZ9ANjes/edit)
- [Context to fonts](http://www.katstubbings.com/theguardian)

### Figma
Note Harry said these are out of date:
- Containers overview: https://www.figma.com/file/EEuMzp8yUSrHfOooE5bio9/
- Card variation: https://www.figma.com/file/fyYTHGFesaVAMp6sIIRcCQ/
- Front container: https://www.figma.com/file/sx2vMFHbL7SsUo0LcpsKNe/

### Dependency issues (and relevant teams)
- Container simplification (design and editorial/CP teams) - can/should happen pre-migration
- New container introduction (design and ed tools) - can/should happen after migration
- Ad placement and rendering (Commercial) - can happen during or after migration
- Personalisation (Identity, editorial, design) - can/should happen after migration

**Comment by sndrs** [comment]
some of the original thinking is outlined here http://www.katstubbings.com/theguardian

**Comment by ajbreuer** [comment]
I forgot we had Kat's study on that!
I will go through those figmas and also create a file with all the patterns we currently get from the dynamic containers, I started yesterday and it feels like there are some simplifications

**Comment by rhiannareechaye** [comment]
@jamesgorrie where best do you think we should put this ticket?

**Comment by jamesgorrie** [comment]
Closing this.
