### ISSUE TITLE
Liveblog contributors' images not appearing on DCR

### ISSUE THREAD

**Issue by jlieb10** [guardian/dotcom-rendering#4548]
This issue was reported to CP by Nicola Slawson

On investigation:

| Non-DCR      | DCR |
| ----------- | ----------- |
| <img width="630" alt="Screenshot 2022-04-07 at 16 38 30" src="https://user-images.githubusercontent.com/3300789/162240538-dde40407-2ff2-44e4-a208-199b4ba4c8b7.png"> | <img width="707" alt="Screenshot 2022-04-07 at 16 39 09" src="https://user-images.githubusercontent.com/3300789/162240760-d2ca918b-8ce2-4959-8f2e-1110e61a78c1.png"> |
| <img width="614" alt="Screenshot 2022-04-07 at 16 39 58" src="https://user-images.githubusercontent.com/3300789/162240975-dcc611ce-cb0b-4679-9fa6-304b34cbf686.png"> | <img width="712" alt="Screenshot 2022-04-07 at 16 39 36" src="https://user-images.githubusercontent.com/3300789/162241096-8be38d81-bac7-4960-9219-3b81a05fd218.png"> |

**Comment by ioannakok** [comment]
Reopening as this is still in progress
