### ISSUE TITLE
Dateline Visual Issues In Safari

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#4551]
Couple of small visual issues with the `Dateline` component, which shows the publication date by default, and opens up to also show a last modified date when clicked. In Safari this is showing the default `<details>` triangle and isn't showing an underline on hover.

## Steps To Reproduce

Open any piece rendered by DCR in Safari and see the publication date. It's in the metadata section just below the byline, typically in the left column on wider breakpoints.

## Screenshots

| | Firefox (expected design) | Safari |
| - | - | - |
| Normal | ![dateline-firefox][] | ![dateline-safari][] |
| Hover | ![dateline-firefox-hover][] | ![dateline-safari][] |

[dateline-safari]: https://user-images.githubusercontent.com/53781962/162252511-f3d7b677-7387-403e-8299-712c84586733.jpg
[dateline-firefox]: https://user-images.githubusercontent.com/53781962/162252516-bafc2faa-cfde-4a42-a051-77651dfad854.jpg
[dateline-firefox-hover]: https://user-images.githubusercontent.com/53781962/162252517-dfd2a8f6-58d3-4589-9be1-5d8b3471f41e.jpg

**Comment by JamieB-gu** [comment]
I actually think the version with the triangle makes this disclosure feature more discoverable and maybe we could consider keeping it? What do you think @guardian/guardian-design-team ?

**Comment by HarryFischer** [comment]
@JamieB-gu I thought the same. Maybe a slight design tweak to use a Source icon instead would make sense but let me design something

**Comment by benwuersching** [comment]
Maybe the icon/arrow/symbol could be to the right of the date, not to the left? On the left it seems to draw a lot of - maybe too much - attention to the datestamp. Or do we think it's important to draw attention to the slightly earlier first publication date?

**Comment by HarryFischer** [comment]
details summary::-webkit-details-marker {
  display:none;
}

**Comment by JamieB-gu** [comment]
FYI @mxdvl only the triangle has been fixed I believe. This is still missing an underline on hover, which is what hints to users that they can click on this element. It may be that we've decided not to change this, in which case this can be closed. But if not then probably this should remain open?

**Comment by HarryFischer** [comment]
I've made a new issue for adding underline
