### ISSUE TITLE
DCR devx - Filter key events breaks the URL

### ISSUE THREAD

**Issue by OllysCoding** [guardian/dotcom-rendering#4555]
If you go to (in the DCR dev server): http://localhost:3030/Article?url=https://www.theguardian.com/world/live/2022/apr/07/russia-ukraine-war-nato-foreign-ministers-to-meet-as-zelenskiy-dismisses-fresh-sanctions-live-news

Then click the filter key events toggle, the URL that's produced is malformed and doesn't filter the key events as expected

NOTE: This is a dev-server only issue; it does not affect prod

**Comment by mxdvl** [comment]
Fixed by #4628
