### ISSUE TITLE
Migrate To AWS CDK v2

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#4573]
The guardian/cdk project is making the move to v2 of the AWS CDK library; more details in https://github.com/guardian/cdk/pull/1174. Let's update to the new release of guardian/cdk when it's ready and re-work our `aws-cdk` dependencies to match. This should simplify our dependency tree.

**Comment by akash1810** [comment]
Worth noting [GUCDK v39.0.0](https://github.com/guardian/cdk/releases/tag/v39.0.0) introduces a significant breaking change, so you'll likely want to move to that first.

**Comment by JamieB-gu** [comment]
Move to MSS backlog, cc @groakland.

**Comment by JamieB-gu** [comment]
This is now tracked in the MSS backlog and will be completed there.

**Comment by groakland** [comment]
https://theguardian.atlassian.net/browse/LIVE-4158
