### ISSUE TITLE
Serve Audio Articles In Beta

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#4574]
We will need to remove the filter in MAPI that filters out audio articles in Beta. These articles are identified in CAPI by the `content.type` field, which is set to Audio. The relevant files in MAPI are:

- `RenderedItemUtils.scala`
- `ContentApi.scala`

**Comment by georgeblahblah** [comment]
Won't do now that we are rendering apps articles in DCR
