### ISSUE TITLE
Surface Github Lighthouse numbers on PRs

### ISSUE THREAD

**Issue by jlieb10** [guardian/dotcom-rendering#4584]
- [ ] [Surface budgets](https://github.com/guardian/dotcom-rendering/blob/main/dotcom-rendering/lighthouserc.js#L16-L24) on PRs. These are already [breaking](https://github.com/guardian/dotcom-rendering/runs/6177839941?check_suite_focus=true#step:6:47), but we aren't reporting them
- [ ] Surface change from `main` on ~PRs~ [this issue](#issuecomment-1113315505).
- [ ] Choose the pages we should be reporting on
  - We should be testing across as many features as we can
  - We should have a representative list of general content that we produce
  - We should make sure we don't negatively impact build speed too much

**Comment by jamesgorrie** [comment]
@jlieb10 could this be "Make lighthouse scores more visible" and a way to do that would be getting lighthouse scores into the PRs to allow us to think more broadly about how we expose these numbers?

**Comment by bryophyta** [comment]
Some notes from initial research:
- As noted in [a related issue](https://github.com/guardian/dotcom-rendering/issues/4583#issuecomment-1095280091), the action is currently configured to host the lighthouse report output at a (temporary) public url, e.g. https://storage.googleapis.com/lighthouse-infrastructure.appspot.com/reports/1650984553946-31245.report.html
- Alternatively, we can pass the raw output of the `lhci-cli` to a further step in the Actions workflow
  - The (3rd party) [lighthouse-ci-action](https://github.com/treosh/lighthouse-ci-action) provides an [uploadArtifacts](https://github.com/treosh/lighthouse-ci-action#uploadartifacts-default-false) option which will make the raw outputs available to subsequent workflow steps.
    -  There's an example of a workflow script accessing these artifacts [here](https://github.com/OskarAhl/Lighthouse-github-action-comment/blob/f4c88735ba0832fe13bdffea563ad03e37f917b2/.github/workflows/lighthouse-on-vercel-preview-url.yml#L41) although I think we'd want to find an alternative way of displaying the results.
  - If we _don't_ want to use that third-party action, their code might nevertheless suggest some ways of implementing the artifact upload ourselves.

**Comment by jlieb10** [comment]
Todo:
- create a comment if it doesn’t (instead of re-writing the PR)
- find comment id and update if it exists
