### ISSUE TITLE
What RUM are we already sending to BigQuery?

### ISSUE THREAD

**Issue by jlieb10** [guardian/dotcom-rendering#4586]

**Comment by mxdvl** [comment]
Currently, we are sending

- [Core Web Vitals via `CoreVitals.importable.tsx`](https://github.com/guardian/dotcom-rendering/blob/main/dotcom-rendering/src/web/components/CoreVitals.importable.tsx)
- [Commercial Metrics via `CommercialMetrics.importable.tsx`](https://github.com/guardian/dotcom-rendering/blob/main/dotcom-rendering/src/web/components/CommercialMetrics.importable.tsx)
