### ISSUE TITLE
Plan architecture for collating metrics

### ISSUE THREAD

**Issue by mxdvl** [guardian/dotcom-rendering#4596]
Client-side &rarr; Fastly &rarr; BigQuery

Add to #4474

**Comment by mxdvl** [comment]
Added https://github.com/guardian/dotcom-rendering/discussions/4474#discussioncomment-2552529

> ```mermaid
> sequenceDiagram
>     participant Client as JavaScript (client-side)
>     participant Edge as Fastly (edge)
>     participant Data as BigQuery (data warehouse)
>     participant Dashboards as Data & Insight Dashboards
>     loop JS Events
>       Client->>Client: build Payload 
>     end
>     Note right of Client: if Payload is empty, do nothing
>     Client->>+Edge: send Payload as JSON on unload
>     Edge->>-Data: Convert Payload keys to rows
>     Dashboards-->>Data: Create “clean” SQL query views
> ```

**Comment by jlieb10** [comment]
What are we asking Fastly/edge computing to do here?
