### ISSUE TITLE
`Card` uses a `picture` tag for images

### ISSUE THREAD

**Issue by oliverlloyd** [guardian/dotcom-rendering#4611]
A `picture` tag is preferable to an `img` tag for lots of reasons. Now that DCR is [able to create its own sources](https://github.com/guardian/dotcom-rendering/pull/5128) we have the flexibility to do better.

**Comment by AshCorr** [comment]
Depends on #4752 for image optimisation

**Comment by oliverlloyd** [comment]
Depends on https://github.com/guardian/dotcom-rendering/issues/5121

**Comment by mxdvl** [comment]
An alternative to using `Picture` is creating a component specifically for fronts: `FrontPicture` introduced in #6065

**Comment by oliverlloyd** [comment]
Replaced by https://github.com/guardian/dotcom-rendering/issues/6062
