### ISSUE TITLE
Labs container

### ISSUE THREAD

**Issue by oliverlloyd** [guardian/dotcom-rendering#4615]
This container has its own background colours, About dropdown, heading and brand positioning

<img width="1408" alt="Screenshot 2022-04-12 at 15 20 05" src="https://user-images.githubusercontent.com/1336821/162983828-1a46eea3-f613-4862-995b-bb995a77f2d9.png">

**Comment by rhiannareechaye** [comment]
Closing as this is a duplicate ticket
