### ISSUE TITLE
Dark Mode Designs For Interview

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#4632]
With the rollout of Apps-Rendering we're in a position to differentiate the designs for interview pieces (`tone/interview`), as dotcom does. The old templates didn't do this; interview pieces used a similar design to feature pieces (`tone/features`). The work so far can be seen in #4627.

In order to complete this work we also need to implement the dark mode variant of these designs. However, because the old templates never used these designs, and because dotcom doesn't support dark mode, there aren't currently any dark mode designs for this.

This leads to a couple of questions for the Design team:

1. Are we happy with the approach taken so far, i.e. introducing these designs?
2. If so, shall we put together some dark mode designs for this?

cc @HarryFischer @ajbreuer 

## Examples

| | News | Sport | Culture |
| - | - | - | - |
| Dotcom | ![interview-news][] | ![interview-sport][] | ![interview-culture][] | 
| Old Templates | ![interview-news-templates][] | ![interview-sport-templates][] | ![interview-culture-templates][] |

### Links

- https://www.theguardian.com/us-news/2022/apr/14/the-lunacy-is-getting-more-intense-how-birds-arent-real-took-on-the-conspiracy-theorists
- https://www.theguardian.com/sport/2022/apr/13/montpelliers-zach-mercer-weve-beaten-the-english-champions-and-still-get-doubted
- https://www.theguardian.com/music/2022/apr/13/grizzly-bears-daniel-rossen-on-going-solo-and-self-criticism-i-dont-expect-to-have-a-good-career-anymore

[interview-news]: https://user-images.githubusercontent.com/53781962/163370794-0f948f2f-7591-4a96-bddd-decee4ba4e85.jpg
[interview-sport]: https://user-images.githubusercontent.com/53781962/163370896-269caa34-a5f5-4d11-b11d-ca6a093c8f42.jpg
[interview-culture]: https://user-images.githubusercontent.com/53781962/163370928-dcfffe6f-b4c2-4d5a-b615-6ceb9b37220c.jpg
[interview-news-templates]: https://user-images.githubusercontent.com/53781962/163371976-a9e5d689-d22e-4b23-b4d5-b1be27128a16.jpg
[interview-sport-templates]: https://user-images.githubusercontent.com/53781962/163372073-a6ab3826-68df-4146-a4d0-16c2b7812d4e.jpg
[interview-culture-templates]: https://user-images.githubusercontent.com/53781962/163372114-2bf50eb3-feb5-440c-a698-e56b707df435.jpg

**Comment by ajbreuer** [comment]
@MarSavar I have done some dark mode designs here
https://www.figma.com/file/MSCs0NHaf6xuDwpvTd3mwM/Lighter-UI-V1?node-id=3005%3A7126
