### ISSUE TITLE
Analysis Headline

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#4635]
There are two features of the headline on analysis pieces that may need tweaking, and both will need input from Design. @HarryFischer @ajbreuer 

| AR | DCR |
| - | - |
| ![analysis-ar][] | ![analysis-dotcom][] |

Screenshots from this piece: [AR](https://mobile.guardianapis.com/rendered-items/politics/2022/mar/24/rishi-sunak-spring-statement-questions-about-his-political-savvy), [Dotcom](https://www.theguardian.com/politics/2022/mar/24/rishi-sunak-spring-statement-questions-about-his-political-savvy)

[analysis-ar]: https://user-images.githubusercontent.com/53781962/163397360-c6b9defd-f4d3-4969-84fd-3fcf11234080.jpg
[analysis-dotcom]: https://user-images.githubusercontent.com/53781962/163397353-d6e919ef-7d91-4151-81a3-0e49c0ef3102.jpg

## Font Weight

The headline font is Guardian Headline. AR currently has its weight set to 300. DCR has its weight set to 500, the same as on standard articles. Which is correct?

## Underline

There are a couple of differences here:

1. Both colours are the same news[400], but DCR's version uses a transparency of 50%
2. AR's underline matches the width of the text, whereas DCR's underline goes full width

Which is correct? Or do we want to consider removing the underline entirely, effectively updating analysis pieces to look no different from standard articles?

If we do remove the underline, we'll want to drop the line height back to the same size as standard articles.

**Comment by ajbreuer** [comment]
@JamieB-gu Not sure if this still live, but on apps we can removed the underline styling completely o apps and they can look like standard articles, we have removed the same underline styling from fronts cards as part of the UI modernisation and so no need to keep it at an article level

**Comment by JamieB-gu** [comment]
Thanks Alex 🙂, in that case closing this in favour of #4803.
