### ISSUE TITLE
moneydeals.theguardian.com DNS and Certificate issues

### ISSUE THREAD

**Issue by AshCorr** [guardian/dotcom-rendering#4657]
# Initial issue

This [certificate](https://us-east-1.console.aws.amazon.com/acm/home?region=us-east-1#/certificates/a9442aa3-c635-4543-88c4-60801a214fe4 ) is stuck at "Pending validation" in ACM(Amazon Certificate Manager) when renewing. This was caused by the CNAME record used to verify that we own the subdomain was not being set.

```bash
➜  ~ dig +short CNAME moneydeals.theguardian.com
gu-domains.net.
```

After adding the CNAME to NS1 (our domain provider) it resolved the "Pending Validation" issue in AWS.

# Follow up Issue

We were able to resolve the initial issue by adding a CNAME to NS1, but we shouldn't have needed to actually do that. This subdomain should be managed automatically by Route 53 which would have set the CNAME to the correct value by itself without any human intervention.

The DNS records around `moneydeals.theguardian.com` seems a bit odd. When checking the NS records of the `moneydeals.theguardian.com` domain we do indeed see that they are pointing to some AWS name servers which would imply that it should be managed by Route 53.

```bash
➜  ~ dig +short NS moneydeals.theguardian.com
gu-domains.net.
ns-574.awsdns-07.net.
ns-56.awsdns-07.com.
ns-1954.awsdns-52.co.uk.
ns-1401.awsdns-47.org.
```

but they don't seem to be the same nameservers that Route 53 specifies

<img width="1183" alt="image" src="https://user-images.githubusercontent.com/21217225/163994664-7526b00c-ecf3-4a5f-8892-5917e7685c29.png">

Checking NS1 we can't actually see any NS records specifically set for the `moneydeals.theguardian.com`, so we're still unsure how these NS records are being set... there is a SOA record set which might explain why this is happening.

```bash

➜  ~ dig +short SOA moneydeals.theguardian.com
gu-domains.net.
ns-1954.awsdns-52.co.uk. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400
```

It would be good to try and investigate how DNS is actually configured for this subdomain and see if we can potentially get Route 53 working correctly.

EDIT: It looks like the nameservers might be pointing to a different Route 53 configuration, it looks like these NS are set under the `domains` AWS account https://prism.gutools.co.uk/route53-zones/arn:aws:route53:::hostedzone%2FZDE3SYJ28JR6L

# Follow up follow up issue

The certificate being used by `moneydeals.theguardian.com` doesn't seem to be the same certificate that is generated by ACM https://github.com/guardian/domains-platform/blob/36ac4ea21ab8dba420e30475caca0b8db2bf182f/cloudformations/domains-cloudformation.yaml#L236

We thought that perhaps there was a plan to migrate the `moneydeals.theguardian.com` from the `domains` AWS account to the `frontend` AWS account which is why theres Route 53 and ACM configuration under frontend for this domain, but this had never been completed which is why the certificate isn't used and why the domain isn't configured correctly.

We should try and see if we can finish this migration.

**Comment by jamesgorrie** [comment]
cc: @akash1810

**Comment by AshCorr** [comment]
Certificate is renewed now, and it should hopefully auto renew next time. The remaining tasks on this ticket would be to figure out whats going on with NS1 / Route 53 and try to clear that up.

**Comment by rhiannareechaye** [comment]
We are deprioritising this ticket by 'closing a not planned' - this won't delete the ticket and it will be searchable if the issue crops up again. Unfortunately we have over 130 health tickets to address in the web team and we can't address them all. With so many tickets we are potentially missing things that are high-impact so we're reorganising.
