### ISSUE TITLE
Fronts Ophan tag parity (`data-component`)

### ISSUE THREAD

**Issue by mxdvl** [guardian/dotcom-rendering#4698]
## Remaining Front components mismatches

Comparing **`data-component`** on the international Front between [Frontend][] & [DCR][].

[Frontend]: https://www.theguardian.com/international?dcr=false
[DCR]: https://www.theguardian.com/international?dcr=true

### Missing from DCR (1 / 25)

- [X] **`palette-styles-new-do-not-delete`** &rarr; `<SECTION/>`

### Tag mismatch (3 / 25)

- [X] **`nav3`** : `<DIV />` &cross; should be &rarr; `<NAV/>`
- [X] **`nav2`** : `<DIV />` &cross; should be &rarr; `<NAV/>`
- [X] **`footer`** : `<DIV />` &cross; should be &rarr; `<FOOTER/>`

---

### Identical match (21 / 25)

- [X] **`headlines`** &rarr; `<SECTION/>`
- [X] **`ukraine-invasion`** &rarr; `<SECTION/>`
- [X] **`spotlight`** &rarr; `<SECTION/>`
- [X] **`opinion`** &rarr; `<SECTION/>`
- [X] **`sport`** &rarr; `<SECTION/>`
- [X] **`wordiply`** &rarr; `<SECTION/>`
- [X] **`around-the-world`** &rarr; `<SECTION/>`
- [X] **`climate-crisis`** &rarr; `<SECTION/>`
- [X] **`contact-the-guardian`** &rarr; `<SECTION/>`
- [X] **`culture`** &rarr; `<SECTION/>`
- [X] **`cotton-capital`** &rarr; `<SECTION/>`
- [X] **`lifestyle`** &rarr; `<SECTION/>`
- [X] **`documentaries`** &rarr; `<SECTION/>`
- [X] **`explore`** &rarr; `<SECTION/>`
- [X] **`take-part`** &rarr; `<SECTION/>`
- [X] **`today-in-focus`** &rarr; `<SECTION/>`
- [X] **`videos`** &rarr; `<SECTION/>`
- [X] **`video-playlist`** &rarr; `<DIV/>`
- [X] **`in-pictures`** &rarr; `<SECTION/>`
- [X] **`most-viewed`** &rarr; `<SECTION/>`
- [X] **`trending-topics`** &rarr; `<SECTION/>`

**Comment by mxdvl** [comment]
See also #4662

**Comment by mxdvl** [comment]
All the missing components/containers/elements are not yet implemented in DCR Fronts:

- `contact-the-guardian`: This is the `Tip us off` banner
<img width="1054" alt="image" src="https://user-images.githubusercontent.com/76776/166439940-9322e440-8f14-4c0c-98ec-7d400c2d4e3e.png">

- `labs-container-12`: This is the Guardian Labs container
<img width="1012" alt="image" src="https://user-images.githubusercontent.com/76776/166440053-d4775ddd-8217-4b64-a8af-cb88e9775746.png">

- `video-playlist`: maybe this is "fixed/video"
<img width="1003" alt="image" src="https://user-images.githubusercontent.com/76776/166440077-5bbff777-64e6-4cf4-888e-9805966f2568.png">

- `trending-topics`: List of topics at the bottom of Front
<img width="1003" alt="image" src="https://user-images.githubusercontent.com/76776/166440541-002f36b5-a3aa-4be3-9c2f-572fce48aa3b.png">

- `footer`: Missing from now
<img width="1001" alt="image" src="https://user-images.githubusercontent.com/76776/166440565-71941809-f372-4f20-958d-9038cb644ed3.png">

**Comment by VDuczekW** [comment]
review at and after launch

**Comment by ioannakok** [comment]
Completed
