### ISSUE TITLE
Correct padding on mobile cards on fronts

### ISSUE THREAD

**Issue by ajbreuer** [guardian/dotcom-rendering#4705]
The padding on headlines and the meta text on cards on the mobile front is not correct.

Attached figma file shows the details 

https://www.figma.com/file/qYoVxqhuA97d7xR4bVMUpu/DCR-Fronts-mobile-Corrections?node-id=0%3A1
<img width="626" alt="Screenshot 2022-04-25 at 14 34 27" src="https://user-images.githubusercontent.com/1144827/165100274-86223eb0-ccde-41fc-834b-d59e1ad35887.png">

**Comment by ioannakok** [comment]
Bottom-padding will be fixed as part of: https://github.com/guardian/dotcom-rendering/issues/4869

**Comment by oliverlloyd** [comment]
Dupe of https://github.com/guardian/dotcom-rendering/issues/4723?

**Comment by jamesgorrie** [comment]
![nice](https://user-images.githubusercontent.com/31692/221852354-c9b60653-206f-4fd7-87d1-9a00b4490737.png)

Fixed on DCR fronts
