### ISSUE TITLE
Review when we show quotes in card headlines

### ISSUE THREAD

**Issue by oliverlloyd** [guardian/dotcom-rendering#4710]
We currently limit quotes to `Design.Comment` & `Design.Letter`, excluding them for `Design.Editorial`

Should we limit this more?

**Comment by ajbreuer** [comment]
> > sometimes we do need to make a headline a quote in a news story / feature / interview … using the fronts tool
> 
> Thanks @ajbreuer , useful information. It sounds like there might be a property in the model that we need to honour for this

Thanks, Yes, it is a useful thing for editors to have across a range of story types
