### ISSUE TITLE
Align card headline with image

### ISSUE THREAD

**Issue by HarryFischer** [guardian/dotcom-rendering#4721]

**Comment by HarryFischer** [comment]
![image](https://user-images.githubusercontent.com/20658471/165267386-e59adc9f-b2a0-45ee-9f45-7f126bcb701d.png)

**Comment by oliverlloyd** [comment]
The meta alignment issue is now covered as part of the wider card meta design work

https://www.figma.com/file/5CfbWOeZPRi15lXBD5u1rW/Card-layout-system?node-id=0%3A1

**Comment by oliverlloyd** [comment]
The has been completed by the work here https://github.com/guardian/dotcom-rendering/pull/4921
