### ISSUE TITLE
Remove analysis underline when `containerPalette` is in use

### ISSUE THREAD

**Issue by HarryFischer** [guardian/dotcom-rendering#4726]
We don't underline analysis headlines when a palette is in use

![Image](https://user-images.githubusercontent.com/1336821/173347482-86088ebc-824e-4b78-90ef-8d8e95c617d6.png)

**Comment by oliverlloyd** [comment]
@HarryFischer I think the bug shown (lines in the wrong place) might now be fixed, do we still want to remove them?

If so, should that be in all cases or conditional?

**Comment by HarryFischer** [comment]
If they are fixed then I think we can leave them on there for now. Eventually we will want to remove these and replace with a better indication that something is analysis (text string probably) so if they are still buggy I wouldn't spend ages fixing them and just remove but if not we can leave them on for now @oliverlloyd

**Comment by oliverlloyd** [comment]
Thanks Harry, that makes sense.

One more question on this. I notice that they get dropped when a palette is in use - should we continue with that behaviour?

<img width="724" alt="Screenshot 2022-05-27 at 09 50 50" src="https://user-images.githubusercontent.com/1336821/170665965-92fb4006-3dd2-422c-957e-b7e04e63f38b.png">

**Comment by HarryFischer** [comment]
I think it's fine to leave it off of those
