### ISSUE TITLE
Hide and borders are not visible when used with dark fronts palettes – design done

### ISSUE THREAD

**Issue by HarryFischer** [guardian/dotcom-rendering#4733]
Colour values to follow

Current:
![image](https://user-images.githubusercontent.com/20658471/165287510-a85963cd-e0e1-482f-80e7-86dcedc3b657.png)

**Comment by Bryony-Szekeres** [comment]
**For longRunning, event, eventAlt, breaking, longRunningAlt:**

  "container-borders": neutral.0 16% opacity;
  "hide": neutral.20;

**For sombre, investigation, sombreAlt:**

  "container-borders": neutral.100, 16% opacity;
  "hide": neutral.86;

[https://www.figma.com/proto/5CfbWOeZPRi15lXBD5u1rW/Card-layout-system?page-id=0%3A1&node-id=45%3A9518&viewport=-4048%2C584%2C0.18&scaling=min-zoom]

**Comment by alinaboghiu** [comment]
We no longer support dark fronts. We can implement dark front backgrounds quite easily however if the need arises with minimal tooling/rendering change.
