### ISSUE TITLE
Images should get darker, not lighter, on hover

### ISSUE THREAD

**Issue by HarryFischer** [guardian/dotcom-rendering#4734]
Can we make background of all images black and then apply opacity on hover? Design can provide opacity value if this is possible

**Comment by paperboyo** [comment]
> Can we make background of all images black

We shouldn’t, because they can be cutouts. See https://github.com/guardian/frontend/issues/8963.

**Comment by oliverlloyd** [comment]
I've removed the Fronts launch milestone from this as I don't think this is a blocker for launch

**Comment by alinaboghiu** [comment]
It looks like this was done. Please reopen if not
