### ISSUE TITLE
Remove MPUs from containers. Instead, house them in completely separate rows (as they would be on mobile).

### ISSUE THREAD

**Issue by HarryFischer** [guardian/dotcom-rendering#4735]
@Bryony-Szekeres @ajbreuer Do you have context for this?

**Comment by oliverlloyd** [comment]
I think this is a post migration change? I'd be nervous making such a change as part of the migration as this would potentially impact the ad revenue metrics we monitor to make sure we don't introduce any issues with the migration. Changing ad position could corrupt those metrics.

**Comment by alinaboghiu** [comment]
This has been done
