### ISSUE TITLE
Standardise the spinning animation on the '+ More Opinion' button to align with other loading buttons styles in Source

### ISSUE THREAD

**Issue by HarryFischer** [guardian/dotcom-rendering#4737]
Design to provide details

**Comment by HarryFischer** [comment]
![image](https://user-images.githubusercontent.com/20658471/172357834-4c85f458-94da-47b5-8455-09d344790974.png)

**Comment by bryophyta** [comment]
<img width="299" alt="image" src="https://user-images.githubusercontent.com/37048459/199234673-a93a8c82-a724-4923-a75b-149b1213f535.png">
<img width="239" alt="image" src="https://user-images.githubusercontent.com/37048459/199234704-4d534071-4506-44c9-8486-f51a4decacd5.png">

@HarryFischer do these look about right to you? I couldn't find the exact colour that Frontend's using in the [current Source palette](https://guardian.github.io/source/?path=/docs/packages-source-foundations-palette--palette#colour-tokens),  so opted for `neutral[7]`.

Also, I wasn't sure if you were  intending there to be a smooth transition from one state to the other? At the moment we're using the `loading` state from the Source Button component to indicate the in-between state, which adds a spinner (hence no smooth transition). But if it's important for the cross icon to actually rotate into position then we should be able to do that (though perhaps in a separate PR from the main showmore one?)
