### ISSUE TITLE
Old football reports are missing min by min content

### ISSUE THREAD

**Issue by ioannakok** [guardian/dotcom-rendering#4748]
This was reported by email by a sport editor and CP:

> Please see the below from James, old football reports appear to be missing lots of min by min content.

> https://www.theguardian.com/football/live/2015/mar/19/dynamo-kyiv-v-everton-europa-league-live?dcr=false shows correctly, so assume DCR related? 

> I just wanted to flag an issue with this old report and whether it's being replicated more widely?

> https://www.theguardian.com/football/live/2015/mar/19/dynamo-kyiv-v-everton-europa-league-live

Chat conversation here: https://chat.google.com/room/AAAAPTsU18A/nUXouk6f0G8

**Comment by OllysCoding** [comment]
Closed by https://github.com/guardian/frontend/pull/24986
