### ISSUE TITLE
Series tag should be getting the pillar colour in sports

### ISSUE THREAD

**Issue by ioannakok** [guardian/dotcom-rendering#4749]
Reported by CP in Dotcom channel:

DCR:
<img width="574" alt="image" src="https://user-images.githubusercontent.com/19683595/165479699-0ba833ef-b84d-4e84-a456-f5b532356f97.png">

frontent:
<img width="531" alt="image" src="https://user-images.githubusercontent.com/19683595/165479630-91688f74-9d98-410b-aed2-b0334db8987c.png">

Other pillars, e.g.
News: https://www.theguardian.com/technology/2022/apr/27/elon-musks-twitter-takeover-the-experts-verdict-on-what-lies-ahead
Culture: https://www.theguardian.com/artanddesign/2022/apr/27/robbie-williams-art-a-level-examiner-verdict

**Comment by OllysCoding** [comment]
Should this now be the darker `sport.300` instead of `sports.400` like it is on frontend? @HarryFischer

**Comment by HarryFischer** [comment]
Can you copy the colour here: https://www.theguardian.com/sport/2022/apr/26/wimbledon-defends-player-ban-as-djokovic-is-given-green-light-for-sw19
