### ISSUE TITLE
Remove Headline Font Size Restriction

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#4757]
Remove the CSS that prevents headlines from being scaled by the font size slider.

https://github.com/guardian/dotcom-rendering/blob/07d56af59dffc5017d2cb2e78bdecda0f2f0cdbc/apps-rendering/src/components/headline.tsx#L130-L136

## Explanation

We allow users to scale the font sizes of their articles up and down using a slider. There may be many reasons for doing this, with the most common being to increase legibility.

We received some feedback early on that some users, upon scaling up their font sizes, found that they didn't like how large the headline text had become. Headline font sizes are much larger relative to the size of other text in articles (body text, standfirst, captions etc.), and the scaling is linear and consistent across all text on the page. In an attempt to remedy this we "opted out" headlines from this scaling: https://github.com/guardian/apps-rendering/pull/702

However, we have now received further feedback that leaving headlines out of this scaling is also problematic. For example, at larger scaling factors the headline can appear smaller than the standfirst. Therefore we'd like to remove the code that opts headlines out of our scaling mechanism, and revert to the previous behaviour where everything scales equally.

**Comment by ajbreuer** [comment]
If there is anyway this could be done quite quickly that would make the boss very happy :)
