### ISSUE TITLE
Resolve Kicker Inconsistency Between Dotcom And Apps

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#4760]
We're inconsistent about the kickers we show between the two platforms.

### Apps

This is the simpler of the two: if the article is part of a series we show that as the kicker, otherwise we don't. This is true on all breakpoints.

Series: https://mobile.guardianapis.com/rendered-items/environment/2022/apr/27/texas-voter-suppression-climate-action-impact
No series: https://mobile.guardianapis.com/rendered-items/politics/2022/apr/27/angela-rayner-hits-back-at-claims-she-enjoys-sexist-slurs

### Dotcom

A bit more complicated. If the articles isn't part of a series, we show the first tag as a kicker. This is true on all breakpoints. If it _is_ part of a series it will show _both_ the series _and_ the top tag as a kicker on desktop, and _only_ the series on narrower breakpoints.

Series: https://www.theguardian.com/environment/2022/apr/27/texas-voter-suppression-climate-action-impact
No series: https://www.theguardian.com/politics/2022/apr/27/angela-rayner-hits-back-at-claims-she-enjoys-sexist-slurs

## Screenshots

| | Dotcom | Apps |
| - | - | - |
| Series Wide | ![dotcom-series-wide][] | ![apps-series-wide][] |
| Series Narrow | ![dotcom-series-narrow][] | ![apps-series-narrow][] |
| No Series Wide | ![dotcom-no-series-wide][] | ![apps-no-series-wide][] |
| No Series Narrow | ![dotcom-no-series-narrow][] | ![apps-no-series-narrow][] |

[dotcom-no-series-wide]: https://user-images.githubusercontent.com/53781962/165544303-2b832172-9bea-460e-8701-ad4f995aeaad.jpg
[apps-no-series-wide]: https://user-images.githubusercontent.com/53781962/165544313-ba5b1cd1-5288-4093-8660-db62f811153c.jpg
[dotcom-series-wide]: https://user-images.githubusercontent.com/53781962/165544318-ab5a7bce-5185-46dc-afa8-9d58d3cca998.jpg
[apps-series-wide]: https://user-images.githubusercontent.com/53781962/165544323-e34bcdbb-4f9b-4415-ab64-105cc31fe9ad.jpg
[dotcom-no-series-narrow]: https://user-images.githubusercontent.com/53781962/165545591-d140571a-c65c-4db2-8dee-506cb25fd518.jpg
[apps-no-series-narrow]: https://user-images.githubusercontent.com/53781962/165545597-2a8d4e24-ddda-4931-bce1-482f9c96da82.jpg
[apps-series-narrow]: https://user-images.githubusercontent.com/53781962/165545604-2684b1f6-a8bb-4654-83a6-094633436ffc.jpg
[dotcom-series-narrow]: https://user-images.githubusercontent.com/53781962/165545608-c6b5d999-b0da-4d94-a40e-4f0d9d3ee812.jpg

**Comment by georgeblahblah** [comment]
@rhiannareechaye and @ajbreuer this might be one of the things that we want to look at as part of the DCR / AR migration?

**Comment by JamieB-gu** [comment]
The rules on dotcom are correct. The dotcom rules will automatically be applied to the apps by the DCAR rollout.
