### ISSUE TITLE
Videos are not playing (both in frontend & DCR) in older interactive article

### ISSUE THREAD

**Issue by ioannakok** [guardian/dotcom-rendering#4802]
Videos are not working (both in frontend & DCR) in this article:

https://www.theguardian.com/world/ng-interactive/2015/sep/23/un-security-council-failing-70-years

It seems to be using this script: https://github.com/guardian/interactive-visual-story-template

**Comment by ioannakok** [comment]
The videos and poster images loaded are from http and that is not allowed by our CSP


![Image](https://user-images.githubusercontent.com/19683595/166683107-9258163f-7c60-425f-aaeb-d31bbbfb8a3f.png)

**Comment by ioannakok** [comment]
Emailed CP & Visuals to see if the content can be re-created using current standard practices

**Comment by ioannakok** [comment]
It is not possible for the content to be re-created. A good solution would be to add SSL to the [guardian.tv](http://guardian.tv/) domain.

**Comment by rhiannareechaye** [comment]
We are deprioritising this ticket by 'closing a not planned' - this won't delete the ticket and it will be searchable if the issue crops up again. Unfortunately we have over 130 health tickets to address in the web team. With so many tickets we are potentially missing things that are high-impact so we're reorganising the board - if we can get through all our high-impact tickets we can re-open these lower impact ones.
