### ISSUE TITLE
Wavy Lines Sometimes Missing On Features

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#4812]
Typically feature pieces (`Design.Feature`, `tone/features`) have wavy lines as part of the byline/metadata. For some feature pieces on dotcom these appear to revert to the straight lines used on standard articles. The only consistency I can find is that the pieces where this happens always seem to be "supported by", and include a logo and extra copy as part of the metadata. AR, by contrast, always uses the wavy lines regardless of whether the piece is "supported by".

Which of the following is true?

1. This a bug and all feature pieces should use wavy lines regardless of whether they're "supported by". In this case we need to update DCR.
2. This is a feature and all "supported by" feature pieces should use straight lines instead. In this case we need to update AR.
3. The platforms are meant to look different here, so everything is as it should be.

## Examples

- There are lots of examples of the "supported by" variant in this series: https://www.theguardian.com/food/series/grace-dent-on-restaurants
- There are lots of examples of normal feature articles here: https://www.theguardian.com/tone/features

## Screenshots

| Piece | DCR | AR |
| - | - | - |
| [Supported By Piece](https://www.theguardian.com/food/2022/mar/25/benoli-norwich-restaurant-review-grace-dent) | ![dotcom-straight-lines][] | ![ar-supported-by][] |
| [Normal Piece](https://www.theguardian.com/food/2022/apr/22/mildreds-london-wc1-unapologetic-and-utterly-un-preachy-restaurant-review) |  ![dotcom-wavy-lines][] | ![ar-normal][] |

[dotcom-straight-lines]: https://user-images.githubusercontent.com/53781962/166493197-bde4832c-b1e5-47e4-9208-3f7dd3478107.jpg
[dotcom-wavy-lines]: https://user-images.githubusercontent.com/53781962/166493200-470d8760-a27f-40a6-9499-3f8f10ba0efa.jpg
[ar-supported-by]: https://user-images.githubusercontent.com/53781962/166494544-4b6d0130-aea5-44b4-aa3d-4b26a7128ed8.jpg
[ar-normal]: https://user-images.githubusercontent.com/53781962/166494536-1e3b66c1-bacd-426c-aa17-1480d3ee8a0b.jpg

**Comment by JamieB-gu** [comment]
@ajbreuer @HarryFischer what do you think?

**Comment by ajbreuer** [comment]
@JamieB-gu I think we can get rid of the wavy lines altogether.

**Comment by JamieB-gu** [comment]
> I think we can get rid of the wavy lines altogether.

Oh interesting! On both dotcom and apps and for feature pieces specifically?

**Comment by ajbreuer** [comment]
> > I think we can get rid of the wavy lines altogether.
> 
> Oh interesting! On both dotcom and apps and for feature pieces specifically?

I would be happy if we removed them from both dotcom and apps altogether. More decorous... less decoration

**Comment by MarSavar** [comment]
@ajbreuer Wavy lines currently appear in Feature and Recipe articles. Should recipes also have straight lines?

**Comment by MarSavar** [comment]
As per https://github.com/guardian/dotcom-rendering/issues/4848, wavy lines need to be removed altogether. 
Closing this issue!
