### ISSUE TITLE
Dropcap Missing When Piece Starts With H2

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#4813]
Dropcaps appear on a number of different article formats; more details on the rules in #4542. In brief, they're generally meant to appear on the first letter on the first paragraph of a piece. Based on @ajbreuer's comment here they're meant to appear even if there's another element that precedes that first paragraph: https://github.com/guardian/dotcom-rendering/issues/4542#issuecomment-1098390249

On DCR they don't seem to be appearing if the first paragraph of a piece is preceded by an `<h2>` element. AR, on the other hand, includes the dropcap even if this is the case. Which is correct?

## Examples

Examples can be found on most (all?) pieces in "The Fiver" series: https://www.theguardian.com/football/series/thefiver

Here's one to demonstrate: https://www.theguardian.com/football/2022/may/03/villarreals-mission-nigh-on-impossible-against-liverpool

## Screenshots

| Piece | AR | DCR |
| - | - | - |
| [Starts With h2](https://www.theguardian.com/football/2022/may/03/villarreals-mission-nigh-on-impossible-against-liverpool) | ![ar-dropcap][] | ![dcr-dropcap][] |
| [Starts With Paragraph](https://www.theguardian.com/football/blog/2022/may/02/real-madrid-seal-carlo-ancelotti-grand-slam-titles-la-liga) | ![ar-para-dropcap][] | ![dcr-para-dropcap][] |

[ar-dropcap]: https://user-images.githubusercontent.com/53781962/166500862-7c07bd27-8401-4bb6-9b32-caa330b622f8.jpg
[dcr-dropcap]: https://user-images.githubusercontent.com/53781962/166500873-99bcdbd8-42a9-4f40-9498-5bb7e8ce39ab.jpg
[ar-para-dropcap]: https://user-images.githubusercontent.com/53781962/166502522-b0a53096-3547-4165-9a8b-f0069ee01dbb.jpg
[dcr-para-dropcap]: https://user-images.githubusercontent.com/53781962/166502515-4cf9b71b-c346-4af9-84f9-4739a8e83097.jpg

**Comment by JamieB-gu** [comment]
@paperboyo @ajbreuer @HarryFischer what do you think?

**Comment by iainjchambers-guardian** [comment]
Are h2s the only headings that would be used? There's a couple of potential fixes here and I'm wondering how specific to be.

**Comment by HarryFischer** [comment]
H2s are the only headings we have in the article body
I think the rule should be that it should show if it follows a H2, img or an atom/embed ? But not a bulleted/numbered list, pull quote etc
Does that work?

**Comment by rhiannareechaye** [comment]
We are deprioritising this ticket by 'closing a not planned' - this won't delete the ticket and it will be searchable if the issue crops up again. Unfortunately we have over 130 health tickets to address in the web team. With so many tickets we are potentially missing things that are high-impact so we're reorganising the board - if we can get through all our high-impact tickets we can re-open these lower impact ones.

**Comment by rhiannareechaye** [comment]
We are deprioritising this ticket by 'closing a not planned' - this won't delete the ticket and it will be searchable if the issue crops up again. Unfortunately we have over 130 health tickets to address in the web team. With so many tickets we are potentially missing things that are high-impact so we're reorganising the board - if we can get through all our high-impact tickets we can re-open these lower impact ones.
