### ISSUE TITLE
Serve Feature In Beta

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#4814]
We will need to remove the filter in MAPI that filters out features in Beta. These articles are identified in CAPI by the presence of the `tone/features` tag; there's already an `isFeature` method (`ContentApi.scala`) used in `RenderedItemUtils.scala` to identify them.

**Comment by MarSavar** [comment]
https://github.com/guardian/mobile-apps-api/pull/1949

**Comment by JamieB-gu** [comment]
@MarSavar did this go out into PROD? If so shall we close?

**Comment by MarSavar** [comment]
Yes and yes!
