### ISSUE TITLE
Refactor image position

### ISSUE THREAD

**Issue by oliverlloyd** [guardian/dotcom-rendering#4822]
Review and refactor the logic for how we size and position images in cards

**Comment by paperboyo** [comment]
Just a note that old fronts have a long-standing bug of sometimes using too-small a pic for when there are only two cards next to each other:

![image](https://user-images.githubusercontent.com/6032869/166665711-dacd7e8e-87eb-4948-9493-fc715f4632ea.png)

Just wanted to mention to avoid parity in DCR here.

**Comment by OllysCoding** [comment]
Before releasing network fronts we should review the sizes & resolutions of images in DCR fronts compared to Frontend, and ensure we're at or close to parity.

**Comment by alinaboghiu** [comment]
We may not always know what size the image needs to be (e.g changes at different breakpoints) - this ticket is to check that we are doing at least a good a job as frontend
- could we fix the image size where possible? 

We should capture this in a Story

**Comment by mxdvl** [comment]
One key issue is that a `Card` element does not know how many columns it actually spans server-side. The final sizing is currently driven by flex & CSS on the client-side. I believe than when we want to tackle this work, we might find that it will work extremely well with CSS grid and explicit sizes for cards.

**Comment by paperboyo** [comment]
> One key issue is that a `Card` element does not know how many columns it actually spans server-side.

You know I don’t know. But even if above is true, the unknown card sizes will still be from an array of predefined CSS pixel sizes, right? (not totally fluid) If that’s the case, wouldn’t Picture Element containing all possible CSS pixel sizes mean that the correctly-sized image will be chosen by the browser on render? Or not?

**Comment by mxdvl** [comment]
> > One key issue is that a `Card` element does not know how many columns it actually spans server-side.
> 
> You know I don’t know. But even if above is true, the unknown card sizes will still be from an array of predefined CSS pixel sizes, right? (not totally fluid) If that’s the case, wouldn’t Picture Element containing all possible CSS pixel sizes mean that the correctly-sized image will be chosen by the browser on render? Or not?

It’s currently [totally fluid and sizes are specified using percentages on the `flex-basis`](https://github.com/guardian/dotcom-rendering/blob/49beb925c758337ed8a372943bddf74172205bf9/dotcom-rendering/src/components/Card/components/ImageWrapper.tsx#L15-L50).

**Comment by rhiannareechaye** [comment]
Dynamic package full-with image [is loaded at 700px](https://m.code.dev-theguardian.com/sublinks-test?dcr#dynamic/package-(dynamo)) wide instead of 940px in Frontend leading to a low resolution
