### ISSUE TITLE
Jump to comment not working persistently

### ISSUE THREAD

**Issue by ioannakok** [guardian/dotcom-rendering#4836]
Reported from userhelp:

1) Chrome

As you can see, normally two comments are pinned to the top by the admins

https://www.theguardian.com/commentisfree/2022/may/04/us-lend-lease-act-ukraine-1941-second-world-war#comment-156234098

<img width="1148" alt="image" src="https://user-images.githubusercontent.com/19683595/166912072-cdcdc16a-b148-4f47-bd91-11d88035374e.png">

[whatsmybrowser.org/b/EWVA5](http://whatsmybrowser.org/b/EWVA5)

- pick any comment
- jump to comment works the first time 
- scroll back up to 'jump to comment' link for that comment
- link does not work
- link does work for the other comment, or if you refresh the page it will load onto the comment that it failed to jump to

(video attached)

2) Firefox - intended function

https://www.whatsmybrowser.org/b/8K738

- pick any comment
- jump to comment works over and over for the same comment

https://user-images.githubusercontent.com/19683595/166912387-5c5af4da-b17b-4a30-ac70-0aade84ea4e9.mp4

**Comment by jlieb10** [comment]
TBD: there is a PR open for this, but it may be closed in favour of doing a better longterm solution. 

https://github.com/guardian/dotcom-rendering/pull/4886

**Comment by jlieb10** [comment]
Related issue: https://github.com/guardian/discussion-rendering/issues/580

**Comment by jlieb10** [comment]
We won't pursue this bug at this time, as this behaviour is not fundamentally breaking the page and the fix is non-trivial - It will involve revisiting the way discussion rendering is architected into DCR
