### ISSUE TITLE
Deprecation of AWSConfigRole IAM Managed Policy

### ISSUE THREAD

**Issue by ioannakok** [guardian/dotcom-rendering#4841]
We received an email from AWS:

> AWS Config will be deprecating the managed policy AWSConfigRole on July 5, 2022, in order to scope down permissions. This policy is replaced with the policy AWS_ConfigRole.

> The AWSConfigRole managed policy will continue working for all currently attached users, groups, and roles. However, after July 5, 2022, the AWSConfigRole managed policy cannot be attached to any new users, groups, or roles. The policy will also not be updated to include permissions for newly supported resource types and new managed rules. As a user of AWSConfigRole, please update the policy attached to your AWS Config role to AWS_ConfigRole.

> To update the policy, please navigate to the IAM Role you use for Config on the IAM console [1], attach the policy AWS_ConfigRole to the role and remove the policy AWSConfigRole from the role.

**Comment by jfsoul** [comment]
Cross-post from another question regarding this:

> Unless you are specifically configuring access to AWS Config for one of your IAM roles, I suspect this comes from the stackset we use to configure AWS Config in every account.

> So I think it's one for DevX to fix globally - but you might want to double check that this policy isn't used outside a role called ConfigRecorderRole (from a cloudformation stackset called StackSet-AWS-Config...)

**Comment by jfsoul** [comment]
Usages can be checked here I believe (if there's only one from a stackset then you can leave it to us to fix): https://us-east-1.console.aws.amazon.com/iam/home#/policies/arn:aws:iam::aws:policy/service-role/AWSConfigRole$jsonEditor?section=attached_entities

**Comment by alinaboghiu** [comment]
Assuming this was done
