### ISSUE TITLE
Remove Wavy Lines From Feature

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#4848]
We'd like to remove the wavy lines that appear as part of the metadata on feature pieces. We'd like to replace them with the straight lines that appear on standard articles. This change should be made for both AR and DCR.

See this for more information: https://github.com/guardian/dotcom-rendering/issues/4812#issuecomment-1119446374

## Examples

Examples of feature pieces can be found here: https://www.theguardian.com/tone/features

**Comment by HarryFischer** [comment]
@ajbreuer There were some questions around this that I'm not sure about:
1. Does this effect both Features and Recipes? Are we replacing with flat lines?
2. Do we then lose the other lines variants across other Pillars? (dotted lines on Sport, 8 lines on Opinion, single line on Labs)
