### ISSUE TITLE
Automatic releases for npm packages?

### ISSUE THREAD

**Issue by bryophyta** [guardian/dotcom-rendering#4864]
DevX mentioned that it is now preferred practice to automate the process of releasing new package versions to npm using a tool like [semantic release](https://github.com/semantic-release/semantic-release) or [changesets](https://github.com/changesets/changesets).

For any future readers, you can find out more in the [guardian recommendations for npm packages](https://github.com/guardian/recommendations/blob/main/npm-packages.md#continuous-delivery)

There's an example of how this was implemented for [@guardian/cdk](https://github.com/guardian/cdk/pull/271)

**Update:** 
- [x] As discussed below, `atoms-rendering` already has this enabled.
- [ ] Todo: add `changesets` to `discussion-rendering` (see [PR #591](https://github.com/guardian/discussion-rendering/pull/591) in `discussion-rendering`).

**Comment by AshCorr** [comment]
Yes please!

**Comment by oliverlloyd** [comment]
🙏 🙏 🙏  This would be great for repos like https://github.com/guardian/discussion-rendering and https://github.com/guardian/atoms-rendering

**Comment by bryophyta** [comment]
Okay great! Would it make sense for us to schedule some time next week to have a quick chat about when/how to approach this?

**Comment by joecowton1** [comment]
@bryophyta we recently added [Changesets](https://github.com/changesets/changesets) to automate NPM releases on [Source](https://github.com/guardian/source/pull/1243) and [Atoms-Rendering](https://github.com/guardian/atoms-rendering/pull/347). 

There is an ongoing review with the Technology Council to officially approve use of the Changesets bot so I'm not sure whether we should add it to more repos while that's in flow, but it certainly works very nicely. @sndrs or @SiAdcock might you be able to offer guidance on that?

**Comment by sndrs** [comment]
apparently the tech council should be done with changesets this week – they also said that because semantic release predates the tech council audit, they'd advise holding off on adding more instances, esp with changesets coming officially on board soon (hopefully)

(CSTI have also found changesets to work more nicely than semrel if that's any use – hence the submission to tech council)

**Comment by bryophyta** [comment]
Okay thanks, that's good to know! We'll wait to hear what the outcome of that discussion is 👍

**Comment by bryophyta** [comment]
Just circling back to this, have you heard any more about the tech council audit @joecowton1 @sndrs ?

**Comment by joecowton1** [comment]
Hi @bryophyta - @SiAdcock messaged earlier in the week to say:

```
Changesets has been approved by tech council on a trial basis for use in public repos with branch protection switched on.
```

So with the caveat that any repos we add it to should be *public* and with branch protection I think we're good to use it. 

Details here: https://docs.google.com/document/d/19NBdyxKJGSuo8VCwdq7KYxRwm1FaJXoR0cqT0i5jhfU/edit#heading=h.5s1qiblv5yjh

@SiAdcock please say now if i've missed something obvious!

**Comment by joecowton1** [comment]
@bryophyta it was relatively easy to add to Atoms-Rendering but there were a couple of things not covered in the docs, so shout if you get stuck at all.

**Comment by oliverlloyd** [comment]
Thanks for taking the time to update this ticket @joecowton1 - looks like we're go for Changesets!

**Comment by bryophyta** [comment]
That's great, thanks very much! There's some ongoing discussion about when we should allocate time for this, given that some of the other changes we were looking to make to discussion rendering are paused at the moment, but hopefully we'll get to it soon and will definitely get in touch if we hit any issues, thanks!

**Comment by ioannakok** [comment]
Moving this to the backlog but assigning people who have expressed interest in picking it up.
