### ISSUE TITLE
Parse Editorial design correctly

### ISSUE THREAD

**Issue by marsavar** [guardian/dotcom-rendering#4908]
All Editorial articles (i.e. articles with the tag `tone/editorials`) currently also have the tag `tone/comment`.

The code in [`CapiModelEnrichment.scala`](https://github.com/guardian/content-api-scala-client/blob/main/client/src/main/scala/com.gu.contentapi.client/utils/CapiModelEnrichment.scala#L111) that decides which design to return is based on a list of predicates. Order matters, and `tone/comment` is parsed before `tone/editorials`, meaning that if an article has both tags, it will always return `CommentDesign`. You can check this by appending `.json?dcr` to the URL of any article in https://www.theguardian.com/tone/editorials. 

```
format: {
    design: "CommentDesign", // <--- should be EditorialDesign
    theme: "OpinionPillar",
    display: "StandardDisplay"
}
```

Even though there is no visual difference between `CommentDesign` and `EditorialDesign`, `format.design` should be `EditorialDesign` for editorials. 

Action: parse `tone/editorials` before `tone/comment` in `CapiModelEnrichment.scala` (Apps-Rendering already does this).

**Comment by rhiannareechaye** [comment]
We are deprioritising this ticket by 'closing a not planned' - this won't delete the ticket and it will be searchable if the issue crops up again. Unfortunately we have over 130 health tickets to address in the web team and we can't address them all. With so many tickets we are potentially missing things that are high-impact so we're reorganising.
