### ISSUE TITLE
Gather data on Instagram link 404s

### ISSUE THREAD

**Issue by bryophyta** [guardian/dotcom-rendering#4910]
See https://chat.google.com/room/AAAAG9rU0m0/DevNFt_BSdI

> was hoping for some help with gathering a lot of data on 404s...
> 
> for 18+ months we've been getting a proportion of our Instagram links going to 404, I believe because Instagram is breaking the links. But to prove the scale of the problem, it would be great to know exactly how much traffic has gone to 404.
> 
> How far back can we gather that data?
> 
> Instagram has been URL encoding some of our Instagram Story links so that instead of `?utm_source=instagram stories` and `?CMP=aus_igstories`, Instagram is changing the URL to `%3Futm_source%3Dinstagramstories` or `%3FCMP%3Daus_igstories`
> 
> So we'd be looking for every request that is 404'ing with the parameter `instagramstories` or `aus_igstories`

**Comment by jlieb10** [comment]
Potentially a device issue - we are continually corresponding with the person who submitted the issue and it's still in discovery phase.

**Comment by ioannakok** [comment]
After investigation, it seems it is a combination of Instagram, Mozilla and iOS issue: https://logs.gutools.co.uk/s/dotcom/app/dashboards#/view/82f54170-e1c9-11ec-80be-db9ab2d7d2c6?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-15d,to:now)). Unfortunately, at the moment we are not in a position to know the exact number of 200s and 404s. Requests that reach Kibana do so after they hit Fastly and we' re caching 200s on articles for 1 hour and 404s for 10 seconds, so the numbers are not accurate. We will query Fastly logs once we finish with the necessary set up: https://github.com/guardian/dotcom-rendering/issues/5215

**Comment by ioannakok** [comment]
Closing this ticket as the next step is https://github.com/guardian/dotcom-rendering/issues/5215
