### ISSUE TITLE
Fix dropcap when letter has accent

### ISSUE THREAD

**Issue by ioannakok** [guardian/dotcom-rendering#4915]
We need to fix this:

<img width="601" alt="image" src="https://user-images.githubusercontent.com/19683595/168823620-a66ee038-c2d7-4c55-946c-7a46bd4c5f4e.png">

Reported here: https://twitter.com/alex_duf/status/1526547034563653637?t=eea9fpPY9df3r_ySZ7FcuQ&s=19
Article: https://www.theguardian.com/world/2022/may/16/elisabeth-borne-becomes-frances-first-female-prime-minister-in-30-years

**Comment by HarryFischer** [comment]
@paperboyo do you know how common this is?

**Comment by paperboyo** [comment]
@HarryFischer Super uncommon. I’m the first fighting for diacritics against the boredom of naked, featureless ASCII. But “fixing” it to allow for all diacritics to work in all circumstances is not realistic. And, I would argue, not even desired. Design would either need to increase all spacing by a huge margin (think Vietnamese with its stacked diacritics), or do a massive amount of layout shifting after reading specific glyph dimensions via js. Crazy. And ugly and inconsistent.

There is one thing that makes it look awful, though. And this one thing needs fixing: the caption text should be in front of the drop cap.

IMHO and all. But I’m right. Unless there is an alternative I haven’t thought about. But I have.

**Comment by HarryFischer** [comment]
So @AshCorr not a priority necessarily but would be nice to increase the z index on the caption to sit on top of the drop cap if not too much work?

**Comment by rhiannareechaye** [comment]
We are deprioritising this ticket by 'closing a not planned' - this won't delete the ticket and it will be searchable if the issue crops up again. Unfortunately we have over 130 health tickets to address in the web team. With so many tickets we are potentially missing things that are high-impact so we're reorganising the board - if we can get through all our high-impact tickets we can re-open these lower impact ones.

**Comment by rhiannareechaye** [comment]
We are deprioritising this ticket by 'closing a not planned' - this won't delete the ticket and it will be searchable if the issue crops up again. Unfortunately we have over 130 health tickets to address in the web team. With so many tickets we are potentially missing things that are high-impact so we're reorganising the board - if we can get through all our high-impact tickets we can re-open these lower impact ones.
