### ISSUE TITLE
Support Code Blocks

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#4919]
Snippets of code included in the article. An example piece can be found here: https://www.theguardian.com/info/2021/oct/19/pondering-some-scala-performance-questions

To add support do the following:

1. Add a new body `ElementKind`: https://github.com/guardian/dotcom-rendering/blob/de66381276f13d7578c49d3ff1f7af484ae97338/apps-rendering/src/bodyElementKind.ts#L3-L9
2. Add a new `BodyElement`: https://github.com/guardian/dotcom-rendering/blob/de66381276f13d7578c49d3ff1f7af484ae97338/apps-rendering/src/bodyElement.ts#L30-L33
3. Add a new parsing `case` for `ElementType.CODE`
4. Add a new component to render the code element

We probably want the component to involve a `<code>` element wrapped in a `<pre>` element: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/code#notes

**Comment by georgeblahblah** [comment]
Won't do now that we are rendering apps articles in DCR
