### ISSUE TITLE
Liveblogs - DCR does renders some liveblogs as articles

### ISSUE THREAD

**Issue by OllysCoding** [guardian/dotcom-rendering#4938]
This should have deadblog in format but does not!

The ordering of in the capi needs to be updated, similar to: https://github.com/guardian/content-api-scala-client/pull/355

https://www.theguardian.com/tv-and-radio/live/2017/nov/25/strictly-come-dancing-week-10-watch-live

**Comment by rhiannareechaye** [comment]
As per our triaging, this is a high impact issue so ideally we should look at it
