### ISSUE TITLE
Create `Design.Picture`

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#4941]
Picture articles (see the milestone for more information) are not currently represented by `Format`. We'll probably want to add them as `Design.Picture`.

The process to update `Format` is a little bit involved. First the models have to be updated:

1. Add `Picture` to the list of `ArticleDesign`s in `@guardian/libs` for AR and DCR. Example here: https://github.com/guardian/libs/pull/332
2. Add `Picture` to the list of `Design`s in the CAPI client, and update the predicates in `CapiModelEnrichment.scala` to parse it (`type: "picture"`) for DCR. Example here: https://github.com/guardian/content-api-scala-client/pull/353

Then the platforms have to be updated:

1. Update AR and DCR with the new version of `libs`. Teach DCR how to parse the new `Design` that will be passed through from frontend, and teach AR how to parse it from the CAPI models. Then update the various areas of code that use `Design` (`switch` statements etc.) in AR and DCR. Examples here: https://github.com/guardian/dotcom-rendering/pull/4824 https://github.com/guardian/dotcom-rendering/pull/4931 . Note that the case for Picture may be a little simpler, because we're not deleting an old `Design` as we were with `Media`.
2. Update frontend to use the new CAPI client version. Example here: https://github.com/guardian/frontend/pull/24986

It's probably a good idea to do some testing on CODE AR, DCR and frontend to make sure it all works!

**Comment by alinaboghiu** [comment]
This has been done
