### ISSUE TITLE
Support 'Boost'

### ISSUE THREAD

**Issue by oliverlloyd** [guardian/dotcom-rendering#4948]
**Boosting**

Individual cards on `dynamic` containers can be boosted when they're in specific slots. When this switch is activated for a card, it adjusts the cards size & position within a container (generally to make it larger / more visually interesting).

As a result of boosting, the position / size of other cards in the container are generally changed.

Container Checklist

- [x] dynamic/fast - Introduced in https://github.com/guardian/dotcom-rendering/pull/5427 (needs refactor)
- [x] dynamic/package - Introduced in https://github.com/guardian/dotcom-rendering/pull/5700
- [x] dynamic/slow-mpu - Introduced in https://github.com/guardian/dotcom-rendering/pull/5427
- [x] dynamic/slow - In progress https://github.com/guardian/dotcom-rendering/issues/5759

**Comment by ajbreuer** [comment]
Hi @oliverlloyd This is another parameter that effects relative size and display of cards  within containers

**Comment by OllysCoding** [comment]
Some interesting things I've learned so far looking into this - 

1. We get the 'huge', 'very big', 'standard' etc groups through as a numbered 'group' for each card: 
![image](https://user-images.githubusercontent.com/9575458/177558147-099c36f4-5432-49a2-b03c-335678bfa320.png)

2. We use boosted to make specific decisions on sizing like:
https://github.com/guardian/frontend/blob/main/common/app/layout/slices/DynamicContainer.scala#L30

**Comment by oliverlloyd** [comment]
Today's dynamic/package has the first card 'boosted' which is resulting in a 50px headline

![Image](https://user-images.githubusercontent.com/1336821/177746419-c394ff21-f0bc-4ebe-9cf6-632ce4d5a639.png)

**Comment by oliverlloyd** [comment]
> > Today's dynamic/package has the first card 'boosted' which is resulting in a 50px headline
> 
> @oliverlloyd was this boosted or was this the 'large headline' option?
> 
> <img alt="image" width="817" src="https://user-images.githubusercontent.com/9575458/178244836-b2daf209-049d-4a1e-987a-c32be190c005.png">

It was boosted. Seems like the `dynamic/package` container does not allow sizes outside of `Standard`, which is nice
<img width="618" alt="Screenshot 2022-07-11 at 11 33 45" src="https://user-images.githubusercontent.com/1336821/178245877-2f3b0277-c99c-4948-ad84-7ce0d5a40e51.png">
