### ISSUE TITLE
`Standard`, `Big`, `Very Big`, `Huge`

### ISSUE THREAD

**Issue by oliverlloyd** [guardian/dotcom-rendering#4949]
What do these classifications mean and how do we support them?
<img width="621" alt="Screenshot 2022-05-19 at 15 54 50" src="https://user-images.githubusercontent.com/1336821/169326616-8e99d679-630a-4162-bbc8-0bac74664a1b.png">

**Comment by ajbreuer** [comment]
@oliverlloyd Hi there, not sure if this is a rhetorical question or not? Apols if so 😁  If not these classifications help define the layout pattern and relative size of cards in the dynamic containers... There are lots of folks who can walk through how it works as needed

**Comment by oliverlloyd** [comment]
> @oliverlloyd Hi there, not sure if this is a rhetorical question or not? Apols if so 😁 If not these classifications help define the layout pattern and relative size of cards in the dynamic containers... There are lots of folks who can walk through how it works as needed

Not rhetorical at all, thanks for the answer!

So these classifications only apply to dynamic containers - this is useful to know 👍  Do you think it would be possible to setup 30m with someone to go through these options (perhaps as well as the [boost setting](#4948 ))?

**Comment by alinaboghiu** [comment]
This has been done
