### ISSUE TITLE
Serve Pictures In Beta

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#5012]
We will need to remove the filter in MAPI that filters out picture articles in Beta. These articles are identified in CAPI by the `type: "picture"` field.

`RenderedItemUtils.scala` currently uses the `isArticleType` method (from `ContentApi.scala`) to filter out all articles without `type: "article"`. We'll have to adjust this to allow other types through. An example for how to do this can be found in https://github.com/guardian/mobile-apps-api/pull/1824

**Comment by georgeblahblah** [comment]
Won't do now that we are rendering apps articles in DCR
