### ISSUE TITLE
Add underline to dateline on Safari

### ISSUE THREAD

**Issue by HarryFischer** [guardian/dotcom-rendering#5025]
Can't work out why this doesn't get applied in Safari on hover
Has both 
```
-webkit-text-decoration: underline;
text-decoration: underline;
```

![Image](https://user-images.githubusercontent.com/20658471/170459162-fbfa5fa8-4252-4c47-ac15-13729ad48244.png)

**Comment by bryophyta** [comment]
Safari seems to be rendering the contents of `<summary>` as shadow-DOM nodes. Given that inheritance of styling  works differently for shadow elements, this might explain why the underline rule isn't being applied in the way we'd expect. I'm not sure why these are being rendered as shadow elements though, so will try to find out more.
