### ISSUE TITLE
Documentaries poster thrasher: No text label in link (DAC Audit)

### ISSUE THREAD

**Issue by VDuczekW** [guardian/dotcom-rendering#5056]
Report Link: https://drive.google.com/file/d/11Tj90HkEFjbW4XsoNOZhxY1uglLAV7a2/view?usp=sharing

Full issue list: https://docs.google.com/spreadsheets/d/1vWQtZfD49uq7uNCNELuYN_HcIj-BKiE4t4Hwda3tJaQ/edit#gid=0

**Comment by bryophyta** [comment]
This issue was addressed for some Documentaries pages by [this PR](https://github.com/guardian/docs-interactive-template/pull/261), and I believe that it should apply to new pages moving forwards. Closing this issue accordingly.
