### ISSUE TITLE
Avatar on comment cards

### ISSUE THREAD

**Issue by oliverlloyd** [guardian/dotcom-rendering#5093]
`Card` already has the avatar included but it is not appearing on DCR Fronts 

<img width="233" alt="Screenshot 2022-05-30 at 16 44 11" src="https://user-images.githubusercontent.com/1336821/171026243-6dbcc7f3-4d41-43a5-aa7f-9b3e6a8dafc1.png">

**Comment by HarryFischer** [comment]
Size and positioning slightly changed - see here:
https://www.figma.com/file/5CfbWOeZPRi15lXBD5u1rW/?node-id=0%3A1
