### ISSUE TITLE
`Card` headline font sizes

### ISSUE THREAD

**Issue by oliverlloyd** [guardian/dotcom-rendering#5106]
Ensure we are setting the correct font sizes for `CardHeadline` based on breakpoint

Figma file pending @HarryFischer

**Comment by HarryFischer** [comment]
Font sizes documented here
https://www.figma.com/file/5CfbWOeZPRi15lXBD5u1rW/Card-layout-system?node-id=0%3A1

Shout if any Q's

cc @oliverlloyd

**Comment by oliverlloyd** [comment]
@HarryFischer are there particular places where we're currently deviating from the designs? I had a look and we seem to be setting the correct sizes in the cases where I checked

**Comment by oliverlloyd** [comment]
Closing after discussing this with Harry, looks like we're now good.
