### ISSUE TITLE
Captions on interactives are awry

### ISSUE THREAD

**Issue by jamesgorrie** [guardian/dotcom-rendering#5110]
DCR renders it mis-aligned. Frontend just didn't render it. Should we render if the same as normal images with a caption? Ping @HarryFischer 

DCR:
![Screenshot 2022-06-01 at 14 57 14](https://user-images.githubusercontent.com/31692/171422262-a1c5ad31-362c-4573-9157-15d28ff9b9ae.png)

Frontend:
![Screenshot 2022-06-01 at 14 57 04](https://user-images.githubusercontent.com/31692/171422485-441e432e-2617-4700-9d1e-975182ca100a.png)

DCR with normal image:
![Screenshot 2022-06-01 at 15 01 21](https://user-images.githubusercontent.com/31692/171423040-4c934be2-c571-47b6-a064-30a102dfb47b.png)

**Comment by HarryFischer** [comment]
@jamesgorrie so put it in a 'i' circle? If so, yes

**Comment by paperboyo** [comment]
Out of curiosity, why was this closed, @jamesgorrie. It still seems to occur, not only in [main media](https://www.theguardian.com/lifeandstyle/2022/jun/12/the-australian-beach-tragedy-that-inspired-a-global-rip-safety-movement), but also [in the body](https://www.theguardian.com/australia-news/2022/aug/01/it-felt-insulting-welfare-recipients-sent-to-body-language-courses-as-job-agencies-profit) (so isn’t directly related to us wanting and being able to add a reveal caption/credit icon on top of custom interactive, which. may or may not be problematic).

**Comment by paperboyo** [comment]
I think this ticket is slightly confused(ing). It should only be about the fact the caption+credit is rendered with too big a gap from preceding element (too low).

**Comment by paperboyo** [comment]
> for interactive main media

Actually not only Main media, but [in-body](https://www.theguardian.com/world/2023/dec/01/hospital-damage-in-gaza-during-israeli-offensive-a-visual-investigation#b7d5b856-38da-4c8a-9cf5-a3c8441d806b) ones too. All of ’em. 😄
