### ISSUE TITLE
Monorepo

### ISSUE THREAD

**Issue by jamesgorrie** [guardian/dotcom-rendering#5127]
The [current proposal](https://docs.google.com/document/d/1O7Uc4mgAeddlw9ig_BMHfmual2LghQnAhvnbQ_nwB_M/edit#heading=h.y52dsefzw9eq) on the decoupling of the repos is currently quite thin.

More detail on what [the new world](https://docs.google.com/document/d/1F2qDRtAJr0Zig2kCX8KU2ggwdxeJ0ykx7STJjUrAMcA/edit#) might look like?

```[tasklist]
- [ ] @jamesgorrie to write up notes from last discussion
```

**Comment by OllysCoding** [comment]
Maybe we can wait until https://github.com/guardian/csnx is available?

**Comment by jamesgorrie** [comment]
Work on https://github.com/guardian/csnx is where we are aiming
