### ISSUE TITLE
Spike: Percy/Cypress integration

### ISSUE THREAD

**Issue by bryophyta** [guardian/dotcom-rendering#5131]
Certain fairly small code changes can cause significant and systematic changes to the visual rendering of the live site, without being picked up by our Chromatic/Storybook tests.

An example is in PR #5119. This PR means that bylines will now be rendered on Fronts cards, whereas they never were before. But the code change itself is limited to the `enhance` pipeline, rather than the rendering code, so the changes aren't picked up by Chromatic because existing stories don't use this pipeline.

In the discussion under that PR, @oliverlloyd suggested that using the [Percy integration with Cypress](https://docs.percy.io/docs/cypress) might be a good way to introduce visual regression testing for elements which integrate a larger part of the pipeline from request to rendering.

If we haven't tried Percy for DCR before, it might be worthwhile to try a test to see whether it will suit our purposes.

**Comment by bryophyta** [comment]
see also @oliverlloyd 's [comment](https://github.com/guardian/dotcom-rendering/pull/5119#issuecomment-1148385402)

**Comment by bryophyta** [comment]
Sorry @jlieb10  I missed this before somehow.

A quick update from earlier this week: It looks like other teams are interested in implementing Percy/Cypress integration into the DCR codebase. The basic process looks straightforward, but they are currently addressing a couple of webpack issues, and once these are resolved I believe that the next step is to integrate it with CI.

I think that some of our use-cases (esp. testing Fronts) will likely pose distinctive challenges, but it seems like all of these will come after getting the basic CI integration set up. Given that work is being done on the latter independently, there's probably limited value in trying a spike for our use-cases at the moment. I think it makes sense to revisit this either along with the other teams who are looking into Percy, or else after they've finished their initial integration.

So I'll put this in the backlog for now, but if anyone has other thoughts, please feel free to say so!

**Comment by arelra** [comment]
I have experience implementing Percy for the commercial dev team.

There are also cost implications which I can convey to whoever picks this up.

Given how far the project has come without Percy we should also reconsider if this is still a requirement.

**Comment by rhiannareechaye** [comment]
Closing this issue as I don't believe it to be a requirement anymore
