### ISSUE TITLE
Fix Webpack Warnings

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#5174]
There are a few warnings that come up when running webpack (e.g. `npm run watch`). Let's try to fix them.

**Comment by rhiannareechaye** [comment]
We are deprioritising this ticket by 'closing a not planned' - this won't delete the ticket and it will be searchable if the issue crops up again. Unfortunately we have over 130 health tickets to address in the web team and we can't address them all. With so many tickets we are potentially missing things that are high-impact so we're reorganising.
