### ISSUE TITLE
Audio Layout

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#5188]
Build a new layout for audio articles. This _may_ be able to fit within the `Standard` layout or, if they're different enough, we may need to create a new layout component for them: https://github.com/guardian/dotcom-rendering/tree/main/apps-rendering/src/components/Layout

If building a new layout, consider using the new grid module (see the immersive layout for examples):

https://github.com/guardian/dotcom-rendering/blob/cebdd2ac0d885ea511b9d315152f2fdf3c979830/apps-rendering/src/grid/grid.ts#L119-L123

Audio articles should follow the current dotcom designs (frontend, these aren't built yet in DCR). For dark mode we'll want to derive colours from how audio articles currently look on the app. If this isn't sufficient we can talk to Design for help.

Audio articles are represented in the `ArticleFormat` type as `ArticleDesign.Audio`. They look similar to video articles, so much of this work could be derived from the video layout if we decide to build that first: #6460.

**Comment by georgeblahblah** [comment]
Won't do now that we are rendering apps articles in DCR
