### ISSUE TITLE
Consider Making Email Signup Embeds An Aside

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#5193]
At the moment email signup embeds are wrapped in a `figure` with a corresponding `figcaption`:

https://github.com/guardian/dotcom-rendering/blob/139e4749f9985bb068d52afb0fb79bdb37e6bd58/apps-rendering/src/components/EmailSignup/index.tsx#L32-L44

It might make sense for these figures to also be wrapped in an `aside`, to demonstrate that they are "indirectly related" to the main content: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/aside

## Exceptions?

Often email sign-ups are embedded in normal articles. Sometimes there are certain articles that are specifically about signing up to newsletters. What should we do in this case?

https://mobile.guardianapis.com/rendered-items/lifeandstyle/2020/sep/09/design-review-get-the-newsletter-for-the-way-we-live-now

**Comment by alinaboghiu** [comment]
Are we thinking of applying this wrap to the new email sign up component that we'll be creating in AR soon? 

It makes sense semantically but I agree that it probably shouldn't be used in newsletter sign up articles where it's very much part of the main content. So I guess two questions come to mind: 

- what advantages does using this html element bring (does it play nicely(er) with screen readers for example)
- are those advantages worth the extra complexity of having to figure out if an email sign up is in a sign up article

Either way this is a cool suggestion

**Comment by JamieB-gu** [comment]
> Are we thinking of applying this wrap to the new email sign up component that we'll be creating in AR soon?

I think so, and as with the previous ones I think it should probably depend on the type of article? If it's a normal article that happens to have an email sign-up in it then an `aside` may be the best choice. If it's specifically a newsletters sign-up page then I think the sign-up is part of the main content and we'll want to avoid this.

> what advantages does using this html element bring (does it play nicely(er) with screen readers for example)

I believe this is the idea, yes. It allows screen readers to better communicate that this is complementary rather than part of the main content, to avoid confusion. @oliverlloyd @jlieb10 and @bryophyta were involved in the discussion on this. Across AR and DCR the `aside` element is also used for rich links, ads, live event links etc.

> newsletter sign up articles

> are those advantages worth the extra complexity of having to figure out if an email sign up is in a sign up article

At the moment it's not easy to figure this out. However, am I right in thinking we're planning to have a dedicated `Design` and layout (#4840) for these pages in future? If so it should be straightforward to render only within an `aside` if we're not on one of those pages.

**Comment by georgeblahblah** [comment]
@dblatcher does this still need to be fixed? I'm not sure if you are using the new-style Newsletter signups yet in AR

**Comment by dblatcher** [comment]
> @dblatcher does this still need to be fixed? I'm not sure if you are using the new-style Newsletter signups yet in AR

We are using the new style Signup components in AR since https://github.com/guardian/dotcom-rendering/pull/6600.  In theory users can still the 'old style' by putting an embed in composer, but this is unlikely to happen. However, 'old style' embeds will still exist in older articles published before we launched the 'new style' on DCR.
