### ISSUE TITLE
Dynamo liveblog latest links

### ISSUE THREAD

**Issue by oliverlloyd** [guardian/dotcom-rendering#5196]
The latest three liveblog posts are displayed as snippets under the headline on Dynamo containers.
<img width="971" alt="Screenshot 2022-06-14 at 21 11 59" src="https://user-images.githubusercontent.com/1336821/173680075-b6502382-5e93-4a26-b960-a03a6e445379.png">

These links only appear if:

1. The container is `dynamic/package`
2. The switch `Live updates` is on in the fronts tool

This is where the fronts tool switch lives
![image](https://user-images.githubusercontent.com/1336821/188608779-16fd3d46-14d9-4bbc-9edd-2b33ac2f675a.png)

Example request
https://api.nextgen.guardianapps.co.uk/politics/live/2022/sep/05/liz-truss-pm-prime-minister-rishi-sunak-energy-bill-freeze-tory-conservative-leader-uk-politics-live-latest-updates.json?rendered=false

### Consider
- These are currently loaded in client side. Space has to be reserved
- Should we refresh these on a poll or offer the ability to refresh?
- Can we use [css elipsis](https://css-tricks.com/snippets/css/truncate-string-with-ellipsis/) for truncation?
- Do we need a loading state?
- What if there are no results?
- Do we filter by key events or all?
- Can we create an in-memory cache for the latest n posts on each live blog and read in from there so we can server render this content? We can then progressively enhance the container by adding javascript to keep these posts up to date

**Comment by OllysCoding** [comment]
Latest link support is also required on

dynamic/fast 'twoOrMoreBigsFirstBoosted' layout

<img width="1307" alt="image" src="https://user-images.githubusercontent.com/9575458/188897320-2fb5a300-8a51-492b-b0e0-1aa50665894e.png">

**Comment by rhiannareechaye** [comment]
See [Investigate what work is left re Dynamo#6381](https://github.com/guardian/dotcom-rendering/issues/6381)

**Comment by mxdvl** [comment]
> These links only appear if:
> 
>     1. The container is `dynamic/package`
> 
>     2. The switch `Live updates` is on in the fronts tool
> 
>     3. The card is the first in the container
> 
>     4. The first card is in the `standard` group

I’ve based the logic to simply rely on: **The switch `Live updates` is on in the fronts tool**
