### ISSUE TITLE
Document Interactives Contract

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#5213]
Interactives articles are one-off, custom pieces that exist outside of many of the normal platform structures and conventions. They are typically powered by interactive atoms and client-side JavaScript. However, they still often rely on some platform features (elements, styles etc.) existing in the page so that they can hook into and modify them.

With the rollout of AR and DCR it was decided that we would provide a contract between the platforms and interactive atoms to guarantee the presence of certain features on the page that they could use. DCR was in a position to work on interactive articles much earlier than AR, so the Dotcom team put together this contract.

We need to document the details of this contract and figure out how to implement it on AR.

**Comment by georgeblahblah** [comment]
Won't do now that we are rendering apps articles in DCR
