### ISSUE TITLE
Parse The Three Kinds Of Interactive Article

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#5214]
There are three kinds of interactive article:

<dl>
<dt>Interactive Article</dt>
<dd>Format: <code>ArticleDesign.Interactive</code>, <code>ArticleDisplay.Standard</code></dd>
<dd>CAPI representation: <code>articleType: "interactive"</code></dd>

<dt>Full Page Interactive Article</dt>
<dd>Format: <code>ArticleDesign.FullPageInteractive</code>, <code>ArticleDisplay.Standard</code></dd>
<dd>CAPI representation: <code>articleType: "interactive"</code>, <code>displayHint: "immersive"</code></dd>

<dt>Immersive Interactive Article</dt>
<dd>Format: <code>ArticleDesign.Interactive</code>, <code>ArticleDisplay.Immersive</code></dd>
<dd>CAPI representation: <code>articleType: "interactive"</code>, <code>displayHint: "immersiveFullWidth"</code></dd>
</dl>

The CAPI representations are a little bit counter-intuitive for historical reasons, so it's best to rely on `Format` to understand them. At the moment AR is not parsing the CAPI representations into the correct `Format` representations; we need to change this:

https://github.com/guardian/dotcom-rendering/blob/cebdd2ac0d885ea511b9d315152f2fdf3c979830/apps-rendering/src/item.ts#L382-L386

**Comment by georgeblahblah** [comment]
to address when we start parsing format in DCR

**Comment by alinaboghiu** [comment]
Closing in favour of https://github.com/guardian/dotcom-rendering/issues/8998
