### ISSUE TITLE
Odd looking links in artice

### ISSUE THREAD

**Issue by OllysCoding** [guardian/dotcom-rendering#5217]
Links look odd in this piece: https://viewer.gutools.co.uk/preview/world/2022/jun/17/dom-phillips-reporting-on-brazil-and-the-amazon

<img width="394" alt="image" src="https://user-images.githubusercontent.com/9575458/174300905-2adb9541-8cbd-45ae-a72a-b0616b112eb8.png">

**Comment by mxdvl** [comment]
Is this done, @OllysCoding? The issue is still open, but I can’t reproduce or find an associated PR.

**Comment by OllysCoding** [comment]
Closing - This was resolved with CP & Ed tools team, no dotcom action was needed :)
