### ISSUE TITLE
Liveblog card byline - improve design

### ISSUE THREAD

**Issue by HarryFischer** [guardian/dotcom-rendering#5271]

**Comment by benwuersching** [comment]
New designs for the card bylines are here: https://www.figma.com/file/6U9qgwKegOaETUqbSoE04r/Contributor-bylines-(liveblog)?node-id=0%3A1
![byline](https://user-images.githubusercontent.com/23035818/178012004-30e64b46-5844-4d75-b64b-026c2610447d.png)

**Comment by alinaboghiu** [comment]
Closing in favour of of https://github.com/guardian/dotcom-rendering/issues/10336
