### ISSUE TITLE
Rich Link Designs Should Match Dotcom

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#5316]
We'd like to alter the way rich links look to make them match the current dotcom designs across all breakpoints.

## Screenshots

| Apps | Dotcom |
| - | - |
| ![rich-link-apps][] | ![rich-link-dotcom][] |

[rich-link-apps]: https://user-images.githubusercontent.com/53781962/177380918-ab4b1ef3-71c6-4362-bad0-6d35a857bbe1.jpg
[rich-link-dotcom]: https://user-images.githubusercontent.com/53781962/177380913-c477d433-d541-48b1-906e-43668cea6e0c.jpg

**Comment by georgeblahblah** [comment]
Won't do now that we are rendering apps articles in DCR
