### ISSUE TITLE
Incorrect hydratation of pinned block in live blog containing a tweet

### ISSUE THREAD

**Issue by shtukas** [guardian/dotcom-rendering#5332]
I am sharing a screenshot just taken from the live blog which seems to show an incorrectly hydrated tweet on a pinned block.

![Screenshot 2022-07-06 at 17 26 48](https://user-images.githubusercontent.com/6035518/177600298-07bc95ad-70fe-4ad7-a767-fb962ecbb2bc.png)

**Comment by alinaboghiu** [comment]
This has been fixed
