### ISSUE TITLE
Horizontal scrolling bug on AMP

### ISSUE THREAD

**Issue by bryophyta** [guardian/dotcom-rendering#5368]
Sometimes AMP articles scroll horizontally when they shouldn't.

This was reported as happening on an iPhone XR on e.g. [this page](https://amp.theguardian.com/business/2022/jul/12/edf-shares-surge-france-nationalise-8bn-energy).

Screen recording from @HarryFischer:

https://user-images.githubusercontent.com/37048459/178508004-fdffe273-284d-4d76-94c7-e6b9096a254f.MOV

We are having trouble replicating this bug at present. However, it seems worth checking whether it's related to [this recent PR](https://github.com/guardian/dotcom-rendering/pull/5345) which fixes horizontal scrolling introduced by using `1fr` in grid layouts, which allows grid children to change the width of the grid parent.

**Comment by rhiannareechaye** [comment]
We are deprioritising this ticket by 'closing a not planned' - this won't delete the ticket and it will be searchable if the issue crops up again. Unfortunately we have over 130 health tickets to address in the web team and we can't address them all. With so many tickets we are potentially missing things that are high-impact so we're reorganising.
