### ISSUE TITLE
Burger menu elements are tabbable

### ISSUE THREAD

**Issue by bryophyta** [guardian/dotcom-rendering#5374]

**Comment by alinaboghiu** [comment]
Is that a bad thing? Please reopen with more detail if still needed

**Comment by bryophyta** [comment]
iirc this is an issue on Frontend, whereby elements inside the burger menu were tabbable even when the menu was collapsed, so you end up having to tab through a lot of links where you can't see where the focus actually is.

if it's a simple fix then it would probably be worth doing? but I guess balanced against the decreased usage of Frontend over time as well..
