### ISSUE TITLE
Okta Spike

### ISSUE THREAD

**Issue by VDuczekW** [guardian/dotcom-rendering#5391]
document: https://docs.google.com/document/d/1PWICbG4oYIbWF0Pl2U1IwPD_ZKeZlYJCpcK1QNuy2tk/edit#heading=h.d2i15gpuvl44

How would this work be split between the dotcom and conversion teams
The 3 teams (dotcom, conversions and Identity) would all participate in the spike. This would take around 2 weeks with all teams focusing on it.

The conversion team would need to pick up more of the work complexity, this would take around 2 months and also require a developer from Identity to support this.

The dotcom team would need around one month after the spike with support from Identity.

Each team would have a pair (2) of developers to support this. ie 2 from dotcom, 2 from Conversions and 2 developers from Identity supporting. We may not need the pair full time, but to cover annual leave etc.

If the work was all done in parallel, this could be completed in 2-3 months with all teams involved.

If this was all just done by the identity team, it would take around 4-5 months.

Chat: https://mail.google.com/chat/u/0/#chat/space/AAAAhDWocf0

**Comment by mxdvl** [comment]
https://github.com/orgs/guardian/projects/43

**Comment by coldlink** [comment]
https://github.com/guardian/gateway/blob/main/docs/okta/web-apps-integration-guide.md

**Comment by ShraddhaPande** [comment]
- [ ] Identity usage of IDAPI in Dotcom code (How we are pulling the data and what all is being picked up inc discussion )
- [ ] Identity the full feature list that needs to be migrated 
- [ ] pick a feature and see how you can migrate it in the fastest way possible ( will provide an idea on what needs to be supported )
- [ ] Estimate the work needed

**Comment by ShraddhaPande** [comment]
- Full list of how DCR uses IDAPI has been done .
- Creating the same for Frontend 
Details here 
https://docs.google.com/document/d/1tXWq_Cudcs6U7ZvpQhw2VGM1cMFR2DnoWB_kgGq1Pn0/edit 

initial discussion on the approach done 
trying to get initial setup for to see how dotcom can work in the OKTA setup ( need to check the libraries that will be needed )

**Comment by ShraddhaPande** [comment]
- Working on trying new libraries for the OKTA setup on DCR 

- Checking the Frontend usage for Identity API

**Comment by Georges-GNM** [comment]
[Draft PR](https://github.com/guardian/dotcom-rendering/pull/7643) for the DCR implementation, based on the gl/okta-spike branch

**Comment by coldlink** [comment]
Outcomes:

- Create a custom library to use - Identity
- Methods which library need - WebX
- Migrating DCR/frontend to use Okta Library - WebX
- Migrating DCR/Frontend to use Custom Library - WebX/Identity
- Testing/Production plan - WebX/Identity
  - Feature switch
  - AB Test
  - Concerns
  - Rate limits
  - Token expiry/refreshing

**Comment by rhiannareechaye** [comment]
Closing as this is done: https://docs.google.com/document/d/1tXWq_Cudcs6U7ZvpQhw2VGM1cMFR2DnoWB_kgGq1Pn0/edit#heading=h.le722un7883g
