### ISSUE TITLE
Comment Count Icon Colour Should Follow Format

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#5407]
The Comment Count icon should be displayed in different colours depending on `Format`. Chromatic suggests a regression may have occurred on #5242, causing this icon to always appear grey (see the UI tests or storybook). We should fix this.

**Comment by georgeblahblah** [comment]
It looks like comment count icons are always grey for Live/Dead blogs - the same as on Dotcom.

For other article types, comment count icons follow the theme colouring:

| Theme |  Screenshot |
|--------|-------|
|   News     |  ![Image](https://user-images.githubusercontent.com/705427/191490818-32a169f8-3732-4727-9d1e-412a18461748.png)  |
|   Opinion | ![Image](https://user-images.githubusercontent.com/705427/191491398-7a4d605e-c68b-4993-ad7f-5b599714875d.png)     |
| Sport | ![Image](https://user-images.githubusercontent.com/705427/191491287-3d1336ab-4699-4649-b2da-fd51f2a20d12.png) |
