### ISSUE TITLE
Missing images and blank areas in print-ready version of recipes (& other articles?)

### ISSUE THREAD

**Issue by bryophyta** [guardian/dotcom-rendering#5412]
A reader reported seeing large blank areas, and some missing images, when trying to print a recipe from Android, e.g. 

https://www.theguardian.com/lifeandstyle/2016/jan/09/chicken-stock-recipes-batch-cooking-get-ahead-regula-ysewijn

I haven't been able to recreate the issue exactly, but I do see large gaps above images on the print preview on Chrome. (And perhaps more importantly, images and lines of text are often split between pages.) There are also a number of unnecessary elements which sometimes show up in print preview (e.g. the support banner).

**Comment by mxdvl** [comment]
I’ve noticed that on Safari iOS, you need to have had the images in view for them to show on the printed document.

Similarly, islands such as Onwards & Discussion are present on the printed page, but only if hydrated.

Below is an example with only two images loaded and no Onwards content:

[One batch of chicken stock, four delicious dishes | Food | The Guardian.pdf](https://github.com/guardian/dotcom-rendering/files/9130291/One.batch.of.chicken.stock.four.delicious.dishes.Food.The.Guardian.pdf)

**Comment by bryophyta** [comment]
That's very helpful to know, thanks!

It seems quite likely that the same thing explains the original android issue (see pdf: [One batch of chicken stock, four delicious dishes _ Food _ The Guardian.pdf](https://github.com/guardian/dotcom-rendering/files/9158972/One.batch.of.chicken.stock.four.delicious.dishes._.Food._.The.Guardian.pdf))

Interestingly, there are other inconsistencies between the two which aren't obviously explained in the same way, though (e.g. the rendering of the header). And overall, it feels to me like we're not currently offering a great experience for people who want to print from the site.

Given that there seem to be a few different things going on here, I wonder if it's worth having a brief discussion next time we triage the rota board to see what kind of priority this has, and whether it's worth having someone dig into the print formatting in a bit of depth at some point to try and create an overall better experience, rather than trying to patch this particular issue as a one-off? (cc. @VDuczekW @jamesgorrie)

**Comment by jlieb10** [comment]
Let's put this in the backlog. Could involve quite a lot of thinking and isn't super pressing.
