### ISSUE TITLE
Parse/validate request data for AJAX endpoints

### ISSUE THREAD

**Issue by bryophyta** [guardian/dotcom-rendering#5442]
We check the structure of data coming into endpoints like `Front/` using AJV.

But we don't currently seem to do the same for endpoints like `Blocks/`, `Cards/` and `KeyEvents/`. It seems worthwhile to do so, although nb. there are also some ongoing discussions about whether the current validation method is best suited.

```[tasklist]
### Tasks
- [x] Blocks https://github.com/guardian/dotcom-rendering/pull/7720
- [ ] Cards
- [ ] KeyEvents
```

**Comment by rhiannareechaye** [comment]
As per our triaging, this is a high impact issue so ideally we should look at it

**Comment by bryophyta** [comment]
> Pulling a parsing lib into the client would be quite heavyweight, and we don't have other precedence to do this.

I don't remember exactly but I think this might have been written when key events were rendered server-side? (And also at a time when there was a server-side `Cards` endpoint, though not sure that was ever used in production.) So iirc the intention was just for it to apply to validating JSON before SSR'ing. Agreed that it would be challenging (though also potentially interesting) to do it for client-side, too 👍
