### ISSUE TITLE
Image covers text on cartoon page

### ISSUE THREAD

**Issue by bryophyta** [guardian/dotcom-rendering#5468]
The image in the body of this article is too large, covering over part of the text content (e.g. byline). This issue appears only to start above the `leftCol` breakpoint. I'm not aware of any other examples at the moment.

![Image](https://user-images.githubusercontent.com/37048459/180257835-d8238283-2561-4b2f-938a-1ee033bf7f69.png)

https://www.theguardian.com/global/2015/may/26/cartoon-a-non-guide-to-avoid-awkwardness-when-greeting-human-beings

**Comment by bryophyta** [comment]
it seems quite plausible that this issue is connected to #5108 -- @oliverlloyd do you think it's simply the same issue as the earlier one? If so, I'll close this issue in favour of the earlier one.

**Comment by oliverlloyd** [comment]
> do you think it's simply the same issue as the earlier one?

Yep, same issue. Making body images immersive is not _really_ supported as there are a number of conflicts and no system to deal with these

**Comment by bryophyta** [comment]
Okay thanks! I'll close this issue for now then, and refer future readers to #5108
