### ISSUE TITLE
Pull in white sponsor logo on liveblogs

### ISSUE THREAD

**Issue by HarryFischer** [guardian/dotcom-rendering#5486]
On sponsored liveblogs the sponsor logo sit's on a dark background at mobile breakpoints (until: desktop). Tag manager allows 2 logos to be uploaded. Can we use the white (high contrast) one instead?
Can we also change "Supported by" and "About this content" to be white on smaller breakpoints too

![Image](https://user-images.githubusercontent.com/20658471/180774822-a981eb8d-0a03-4cbb-bf9d-62c1c55e40c9.png) 
![Image](https://user-images.githubusercontent.com/20658471/180775854-883377d2-ca72-4016-bd1a-89902d5e3d60.png)

Tag manager:
![Image](https://user-images.githubusercontent.com/20658471/180775663-1215fae4-cb39-4559-80f8-93ee79c320fe.png)

**Comment by bryophyta** [comment]
Original PR was reverted, but this issue has now been closed by #5546
