### ISSUE TITLE
EPIC - Adverts

### ISSUE THREAD

**Issue by VDuczekW** [guardian/dotcom-rendering#5489]
Adverts and reader revenue requirements
Use this ticket to collate

**Comment by mxdvl** [comment]
- Page Skins:
  - [`frontend/…/creatives/page-skins.ts` ](https://github.com/guardian/frontend/blob/39edd883240844ab27cb8347819f078e969df5ca/static/src/javascripts/projects/commercial/modules/creatives/page-skin.ts)
  - `window.guardian.config.page.hasPageSkin` will be `true` if there is one. Known server-side.
- Ad Slots
 - TBC

**Comment by oliverlloyd** [comment]
Closed in favour of individual tickets
