### ISSUE TITLE
Upgrade to React 18

### ISSUE THREAD

**Issue by georgeblahblah** [guardian/dotcom-rendering#5507]
- will require updating all dependant libraries too
- will this affect DCR (via `common-rendering` and other libraries (`atoms-rendering`, `source-react-components`)?

**Comment by arelra** [comment]
fyi this can cause a lot of WTFs when upgrading to React 18:
https://reactjs.org/blog/2022/03/29/react-v18.html#new-strict-mode-behaviors

**Comment by VDuczekW** [comment]
this will be taken up by CSTI - we will not need a separate issue
