### ISSUE TITLE
Culture thrasher (is it a thrasher?) incorrectly positioned

### ISSUE THREAD

**Issue by oliverlloyd** [guardian/dotcom-rendering#5515]
<img width="447" alt="Screenshot 2022-07-27 at 10 11 29" src="https://user-images.githubusercontent.com/1336821/181209719-54b46859-3be9-4624-8211-9e17ef602ce9.png">

**Comment by AshCorr** [comment]
This kind of Thrasher should be setup using `PLATFORM_TREATS` now https://github.com/guardian/dotcom-rendering/pull/5716
