### ISSUE TITLE
A/B testing the build output using existing server side test framework

### ISSUE THREAD

**Issue by arelra** [guardian/dotcom-rendering#5519]
Suggestion:

Could we use the existing server side A/B test framework to A/B test build output?

Essentially:

- webpack can output control and variant builds (A/B only not multivariate)
- server side in `articleToHtml.tsx` we load either the control or variant entry points

This would allow us to get D&I analysis of vitals and commercial metrics as per normal tests.

**Comment by ashishpuliyel** [comment]
To add to this: Ravi had the idea is that we should use tags in sentry to help capture which variant a client-side bug is in.

**Comment by JamieB-gu** [comment]
@arelra @ashishpuliyel we think this is solved by #5598
