### ISSUE TITLE
Immersive Design Review

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#5540]
The new immersive layout comes with a number of new design features:

1. It derives a lot from the dotcom designs, and so may look different from the previous old template designs.
2. It uses the Guardian Grid rules laid out in Source (via the new `grid` module), and updates any elements taken from the existing dotcom designs to align to this grid when they diverge.
3. It introduces an updated layout for the related content and footer at the bottom of the article, which differs from the way these sections look on other AR articles.

Before we release immersive articles to (Beta) users it would be a good idea for Design to review them to make sure they're acceptable, and suggest any necessary changes.

**Comment by JamieB-gu** [comment]
List of things to tweak:

1. On the headline, make sure that the top padding matches the left padding (look at the current app designs for an example).
2. On the standfirst, make sure that the top padding matches the left padding.
3. Make sure that the standfirst text matches the width of the headline text.
4. Drop the related content heading into the left column on wider breakdpoints.

**Comment by JamieB-gu** [comment]
@ajbreuer you were right about the headline being cropped! With the app chrome included the new immersives looked like the screenshot on the left below. I've reduced the main media height and now we get much more of the headline text, as seen on the right. I can reduce it further if needed?

These were taken on an iPhone 13 Pro (same dimensions as a 12, 12 Pro and 13).

| Before | After |
| - | - |
| ![immersive-before] | ![immersive-after] |

[immersive-after]: https://user-images.githubusercontent.com/53781962/184191725-fb154c9b-fd1a-4308-bd99-70aaf06efbe0.jpg
[immersive-before]: https://user-images.githubusercontent.com/53781962/184191734-392084fc-9143-4589-bf4f-2ce6b67414a0.jpg

**Comment by ajbreuer** [comment]
> @ajbreuer you were right about the headline being cropped! With the app chrome included the new immersives looked like the screenshot on the left below. I've reduced the main media height and now we get much more of the headline text, as seen on the right. I can reduce it further if needed?
> 
> These were taken on an iPhone 13 Pro (same dimensions as a 12, 12 Pro and 13).
> 
> Before	After
> ![immersive-before](https://user-images.githubusercontent.com/53781962/184191734-392084fc-9143-4589-bf4f-2ce6b67414a0.jpg)	![immersive-after](https://user-images.githubusercontent.com/53781962/184191725-fb154c9b-fd1a-4308-bd99-70aaf06efbe0.jpg)

Thanks @JamieB-gu I think we could reduce it a bit more, maybe one more line of headline

**Comment by JamieB-gu** [comment]
@ajbreuer I've dropped it down a bit further. Here are some examples with different length headlines.

| Four Lines | Five Lines | Six Lines |
| - | - | - |
| ![immersive-headline-four-lines] | ![immersive-headline-five-lines] | ![immersive-headline-six-lines] |

[immersive-headline-four-lines]: https://user-images.githubusercontent.com/53781962/184346900-f48e23ca-21cd-422c-898a-be22b5b06eed.jpg
[immersive-headline-five-lines]: https://user-images.githubusercontent.com/53781962/184346905-d536a25a-a94c-4806-b7bc-ff6eec02391e.jpg
[immersive-headline-six-lines]: https://user-images.githubusercontent.com/53781962/184346907-9a97fe27-b656-48e9-9288-09e8e4a32597.jpg

**Comment by ajbreuer** [comment]
> @ajbreuer I've dropped it down a bit further. Here are some examples with different length headlines.
> 
> Four Lines	Five Lines	Six Lines
> ![immersive-headline-four-lines](https://user-images.githubusercontent.com/53781962/184346900-f48e23ca-21cd-422c-898a-be22b5b06eed.jpg)	![immersive-headline-five-lines](https://user-images.githubusercontent.com/53781962/184346905-d536a25a-a94c-4806-b7bc-ff6eec02391e.jpg)	![immersive-headline-six-lines](https://user-images.githubusercontent.com/53781962/184346907-9a97fe27-b656-48e9-9288-09e8e4a32597.jpg)

Thats great! thanks @JamieB-gu
