### ISSUE TITLE
Cards links don't have labels

### ISSUE THREAD

**Issue by bryophyta** [guardian/dotcom-rendering#5547]
Our [lighthouse reports for Fronts](https://storage.googleapis.com/lighthouse-infrastructure.appspot.com/reports/1659080533828-15999.report.html) are showing that our fronts cards don't have discernible names: 

![screenshot of lighthouse results from the page linked above](https://user-images.githubusercontent.com/37048459/181800180-93609b4e-44f6-47ce-967d-73719bc7f1d5.png)

In the DOM, the `<a>` element is sized using a pseudo-element, and doesn't actually wrap the card contents. It should either be made to wrap the card contents so that the card's text shows up as the link's name, or else we should add a label using visually hidden text, aria attributes, or similar. Unless there's a strong reason against this, I think having the `<a>` wrap the card contents would be simplest and most semantic.

Can we refactor `CardLink.tsx` to use a `children` prop?

https://github.com/guardian/dotcom-rendering/blob/f8dfaf81508d1fee74e9d9ff26b23701157aa598/dotcom-rendering/src/web/components/Card/Card.tsx#L295-L300

**Comment by bryophyta** [comment]
I came across this in the context of accessibility issues, but I can only add one milestone from `Accessibility` or `Fronts Launch`. My feeling is that it's an important requirement for the fronts launch so I've gone with that, but not sure if I can unilaterally make that decision 😅. I thought @VDuczekW and @oliverlloyd might have some thoughts

**Comment by oliverlloyd** [comment]
Great spot! We should absolutely make these links accessible.

> we should add a label using visually hidden text, aria attributes, or similar. Unless there's a strong reason against this

There is, we use nested links so the pseudo element is the best approach to solve this use case. There's more info on what this pattern is about and why we use it in [the PR to add it to DCR](https://github.com/guardian/dotcom-rendering/pull/4798).

> or else we should add a label using visually hidden text, aria attributes, or similar

Yep 👍

**Comment by oliverlloyd** [comment]
I believe this is fixed by [this PR](https://github.com/guardian/dotcom-rendering/pull/5737). Please reopen me if this is not true.
