### ISSUE TITLE
Frontend decides what onwards content to show

### ISSUE THREAD

**Issue by oliverlloyd** [guardian/dotcom-rendering#5566]
The logic for which onwards slices to show is currently contained in [OnwardsUpper](https://github.com/guardian/dotcom-rendering/blob/main/dotcom-rendering/src/web/components/OnwardsUpper.importable.tsx). We want to move this to Frontend, simplifying the task of DCR to that of a renderer.

That logic looks complex but it is likely that it can be greatly simplified. The essential flow is

** For the top row (the first item in the array): **
Do I have a story package, if yes, render `more-on-this-story`
Do I have a series tag, if yes, render `series`
Do I have a popular tag, if yes, render `popular-in-tag`
Else, render `related-stories`

** For the bottom row (the second item in the array): **
Render `curated-content` - always

### The general flow
When as article request is made the data is fetched from CAPI and Frontend runs some transformations. At a certain point in this process we need to insert a new property `onwards` with the type:

```ts
type CAPIOnwardsType = {
	heading: string;
	trails: CAPITrailType[];
	description?: string;
	url?: string;
	onwardsType: OnwardsType;
	format: CAPIFormat;
	isCuratedContent?: boolean;
};

onwards: CAPIOnwardsType[];
```

DCR will use [this PR](https://github.com/guardian/dotcom-rendering/pull/5551) to read and render that property.

## Why?
This is part of a larger effort to move the rendering of `Cards` to the server. As part of this work, the various different onwards types are going to be rendered in different places

### Now
`more-on-this-story` - This is already server side rendered with the data provided by CAPI
`popular-in-tag` - This is currently [fetched as json](https://github.com/guardian/dotcom-rendering/issues/5568#issuecomment-1215160054) by the client and rendered on the client
`series` - This is currently [fetched as json](https://github.com/guardian/dotcom-rendering/issues/5569#issuecomment-1215215257) by the client and rendered on the client
`related-stories` - This is currently fetched as json by the client and rendered on the client
`curated-content` - This is currently [fetched as json](https://github.com/guardian/dotcom-rendering/issues/5567#issuecomment-1215260498) by the client and rendered on the client

### Target
`more-on-this-story` - No change
`popular-in-tag` - This will be read from a cache on Frontend, inserted into the DCR model and then server side rendered by DCR
`series` - This will be read from a cache on Frontend, inserted into the DCR model and then server side rendered by DCR
`related-stories` - This will still be fetched from the client but as html, not json
`curated-content` - This will be read from a cache on Frontend, inserted into the DCR model and then server side rendered by DCR

**Comment by ioannakok** [comment]
Closing this. See epic for more info: https://github.com/guardian/dotcom-rendering/issues/5349
