### ISSUE TITLE
The in-memory cache is populated with `popular-in-tag`

### ISSUE THREAD

**Issue by oliverlloyd** [guardian/dotcom-rendering#5568]
Part of: #5349 
## Background
This ticket and:
* https://github.com/guardian/dotcom-rendering/issues/5843
are to create an agent that fetches the content to populate this carousel at the onwards section of articles / liveblogs / interactives:

**Popular in tag** (aka "Related content" - can easily get confused with "related stories" but it's _not_ the same)
![image](https://user-images.githubusercontent.com/19683595/186446772-7a86e0d1-79d4-4268-8e42-5b4e58375356.png)

## Todo
An agent runs that populates the in-memory cache with the data used for onwards.

**Comment by bryophyta** [comment]
Current setup:
- DCR queries the `popular-in-tag` endpoint which is served via Frontend's Onwards app.
- The Frontend endpoint makes a query to the CAPI `search` endpoint to get items sharing the same tag(s?)
- It then [uses data from the `MostReadAgent`](https://github.com/guardian/frontend/blob/0657f594e2fd51125d28df9048c48d6eede26bb6/onward/app/services/repositories.scala#L60) to sort the results ([if the article is sport or football](https://github.com/guardian/frontend/blob/995d8b9037575306d9038d4c1413fff3f89259c3/onward/app/feed/MostReadAgent.scala#L16))

**Comment by ioannakok** [comment]
Closing. See epic: https://github.com/guardian/dotcom-rendering/issues/5349
