### ISSUE TITLE
The in-memory cache is populated with `series`

### ISSUE THREAD

**Issue by oliverlloyd** [guardian/dotcom-rendering#5569]
Part of: #5349 
## Background

This ticket and:
* https://github.com/guardian/dotcom-rendering/issues/5844

are to create an agent that fetches the content to populate this carousel at the onwards section of articles / liveblogs / interactives:

![image](https://user-images.githubusercontent.com/19683595/186443754-d71ca0db-d63f-4a29-a19e-5e58c120901c.png)

## Todo
An agent runs that populates the in-memory cache with the data used for onwards.

**Comment by bryophyta** [comment]
Current setup:
- DCR query comes into the `series` endpoint in the `onward` app. (Pretty sure this is the one, although it's [marked as 'experimental'](https://github.com/guardian/frontend/blob/695e58798ecbf1458e572c39b30f8f3584bbedb7/onward/conf/routes#L64).)
- Frontend queries CAPI's item endpoint for a series, which comes with a list of `trail`s as its results. (e.g. `https://content.guardianapis.com/cities/series/the-illustrated-city`)
  - There's some logic around how the current article gets determined which seems like it could be refactored in the agent.
- The response is transformed into a `Series`, which we might be able to refactor as an `OnwardsCollection`?

**Comment by ioannakok** [comment]
Closing. See epic: https://github.com/guardian/dotcom-rendering/issues/5349
