### ISSUE TITLE
Live Blog cards metadata colour -> neutral.100

### ISSUE THREAD

**Issue by bryophyta** [guardian/dotcom-rendering#5603]
**Live Blog cards** The kicker and all metadata needs to change to neutral.100, other than Labs.

- [x] DCR
- [ ] Frontend

_Part of an issue raised by @Bryony-Szekeres in https://github.com/guardian/dotcom-rendering/issues/4953#issuecomment-1139546312_

**Comment by bryophyta** [comment]
In our storybook we currently have stories for liveblogs on some palettes which don't have dark backgrounds, and also aren't Labs. e.g. `LongRunningAltPalette`: https://www.chromatic.com/component?appId=5dfcbf3012392c0020e7140b&csfId=layouts-palettes--long-running-alt-palette&buildNumber=14363&k=62eba7ec7afd5a3ca5789b26-1200-interactive-true&h=14&b=-2

Should we be converting the metadata colours for the dark palettes to `neutral.100` (and leaving the light background ones as they are)? Or is it the case that some of these palettes will never actually have liveblogs associated with them?

(cc. @Bryony-Szekeres, @oliverlloyd, @HarryFischer)

**Comment by oliverlloyd** [comment]
> In our storybook we currently have stories for liveblogs on some palettes which don't have dark backgrounds, and also aren't Labs. e.g. `LongRunningAltPalette`: https://www.chromatic.com/component?appId=5dfcbf3012392c0020e7140b&csfId=layouts-palettes--long-running-alt-palette&buildNumber=14363&k=62eba7ec7afd5a3ca5789b26-1200-interactive-true&h=14&b=-2
> 
> Should we be converting the metadata colours for the dark palettes to `neutral.100` (and leaving the light background ones as they are)? Or is it the case that some of these palettes will never actually have liveblogs associated with them?
> 
> (cc. @Bryony-Szekeres, @oliverlloyd, @HarryFischer)
> 
> <img alt="image" width="777" src="https://user-images.githubusercontent.com/37048459/182867964-cbb2bbc9-5633-417c-841e-d47f1639fccf.png">

When you put any card inside a container that has a 'Palette' (e.g.: `containerPalette`) applied to it, then that card has its normal colours overridden by the special palette, regardless of the type of card.

**Comment by bryophyta** [comment]
Thanks! So for the palettes that do have dark backgrounds, presumably we do want to update the colour of the metadata to `neutral.100`? And I'll check this specific case of LongRunningAlt to see whether the current red styling has sufficient contrast or whether it should be changed to black, like for Labs.

**Comment by bryophyta** [comment]
Having looked into the `containerPalette` overrides in a bit more detail, I think that a decision should probably be made on these separately, in consultation with design colleagues, because some of them differ quite a lot from other fronts cards.

**Comment by alinaboghiu** [comment]
I think this has been addressed in the meantime. Please reopen if you don't thin that's the case.
