### ISSUE TITLE
Card meta colours: Media

### ISSUE THREAD

**Issue by bryophyta** [guardian/dotcom-rendering#5604]
**Media cards** Make the metadata neutral.86 across all variants

The old and new colours are laid out side-by-side in this Figma file:
https://www.figma.com/file/5CfbWOeZPRi15lXBD5u1rW/?node-id=160%3A4026

- [ ] DCR
- [ ] Frontend

_Part of [this issue](https://github.com/guardian/dotcom-rendering/issues/4953#issuecomment-1139546312)_

**Comment by bryophyta** [comment]
@oliverlloyd am I right in thinking that we don't support media cards on DCR fronts yet?

<img width="1067" alt="image" src="https://user-images.githubusercontent.com/37048459/182873353-8ca4e102-da33-49cc-a223-998e57bae3c4.png">

**Comment by oliverlloyd** [comment]
> @oliverlloyd am I right in thinking that we don't support media cards on DCR fronts yet?
> 

DCR supports media cards. Here's one on today's front

<img width="575" alt="Screenshot 2022-08-04 at 15 41 22" src="https://user-images.githubusercontent.com/1336821/182875655-f59cef08-be78-4047-bae8-eb923d43f832.png">
