### ISSUE TITLE
Ad-free content when Show More button gets clicked

### ISSUE THREAD

**Issue by ioannakok** [guardian/dotcom-rendering#5652]
After the `Show more` button gets clicked, `frontend` checks whether the content should be ad-free in order to decide how to render the extra cards: 

`frontend` code:
https://github.com/guardian/frontend/blob/main/facia/app/controllers/FaciaController.scala#L358
https://github.com/guardian/frontend/blob/main/common/app/layout/Front.scala#L123
https://github.com/guardian/frontend/blob/main/common/app/layout/Front.scala#L64

A lot of this logic was added in this PR: https://github.com/guardian/frontend/pull/17502

**Comment by alinaboghiu** [comment]
Todo: include screenshot of ads in the show more section

**Comment by rhiannareechaye** [comment]
This needs some investigation - this would be a medium size ticket

**Comment by alinaboghiu** [comment]
@arelra when you're back please can you confirm if this has already been done as part of your "adFree" clean up?

**Comment by arelra** [comment]
@ioannakok and I investigated this and can confirm we do not show ads when clicking 'show more' so this issue can be closed.
