### ISSUE TITLE
Slideshow on fronts

### ISSUE THREAD

**Issue by jamesgorrie** [guardian/dotcom-rendering#5655]
We need to implement the slideshow on fronts in DCR

https://user-images.githubusercontent.com/31692/183913793-bb848c51-f6c6-4038-9e33-11b3e5790928.mp4

**Comment by oliverlloyd** [comment]
Duplicate of https://github.com/guardian/dotcom-rendering/issues/4612

**Comment by jamesgorrie** [comment]
@oliverlloyd is this a duplicate to a carousel? I didn't realise they were the same thing.
