### ISSUE TITLE
Implement new designs for Explainer & Analysis

### ISSUE THREAD

**Issue by HarryFischer** [guardian/dotcom-rendering#5661]

**Comment by HarryFischer** [comment]
Remove red underline
Bold Headline
Medium standfirst
Bigger byline
news.800 page background

**Comment by alinaboghiu** [comment]
Remove red underline 
- DCR, AR - Article 
- DCR, Frontent Card

(Native cards don't have the red underlines)

**Comment by JamieB-gu** [comment]
> Remove red underline

AR doesn't have these underlines any more, they were removed in #4803
