### ISSUE TITLE
Replace `news[400]` with `news[300]`

### ISSUE THREAD

**Issue by HarryFischer** [guardian/dotcom-rendering#5663]

**Comment by oliverlloyd** [comment]
Should we merge this change with the work currently happening in [this ticket](https://github.com/guardian/dotcom-rendering/issues/4953#issuecomment-1139546312)?

@bryophyta and @DanielCliftonGuardian have been implementing accessibility colour changes on the site this week and it looks like this might already be included in that work or, if not, get added to it.

**Comment by bryophyta** [comment]
I don't think that it falls under what's currently covered in that issue, but can be added -- are you able to say anything more about what it involves @HarryFischer ?

**Comment by oliverlloyd** [comment]
@HarryFischer there are approximately 55 places where this colour is used on the site, do we want to do a straight replacement or does this need to be done on a case by case basis?

I wonder if the easiest thing here would be to just go through them one by one? I have a feeling it won't take long as a lot of them as very similar and they all mostly live in one file (decidePalette)
