### ISSUE TITLE
Deeply read in-memory cache

### ISSUE THREAD

**Issue by jamesgorrie** [guardian/dotcom-rendering#5664]
Part of: https://github.com/guardian/dotcom-rendering/issues/5554

This should be fed from [Ophan's deeplyread API](https://dashboard.ophan.co.uk/api/deeplyread).

Here is a past implementation https://github.com/guardian/frontend/pull/23368#discussion_r544949872.

This is editionalised.

**Comment by mxdvl** [comment]
Is this closed with https://github.com/guardian/frontend/pull/25358 ?

**Comment by jamesgorrie** [comment]
Closed in favour of https://github.com/guardian/dotcom-rendering/issues/6036

**Comment by jamesgorrie** [comment]
Closed in favour of https://github.com/guardian/dotcom-rendering/issues/6036
