### ISSUE TITLE
Deeply read UI

### ISSUE THREAD

**Issue by jamesgorrie** [guardian/dotcom-rendering#5665]
First iteration of the test will run on articles only. 99% (or TBD) of the audience will be in **control** and see two-tab onwards with exposed tab being "Most Popular" and next tab to be popular in that section. The test group will see the test **variant** which is a tabless display, showing two columns of 5 articles: on the left is Most Popular and the right is "Deeply Read" - there will be an expand button to show 10 articles in each column. On mobile, this UI collapses into a single column with two sections (Most Popular and Deeply Read) which can be toggled independently.

We anticipate more iterations on this UI, including a version without "most commented" and "most shared" (conversation w Chris M pending)

Here are the designs:

![pasted image 0 (1)](https://user-images.githubusercontent.com/3300789/183930399-3ed17583-ee42-4f01-8896-e8d1d4a5b27d.png)

![pasted image 0](https://user-images.githubusercontent.com/3300789/183930405-1f5b08fe-26d4-4d80-8c47-dc73f059e522.png)

@HarryFischer if you have these on Figma, would you kindly drop a link?

**Comment by VDuczekW** [comment]
Web X will not work on this - the ticket link has been passed on to EDX
