### ISSUE TITLE
Cards: Separate palette colour for media icons

### ISSUE THREAD

**Issue by bryophyta** [guardian/dotcom-rendering#5672]
The [current designs](https://www.figma.com/file/5CfbWOeZPRi15lXBD5u1rW/Card-layout-system?node-id=160%3A4026) call for the media icon and play length (if applicable) on media cards to be a different colour than the rest of the footer text. Currently the colours for all of these are set via the same property `palette.text.footer` in `decidePalette`.

These need to be de-coupled, and the media icons should be set to the relevant palette colour for the pillar.

![Image](https://user-images.githubusercontent.com/37048459/184090828-04b56a36-e470-4dd0-9b59-82cad3031be1.png)

Questions:
- Are there any other footer elements which need to observe the same kind of pattern?
- If so, is it worth introducing a new value into the `decidePalette` palette, and if so what would be a useful name for this value?

**Comment by VDuczekW** [comment]
@bryophyta could you clarify why we need to decouple - is it an accessibility issue?

**Comment by bryophyta** [comment]
I'm not sure sorry @VDuczekW! If I remember rightly I was just reflecting what the figma designs said, but they don't seem to be at that link anymore. I would imagine that the original reason was accessibility, but @HarryFischer might know more?

**Comment by HarryFischer** [comment]
I think it just looks too pink so meta at bottom can go grey

**Comment by bryophyta** [comment]
@OllysCoding am I right in thinking that your [recent PR](https://github.com/guardian/dotcom-rendering/pull/6956) should address this, because it switches the media icon to use the kicker colour?
