### ISSUE TITLE
Supporting EU edition

### ISSUE THREAD

**Issue by jamesgorrie** [guardian/dotcom-rendering#5673]
create 0% test
and UI

**Comment by VDuczekW** [comment]
added you @OllysCoding to the ticket as you have kindly stepped in to help pair - and added to progress

**Comment by VDuczekW** [comment]
Rowanne's update https://docs.google.com/document/d/1a2MW3NRARHFKAR6as_bM4BIfOitwACKamLWHE11IEuI/edit

**Comment by VDuczekW** [comment]
The Europe edition is now (finally) live on PROD behind a 0% test

**Comment by VDuczekW** [comment]
awaiting confirmation on launch date - assuming end of January 2023
