### ISSUE TITLE
Darken grey bullets

### ISSUE THREAD

**Issue by oliverlloyd** [guardian/dotcom-rendering#5710]
Darken the light grey bullets for accessibility

@HarryFischer for the details / screenshots

**Comment by OllysCoding** [comment]
@HarryFischer Can you provide info?

**Comment by bryophyta** [comment]
hey @HarryFischer -- is this still a live issue? do you have any more context for it?

**Comment by HarryFischer** [comment]
@bryophyta Please can they be:
neutral.46 / #707070

**Comment by bryophyta** [comment]
The exact nature and scope of this issue is not clear, so in conversation with @HarryFischer we've decided to close this issue in favour of raising new issues that might arise from future design reviews.
