### ISSUE TITLE
Refactor Onward Content Cards

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#5712]
Let's use the new models from #5711 to rebuild the card components, for both onward content and rich links.

#5316 says that rich links should look like dotcom. However, our onward content card designs have moved on, and been brought into line with the UI modernisation work on apps. It's a question for Design whether we make rich link cards match dotcom but differ from onward content cards, or whether they match our onward content cards but differ from dotcom rich links.

**Comment by georgeblahblah** [comment]
Won't do now that we are rendering apps articles in DCR
