### ISSUE TITLE
Have OnwardCollectionResponse match CAPIOnwardsType

### ISSUE THREAD

**Issue by jamesgorrie** [guardian/dotcom-rendering#5734]
Currently the [`OnwardCollectionResponse`](https://github.com/guardian/frontend/blob/main/common/app/model/dotcomrendering/MostPopular.scala#L160-L166) partially matches the [`CAPIOnwardsType `](https://github.com/guardian/dotcom-rendering/blob/main/dotcom-rendering/index.d.ts#L742-L760).

We should extend the model in `frontend` to reflect what we're expecting in DCR.

**Comment by bryophyta** [comment]
I'm finding the existing naming a bit confusing -- it seems like sometimes we're making a distinction between `onwards` and `most popular/commented/etc.` and sometimes not. e.g. The `OnwardCollectionResponse` type is used for `most popular`.

So just to clarify: from the perspective of the models, is the intention that we should aim to have a single `OnwardsCollectionResponse` type that fits _all_ of these cases (with sub-types as appropriate)? Or do Onwards and Most Popular need separate base types?

**Comment by jamesgorrie** [comment]
Closing in favour of https://github.com/guardian/dotcom-rendering/issues/5794 where those concerns have been addressed @bryophyta
