### ISSUE TITLE
Add A Banner To Labs Pieces

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#5742]
Labs pieces on the old templates and dotcom have a banner at the top explaining what they are. We should add this to the AR versions.

There are a couple of differences between the dotcom and old templates designs (for example, "Paid story" vs "Paid content"). We'll need to decide how the AR designs should look - they should probably match the dotcom designs. Commercial may be able to help with this.

| Old Templates | Dotcom |
| - | - |
| ![labs-apps] | ![labs-dotcom] |

[labs-apps]: https://user-images.githubusercontent.com/53781962/185142136-f24fbf6f-81b9-4f06-8151-f927b2e88a29.jpg
[labs-dotcom]: https://user-images.githubusercontent.com/53781962/185142140-4b1b44f8-a1b7-4bcc-ac97-55d351c528fc.jpg

**Comment by georgeblahblah** [comment]
Won't do now that we are rendering apps articles in DCR
