### ISSUE TITLE
About This Content

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#5744]
The dotcom versions of labs pieces have an "About this content" link next to the branding logo. Should we add this too? Commercial may be able to help with this.

| AR | Dotcom |
| - | - |
| ![branding-logo-ar] | ![branding-logo-dotcom] |

[branding-logo-ar]: https://user-images.githubusercontent.com/53781962/185146433-096c576e-edf0-4c2b-bdb1-beafb476049e.jpg
[branding-logo-dotcom]: https://user-images.githubusercontent.com/53781962/185146444-4f83e967-8390-413c-ae38-515f93e7b067.jpg

**Comment by georgeblahblah** [comment]
Won't do now that we are rendering apps articles in DCR
