### ISSUE TITLE
Render correct `<title>` for network fronts

### ISSUE THREAD

**Issue by bryophyta** [guardian/dotcom-rendering#5748]
DCR currently passes the top-level `.webTitle` property as the `<title>` for Fronts. This works for many cases, but for some (e.g. the `/uk` homepage) `.webTitle` is 'Network Front', which is not the right value to use.

Identified discrepancies

|url|Frontend title|DCR title|
|-|-|-|
|https://www.theguardian.com/uk|`News, sport and opinion from the Guardian's UK edition \ The Guardian`|`Network Front`|
|https://www.theguardian.com/us?INTCMP=CE_US|`News, sport and opinion from the Guardian's US edition \ The Guardian`|`Network Front`|
|others?|||

I haven't been able to find prior mention of this issue.

@oliverlloyd I feel like you might have some insight here -- is this something that should be resolved in the fronts tool, or do  we need to e.g. hard-code a mapping from url to title in DCR for these  special cases?

**Comment by paperboyo** [comment]
Just a comment that they should be proper apostrophes: `‘`, not ticks. Why a back slash and not forward slash (I would vote for `/`)?

**Comment by paperboyo** [comment]
Oh, it’s actually an `|` which seems fine too?

![image](https://user-images.githubusercontent.com/6032869/186880806-979f2c78-faf0-4e31-8488-7cd88c160fec.png)

**Comment by bryophyta** [comment]
good call!

for the divider I think it was just because `|` is used for creating a table column in github markdown and seemst o take precedence over the  `code block backticks` so I had to switch it out. 

but I'm not sure I'd spotted the apostrophes. iirc they can be troublesome when being parsed from one format to another so we should make sure to pay attention to that when implementing the new titles, cheers! 👍
