### ISSUE TITLE
Supporting content visual bugs

### ISSUE THREAD

**Issue by ioannakok** [guardian/dotcom-rendering#5801]
To maintain parity with frontend we need to:

1.a. Have horizontal alignment when there is supporting content in primary card (1440px - 980px)
![Image](https://user-images.githubusercontent.com/19683595/186120665-08214861-a5f7-4dc9-a3ac-c2f1a2c9e421.png)

1.b. Below 980px
![Image](https://user-images.githubusercontent.com/19683595/186121073-d41cea4b-e750-4d76-984b-4f7dea64eab4.png)

1.c. Below 740px
![Image](https://user-images.githubusercontent.com/19683595/186121485-133fc58e-3aae-426f-88bb-5f46e15d04bf.png)

2. Supporting content should be full with in mobile instead of:
![Image](https://user-images.githubusercontent.com/19683595/186122322-7826dad6-6a58-498b-acf7-a0554e4e4f00.png)

**Comment by VDuczekW** [comment]
being fixed by sublinks epic ticket
