### ISSUE TITLE
Should we migrate `Display.NumberedList` to `Design`?

### ISSUE THREAD

**Issue by oliverlloyd** [guardian/dotcom-rendering#5884]
Following on from [the discussion](https://github.com/guardian/dotcom-rendering/issues/5353#issuecomment-1201332115) in this [issue](https://github.com/guardian/dotcom-rendering/issues/5353) there's a question about if we're representing `NumberedList` article correctly.

Should `Display.NumberedList` become `Design.NumberedList`?

Choosing between display and design is often done by considering what needs to be mutually exclusive. In a world where all numbered list articles have specific layouts forcing the main media to be showcase then representing them as a `Display` makes sense. But if we're now saying we might allow inline main media (that we will respect what role is given in Composer) then this argument goes away and it makes more sense to combine `Design.NumberedList` with other displays, the same as we do generally.

This also has the advantage of removing the (always strange) situation where we had to support `Display.NumberedList` for all other design types.

Another plus is fewer design types means the size of the the model decreases, removing complexity and the volume of visual snapshots needed.

**Comment by mxdvl** [comment]
I agree that this would be more appropriate.

**Comment by JamieB-gu** [comment]
The following two questions spring to mind when thinking about this:

1. Does it make sense to have immersive or showcase numbered lists?
2. Is it **impossible** for something to be a numbered list _and_ one of the existing `Design`s (e.g. analysis, feature, explainer)?

If the answer to both of those is "yes", then this sounds sensible to me 🙂

**Comment by oliverlloyd** [comment]
> The following two questions spring to mind when thinking about this:
> 
> 1. Does it make sense to have immersive or showcase numbered lists?

Previously, we forced main media to showcase for numbered lists so it didn't make sense to have immersive or standard versions of them. But now there's talk of removing this main media role override and acting the same as other articles, in which case this _does_ make sense

> 2. Is it **impossible** for something to be a numbered list _and_ one of the existing `Design`s (e.g. analysis, feature, explainer)?

The might have been some thinking before where other types of articles could also get the numbered list treatment (numbers against h2 and bigger) but I think the direction we've actually gone in is to have separate designs have their own styles for lists of things. Look at Explainers for an example of this

**Comment by rhiannareechaye** [comment]
We are deprioritising this ticket by 'closing a not planned' - this won't delete the ticket and it will be searchable if the issue crops up again. Unfortunately we have over 130 health tickets to address in the web team and we can't address them all. With so many tickets we are potentially missing things that are high-impact so we're reorganising.
