### ISSUE TITLE
Containers with MPUs vary content when `isSignedIn`

### ISSUE THREAD

**Issue by oliverlloyd** [guardian/dotcom-rendering#5926]
E.g.: `fixed/medium/slow-XII-mpu`:

When not signed in
<img width="1333" alt="Screenshot 2022-09-03 at 13 59 00" src="https://user-images.githubusercontent.com/1336821/188271561-604dbfa6-2f52-43b1-8be2-ad6b6e401e3c.png">

When signed in
<img width="1333" alt="Screenshot 2022-09-03 at 13 30 04" src="https://user-images.githubusercontent.com/1336821/188271491-11b405d7-f36e-4ac8-b35d-d741ccff6ab4.png">

**Comment by mxdvl** [comment]
I think this is more about whether a user is `adFree`

**Comment by alinaboghiu** [comment]
I think maybe that this has been done

**Comment by alinaboghiu** [comment]
Closed by https://github.com/guardian/dotcom-rendering/pull/7339
