### ISSUE TITLE
Review `lib` files?

### ISSUE THREAD

**Issue by bryophyta** [guardian/dotcom-rendering#5927]
I was looking at what files haven't been edited for a long time in the repo. Excluding things like docs and config, a number of the files in the `dotcom-rendering/src/lib/` directory are among those which haven't been touched for a while, in some cases a few years.

I'm not aware of any positive reason to think that there are any issues with these scripts, but as a general health check it might be worth reviewing them at some point -- some of the functions are used for things like escaping html and parsing urls, and these are areas where best practices often change over time.

**Comment by jamesgorrie** [comment]
@bryophyta are we sure we want to look at refactoring this? Often untouched code is fine, and even if best practise evolves, if the code works, why change it if our requirements are the same?
