### ISSUE TITLE
Deprecate old node lambdas

### ISSUE THREAD

**Issue by jamesgorrie** [guardian/dotcom-rendering#5928]
AWS often deprecates runtimes for Lambda functions. They do this in two phases: first they prevent new lambdas being created, second they prevent existing lambdas being updated. More information can be found [here](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html#runtime-support-policy).

When running the following command it seems we have two lambdas in the `frontend` account:
```bash
aws lambda list-functions --profile frontend --function-version ALL --region eu-west-1 --output text --query "Functions[?Runtime=='nodejs10.x'].FunctionArn" 
```

## `frontend-consent-logs-lambda-CODE` and `frontend-consent-logs-lambda-PROD`
These seem to be related to this repo: https://github.com/guardian/consent-logs

From @ashishpuliyel 
> this dates from when we rolled our own CMP (before we had sourcepoint).
> `"iab": string, <- a valid IAB TCF v1.1 consent string`
> Yes, with TCF v2 we switched to sourcepoint and this shouldn't be bringing back any data anymore.
> The three sourcesDef in https://github.com/guardian/consent-logs/blob/master/src/model.ts are www (frontend?), DCR and AMP. All three of which now use sourcepoint. This looks entirely redundant/obsolete.

So this looks good to just remove and archive the repo.

## `AMPValidationLambda`
This is running from this repo: https://github.com/guardian/amp-validation-api

As that repo is archived, I am going to assume safe to remove the infrastructure.

**Comment by jamesgorrie** [comment]
Talk to DevX about tearing down infrastructure from `CloudFormation`.

**Comment by jamesgorrie** [comment]
There is traffic going to `consent-logs.guardianapis.com` and I would want to figure out where this is coming from before destroying the infrastructure.

**Comment by VDuczekW** [comment]
done on Monday

**Comment by jamesgorrie** [comment]
There was a small amount of traffic going through to consent-logs.guardianapis.com.

This was deemed negligible and was returning errors mostly, so we deleted the stack & fastly services associated.

Thanks @Georges-GNM for helping on this.
