### ISSUE TITLE
Redirect unsupported AMP pages

### ISSUE THREAD

**Issue by mxdvl** [guardian/dotcom-rendering#5931]
> **Note**
> Follow-up on #5930

If we don’t support an article type (Immersive, Quiz), we should redirect `amp.theguardian.com` URLs to `www.theguardian.com` ones.

**Comment by bryophyta** [comment]
This issue is in the 'In Progress' column in the Rota board, but no-one's assigned to it. Do we know if it's currently in progress? (cc. @mxdvl )

**Comment by mxdvl** [comment]
I think it may have been fixed by #6287 ?
