### ISSUE TITLE
DCR can serve a more generic 'page'

### ISSUE THREAD

**Issue by oliverlloyd** [guardian/dotcom-rendering#5941]
If DCR serves a page that isn't an article or a front, then what should be the flow for that request and what elements of the page construction can be shared?

**Comment by OllysCoding** [comment]
This seems like the kind of task that would need to be adopted as a bubble?

**Comment by alinaboghiu** [comment]
Closing in favour of @arelra's work https://docs.google.com/document/d/1E8VNfKQ5ues9uQww7t_ZSbOcBscirT1nlCY9Q2cdTm4/edit#heading=h.jbtsgr75cz7
