### ISSUE TITLE
Support 'live updates' functionality on `dynamic/package`

### ISSUE THREAD

**Issue by OllysCoding** [guardian/dotcom-rendering#5944]
Liveblogs placed in the first ('standard' grouped) slot in `dynamic/fast` can have the 'Live updates' switch enabled.

Currently in frontend, is appears a client side switch queries for recent updates from the liveblogs, and places it in the card.

Frontend:
<img width="1338" alt="image" src="https://user-images.githubusercontent.com/9575458/188600663-0332e740-f31c-424a-884d-0c2acfaa208b.png">

Fronts tool:
<img width="1229" alt="image" src="https://user-images.githubusercontent.com/9575458/188600864-12562143-9e1f-41b6-8728-ec6f24b2f4d6.png">

**Comment by oliverlloyd** [comment]
Closing in favour of https://github.com/guardian/dotcom-rendering/issues/5196
