### ISSUE TITLE
Support paid fronts

### ISSUE THREAD

**Issue by oliverlloyd** [guardian/dotcom-rendering#5945]
Some fronts are entirely paid for (not just a container). They have the special `GuardianLabs` header showing, and perhaps other changes.

Use the existing `LabsHeader` component

Example: https://www.theguardian.com/climate-academy

See `front.config.isPaidContent`

<img width="1428" alt="Screenshot 2022-09-06 at 11 27 16" src="https://user-images.githubusercontent.com/1336821/188612438-f9cc3b53-ca36-4d00-9eb1-1bc8902bde8a.png">

**Comment by alinaboghiu** [comment]
We now have the badge on these fronts, we need to 
 - hide the badge from the cards when the badge is passed at the container level (this logic already exists in the FrontLayout we just need to make it available to all containers)
- add the labs header - we already have this as it's used in articles 

Note: the badge would appear on all containers that are paid for, but I'm yet to see a paid front with more than one container so I don't think we should do any work on this until necessary

**Comment by alinaboghiu** [comment]
- [ ] Remove unnecessary badges https://github.com/guardian/dotcom-rendering/pull/8004
- [ ] Style the badge to be bigger when it is a paid for badge

**Comment by ioannakok** [comment]
> We now have the badge on these fronts, we need to
> 
> * hide the badge from the cards when the badge is passed at the container level (this logic already exists in the FrontLayout we just need to make it available to all containers)
> * add the labs header - we already have this as it's used in articles
> 
> Note: the badge would appear on all containers that are paid for, but I'm yet to see a paid front with more than one container so I don't think we should do any work on this until necessary

Closing this ticket as the only thing left from the above list is point 1. Created a ticket only for this: https://github.com/guardian/dotcom-rendering/issues/8827
