### ISSUE TITLE
`dynamic/slow` bigs are in the wrong order

### ISSUE THREAD

**Issue by OllysCoding** [guardian/dotcom-rendering#5960]
Bigs (bottom right cards) are displaying in the wrong order on DCR.

Frontend:
<img width="1001" alt="image" src="https://user-images.githubusercontent.com/9575458/188832621-323f6037-eeeb-4ac7-b5e0-2524c7759182.png">

DCR:
<img width="1013" alt="image" src="https://user-images.githubusercontent.com/9575458/188832654-81b6a494-455d-47e2-8cbc-3aebbbf0dabb.png">

**Comment by ioannakok** [comment]
Is this still an issue? Looking at the latest main stories seems to have been fixed:

https://www.chromatic.com/component?appId=637e40d1bc73bf3f604394b9&csfId=components-dynamicslow--two-very-bigs-1st-boosted-two-bigs-four-standards&buildNumber=859&k=63bc31f8a3e6b00bf034356f-320-interactive-true&h=4&b=-2

https://github.com/guardian/dotcom-rendering/blob/main/dotcom-rendering/src/web/components/DynamicSlow.stories.tsx#L143

https://github.com/guardian/dotcom-rendering/blob/main/dotcom-rendering/fixtures/manual/trails.ts#L89-L119

**Comment by ioannakok** [comment]
This has been fixed:

### Frontend
![image](https://user-images.githubusercontent.com/19683595/214063205-51040ecd-bbc5-492b-8419-f95ebe5d7e38.png)

### DCR
![image](https://user-images.githubusercontent.com/19683595/214063323-e9666698-3513-4370-84c5-d6e8ee782afb.png)
