### ISSUE TITLE
Dinkus `BodyElement`

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#5962]
As @georgeblahblah noted recently, our rendering code handling the dinkus is fragmented: https://github.com/guardian/dotcom-rendering/pull/5937#discussion_r963060695

One possible solution to this would be to move handling of the dinkus up into our parsing step, rather than handling it in several places within the rendering code. DCR do something similar as part of one of their "enhancers" [^1].

These appear inside CAPI text elements, so we could leverage the new `flattenTextElement` pattern introduced in #5767. Then the element itself might look like:

```ts
type Dinkus = {
  kind: ElementKind.Dinkus;
}
```

or possible `HorizontalRule`, if we would like this to work more widely than via a dinkus.

## Parsing Step vs Rendering Step?

AR is broken down into two main transformations:

1. Parsing step: we take the CAPI model (plus some other data) as input and transform it into our own internal data model, `Item`.
2. Rendering step: we take our internal data model, `Item`, and transform it into HTML and CSS, which is what we return.

DCR have a similar concept to step 1, referred to as "enhance CAPI" [^2]. However, this differs in that a) it doesn't take CAPI data as input, but rather the data model provided by frontend, and b) it updates the existing model (`CAPIArticleType -> CAPIArticleType`), whereas AR transforms to an entirely new model (`Content (and others) -> Item`).

## What is a dinkus?

See the "What is a dinkus?" section in #2500.

[^1]: https://github.com/guardian/dotcom-rendering/blob/2dd0abfd1cadcc49aad67fcc54cf17660ed06678/dotcom-rendering/src/model/enhance-dividers.ts
[^2]: https://github.com/guardian/dotcom-rendering/blob/main/dotcom-rendering/docs/patterns/enhance-capi.md

**Comment by alinaboghiu** [comment]
Assuming we don't want to do this now that AR is in maintenance mode
