### ISSUE TITLE
Should Preview Instances Remain `t4g.micro`?

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#5966]
In #5915 we migrated the AR instances to `t4g.small` as part of a test. If we stick with this change, should we keep the preview instances on `t4g.micro` since they receive less traffic?

To do this we'll need to make some changes to the way the CDK app is created. Currently all four stacks use the same constructor, which is hard-coded to `t4g.small`: https://github.com/guardian/dotcom-rendering/blob/200a0db50905e2856eb38d644ae45d9605308249/apps-rendering/cdk/lib/mobile-apps-rendering.ts#L85-L88

**Comment by VDuczekW** [comment]
@JamieB-gu to check cost
