### ISSUE TITLE
`dynamic/slow` - First card is incorrect when there are 2 standard cards

### ISSUE THREAD

**Issue by OllysCoding** [guardian/dotcom-rendering#6006]
Sublinks are missing, and the styling is wrong (possibly needs to be 'is dynamo')

Frontend:
<img width="1339" alt="image" src="https://user-images.githubusercontent.com/9575458/190342888-5816428d-d5e7-44b6-8c22-98c836a0e144.png">

DCR:
<img width="1331" alt="image" src="https://user-images.githubusercontent.com/9575458/190342946-33ed7127-cff2-4b0b-a2e4-e5934d63a2ae.png">

Fronts Tool:
<img width="1249" alt="image" src="https://user-images.githubusercontent.com/9575458/190343001-00906c76-3706-4d8d-a006-153bb842757f.png">

**Comment by VDuczekW** [comment]
@OllysCoding we assume this has been done via the other sublinks tickets/epic we created and will close
