### ISSUE TITLE
Missing Image Salt variable for local cypress testing

### ISSUE THREAD

**Issue by vlbee** [guardian/dotcom-rendering#6010]
I was unable to successfully run Cypress tests locallly due to a missing `.env` file with image salt variable. This was not well documented in the [testing doc](https://github.com/guardian/dotcom-rendering/blob/main/dotcom-rendering/docs/testing.md)

Tests produced a 500 error and navigating to the url in the browser gave a missing image salt error message. 

Perhaps this is a temporary issue given the project's lines in the sand about `.env` files, but for the time being it was an unexpected blocker to local cypress testing.

**Comment by mxdvl** [comment]
No longer an issue since we removed the `.env` in #6036
