### ISSUE TITLE
Create Chromatic budget

### ISSUE THREAD

**Issue by jamesgorrie** [guardian/dotcom-rendering#6037]
Part of #5940 

We need to budget for what Chromatic might cost us over the next 6-12 months. This should help us work with Chromatic in getting a better cost plan than what we're on and allow us to put it within our own budget.

**Comment by VDuczekW** [comment]
ongoing

**Comment by jamesgorrie** [comment]
This ticket isn't useful, and the parent issue captures more of the progress.
