### ISSUE TITLE
Stop Re-Writing The News Pillar On Comment Pieces

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#6053]
Remove this workaround and derive colours on `Comment` pieces from the `Design` rather than the pillar:

https://github.com/guardian/dotcom-rendering/blob/3ae0d2b83235c687467184747bcfba41d8dfc0ab/apps-rendering/src/item.ts#L503-L506

**Comment by paperboyo** [comment]
Interested in this as the logic for Opinion is different to all else. And hairy too (with `Comment is Free (Blog)` tag driving section, so Pillar). No idea how `Design` is arrived at, though…

**Comment by georgeblahblah** [comment]
Won't do now that we are rendering apps articles in DCR
