### ISSUE TITLE
Support Soundcloud Embeds

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#6055]
These come through from CAPI as a body element with type "audio", which is currently handled here:

https://github.com/guardian/dotcom-rendering/blob/8527bdbc13f943ef1b43fca1466861943670e698/apps-rendering/src/bodyElement.ts#L413

Other uses of the audio element include Guardian podcast pages (e.g. Today In Focus) and Spotify embeds.

DCR added support for Soundcloud in #1452. See also #2525.

**Comment by georgeblahblah** [comment]
Won't do now that we are rendering apps articles in DCR
