### ISSUE TITLE
Enable `noUncheckedIndexedAccess` In TSConfig

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#6058]
Provides us with better type safety: https://www.typescriptlang.org/tsconfig#noUncheckedIndexedAccess

Turning this on creates a handful of build errors that will need fixing. It's possible that most of the errors in `date.ts` will no longer be an issue if we migrate to the `datetime` module introduced in #5705.

Equivalent DCR issue: #5696.

**Comment by georgeblahblah** [comment]
Won't do now that we are rendering apps articles in DCR
