### ISSUE TITLE
Can We Delete The `InteractiveImmersive` Layout?

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#6061]
It's not wired up to anything, but it was created like that with the intention of using it when other bits of work were finished. However, the equivalent dotcom layout was recently removed from DCR: https://github.com/guardian/dotcom-rendering/pull/5839#pullrequestreview-1113355587

If no further work on this is imminent we may be better removing it for now so we don't have to maintain it. We can always refer back to the code if we need to re-implement.

There's also some code in MAPI related to this (e.g. in `RenderedItemUtils`) that we could remove at the same time.

**Note:** Don't make this change without talking to @jlieb10 first!

**Comment by rhiannareechaye** [comment]
Could we address this clean up when we're in the DCAR project as we'll have context?

**Comment by rhiannareechaye** [comment]
Looks like this was done by the attached PR so I will close this ticket
