### ISSUE TITLE
Front Picture

### ISSUE THREAD

**Issue by mxdvl** [guardian/dotcom-rendering#6062]
We need to implement a version of `Picture` for Fronts.

Supporting all images sizes at breakpoints is going to be a significant endeavour. Looking at a frontend page, there are at least these sizes on desktop + mobile:
- 90 / 93
- 100
- 130
- 140
- 160
- 220 / 221
- 300 (?)
- 460 / 462 / 470
- 640 / 650
- 940

**Comment by paperboyo** [comment]
Also, 940 (`training-site-1#headlines`; not sure if that’s the biggest)? [470](https://www.theguardian.com/news/series/the-long-read/2022/sep/05/all)?

**Comment by oliverlloyd** [comment]
This ticket supersedes https://github.com/guardian/dotcom-rendering/issues/4611 because this work now means that the `Card` component will be using a `picture` tag 🎉

**Comment by mxdvl** [comment]
We’ve decided to tackle a subset of sizes to begin with and pick up remaining ones over time.
