### ISSUE TITLE
Do not use `h1` tag for Advertisement header

### ISSUE THREAD

**Issue by georgeblahblah** [guardian/dotcom-rendering#6091]
The heading "Advertisement" above adverts should not be an `h1`, as we should have only one `h1` tag per page.

We should instead use non-heading markup, like `p` and/or `strong` tags. Although this isn't semantically correct, it is the best thing we can do for our readers using assistive technologies.

**Comment by JamieB-gu** [comment]
@georgeblahblah to create an updated issue on this.
