### ISSUE TITLE
Review dynamic & fixed container behaviour when an unexpected number of cards are provided

### ISSUE THREAD

**Issue by OllysCoding** [guardian/dotcom-rendering#6099]
DCR will currently 500 if an unexpected number of cards are provided on some fixed & dynamic containers. We should avoid this - DCR should always at least be able to render the page.

We should review all of our container types & add testing for incorrect card numbers, fixing any that require it.

Containers with known issues

- [ ] `dynamic/slow-mpu`: Uses direct indexes (`cards[0]`, `cards[1]`, etc) causing DCR to error if not enough standard cards are provided.
- [ ] TODO: Investigate more

**Comment by bryophyta** [comment]
Has this been addressed by #6485, or are there further edge cases we need to investigate? (cc. @AshCorr and @OllysCoding)

**Comment by VDuczekW** [comment]
done as per comment
