### ISSUE TITLE
Footer background colour on Live/Deadblogs in dark and light mode is inconsistent

### ISSUE THREAD

**Issue by georgeblahblah** [guardian/dotcom-rendering#6135]
## Description

Across all breakpoints, the background colour around the footer on Live/Deadblogs in light and dark mode is inconsistent. The background around the footer and the footer itself should share the same colour (#000000).

### Wide

<img width="1280" alt="Screenshot 2022-10-05 at 13 16 25" src="https://user-images.githubusercontent.com/705427/194059010-f56fe365-bae6-4fe8-bf0b-de400b5aed20.png">

### Mobile

<img width="378" alt="Screenshot 2022-10-05 at 13 16 45" src="https://user-images.githubusercontent.com/705427/194059018-0fea5af9-823f-4a87-af65-45c8e471b7ca.png">

**Comment by VDuczekW** [comment]
this will not continue happening once in DCAR
