### ISSUE TITLE
HTTP3 on theguardian.com

### ISSUE THREAD

**Issue by jamesgorrie** [guardian/dotcom-rendering#6140]
Supporting @paulmr on having HTTP3 on the site.

**Comment by paulmr** [comment]
+ Ensure that the metrics that we are collecting are tagged with the A/B test membership
+ Start increasing the membership of the test group

**Comment by VDuczekW** [comment]
@jamesgorrie moving to the rota board so it won't get missed

**Comment by rhiannareechaye** [comment]
Ash to Paul know they can turn it on as long as they check up on CWVs etc

**Comment by VDuczekW** [comment]
Ash staying assigned - longer piece of work

**Comment by bryophyta** [comment]
@paulmr are there any updates on this from your end?

**Comment by alinaboghiu** [comment]
This has been done
