### ISSUE TITLE
`fixed/small/slow-V-mpu` should not show author's photo in the 2nd column

### ISSUE THREAD

**Issue by ioannakok** [guardian/dotcom-rendering#6157]
Make sure you're signed out and visit: https://www.theguardian.com/info/complaints-and-corrections

`frontend`:

![Image](https://user-images.githubusercontent.com/19683595/194926617-82d492d1-6818-48f3-8f61-3da7f84e6e32.png)

`DCR`:

![Image](https://user-images.githubusercontent.com/19683595/194926658-062c2f94-35aa-403c-b2f2-a060697dad6e.png)

**Comment by VDuczekW** [comment]
@ioannakok to check and close if done

**Comment by ioannakok** [comment]
This is still an issue
