### ISSUE TITLE
Add React.FC rule to code style docs

### ISSUE THREAD

**Issue by bryophyta** [guardian/dotcom-rendering#6182]
We have a linting rule which warns against using `React.FC`/`React.FunctionalComponent` to annotate component types. Given that there are still easily discoverable resources online which recommend using this type (and given that there are still plenty of places where we still use it in DCR) it seems worth adding an explanation to [the TypeScript section of our contribution guide](https://github.com/guardian/dotcom-rendering/blob/main/dotcom-rendering/docs/contributing/code-style.md#typescript).

There are some linked resources which explain the rationale behind this rule in @oliverlloyd's [PR](https://github.com/guardian/dotcom-rendering/pull/5622#issue-1331731673) for the eslint rule.

**Comment by jamesgorrie** [comment]
Fixed in https://github.com/guardian/dotcom-rendering/pull/6666
