### ISSUE TITLE
Missing container data for Headlines

### ISSUE THREAD

**Issue by mxdvl** [guardian/dotcom-rendering#6224]
Container data is broken an `useAPI` returns `404`s: [Sentry DOTCOM-RENDERING-GSR](https://sentry.io/organizations/the-guardian/issues/2355599340/).

https://github.com/guardian/dotcom-rendering/blob/3ce2432b1a82e8cb3f609565f3508c6f95df0616/dotcom-rendering/src/web/components/OnwardsUpper.importable.tsx#L81-L86

- https://api.nextgen.guardianapps.co.uk/container/data/au-alpha/news/regular-stories.json

**Comment by alinaboghiu** [comment]
@mxdvl how is this triggered/how does it affect the website? 
Just trying to understand this issue ahead of health prioritisation.

**Comment by mxdvl** [comment]
I think it may be triggered when there's no story package? At any rate it's far from being the top issue with `useApi` erroring and has not happened for two months.
