### ISSUE TITLE
Support crossword SVGs on Fronts cards

### ISSUE THREAD

**Issue by bryophyta** [guardian/dotcom-rendering#6236]
Trail  data for Fronts cards that link to crosswords does not have an image URL. Instead, Frontend checks whether the card is a crossword card, and if so it constructs a URL for an svg of the crossword:

https://github.com/guardian/frontend/blob/9a69dd4fdc2f09cbc2459dedd933b03215d2cad7/common/app/model/FaciaDisplayElement.scala#L10-L33

It doesn't look like DCR currently supports this:

|Frontend|DCR|
|---|---|
|<img width="1340" alt="image" src="https://user-images.githubusercontent.com/37048459/196698410-fa303875-18ec-40d0-b50b-e3c1efb33323.png">|<img width="1353" alt="image" src="https://user-images.githubusercontent.com/37048459/196698288-308c7558-69a0-4640-b911-11f79c229bb9.png">|

(The discrepancy was noted by @Georges-GNM in connection with PR #5145)

Checking whether a trail `isCrossword` and constructing the svg URL should be straightforward. 

However, it's not immediately obvious _where_ to put this logic. e.g. Frontend seems to give video priority over the crossword svg, if it's present. Do we know where crossword svgs fall in terms of the overall priority decision tree?

(Also, are there any occasions where we _don't_ want to display any image for a crossword card?)

cc. @oliverlloyd -- do you have any insight on this?

**Comment by mxdvl** [comment]
I worked on the SVG rendering logic in Frontend, so happy to have a look at porting the Scala to Preact if that’s helpful.

**Comment by VDuczekW** [comment]
not supported in 1% test and mark so
