### ISSUE TITLE
Fullscreen icon is out of place on cartoons

### ISSUE THREAD

**Issue by jamesgorrie** [guardian/dotcom-rendering#6239]
The control to make cartoons full screen is out of place.

It should be in the top-right corner, as per other areas it's used.

A potential offender could have been this PR:
https://github.com/guardian/frontend/pull/25110

This code is on frontend, not DCR as cartoons are not yet supported via DCR.

## right
<img width="912" alt="Screenshot 2022-10-19 at 16 41 25" src="https://user-images.githubusercontent.com/31692/196739357-b94fb863-c614-4e70-bf33-b9b419836a50.png">

## wrong
<img width="731" alt="Screenshot 2022-10-19 at 16 39 37" src="https://user-images.githubusercontent.com/31692/196738992-1657a5b8-7537-4bda-90f0-8e6559b38d91.png">

See: https://www.theguardian.com/commentisfree/picture/2022/oct/16/ben-jennings-on-liz-trusss-precarious-hold-on-power-cartoon

**Comment by paperboyo** [comment]
The offender broke all icons for `dcr=false`. Why would it also affect Cartoon type if it’s not yet DCR, but not Gallery type (which also isn’t DCR) – I don’t know. But I don’t like the offender. He meanie (if self-righteous).

**Comment by rhiannareechaye** [comment]
We are deprioritising this ticket by 'closing a not planned' - this won't delete the ticket and it will be searchable if the issue crops up again. Unfortunately we have over 130 health tickets to address in the web team and we can't address them all. With so many tickets we are potentially missing things that are high-impact so we're reorganising.
