### ISSUE TITLE
Special Report Alt

### ISSUE THREAD

**Issue by VDuczekW** [guardian/dotcom-rendering#6246]
linked tickets: 

- [x] [#6112](https://github.com/guardian/dotcom-rendering/issues/6112) & 
- [x] #6115

Documentation: https://docs.google.com/document/d/1YnWmfEa1nQKEGgJbPgs9cp9VaMBOBILqGNRqqsZ0Jys/edit

**Comment by VDuczekW** [comment]
https://github.com/guardian/dotcom-rendering/pull/6174

**Comment by ioannakok** [comment]
List of tasks and status: https://docs.google.com/document/d/1bQwJHZyKtSobULRLYppgxnrbcrPqKifmoBWK895jEiE/edit

**Comment by ioannakok** [comment]
Work has been completed. See linked tickets for details
