### ISSUE TITLE
Make Analysis quote text black

### ISSUE THREAD

**Issue by HarryFischer** [guardian/dotcom-rendering#6254]
Just need to change the text here from grey to black (neutral.7 / #121212)

![Image](https://user-images.githubusercontent.com/20658471/197152585-7f0c576d-a6a3-47aa-abdb-767403f05e3a.png)

**Comment by tkgnm** [comment]
moved to journalism board https://trello.com/c/6IaZpvps/636-just-need-to-change-the-text-here-from-grey-to-black-neutral7-121212
