### ISSUE TITLE
Remove deprecated `set-output` methods from GHA workflows

### ISSUE THREAD

**Issue by bryophyta** [guardian/dotcom-rendering#6273]
This issue is a WIP, but relates to [this recent deprecation notice](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/).

**Comment by jamesgorrie** [comment]
[A code search](https://github.com/search?q=org%3Aguardian%20set-output&type=code) shows we don't have any repos with this in, so closing.

**Comment by bryophyta** [comment]
ah okay -- I've seen the warning fairly recently in our logs but maybe it was coming through from a third-party action's use of those methods? I can't find an example right now but will post here if I spot it again. Happy to leave this closed for now 👍
