### ISSUE TITLE
Onward Content Images Not Loading

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#6274]
Example here: https://mobile.guardianapis.com/uk/rendered-items/culture/2022/oct/23/barbra-streisand-interview-bon-soir-new-album

May be related to #6267.

**Comment by JamieB-gu** [comment]
We might want to consider looking at #5711 first, which may simplify the onward content model.

**Comment by bryophyta** [comment]
Given that #5711 is closed due to the merger, does that mean that this one is, too? (cc. @georgeblahblah )
