### ISSUE TITLE
Use `changesets` to manage Bridget version and releases

### ISSUE THREAD

**Issue by georgeblahblah** [guardian/dotcom-rendering#6283]
The release process for [Bridget](https://github.com/guardian/bridget) is not easily discoverable, and does not follow the [department recommendations](https://github.com/guardian/recommendations/blob/main/npm-packages.md#publishing).

To align with the recommendations, we should introduce `changesets` to manage versioning and improve the publishing workflow.

**Comment by shesah** [comment]
Not high priority

**Comment by georgeblahblah** [comment]
Done in https://github.com/guardian/bridget/pull/116!
