### ISSUE TITLE
Discussion loader never stops

### ISSUE THREAD

**Issue by mxdvl** [guardian/dotcom-rendering#6292]
Seen on: https://www.theguardian.com/environment/2022/oct/26/dont-try-this-at-home-why-theres-nothing-better-than-sharkskin-for-a-good-scratch-if-youre-a-tuna#comments

<img width="532" alt="image" src="https://user-images.githubusercontent.com/76776/198075121-877d1daa-5a87-4bfb-b205-0d436fe888b1.png">

**Comment by mxdvl** [comment]
Cannot reproduce

**Comment by Georges-GNM** [comment]
Low impact - can reopen if it comes up again

**Comment by Georges-GNM** [comment]
Seen again today on https://www.theguardian.com/culture/2023/mar/08/why-are-clowns-so-terrifying-science-has-the-answer-and-its-not-all-down-to-the-makeup

No comments to display:
![image](https://user-images.githubusercontent.com/102960844/223786055-2906f036-56a5-4dba-92f3-471ac464cc5d.png)

Then after a couple of comments:
![image](https://user-images.githubusercontent.com/102960844/223786210-c172a4f1-a810-40e7-9584-f3c7e1a7580f.png)

**Comment by VDuczekW** [comment]
Closing as low priority

**Comment by mxdvl** [comment]
Still not a priority, but it seems like the issue is caused by setting [`setLoadingMore`](https://github.com/guardian/dotcom-rendering/blob/07e8d93504f1424ebd830d0df7ccc6a949a5f042/dotcom-rendering/src/discussion-rendering/App.tsx#L290) to `true` without an event to stop it.
