### ISSUE TITLE
Move mxdvl to another team

### ISSUE THREAD

**Issue by gtrufitt** [guardian/dotcom-rendering#6296]
@mxdvl is getting too near my commit record, can we move him to another team that doesn't contribute to dotcom-rendering please

**Comment by mxdvl** [comment]
You snooze, you lose! <3

**Comment by mxdvl** [comment]
<img width="851" alt="image" src="https://user-images.githubusercontent.com/76776/199969265-0a6b41e5-8f03-46c6-a360-596751f6746a.png">

**Comment by gtrufitt** [comment]
💔
