### ISSUE TITLE
a11y: no `<h3>` tags on Fronts

### ISSUE THREAD

**Issue by bryophyta** [guardian/dotcom-rendering#6315]
Lighthouse for the UK front is reporting that our headings are not in sequentially descending order. I believe that this is because the headings on Fronts containers are `<h2>`, but the headings for the cards are  `<h4>`, with no `<h3>` currently on the page at all.

Frontend currently uses `<h3>` for cards (see screenshot). We should do the same in DCR, unless we're planning introduce a new heading in the hierarchy between the container heading and the card headline.

<img width="321" alt="Card headlines on Frontend Fronts are <h3> tags" src="https://user-images.githubusercontent.com/37048459/198967218-a125105c-5e0e-43b1-927b-2d007fb0aee3.png">

## Proposed solution

The current proposal is to add a `getHeadingLevel()` function, or similar, analogous to how we currently have `getZIndex`. Unless the heading hierarchy is tightly constrained on the tools side of things, then we should accommodate the possibility that the heading level used by a given component (e.g. a Card) might vary depending on what context it is found in.

**Comment by nishtha53** [comment]
can I work on this issue?

**Comment by bryophyta** [comment]
Hi, thanks for your interest in contributing to this issue!

Unfortunately when we were discussing this issue yesterday we decided to implement a fix for it which requires quite a lot of coordination across different parts of the codebase, so I am removing the 'good first issue' label for now. Once we've fixed it, though, we will link back to this issue from the PR, so please feel free to take a look and comment on the PR when it's opened, if you're interested in doing so.

More generally, we have been discussing recently how to enable contributions to this codebase, because it's currently not as easy as we would like, especially for external contributors. We're part way through writing up a first draft of a new contribution guide, and we hope that this will be available soon.

(We have [an initial PR for the contribution guide](https://github.com/guardian/dotcom-rendering/pull/6128), and we plan to add more detail to it soon.)

**Comment by bryophyta** [comment]
Update on the discussion above -- when we started to look into it as a team, it looks like at the moment the heading structure is actually quite stable across different kinds of pages. Given this, we just updated the hard-coded `<h4>` value in card headlines to be a `<h3>` instead.

If we get more complicated rules at some point in the future then we may want to revisit this.
