### ISSUE TITLE
Review Speedcurve settings

### ISSUE THREAD

**Issue by bryophyta** [guardian/dotcom-rendering#6316]
Questions from our recent dashboard review:

- Are we measuring what matters with Speedcurve at the moment?
- Is there any way we can slim down the dashboards, or make it easier to see what matters?
- Are our targets still appropriate?
    - Should we be setting finer-grained targets for ads vs no-ads, when it  comes to things like JS size?
    - What other teams might we need to coordinate with in order to establish SLOs that we could enforce?

**Comment by bryophyta** [comment]
@jamesgorrie and @Georges-GNM to work on this next week?

**Comment by jamesgorrie** [comment]
Speedcurve is being used as part of our dashboard sessions and seems to be fine.
