### ISSUE TITLE
Add `bucketSsmLookup: true` to DCR and frontend `riff-raff.yaml`

### ISSUE THREAD

**Issue by ioannakok** [guardian/dotcom-rendering#6317]
After this PR https://github.com/guardian/riff-raff/pull/704 Riff Raff can discover the target S3 bucket from SSM Parameter Store, rather than having the bucket name hardcoded in `riff-raff.yaml`. See the PR for further details and example. We should make this change both in [DCR](https://github.com/guardian/dotcom-rendering/blob/main/dotcom-rendering/scripts/deploy/riff-raff.yaml) and [frontend](https://github.com/guardian/frontend/blob/main/riff-raff.yaml) `riff-raff.yaml`.

**Comment by bryophyta** [comment]
These two PRs will close this:
- [ ] Frontend [#25708](https://github.com/guardian/frontend/pull/25708)
- [x] DCR #6560
