### ISSUE TITLE
Data: Create easy-access dashboards for key user metrics

### ISSUE THREAD

**Issue by rhiannareechaye** [guardian/dotcom-rendering#6318]
While our user metrics are accessible via datalake, we would like to be able to access this in Tableau so that we can monitor these in our weekly dashboard check ins 

This would include: 
- Attention time
- Click through rate (incl thrashers)
- Impressions for each component
- Bounce rate

**Comment by guyparr** [comment]
Do you know how you'd like to be able to filter and split the data? eg, by device, territory, content vs front etc.

I've had a look and I don't think we can see impressions for the thrashers so CTR for those might not be possible.
