### ISSUE TITLE
Add TBT (Total Blocking Time) to Lighthouse report

### ISSUE THREAD

**Issue by mxdvl** [guardian/dotcom-rendering#6322]
Says it on the tin!

Our Github Action running on each PR should surface this value so we can track how it evolves over time.

**Comment by jamesgorrie** [comment]
@mxdvl which lighthouse report do you mean? The GitHub action, or something else?

**Comment by mxdvl** [comment]
> @mxdvl which lighthouse report do you mean? The GitHub action, or something else?

Yes, the github action's results on pull requests. The data is there in the full report.

**Comment by bryophyta** [comment]
Closed by #6838
