### ISSUE TITLE
Media Atoms

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#6326]
These are used to power some of the videos that appear in articles, and are therefore sometimes referred to as "video atoms".

## Work Involved

The implementation of these will be different between dotcom and apps. While DCR will use the atoms-rendering implementation, these videos are actually powered by the native layer in apps. Therefore the work in AR will involve creating a placeholder and then communicating to the native layer where to place the video via Bridget.

We'll also want to make sure we version this Bridget API, so only native clients that have added support for these videos will show the AR version of the article.

## Examples

- https://www.theguardian.com/business/video/2022/jan/27/just-in-time-why-we-keep-running-out-of-everything-video

**Comment by georgeblahblah** [comment]
Done in https://github.com/guardian/mobile-apps-api/pull/2239
