### ISSUE TITLE
Chart Atoms

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#6327]
These are used to power some of the charts that appear in articles. Not all charts are powered by chart atoms - some may be interactive atoms, for example.

## Work Involved

These are included in atoms-rendering, so we can look into updating and using the implementation there.

## Examples

- https://www.theguardian.com/world/2022/jan/25/australia-records-its-worst-ever-score-on-anti-corruption-index-after-decline-to-match-hungarys

**Comment by georgeblahblah** [comment]
Won't do now that we are rendering apps articles in DCR
