### ISSUE TITLE
Audio Atoms

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#6328]
These are used to power some of the audio content that can appear in articles.

## Work Involved

These are included in atoms-rendering, so we can look into updating and using the implementation there.

## Examples

- https://www.theguardian.com/gnm-archive/2021/nov/24/the-guardian-bicentenary-oral-history-project
- https://www.theguardian.com/world/2022/apr/14/thursday-briefing-uk-may-send-asylum-seekers-to-rwanda

**Comment by georgeblahblah** [comment]
Won't do now that we are rendering apps articles in DCR
