### ISSUE TITLE
Fix focus behaviour for `ShowMore` container

### ISSUE THREAD

**Issue by bryophyta** [guardian/dotcom-rendering#6343]
Currently, when a user clicks the 'Show More' button on a Fronts container to load a new set of cards, their focus will remain on the button and the cards will be loaded _above_ the button in the DOM.

The new cards should be announced to screen readers. But for screen readers and others who are navigating using the `tab` key, it may be surprising that they have to tab _backwards_ to get to the new cards.

---
<img width="50%" alt="" src="https://user-images.githubusercontent.com/37048459/199680338-de6be4ef-5033-4a7f-beab-a53525323ce2.png">
(prior to clicking the 'More' button)

---

<img width="50%" alt="" src="https://user-images.githubusercontent.com/37048459/199680404-ba804fea-805f-4be7-a5f5-b24f5867accf.png">
(after clicking the 'More' button; new cards are loaded above it in the DOM)

---

**Potential solutions:**

1. Programmatically move focus to the new cards when they are loaded in.
2. Use CSS to place the button _visually_ below the cards, while keeping it above them in the DOM, so that you could tab forwards from the button to the cards.
3. Place the button above the cards both visually and in the DOM.

Option (1) currently seems to be the preferred route, but this is the topic of continuing discussion with UX and design.

**Comment by isabellapurchas** [comment]
@bryophyta My thoughts on potential solutions:
1. I think programatically moving focus is not ideal, but if we do find it the best option then moving to the container for the new set of links would be best, not just the first link of the new set.
2. I think this will be strange for sighted users accessing via keyboard. If they tab backwards, they'll go through the new set of links, then the button which now says 'show less' and then through the original links.
3. We want to avoid this, but it can be a design question when we look at these containers in future.

I had another thought which was, (keeping the visual order & DOM aligned) could we introduce a hidden 'skip to' button which is the next element in the tab order after the 'show more' button, and when activating this 'skip to' button their focus is moved backwards in the tab order to the new set of links. Let me know if you want to discuss this?
