### ISSUE TITLE
Fewer than expected cards

### ISSUE THREAD

**Issue by VDuczekW** [guardian/dotcom-rendering#6346]
"This is a bug, we have developed our own fallbacks

These are containers that claim to be fixed (i.e. they claim to only accept 10 cards, but the tools don't enforce the number of cards expected so sometimes people will put 9 cards in, and we need to account for this in how these containers look)"

**Comment by rhiannareechaye** [comment]
Tools happy to pair on this - they're going to tell us whether or not tools can enforce a strict number of cards

**Comment by AshCorr** [comment]
> Tools happy to pair on this - they're going to tell us whether or not tools can enforce a strict number of cards

Perfect, thanks Rhianna!

**Comment by ioannakok** [comment]
Fixed by: https://github.com/guardian/dotcom-rendering/pull/6485
