### ISSUE TITLE
Bug on Sublinks

### ISSUE THREAD

**Issue by VDuczekW** [guardian/dotcom-rendering#6347]
"These are the links under cards. There are other cases where they look a bit broken.
We would like to do a review of the way they work. We need to go into the fronts tool. We can’t just fix it as it needs some thought. Double check colours of these. Main problem is whether they show horizontally or vertically - we've made some changes with how cards look in relation meta data"

**Comment by VDuczekW** [comment]
related tickets 

- [ ] [#5917](https://github.com/guardian/dotcom-rendering/issues/5917)
- [ ]

**Comment by VDuczekW** [comment]
@Georges-GNM & @DanielCliftonGuardian is this one relevant to the sublink work [#5267](https://github.com/guardian/dotcom-rendering/issues/5267)

**Comment by mxdvl** [comment]
Follow-up work on #6691
