### ISSUE TITLE
AUS Footer update

### ISSUE THREAD

**Issue by VDuczekW** [guardian/dotcom-rendering#6353]
We need to add ‘[Acknowledgement of Country](https://www.reconciliation.org.au/)’ (a statement that will sit at the bottom of the Aus Website to show respect to Indigenous Australian people) 

We will implement this as part of our rota work this sprint

**Comment by ajbreuer** [comment]
@VDuczekW @i-hardy @mxdvl 

Here are my draught designs for adding the new copy to the Australian Footer... I prefer option 1, but I was concerned that this might be more difficult to implement... so tried option 2 which I thought might be easier

https://www.figma.com/file/eT6V6c69KxPhKmLReFfZ08/Australia-Footer?node-id=0%3A1

**Comment by rhiannareechaye** [comment]
Team are keen on option 1
