### ISSUE TITLE
Support with Nav Bar changes

### ISSUE THREAD

**Issue by VDuczekW** [guardian/dotcom-rendering#6354]
Supporter Revenue will be picking up this work with support from Dotcom, see document [here](https://docs.google.com/document/d/1neiLnawxPOxz_8CMFJqbrq_UcV2GpqGTKFU0UFlvaPc/edit?hl=en-GB&forcehl=1)

Fixes here: https://github.com/guardian/dotcom-rendering/issues/6436

**Comment by ioannakok** [comment]
Completed
