### ISSUE TITLE
Lint out `line-height` usage applying standard rules from pasteup

### ISSUE THREAD

**Issue by gtrufitt** [guardian/dotcom-rendering#636]
&nbsp; | &nbsp; 
--- | --- 
<img src="https://user-images.githubusercontent.com/638051/60902622-d3304d00-a267-11e9-855d-634aba1880a2.png" width="800"  /> | In an attempt to normalise the spacing in Dotcom, I would like to completely lint out the ability to use certain properties. One of which is `line-height`.<br><br>Reviewing this, maybe we can create a pasteup function that returns 1, 2, 3 or 4 rem (16px, 32px, 48px, 64px) and refactor the current elements to use the closest value.<br><br>Not sure if this is sensible and whether it should be looked at more holistically with the other spacing methods (margins, padding?)<br><br>Thoughts from DS team welcome.

**Comment by SiAdcock** [comment]
I agree we should try to remove custom `line-height`s wherever possible. 

Would it not be ideal to use Pasteup's [typography](https://github.com/guardian/dotcom-rendering/tree/master/packages/pasteup#fonts) module in all circumstances and have no hard-coded `font-size` or `line-height` anywhere? Are there common patterns in which `line-height` is necessarily decoupled from `typography`?

**Comment by gtrufitt** [comment]
Line height being used for centering text is often a use case I guess where it's separated from font-size

**Comment by SiAdcock** [comment]
I see. Could we use flexbox for that? Or maybe a `verticallyCentre(height: number)` mixin that takes the `height` of a container, and returns the `height` and `line-height`?

**Comment by rcrphillips** [comment]
One for @zeftilldeath to think about regarding the actual values and this is something he has said he wants to fix. Regarding the approach, it sounds sensible to me. 

Base on my limited experience, the flexbox approach for centring might be a bit more straightforward?

**Comment by gtrufitt** [comment]
https://github.com/guardian/dotcom-rendering/pull/651

**Comment by SiAdcock** [comment]
@gtrufitt Can we close this now?

**Comment by gtrufitt** [comment]
wait wait wait @jamesgorrie 👀

**Comment by jamesgorrie** [comment]
@gtrufitt happy to reopen, but as far as I can tell we're not using pasteup anymore?

**Comment by gtrufitt** [comment]
It's ok James, I was just surprised to see you. I don't care about pasteup as much as I once did tbh. 💀 😁

**Comment by jamesgorrie** [comment]
@gtrufitt back in action. Ping me on email, we'll say hi.
