### ISSUE TITLE
Weather widget

### ISSUE THREAD

**Issue by VDuczekW** [guardian/dotcom-rendering#6378]
What is it: 
The widget on the top left of the Front - apparently we are contractually obliged to show this but James & Rhianna are investigating
What has been done so far:
my sense is that we need to do some discovery on things like Weather Widget and Ad Free to know what's involved. So it might make sense to plan time in for the discovery itself?

**Comment by bryophyta** [comment]
On widget accessibility from #4602:

> The current icons do not pass contrast checks
> Add aria labels with the weather described in words

See also the recent accessibility PR in Frontend for this widget: [Frontend #25480](https://github.com/guardian/frontend/pull/25840)

**Comment by sndrs** [comment]
the two PRs referenced above are the current state of play. 

#8096 creates a react component to display the weather data, and #8097 is a WIP that fetches the data and displays the component on fronts.

There are some outstanding things to do on both, but the component is _almost_ there (todos are listed on the PR).

Once it's merged, knocking the data-fetching PR into shape shouldn't be too tricky (i hope!), but it will need to align with the response @alinaboghiu has been working on in frontend.

do shout if any of this needs more clarification

**Comment by VDuczekW** [comment]
integration work still outstanding - @AshCorr to check in with James and pick up

**Comment by rhiannareechaye** [comment]
Closing this ticket as it's been marked as 'done'
