### ISSUE TITLE
Investigate what work is left re Dynamo

### ISSUE THREAD

**Issue by VDuczekW** [guardian/dotcom-rendering#6381]
This is a type of special card with dynamic type features (the styling of the sub-links etc.)
This is in tickets, but it’s not part of the Fronts launch currently.

- [ ] #7951
- [x] Decide whether to show Byline - The byline is present on DCR but not on Frontend. If we want to start showing the byline here, it should be styled as a byline.
- [x] Decide whether to show comment count
- [x] Sublink alignment
- [X] Sublink styling

**Comment by rhiannareechaye** [comment]
This is left:  https://github.com/guardian/dotcom-rendering/issues/5196

**Comment by bryophyta** [comment]
There are some other (potential) visual bugs that I can't find tickets for (screenshots are from [this test front](https://m.code.dev-theguardian.com/sublinks-test).)

>**Note**
>I've created a pretty odd card here, so it may be that most of these issues will be avoided by editorial behaviour, but it seems like it's worth checking how important they are, and at least some of them look like broader bugs?

## Card background colour

The main card here has a white background on DCR and a comment-coloured background on Frontend. When you hover over them they both go the same colour, so presumably DCR should have the comment-coloured bg when not hovered, too.

## Byline

The byline is present on DCR but not on Frontend. If we want to start showing the byline here, it should be styled as a byline.

## Comment count

We're showing the comment count on DCR but not on Frontend. Should we be showing it or not?

## Sublink alignment

The fourth sublink is spilling over the edge of the photo in DCR.

## (?) Sublink styling

imo the styling for the sublinks looks nicer in DCR than in Frontend, but they are different. Also, have we checked how the semi-transparent background works for accessibility (colour contrast for the text)?


|Frontend|DCR|
|-|-|
|<img width="1305" alt="image" src="https://user-images.githubusercontent.com/37048459/216400519-a595e342-fc3e-48ce-b76d-6196695f016b.png">|<img width="1308" alt="image" src="https://user-images.githubusercontent.com/37048459/216400942-54475bda-2a87-41ed-bec1-6f9002195dbe.png">|

**Comment by Georges-GNM** [comment]
@HarryFischer Think we're close to being able to work on this ticket, just wondering what you think of some of the design questions here? 

- Presumably DCR should have the comment-coloured bg when not hovered, too?
- Should we be showing the byline and comment count?
- Should we keep the current DCR styling for sublinks or make it the same as frontend?

Thanks!

**Comment by mxdvl** [comment]
> ## Card background colour
> 
> The main card here has a white background on DCR and a comment-coloured background on Frontend. When you hover over them they both go the same colour, so presumably DCR should have the comment-coloured bg when not hovered, too.

This is the main thing that remains doing. I’ll align to @Georges-GNM’s proposal:

> Presumably DCR should have the comment-coloured bg when not hovered, too?

--- 

> Should we be showing the byline and comment count?

I think yes, unless there are latest links (live updates). This is handled in #7914 

--- 

> Should we keep the current DCR styling for sublinks or make it the same as frontend?

Talking with Alex Breuer yesterday he preferred the DCR styling of sublinks, so I think we should keep them as-is.
