### ISSUE TITLE
Mob on reducing Sentry noise

### ISSUE THREAD

**Issue by rhiannareechaye** [guardian/dotcom-rendering#6400]
https://docs.google.com/document/d/1fHg5eyftWoUihR-9MDjY674WIGHJ8uH97FQGBzFHCLk/edit

**Comment by bryophyta** [comment]
@AshCorr and I started looking through some of the most common errors on the Sentry board yesterday and have raised a couple of tickets using the [Sentry label](https://github.com/guardian/dotcom-rendering/issues?q=is%3Aopen+label%3A%22Sentry+%E2%96%B5%22+sort%3Aupdated-desc).

Continuing to work through these most common errors will hopefully help us reduce the 'noise' we currently see on Sentry and make it easier to spot new issues.

We're also looking at whether we can enable the github integration, which should hopefully make it easier to surface issues.

**Comment by VDuczekW** [comment]
this is more of an Epic and lots of smaller items are coming up and being done as an when - this Epic needs a bit of work and reword

**Comment by rhiannareechaye** [comment]
Mobbing in for 31st

**Comment by bryophyta** [comment]
mobbing to happen on Monday
