### ISSUE TITLE
Sublink styling with liveblog/special report parents

### ISSUE THREAD

**Issue by bryophyta** [guardian/dotcom-rendering#6421]
There is currently a bug in how we render SpecialReport sublinks, when their parent card is not also a SpecialReport:

SpecialReport kickers and headline text is light, because SpecialReport cards are dark. So when it's a sublink on e.g. a News card, which has a light background, there is insufficient contrast.

It looks like Frontend uses ~the parent's styling~ the sublink's _pillar/theme_ styling in this situation. We're waiting for some input from @HarryFischer to determine what the actual rules should be for this case (and for Liveblogs, too).

Frontend is on the left, DCR is on the right. (nb. there are a number of other differences, but these are separate issues.)

![Image](https://user-images.githubusercontent.com/37048459/201149826-7f65533f-4ff4-4d00-abad-424bdd51e598.png)

**Comment by HarryFischer** [comment]
I think frontend is the best solution here. So:

- if a 'normal' card (eg. on light grey) sublinks use their pillar colour. We'd have to make an exception here for specialReport stories and revert to News/nearest pillar (Not sure if we get this data through)
- If it's a sublink on a liveblog card it should use liveblog palette

Does that work?

**Comment by ioannakok** [comment]
Close by: https://github.com/guardian/dotcom-rendering/pull/6466
