### ISSUE TITLE
Support `description` container config

### ISSUE THREAD

**Issue by AshCorr** [guardian/dotcom-rendering#6433]
Description should be used to populate the text under a container header.

## DCR

<img width="461" alt="image" src="https://user-images.githubusercontent.com/21217225/201367688-9711035d-a6b7-40b9-bd44-4f96aa41d718.png">

## Frontend

<img width="417" alt="image" src="https://user-images.githubusercontent.com/21217225/201367715-982e9367-2cae-4dfb-983c-7bd73561eb16.png">

**Comment by OllysCoding** [comment]
Picking this up
