### ISSUE TITLE
Support `Show latest update in header` in container config

### ISSUE THREAD

**Issue by AshCorr** [guardian/dotcom-rendering#6437]
![image](https://user-images.githubusercontent.com/21217225/201371551-70888d50-fbfb-49d6-a5b8-529e59d87b23.png)

## Frontend

<img width="469" alt="image" src="https://user-images.githubusercontent.com/21217225/201371172-8e7b7018-fe5a-403a-a257-d380e6312627.png">

## DCR

<img width="477" alt="image" src="https://user-images.githubusercontent.com/21217225/201371294-e4428b5d-94e3-4f19-b18d-6c723b93d706.png">

## Should we support this?

I had a brief flick through a number of fronts but couldn't find any containers using this feature, can we deprecate this?

**Comment by rhiannareechaye** [comment]
We'll discuss it in Alina's session about container tools

**Comment by alinaboghiu** [comment]
- displays a date under the container header 
– not currently used for any container, when it is used it should only ever be used on the very top one
– no need to support it for any container
– should move to front metadata, not container metadata
– In practice this is hardcoded platform-side to top container 

For reference, in this screenshot the top container date comes from the rendering platform, the second (Ukraine Invasion) comes from the "show latest update in header" checkbox.

![Image](https://github.com/guardian/dotcom-rendering/assets/1229808/30f65fdd-c814-4d58-a41a-e9fb03e65b58)
