### ISSUE TITLE
Review “Contributors” page

### ISSUE THREAD

**Issue by mxdvl** [guardian/dotcom-rendering#6447]
There’s quite a few differences between the [DCR](https://www.theguardian.com/index/contributors?dcr=true) and [frontend contributors](https://www.theguardian.com/index/contributors?dcr=false) pages

| Frontend | DCR |
|--|--|
| ![Image](https://user-images.githubusercontent.com/31692/230040152-b2bcc087-0e64-410f-ab86-e3b993190388.png) | ![Image](https://user-images.githubusercontent.com/31692/230039855-9b71dd2d-2612-417e-95fb-621efbc5454e.png) |

```[tasklist]
## Noticeable differences
- [ ] Gallery cards don't seem to have their treatment applied
- [ ] The ["Opinion"](https://github.com/guardian/csnx/blob/main/libs/%40guardian/libs/src/format/ArticlePillar.ts#L3) colour isn't being applied
```

**Comment by VDuczekW** [comment]
this ticket is to review all the different containers with Avatars as it seems to look better on some and not others - some more manual checks needed

**Comment by ioannakok** [comment]
After a more careful look on this, here's an explanation of what is happening and possible fix: https://github.com/guardian/frontend/pull/26092
