### ISSUE TITLE
Video Layout

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#6460]
Build a new layout for video articles. This _may_ be able to fit within the `Standard` layout or, if they're different enough, we may need to create a new layout component for them: https://github.com/guardian/dotcom-rendering/tree/main/apps-rendering/src/components/Layout

If building a new layout, consider using the new grid module (see the immersive layout for examples):

https://github.com/guardian/dotcom-rendering/blob/cebdd2ac0d885ea511b9d315152f2fdf3c979830/apps-rendering/src/grid/grid.ts#L119-L123

Video articles should follow the current dotcom designs (frontend, these aren't built yet in DCR). For dark mode we'll want to derive colours from how video articles currently look on the app. If this isn't sufficient we can talk to Design for help.

Video articles are represented in the `ArticleFormat` type as `ArticleDesign.Video`. They look similar to audio articles, so much of this work could be derived from the audio layout if we decide to build that first: #5188.

**Comment by georgeblahblah** [comment]
Won't do now that we are rendering apps articles in DCR
