### ISSUE TITLE
Decide a policy for treat/nugget thrashers with Visuals

### ISSUE THREAD

**Issue by bryophyta** [guardian/dotcom-rendering#6535]
Adding a custom 'platform treat' thrasher to a front requires adding config for it in DCR (in contrast to the implementation in Frontend). Additionally, we need to add the thrasher to a blocklist which will prevent DCR trying to render it as a container (see below for what this looks like):

## DCR
<img width="1441" alt="image" src="https://user-images.githubusercontent.com/37048459/203121909-aaadaadc-1baf-4c10-a3fe-c4c2209a1b54.png">

## Frontend 
<img width="1433" alt="image" src="https://user-images.githubusercontent.com/37048459/203121983-fd841e62-555f-4997-8a45-378f41505ac1.png">

When we roll out the test, we'll need to make sure both that new treat thrashers are added to the allowlist, and that we are told about the addition of new legacy treats before they're launched. Otherwise we will end up rendering the legacy ones in a broken way by accident (see screenshot above).

We should make sure that we know who in Visuals might add new treat thrashers, and that we've agreed a plan with them to keep both lists up to date.

cc. @AshCorr @HarryFischer and @rhiannareechaye

**Comment by ioannakok** [comment]
Closing for now - will be revisited cc @HarryFischer
