### ISSUE TITLE
Font Weights in pasteup

### ISSUE THREAD

**Issue by gtrufitt** [guardian/dotcom-rendering#654]
https://trello.com/c/exoFBmVf/495-font-weights-in-pasteup

> On dotcom-rendering we support a subset of font weights for each font family, one reason we do this is because this limits the amount of font files a user might potentially download. 

> font-weights can be represented by numbers eg. `font-weight: 700`. `font-weight: 700` is also equal to `font-weight: bold`.

> We should however discourage the use of string values such as `font-weight: bold` in favour of an API exposed by pasteup that maps weight values (`thin`, `regular`, `bold` for example) to our own mappings of font-weight numbers/files, this will give us the flexibility to adjust the bold font file in the future.

There are two things to consider:

- Font weights applied to headlines - should we apply consistently even if it means changing the design?
- Font weights that are applied to textSans as a design feature - how do we handle these?
- `Strong` having font-weight applied directly - should we apply this globally?

We should work with the @guardian/design-system team to consolidate these (there's 75 font-weight applications in dotcom-rendering).

Here's a few examples (in code):

![image](https://user-images.githubusercontent.com/638051/61128362-9358a800-a4a9-11e9-9b36-064066f7e601.png)

Update button in liveblogs

![image](https://user-images.githubusercontent.com/638051/61128433-bb480b80-a4a9-11e9-97ce-0e9b335bc6b8.png)

Sidebar navigation

![image](https://user-images.githubusercontent.com/638051/61128460-cf8c0880-a4a9-11e9-92b7-4ffe05940270.png)

Standfirst
![image](https://user-images.githubusercontent.com/638051/61128775-c485a800-a4aa-11e9-9fe5-f9af9fc41f95.png)

Byline
![image](https://user-images.githubusercontent.com/638051/61128788-cc454c80-a4aa-11e9-98e9-84a522272a2e.png)

Article body
![image](https://user-images.githubusercontent.com/638051/61128811-dbc49580-a4aa-11e9-88ab-e9df04a28afa.png)

And so on...

**Comment by jamesgorrie** [comment]
Pasteup is now deprecated
