### ISSUE TITLE
Add pasteup to Github package registry?

### ISSUE THREAD

**Issue by gtrufitt** [guardian/dotcom-rendering#655]
https://help.github.com/en/articles/about-github-package-registry

@guardian/design-system @guardian/dotcom-platform

**Comment by gtrufitt** [comment]
Note, don't know if this is the best place to be adding questions like this that are shared between the teams (probably not) so let me know!

**Comment by SiAdcock** [comment]
Given that we're probably migrating to the Design System's component library, perhaps we should leave this in their capable hands? 😄

**Comment by gtrufitt** [comment]
I, err, can't remember why this felt like a good idea. Maybe something to do with deployment but there are tools with the Github Actions that might make that easier now too. I think I added this after trying to release Pasteup properly. 

It's an open question for the DS team though!

**Comment by gtrufitt** [comment]
I'll close on this repo :)
