### ISSUE TITLE
Log useAPI errors in a more fine-grained way

### ISSUE THREAD

**Issue by bryophyta** [guardian/dotcom-rendering#6550]
Currently we're logging 404 errors from the `useAPI` hook in Sentry, but because they all have the same error message/stack trace, they're all getting grouped together, which isn't very useful insofar as the root issues are with the endpoints being called, rather than in the `useApi` hook itself.

If we want to receive these errors, it would be good to differentiate their stack traces by including the base of the URL that's 404ing (not the whole path, because that would be too fine-grained).

https://github.com/guardian/dotcom-rendering/blob/1668217a8831d6edf93cda5f53d183fb64767b82/dotcom-rendering/src/web/lib/useApi.tsx#L8

**Comment by rhiannareechaye** [comment]
We are deprioritising this ticket by 'closing a not planned' - this won't delete the ticket and it will be searchable if the issue crops up again. Unfortunately we have over 130 health tickets to address in the web team and we can't address them all. With so many tickets we are potentially missing things that are high-impact so we're reorganising.
