### ISSUE TITLE
[EPIC] Fronts design review bugs

### ISSUE THREAD

**Issue by HarryFischer** [guardian/dotcom-rendering#6644]
## February 2023 review bugs

- [ ] Sub-epic: #7287

## January 2023 review bugs
- [x] #6922
- [x] #6992
- [x] Live kicker look off without colour. Harry to provide values
- [x] #6926
- [x] #6669
- [x] #6923
- [x] #6925
- [x] #6987
![Image](https://user-images.githubusercontent.com/20658471/205276017-b7cad0c6-a779-4c36-aa5d-e043d5e6b281.png)

- [x] #6981
Frontend pulls in this image: https://i.guim.co.uk/img/uploads/2019/02/13/Adrian_Chiles,_L.png?width=216&quality=85&auto=format&fit=max&s=29fb89891b3eb867991e3e6e8c3bb808
DCR is pulling in this: https://uploads.guim.co.uk/2019/02/13/Adrian_Chiles,_L.png
- [x] #6921
- [x] #6947
<img width="1361" alt="image" src="https://user-images.githubusercontent.com/20658471/205288545-fc7c8b67-2dca-4a55-ac9a-206784073175.png">

- [x] #6948
<img width="1335" alt="image" src="https://user-images.githubusercontent.com/20658471/205291287-3a3aec4f-83b8-4630-805e-1c9ac8a81561.png">

**Comment by bryophyta** [comment]
From February 20th Review:

- [ ] [FaciaPicker isn't checking for snapLink cards](https://github.com/guardian/frontend/issues/25922)

**Comment by rhiannareechaye** [comment]
I am closing this Epic ticket as we already have another design Epic ticket #7287 and the only remaining issue on this ticket #6669 has been closed
