### ISSUE TITLE
Support geo-targeted containers

### ISSUE THREAD

**Issue by AshCorr** [guardian/dotcom-rendering#6646]
![image](https://user-images.githubusercontent.com/21217225/205277461-d21340f4-3487-4ca4-af2a-77a0925eacc9.png)

I think we probably hide containers that aren't part of a users territory already but we don't provide any option for the user to switch territory

**Comment by alinaboghiu** [comment]
> I think we probably hide containers that aren't part of a users territory
yes we do

> we don't provide any option for the user to switch territory
I don't think we need/anyone wants us to do this. So will close for now.
