### ISSUE TITLE
General health & rota

### ISSUE THREAD

**Issue by jamesgorrie** [guardian/dotcom-rendering#6647]
### Snyk Vulnerabilities
- Address all critical
- Prioritise high vulnerabilities

### Sentry
- See if there are any new errors we should address
- See if there's any longstanding issues we should address

### `dependabot` PRs
Address any PRs

## Future themes
- [ ] ELK for warnings / errors
- [ ] Fastly log analysis, maybe Athena?
- [ ] ???

**Comment by bryophyta** [comment]
We spoke earlier in Future of WebX about processes around checking and responding to RFCs, so hopefully there will be some more general work on this coming soon. But, in the meantime does it make sense to add a new item here? i.e.

> Check for new RFCs in [discussions](https://github.com/guardian/dotcom-rendering/discussions) and [issues](https://github.com/guardian/dotcom-rendering/issues?q=is%3Aopen+label%3ARFC+sort%3Aupdated-desc).

**Comment by jamesgorrie** [comment]
RFCs feel like they should have a . I'll move this discussion elsewhere.

**Comment by ioannakok** [comment]
Moved the discussion here https://docs.google.com/document/d/1s2-YQmcleP3d2MQU3FCOHdH3pKn7sgyAZp-1x3KbD-A/edit#heading=h.h3437bw9f5m4 so closing this
