### ISSUE TITLE
Show video

### ISSUE THREAD

**Issue by AshCorr** [guardian/dotcom-rendering#6662]
Videos won't be supported until after the 1% launch, but once they are supported we should make sure that the "Show video" config allows toggling the video functionality on a card. I assume this means reverting to the original image if this is toggled off.

**Comment by rhiannareechaye** [comment]
@AshCorr would you mind adding a bit more detail to this - assume you mean after 1% launch but we'll need to revisit this for Fronts 100%?

**Comment by alinaboghiu** [comment]
> Videos won't be supported until after the 1% launch
I guess we decided this at some point (sorry I probably was not around)? My impression is they use this functionality for bigger events so maybe we should support it before we launch 1%? Or at least very soon after?
