### ISSUE TITLE
Reporting a comment is anonymous

### ISSUE THREAD

**Issue by ioannakok** [guardian/dotcom-rendering#6665]
In CODE reporting a comment seems to always be anonymous but if you add `dcr=false` to the url then your user is included as the reporter if you are logged in. (Very likely PROD has same behaviour - to investigate)

**Comment by bryophyta** [comment]
Update: From speaking to the mods it looks like this might be better tackled as part of a separate feature request. @rhiannareechaye to work out where this request would sit and update.

**Comment by JamieB-gu** [comment]
Identity looking into this.
