### ISSUE TITLE
Media cards missing play button and icon

### ISSUE THREAD

**Issue by bryophyta** [guardian/dotcom-rendering#6669]
Add play button and icon to media cards, to match Frontend.

Also:
- The play buttons should be changed to always be yellow, to match with apps (@HarryFischer can you confirm which yellow we should use here?)
- The media icon should still be determined by card pillar.

Frontend:
<img width="1325" alt="image" src="https://user-images.githubusercontent.com/20658471/205287541-b8825161-1187-4df6-b868-d3b1507a371d.png">
DCR:
<img width="1333" alt="image" src="https://user-images.githubusercontent.com/20658471/205287619-1cc1cbfd-0374-42e1-821f-a078e2c95931.png">

In the screenshot below (DCR on the left) the first card is also missing a picture. Is this part of the same issue or unrelated?
![image](https://user-images.githubusercontent.com/37048459/205651994-52744edd-6e5d-48e3-ae17-6035ea89638e.png)

**Comment by HarryFischer** [comment]
@bryophyta brandAlt.400 please. With a neutral.7 icon

**Comment by rhiannareechaye** [comment]
@OllysCoding you are assigned to this but I don't think this is in progress, would you mind if I unassigned you and moved into the 'to do'?

**Comment by OllysCoding** [comment]
This work was completed in https://github.com/guardian/dotcom-rendering/pull/6959, https://github.com/guardian/dotcom-rendering/pull/6956 & https://github.com/guardian/dotcom-rendering/pull/6953

I'll close this now @rhiannareechaye
