### ISSUE TITLE
Configure amiable to check onion-proxy AMI every 40 days

### ISSUE THREAD

**Issue by ioannakok** [guardian/dotcom-rendering#6687]
`onion-proxy` scheduled deployments are happening once a month because they cause downtimes. However, amiable is checking at earlier intervals whether the ami has been updated and sends email notifications for out-of-date AMI. Can we reconfigure amiable for this service to check its AMI at a larger interval?

**Comment by Georges-GNM** [comment]
Instead, have reduced the interval at which the service gets deployed; next deployment should occur on the 6th Jan, and then every 30 days after that.
