### ISSUE TITLE
Investigate PR workflow for snyk

### ISSUE THREAD

**Issue by Georges-GNM** [guardian/dotcom-rendering#6721]
Sounds like this was previously working but then removed or stopped - worth investigating if this can/should be re-instituted for dotcom repos

**Comment by VDuczekW** [comment]
first investigation then have an understanding of way forward - what is this ticket_ @OllysCoding flesh out please

**Comment by bryophyta** [comment]
@Georges-GNM to update

**Comment by Georges-GNM** [comment]
This regarded some snyk workflows, e.g. [this one which hasn't run in 9 months](https://github.com/guardian/frontend/actions/workflows/snyk-node.yml) which were actually replaced by other ones (e.g [this current snyk workflow](https://github.com/guardian/frontend/actions/workflows/snyk.yml)).

They're still appearing in the github actions history but it doesn't seem like there's a [way to delete/hide this](https://github.com/orgs/community/discussions/26256). This isn't actually an issue however, as our repos are indeed getting checked by snyk.
