### ISSUE TITLE
First related story can be the article itself

### ISSUE THREAD

**Issue by ioannakok** [guardian/dotcom-rendering#6735]
![Image](https://user-images.githubusercontent.com/19683595/206684469-b566caa0-aeef-47ab-9dc9-74f5bb534567.png)

Related content is fetched by tag (currently only for sports content) and sorted by page views (info coming from Ophan). This happens if the article we're reading happens to be the most read in the tag. In the client we need to filter out the article itself from the list of related content. Good place to start is [here](https://github.com/guardian/dotcom-rendering/blob/main/dotcom-rendering/src/web/components/OnwardsUpper.importable.tsx#L238-L240)

**Comment by VDuczekW** [comment]
will cose as not planned but if it comes up again we may have capacity
