### ISSUE TITLE
Related content can show content from non-primary tag

### ISSUE THREAD

**Issue by ioannakok** [guardian/dotcom-rendering#6737]
Example: This article's primary tag is "Russia": https://www.theguardian.com/world/2022/dec/08/brittney-griner-russia-us-prisoner-swap-viktor-bout.

However, when the first row of onwards was showing "Related content" the client made this request https://api.nextgen.guardianapps.co.uk/popular-in-tag/sport/us-sport.json?dcr=true&exclude-tag=tone/advertisement-features fetching `sports-us` related content.

This is happening because: 
1. The article has both tags `world/russia` and `sport/us-sport`: https://www.theguardian.com/world/2022/dec/08/brittney-griner-russia-us-prisoner-swap-viktor-bout.json?dcr 
2. the code looks for the first tag in pageTags that exists in [this allowlist](https://github.com/guardian/dotcom-rendering/blob/main/dotcom-rendering/src/web/components/OnwardsUpper.importable.tsx#L19) and fetches the content.

Can we verify the first tag of an article is the primary tag? If yes, is this the only tag we should take into account for related content?

**Comment by VDuczekW** [comment]
will not plan to do - but will open up again if it becomes more urgent
