### ISSUE TITLE
Investigate why CLS has gone up

### ISSUE THREAD

**Issue by ioannakok** [guardian/dotcom-rendering#6792]
![Image](https://user-images.githubusercontent.com/19683595/207894169-e77fd488-af2b-483c-88bc-f0541ca5a66f.png)

https://metrics.gutools.co.uk/d/oi0YcYI4k/web-vitals?orgId=1&refresh=1d

**Comment by VDuczekW** [comment]
to be looked at via Q4 OKR observability work
