### ISSUE TITLE
Investigate why JS has gone up

### ISSUE THREAD

**Issue by ioannakok** [guardian/dotcom-rendering#6793]
![Image](https://user-images.githubusercontent.com/19683595/207894582-1037a376-f172-4587-8cdc-6e99f1f17b44.png)

https://app.speedcurve.com/guardian/webx/favorite/?cs=lg&d=30&db=51598&dc=2&de=1&df=%7B%7D&ds=1

**Comment by VDuczekW** [comment]
will address/review via our OKR observability work
