### ISSUE TITLE
Show captions in quiz atoms images

### ISSUE THREAD

**Issue by ioannakok** [guardian/dotcom-rendering#6795]
Currently captions in quiz atoms images do not show even though the quizzes tool allows them. This ticket is to add support for them in DCR.

https://www.theguardian.com/tv-and-radio/2022/oct/21/doctor-who-quiz-can-you-tell-your-sontarans-from-your-skithra
https://quizzes.gutools.co.uk/quiz/6cbf0860-57cf-4c57-87fd-59e43f8f6754/question/1

Note: They weren't supported in frontend either: https://www.theguardian.com/tv-and-radio/2022/oct/21/doctor-who-quiz-can-you-tell-your-sontarans-from-your-skithra?dcr=false

**Comment by VDuczekW** [comment]
@rhiannareechaye go back to CP re this - we may want to address this, when we look at the quizzes and puzzles at point of migration and maybe close as not planned for now
