### ISSUE TITLE
Can we reduce further the DCR artefact?

### ISSUE THREAD

**Issue by ioannakok** [guardian/dotcom-rendering#6804]
#### Background

We recently found ourselves in a position where DCR instances were very close to using all their disk space (~99.4%). https://github.com/guardian/dotcom-rendering/pull/6770 reduced the artefact to less than 40% of its original size.

#### Task
Investigate whether we can reduce the artefact even further. Audit needed packages for PROD, currently still 1.3GB are shipped in the artefact. We probably only need pm2 and a handful of other things.

**Comment by VDuczekW** [comment]
also a low priority but for the backlog

**Comment by ioannakok** [comment]
And a PR that has already reduced it: https://github.com/guardian/dotcom-rendering/pull/6770

**Comment by rhiannareechaye** [comment]
As per our triaging, this is a high impact issue so ideally we should look at it

**Comment by rhiannareechaye** [comment]
I am closing this ticket as it Ioanna has pasted a PR that has already reduced it above

**Comment by AshCorr** [comment]
https://github.com/guardian/dotcom-rendering/pull/7499 has been merged.
