### ISSUE TITLE
[EPIC] Address high vulnerabilities

### ISSUE THREAD

**Issue by ioannakok** [guardian/dotcom-rendering#6848]
High vulnerabilities are planned to be zero by end of Q4. This is an epic issue to track this piece of work.

#### How to pick up a ticket
1. Before picking up a task please read the [DevX recommendations for Snyk](https://github.com/guardian/security-hq/blob/05f31deb4d8e3d44a6918253e394b321e1aad9bb/hq/markdown/snyk.md). Please note that for now we are focusing on Snyk issues other than "Deserialization of Untrusted Data: Jackson Databind". 
2. Assign yourself to one of the tasks below
3. Check the project in the [Snyk dashboard](https://app.snyk.io/org/guardian-dotcom-n2y/projects)
4. Start fixing issues!

- [ ] #6850
- [ ] #6851
- [ ] #6852
- [x] #6853
- [x] #6854
- [x] #6855
- [x] #6856
- [x] #6857
- [ ] #6858
- [ ] #6859
- [ ] #6860
- [ ] #6861
- [ ] #6862
- [ ] #6863
- [ ] #6864
- [ ] #7122
- [x] #7123

**Comment by bryophyta** [comment]
This is still being worked on, with @ioannakok coordinating. Mobbing sessions are planned, and perhaps a mobbing week beginning 27th February.

**Comment by jamesgorrie** [comment]
These have a;; been completed - fantastic work 🥳
