### ISSUE TITLE
Investigate expiring experiments email alerts

### ISSUE THREAD

**Issue by VDuczekW** [guardian/dotcom-rendering#6866]
The sellByDate on the TableOfContents experiment expired without any email being sent.

James: "This makes me think the emails are down for some reason - we should investigate."

**Comment by VDuczekW** [comment]
to be triaged in next session with James

**Comment by VDuczekW** [comment]
emails are working - flesh out this ticket @jamesgorrie

**Comment by rhiannareechaye** [comment]
Closing this ticket as it's been around for 4months with minimal detail
