### ISSUE TITLE
DCR fonts should support container anchors navigation

### ISSUE THREAD

**Issue by paperboyo** [guardian/dotcom-rendering#6895]
Roseal. Compare:
https://www.theguardian.com/uk#ukraine-invasion
and
https://www.theguardian.com/uk?dcr#ukraine-invasion
(unless it’s the corollary of having a `?` there… in which case, apologies and pls close)

We should only ever have more of these clever URL hack, not less :-).

**Comment by mxdvl** [comment]
Indeed, in `frontend`, the id `#ukraine-invasion` is set on the containing section. In DCR there’s instead a UUID on the section’s first child: `01c94be3-f4f1-45ee-976e-b0fcd384cc16`.

**Comment by paperboyo** [comment]
Just like we are better than sites who use UUID in URL, we should always strive to be human-readable (see how we made in-body H2 anchors human-readable, hence – human predictable: 👏 )

**Comment by AshCorr** [comment]
Fixed in #7108 :)
