### ISSUE TITLE
Day of the week should be black, currently red in DCR

### ISSUE THREAD

**Issue by bryophyta** [guardian/dotcom-rendering#6926]
Part of #6644 

I assume that 'Wednesday' in the top corner of this screenshot is what you were referring to @HarryFischer -- is that correct?

Frontend:
<img width="1365" alt="image" src="https://user-images.githubusercontent.com/37048459/211787754-38e4d95c-5954-416c-9893-1ba824be81b3.png">

'Wednesday' is currently in red on DCR.

**Comment by HarryFischer** [comment]
Yep exactly

**Comment by ioannakok** [comment]
Closed by https://github.com/guardian/dotcom-rendering/pull/6934
