### ISSUE TITLE
Add 'external link' icon to Card headlines

### ISSUE THREAD

**Issue by bryophyta** [guardian/dotcom-rendering#6942]
On Frontend, cards which link to external pages have an 'external link' icon in their headline:

<img width="254" alt="image" src="https://user-images.githubusercontent.com/37048459/212049500-20173f37-138a-4835-ba12-20ffa9d7a8c6.png">

It looks like we could use the `cardStyle` value passed from Frontend to target these cards. For this card the style is `ExternalLink`. It's passed as part of the card model, although it would need to be added to the `DCRFrontCardType` (and passed via `enhanceCard`).

## Questions
1. Is the `cardStyle` value the right way to determine external links? Could we potentially just look at the URL for the link instead? (The latter might work more generally, e.g. for sublinks, and would create less coupling; but do we always want the icon for external links?)
2. Should we use the existing icon used by Frontend, or do we have another one (e.g. in Source) that we should use moving forward? (cc. @HarryFischer)
3. Currently the external link doesn't open in a new window, but (imo) this is expected behaviour for links that are explicitly marked as external on the web, using this icon. Should we open them in a new tab? (i.e. with `target="_blank"` and the appropriate `rel` attributes)

**Comment by HarryFischer** [comment]
@bryophyta We have this icon 
https://theguardian.design/2a1e5182b/p/3892a2-icons/i/10591792

Also agree it should open in new tab

**Comment by paperboyo** [comment]
This reminds me I always wondered if we should not be doing the same for in body (and other) links.

**Comment by bryophyta** [comment]
As part of the slashes removal work, we've been asked to move the icon to the end of the headline, instead of the end of the kicker. If that presents any trouble given the work that's been done so far then I can open this as a separate issue?

**Comment by Georges-GNM** [comment]
Don't think that's any trouble! I'll give it a go.

**Comment by rhiannareechaye** [comment]
Closing as done
