### ISSUE TITLE
Can't update to `"@guardian/libs": "11.1.2"`

### ISSUE THREAD

**Issue by joecowton1** [guardian/dotcom-rendering#6961]
## What's issue?
DCR has got itself into something of types based bind, where it's impossible to do a simple package update.

## Why?
DCR uses `"@types/react": "^18"` where the vast majority of packages within it use `"@types/react": "^17"`.  This works fine until you delete the `package.lock` and run `yarn` at which point TSC finds a whole load of type mismatches.  My hunch is that we've had the same `package.lock` for a long time and this has masked this issue.

In order to bump libs, we need to update 

## How did we get here?
`"@types/react": "^18"` was introduced [by this PR](https://github.com/guardian/dotcom-rendering/pull/4650). We could always just use a different story format and roll this back, but...

What makes this difficult is that some packages rely on `"@types/react": "^18"`,  `"react-google-recaptcha": "^2.1.0"` for example. There's no earlier version of this package that uses `"@types/react": "^17"`.

## How do we fix it?
There are a couple of solutions to this:
- use type `resolutions` to coerce all packages to use `"@types/react": "^17"`
- bump react itself to version 18 and update all other packages to use the latest versions

The problem with resolutions is they're very much a sticking plaster and often lead to issues later, however, given we're pretty much stuck as it stands this might be the only way out in the short term until we're ready to bump to React 18 across all platforms and packages?

**Comment by mxdvl** [comment]
React is on v18.2 now
