### ISSUE TITLE
Apple News shows incorrect timestamp on AMP articles

### ISSUE THREAD

**Issue by AshCorr** [guardian/dotcom-rendering#6976]
On site:
<img width="594" alt="Screen Shot 2023-01-17 at 11 53 08 am" src="https://user-images.githubusercontent.com/21217225/212904772-b2ae74d9-557c-46dc-88fe-ef5ffa55e79f.png">

Apple News:
![Screen Shot 2023-01-17 at 10 29 38 am](https://user-images.githubusercontent.com/21217225/212904763-7269cd0a-c5d1-4c88-bb4d-f1e191137752.png)
Similarly on Apple News, [the breaking news story](https://www.theguardian.com/australia-news/2023/jan/17/liberal-senator-jim-molan-dies-aged-72-after-sudden-decline-in-health) on the same topic appears to have happened at 11pm Monday night instead of 10am Tuesday morning.

![amp-search](https://user-images.githubusercontent.com/21217225/212904703-b8647004-8e44-4f80-b90c-f2a7f00d76a8.jpeg)

To replicate the EST timestamp on desktop I had to use mobile search in Chrome via developer tools, before clicking through. But in mobile search via the Google app it's always EST for AMP.

https://amp.theguardian.com/australia-news/live/2023/jan/17/australia-news-live-floodwaters-floods-queensland-bruce-highway-rain-weather-climate-economy-jim-chalmers-wages-jobs-voice
If you just add 'amp.' to the start of today's live blog URL, it still correctly displays AEDT time on desktop

Obviously this isn't a good reader experience ever, but particularly not when our Australia news live blog is top of search. eg today if people opened it in AMP on mobile the most recent update showed as Monday 19.28 EST instead of Tuesday 11.28 AEDT. Many people wouldn't notice timezones immediately and, at least on stories, are more likely to think something is out of date than take account of the timezone indicator (applies to both AMP and AN)

I don't know what the timestamps are set to for Apple News in the US. Tom cc'd in case this would apply there as well.

It's been an ongoing issue for a long time, but I was just reminded of it today. In Australia, our AppleNews timestamps always show in UTC, and AMP timestamps always show in EST (US).

Could we look at fixing timestamps to show local time in Apple News and AMP?

**Comment by AshCorr** [comment]
My thoughts are that when Google or Apple News cache our AMP pages we render the page using whatever locale the crawler has used, which usually ends up being a US IP.

Looking at the AMP cache for one of our articles we're able to see the exact same issue occuring: https://amp-theguardian-com.cdn.ampproject.org/c/s/amp.theguardian.com/sport/live/2023/jan/17/australian-open-day-two-murray-v-berrettini-and-novak-djokovic-in-action-live

We probably need to be hydrating the publication date on client side if we need to show different timezones based on locale.

**Comment by ioannakok** [comment]
To be reviewed after AMP discussions

**Comment by rhiannareechaye** [comment]
We are deprioritising this ticket by 'closing a not planned' - this won't delete the ticket and it will be searchable if the issue crops up again. Unfortunately we have over 130 health tickets to address in the web team and we can't address them all. With so many tickets we are potentially missing things that are high-impact so we're reorganising.
