### ISSUE TITLE
Remove padding-left and -right on the cards at edge so they sit on the grid

### ISSUE THREAD

**Issue by ioannakok** [guardian/dotcom-rendering#6987]
## Issue

DCR fronts do not sit well in the [Guardian grid](https://theguardian.design/2a1e5182b/p/41be19-grids) in smaller break points.

| frontend | DCR |
|----------|-----|
| ![image](https://user-images.githubusercontent.com/19683595/216038357-2f0c2e52-f833-4f22-b713-b3c20eea3c98.png) | ![image](https://user-images.githubusercontent.com/19683595/216037799-57d58e99-88ea-4d8b-9251-4fd4c71a589e.png) |
| ![image](https://user-images.githubusercontent.com/19683595/216038178-368e44ba-cdf8-4d61-8afa-b650404348a4.png) | ![image](https://user-images.githubusercontent.com/19683595/216037935-ce26e512-6ed8-4656-9003-ba83fcbe695e.png) |

There was an [attempt](https://github.com/guardian/dotcom-rendering/pull/6993) to fix it without refactoring but we had to [revert](https://github.com/guardian/dotcom-rendering/pull/7044).

Inspired by the [work done in AR that implemented Guardian grid using CSS grid](https://github.com/guardian/dotcom-rendering/pull/4874) we aim to do the same for article layouts and fronts layout.

### Benefits
* It will be a lot easier to fix the current bug and manipulate the layouts in the future
* This will reduce layout shift, hence also contribute to the work the Open Journalism team does.  Here's an [interesting video](https://www.youtube.com/watch?v=7EKEav7Io5Y) that explains how and why.

**Comment by ioannakok** [comment]
Reopening as this was reverted: https://github.com/guardian/dotcom-rendering/pull/7044

**Comment by ioannakok** [comment]
This work is still in progress. An alternative to #7178 has been merged: https://github.com/guardian/dotcom-rendering/pull/7182 and @Georges-GNM with @mxdvl are working on the next PR(s)

**Comment by rhiannareechaye** [comment]
Can we mark this one as done @mxdvl?

**Comment by mxdvl** [comment]
Closed by #7195
