### ISSUE TITLE
Spike: investigate whether we need MAPI to pass requests to frontend

### ISSUE THREAD

**Issue by georgeblahblah** [guardian/dotcom-rendering#7059]
#### MAPI calls Frontend

If MAPI simply acts as a proxy for Frontend, we can achieve a lot of our goals with little downsides.

- We can use Frontends existing data model & CAPI implementation for passing data to DCR.
- Avoids much change in Apps as we may be able to continue using existing endpoints in MAPI.

But it does come with the downside that we're introducing an extra jump in our request flow which will increase TTFB on un-cached requests and introduce additional complexity.

We also need to consider that we would likely need a new/different way to access Frontend, we'll speak about this later.

#### MAPI calls DCR

As mentioned previously, Apps already does an API call to MAPI which we can potentially "hijack" for DCAR.

Ideally MAPI would conform with DCRs existing model, I imagine we want to re-use as much of DCRs data model as possible in DCAR. If this is the case then MAPI would have to duplicate a lot of the work that Frontend is already doing when it comes to constructing the data model from CAPI.

#### Apps calls Frontend

The DCR Apps endpoint is currently available through our regular frontend routes by adding `?dcr=apps` to the URL, so in theory the app could request a page via something like https://www.theguardian.com/technology/2023/mar/30/vulkan-files-leak-reveals-putins-global-and-domestic-cyberwarfare-tactics?dcr=apps

However, this would involve going through our Web fastly configuration which will be doing a lot of things that we potentially don't want such as handling experiments, cookies, WAF etc.

#### Apps calls DCR

No-go, we don't want DCR to be exposed to the internet, this would create more problems than it solves. 

## My thoughts (Ash)

We should have Apps call MAPI which calls Frontend, this avoids any of the complications that might arise from the Web VCL as we'll be using the existing MAPI VCL settings which we know work already.

If needs be we can switch to a new route in future, but for the time being this seems like it is the safest option for rendering DCR in Apps.

**Comment by georgeblahblah** [comment]
We'll write this up as an ADR in DCR

**Comment by VDuczekW** [comment]
we will use the dotcom service  - raise a ticket for the piece of work

**Comment by rhiannareechaye** [comment]
Closing this ticket as we've decided to attempt passing requests to Frontend directly
