### ISSUE TITLE
Spike: dark mode support

### ISSUE THREAD

**Issue by georgeblahblah** [guardian/dotcom-rendering#7071]
https://github.com/guardian/dotcom-rendering/pull/7734

**Comment by rhiannareechaye** [comment]
@ajbreuer I don't think there's much that needs to be done here from a design perspective, but @georgeblahblah please could you make sure you look Alex in when you look at this ticket in case there is

**Comment by JamieB-gu** [comment]
Also #7766.

**Comment by JamieB-gu** [comment]
This issue was to conduct a spike, which I think we completed with the work in #7734 mentioned above, and finally the proposal in #7766. I'm going to close this and use #8729 to track the actual work to implement dark mode.
