### ISSUE TITLE
Bridget Navigation Service (Apps Footer)

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#7083]
We'd like to add support for the Bridget [`Navigation`](https://github.com/guardian/bridget/blob/main/thrift/native.thrift#L127-L130) service in DCR. This work will likely involve building the apps footer, as interaction with the footer is powered by this service.

**Comment by georgeblahblah** [comment]
Footer implemented in https://github.com/guardian/dotcom-rendering/pull/8611 but I hadn't realised there was prior work here! Might be worth seeing how the approach differed and making any changes, it looks like we came up against similar questions.

**Comment by rhiannareechaye** [comment]
I'm going to close this ticket - definitely helpful to keep it as a record but given we're aiming to close off all bridget work this sprint, I'd like to make sure the board is reflective of the 'must-do' work!
