### ISSUE TITLE
Bylines (Bridget Notifications Service)

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#7090]
We'd like to add support for the Bridget `Notifications` service in DCR. This is used for the follow/un-follow button near the top of articles, which allows users to sign up for notifications for individual contributors.

A pre-requisite for this is probably the byline refactor described in #7387.

**Comment by rhiannareechaye** [comment]
It's worth noting that the Personalisation team have plans in this area so we may not need to do this exactly: https://docs.google.com/presentation/d/1hP6kXDEmyOEdwB6vnBDkd59JcSecmPlnMCnIo7aN1EU/edit#slide=id.gde111297c9_0_3486
