### ISSUE TITLE
Use `bucketSsmLookup=true` in DCR and frontend `riff-raff.yaml`

### ISSUE THREAD

**Issue by ioannakok** [guardian/dotcom-rendering#7098]
To get rid of this warning from our deployments:

![Image](https://user-images.githubusercontent.com/19683595/216001563-7464f025-b18a-4439-b1c4-493868484288.png)

**Comment by bryophyta** [comment]
This will be closed by:

- [ ] https://github.com/guardian/dotcom-rendering/pull/7170
- [ ] https://github.com/guardian/frontend/pull/25895
