### ISSUE TITLE
which 'other' Container need supporting

### ISSUE THREAD

**Issue by VDuczekW** [guardian/dotcom-rendering#7109]
We have lots of variations of containers
Currently we support a small % of these, but we need to up the volume of container types that we support

**Comment by VDuczekW** [comment]
Pick a selection of container cards

**Comment by bryophyta** [comment]
There are a number of containers that are not marked as being supported in [faciaPicker](https://github.com/guardian/frontend/blob/85e740d5a95f0e13306d71058590568253e5c2da/facia/app/services/dotcomrendering/FaciaPicker.scala#L16), but which we don't have tickets open for.

Are some of these containers still incomplete? If so, can we open GH issues for the remaining work needed to support them?

**Comment by rhiannareechaye** [comment]
We have raised tickets for every container type so closing this
