### ISSUE TITLE
Increase in Core Web Vitals

### ISSUE THREAD

**Issue by ioannakok** [guardian/dotcom-rendering#7243]
In today's dashboard's check we noticed an increase in all CVW. To investigate:

https://metrics.gutools.co.uk/d/oi0YcYI4k/web-vitals?orgId=1&refresh=1d
![Image](https://user-images.githubusercontent.com/19683595/220090499-741e5a94-1649-4ec0-8cf0-b3f27daa0bcc.png)

**Comment by bryophyta** [comment]
This seems to have resolved itself.
