### ISSUE TITLE
Align treats to bottom of the container

### ISSUE THREAD

**Issue by bryophyta** [guardian/dotcom-rendering#7291]
Treats should be aligned to the bottom card of the main container, rather than the 'show more' button. And it should stay in place if new 'show more' cards are loaded below the main container (i.e. it shouldn't align to the bottom of the 'more' cards)

<img width="570" alt="image" src="https://user-images.githubusercontent.com/37048459/221593435-071611c8-405f-4491-8135-b86ce3aa60cb.png">

**Comment by VDuczekW** [comment]
it's broken in front end and dcr

**Comment by rhiannareechaye** [comment]
https://github.com/guardian/dotcom-rendering/pull/7564
