### ISSUE TITLE
Unstyled text in 'description' on crosswords container

### ISSUE THREAD

**Issue by bryophyta** [guardian/dotcom-rendering#7292]
Seems likely that this applies to other containers, too, but the use of links in a container description is less common elsewhere?

The first sub-heading looks like it's styled okay, but the smaller sub-text (i.e. in first container, not in second container, in screenshot) is not styled correctly.

<img width="1208" alt="image" src="https://user-images.githubusercontent.com/37048459/221594557-17eaef32-df0e-456e-aaa2-9d3c84b32105.png">

**Comment by rhiannareechaye** [comment]
High priority
