### ISSUE TITLE
Analysis Byline Layout Bug With Multiple Contributors

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#7314]
## Bug

In AR, when there are multiple contributors on an analysis piece, each contributor appears on a new line. This causes problems when the number of contributors goes above two.

| Article | AR | DCR |
| - | - | - |
| https://www.theguardian.com/politics/2016/apr/06/the-cameron-network-inherited-wealth-and-family-companies  | ![several-contributors] | ![dcr-several-contributors] |
| https://www.theguardian.com/business/2023/feb/26/bitter-harvest-for-some-in-a-global-economy-changed-by-russias-war | ![two-contributors] | ![dcr-two-contributors] |

[several-contributors]: https://user-images.githubusercontent.com/53781962/221907576-565d780f-b00f-40df-adcb-fa1578150910.jpg
[two-contributors]: https://user-images.githubusercontent.com/53781962/221907583-e695b5d1-5483-4aba-89f1-f16dcdb2e138.jpg
[dcr-several-contributors]: https://user-images.githubusercontent.com/53781962/221908211-e016ce85-4f83-4708-a7e2-0e2190dba5c0.jpg
[dcr-two-contributors]: https://user-images.githubusercontent.com/53781962/221908218-796d0768-42e1-4268-be2d-e7b7be513831.jpg

This seems to happen because the byline is laid out using a column-based flexbox, to allow for the following scenario:

![byline](https://user-images.githubusercontent.com/53781962/221909763-6f15a8f7-dace-44a9-a9db-65821193cdec.jpg)

The bug doesn't occur on DCR, because there is some additional logic to avoid breaking the byline onto multiple lines (i.e. removing the flexbox rule) when there's more the one contributor.

## Possible Solutions

1. Keep the contributors on multiple lines, but adjust the commas so that they appear at the end of each line, rather than on a new line.
2. Implement something similar to DCR, where the layout switches to inline when there are multiple contributors.

**Comment by alinaboghiu** [comment]
https://github.com/guardian/dotcom-rendering/issues/9876
