### ISSUE TITLE
Get traffic stats and AWS resources for AR

### ISSUE THREAD

**Issue by jamesgorrie** [guardian/dotcom-rendering#7317]
We'll need this to be able to ensure that we reserve the right amount of resource in AWS.

Knowing what we already use in AWS would be even more useful.

**Comment by JamieB-gu** [comment]
AR's EC2 resources are defined in CDK. There are two stacks, `mobile` and `mobile-preview`, and two stages, `CODE` and `PROD`. This multiplies together to get four services (four ASGs):

- mobile CODE: https://github.com/guardian/dotcom-rendering/blob/97c50fa4e43e23f3d81c416456980dc3a75152d7/apps-rendering/cdk/bin/cdk.ts#L12-L15
- mobile PROD: https://github.com/guardian/dotcom-rendering/blob/97c50fa4e43e23f3d81c416456980dc3a75152d7/apps-rendering/cdk/bin/cdk.ts#L26-L29
- mobile-preview CODE: https://github.com/guardian/dotcom-rendering/blob/97c50fa4e43e23f3d81c416456980dc3a75152d7/apps-rendering/cdk/bin/cdk.ts#L40-L43
- mobile-preview PROD: https://github.com/guardian/dotcom-rendering/blob/97c50fa4e43e23f3d81c416456980dc3a75152d7/apps-rendering/cdk/bin/cdk.ts#L54-L57

All of the above use `t4g.small` instances: https://github.com/guardian/dotcom-rendering/blob/97c50fa4e43e23f3d81c416456980dc3a75152d7/apps-rendering/cdk/lib/mobile-apps-rendering.ts#L59-L62

This results in **9 `t4g.small`** instances under current load.
