### ISSUE TITLE
Discuss CSS for `interactive` embeds with Design

### ISSUE THREAD

**Issue by bryophyta** [guardian/dotcom-rendering#7325]
Some interactives/thrashers look broken on DCR because they rely on global styling which is present in Frontend but not on DCR. (See e.g. the screenshots in [this PR adding thrasher support to DCR](https://github.com/guardian/dotcom-rendering/pull/5182).

## Small bugs?

Some of these bugs seem pretty small and common, e.g. styling of links and buttons:

<img width="1342" alt="image" src="https://user-images.githubusercontent.com/37048459/222493006-611b2ca6-2d87-4db9-a80d-b83f727549b8.png">
<img width="1325" alt="image" src="https://user-images.githubusercontent.com/37048459/222493086-225eec4f-d189-4482-8ae7-85c0cf59e742.png">

If these smaller bugs do have a shared cause, can we either add the relevant CSS to the thrasher template, or possibly to DCR? Or is there some deeper issue with how the inline CSS is interacting with emotion etc.?

## Larger bugs?

Some interactives/thrashers look more broken and presumably have more complex fixes. Can we find a list of the most important ones for us to support, so that we could start fixing those which will have the most impact?

**Comment by rhiannareechaye** [comment]
@DanielCliftonGuardian please put an update on next steps

**Comment by AshCorr** [comment]
Hey @HarryFischer 

We've compiled a list of Thrashers here -> https://gist.github.com/AshCorr/399c8ef7758ccb6b1395077e73b08caf

1st column is the container ID, and 2nd column is the Front URL. Since a container can be on multiple fronts we only include unique container ID's and the first front its found on.

**Comment by ioannakok** [comment]
This PR adds a list of unsupported thrashers in `FaciaPicker`: https://github.com/guardian/frontend/pull/26126
