### ISSUE TITLE
Onward Content Design Refactor

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#7390]
Make the onward content cards on dotcom look like the onward content cards on AR. We may want to consider doing this on fronts too?

**Comment by rhiannareechaye** [comment]
Requires product/UX input. Needed for Beta test new milestone

**Comment by rhiannareechaye** [comment]
We'll aim to get the design work completed by the 5th of June

**Comment by ajbreuer** [comment]
![Image](https://github.com/guardian/dotcom-rendering/assets/1144827/4fb65702-7a3d-4a23-992b-232feb9652d0)

New design for onward content
https://www.figma.com/file/R5kfAuzgovB4lVlCKKyCww/DCAR-Anomalies-and-App-preferences?type=design&node-id=1%3A2&mode=design&t=2S43v3wbca1MOi8E-1

**Comment by ajbreuer** [comment]
@alinaboghiu Design added
