### ISSUE TITLE
Support The Guardian Button Under Ads

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#7393]
This button exists on the app but not on dotcom. What do we want to do about this?

**Comment by rhiannareechaye** [comment]
I will speak to the reader revenue team about this

**Comment by ajbreuer** [comment]
@JamieB-gu I did a little new design fro this if we end up having it universal across dotcom and app

**Comment by rhiannareechaye** [comment]
Apps has a reader revenue CTA, Web doesn't - it would be nice to have a solution that works for both

See Figma file here of proposed design: https://www.figma.com/file/R5kfAuzgovB4lVlCKKyCww/DCAR-Anomalies-and-App-preferences?type=design&node-id=178-65&mode=design&t=re3n3k76lSdzZA2e-0

Note that we might need to run this past Supporter Revenue as an FYI
