### ISSUE TITLE
React 18 Upgrade: AR

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#7415]
`atoms-rendering` and the Source libraries must be upgraded first. An upgrade guide is available here: https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html

**Comment by rhiannareechaye** [comment]
We're going to look at these on Wednesday and Thursday 26th & 27th (we're going to hold all the applications till then so that we can use the new versions of the libraries)
