### ISSUE TITLE
React 18 Upgrade: DCR

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#7416]
`atoms-rendering`, `discussion-rendering` and the Source libraries must be upgraded first. An upgrade guide is available here: https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html

DCR uses Preact and `preact-compat`.

We should create a branch to allow other teams to test integration before we merge this change. Speak to @tomrf1 when this branch is ready.

@joecowton1 did some preliminary testing in #7275.

**Comment by rhiannareechaye** [comment]
We're going to look at these on Wednesday and Thursday 26th & 27th (we're going to hold all the applications till then so that we can use the new versions of the libraries)
