### ISSUE TITLE
React 18 Upgrade: discussion-rendering

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#7418]
This must be done before we can upgrade DCR. An upgrade guide is available here: https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html

**Comment by rhiannareechaye** [comment]
Olly to hold off merging this till Tuesday

**Comment by OllysCoding** [comment]
This work was completed in https://github.com/guardian/discussion-rendering/pull/695
