### ISSUE TITLE
`StandardLayout` Component For Apps

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#7421]
Get a `StandardLayout` component working for apps, either by reusing the existing web component or by creating a new one.

**Comment by Georges-GNM** [comment]
**Combined component**: I've got a draft PR [here](https://github.com/guardian/dotcom-rendering/pull/7549)

This adds a `renderingTarget` props to the StandardLayout component (currently in src>web>layouts) and uses it to establish an `isWeb` boolean, which then gets checked ahead of web-only elements, e.g.:

```
{isWeb && (
				<div data-print-layout="hide" id="bannerandheader">
					{renderAds && (
						<Stuck>
							<Section ...
``` 

The same type of logic could be used for app-specific or elements which need to be on both web and apps: 

```
{isWeb && (
	<div>
	        <p>Web test</p>
	</div>
)}
{isApps && (
	<div>
		<p>Must be app test</p>
	</div>
)}
{isWeb && isApps && (
	<div>
		<p>Gotta be on both</p>
	</div>
)}
```

**Comment by OllysCoding** [comment]
**Duplicated Component**: I have a draft PR available here - https://github.com/guardian/dotcom-rendering/pull/7559

**Comment by JamieB-gu** [comment]
We've had a discussion (@OllysCoding @georgeblahblah @Georges-GNM and myself) and decided we're going to try the combined approach demonstrated in #7549. We will branch off the branch created by @Georges-GNM and open a fresh pull request in order to keep the original branch and PR intact for reference. We may try to go further and also combine the `ArticlePage` and `DecideLayout` components as part of this.

If it turns out that, over time, the combined approach runs into problems, we feel it shouldn't be too difficult to revisit this and switch to the duplicated approach if necessary.
