### ISSUE TITLE
Euro 2024: Badge & Logo Setup

### ISSUE THREAD

**Issue by AshCorr** [guardian/dotcom-rendering#7436]
Once a logo is ready we need to add it to https://github.com/guardian/frontend/tree/main/static/src/inline-svgs/badges and then update our competition settings again in https://github.com/guardian/frontend/blob/main/sport/app/football/feed/Competitions.scala

**Comment by AshCorr** [comment]
cc @HarryFischer will you be creating the logo this time?

**Comment by mxdvl** [comment]
Badges no longer need to be created as we are moving away from them.

**Comment by HarryFischer** [comment]
Think you'll still need a badge for middle of spider chart @mxdvl
