### ISSUE TITLE
Euro 2024: Group tables and Spider diagram

### ISSUE THREAD

**Issue by AshCorr** [guardian/dotcom-rendering#7437]
Once the qualifiers are over the winners of each group will be pitched against eachother. We should have a spider diagram to show the pairings of winners from each group.

## Interactives

The [footbal atoms collection](https://github.com/guardian/interactives/tree/main/atoms/webex/football-atoms-collection) contain the relevant projects to display reusable components.

---

## Frontend

This can be configured in https://github.com/guardian/frontend/blob/main/sport/app/football/model/CompetitionStages.scala#L128

You can look at UEFAs [site](https://www.uefa.com/euro2024/fixtures-results/bracket/) for details on the games (Look at the Round of 16, Semi final, and Final stages, these are all the stages that should be included in the spider)

The spider diagram can be a bit finicky, we usually don't get it quite right the first time its setup for any tournament. Don't worry if its not quite right the first try, usually its hard to tell if its broken or not until the "Round of 16" stage actually starts, just be ready to fix it if it does break.

**Comment by AshCorr** [comment]
The spider diagram needs to be ready by the time the "Round of 16" stage starts which isn't till 29th of June, 2024.

**Comment by mxdvl** [comment]
This is now available on https://www.theguardian.com/football/euro-2024.
