### ISSUE TITLE
Euro 2024: Interactives

### ISSUE THREAD

**Issue by AshCorr** [guardian/dotcom-rendering#7438]
Once the competition has been setup we need to create the interactives used in articles and on fronts to track fixtures.

The code for these interactives can be found in https://github.com/guardian/football-interactive-atoms.

- [ ] Update the path in [config.json](https://github.com/guardian/football-interactive-atoms/blob/main/config.json#L4) to use the Euro 2024 start date.
- [ ] Update ALL of the embed urls used in the individual atom [config.json](https://github.com/guardian/football-interactive-atoms/blob/main/atoms/group-table-a-b/config.js#L2) (theres multiple atoms to update)
- [ ] Check if theres any special requirements for this tournament. Sometimes we need to remove the "Show more fixtures" button.

**Comment by mxdvl** [comment]
Spider diagram done in #7437
