### ISSUE TITLE
Euro 2024: Golden Boot

### ISSUE THREAD

**Issue by AshCorr** [guardian/dotcom-rendering#7439]
A golden boot page needs to be setup for the 2024 euros, similar to https://www.theguardian.com/football/ng-interactive/2021/jul/07/euro-2020-golden-boot-top-goalscorers-game-by-game

Usually the Visuals team create this page, not us, but we tend to get asked about it a lot. This ticket is to help track the progress.

**Comment by alinaboghiu** [comment]
From @JamieB-gu:  "I think the golden boot data for this should be available here when the time comes: https://mobile.guardianapis.com/sport/football/competitions/751/golden-boot"

**Comment by mxdvl** [comment]
@shesah to speak with MSS @guardian/mss-developers and Visuals about whether the endpoint above is working for the current competition

**Comment by alinaboghiu** [comment]
MSS to do 
- [ ] https://theguardian.atlassian.net/browse/LIVE-6629
- [ ] https://theguardian.atlassian.net/browse/LIVE-6630

**Comment by mxdvl** [comment]
Working as expected: https://www.theguardian.com/football/ng-interactive/2024/jun/10/euro-2024-golden-boot-top-goalscorers-game-by-game
