### ISSUE TITLE
Investigate performance benefits we can get out of DCR's infrastructure

### ISSUE THREAD

**Issue by jamesgorrie** [guardian/dotcom-rendering#7441]
# Multi-threading
This would allow us to investigate whether we should/could scale vertically and reduce the amount of servers we have in our fleet. 

This would also be much helped by having a different stack for each endpoint as their need is very different as outlined in @AshCorr's [RFC](https://github.com/guardian/dotcom-rendering/issues/7316).

**Comment by alinaboghiu** [comment]
We have addressed this as part of our wider work to break up the app into separate stacks
