### ISSUE TITLE
Change to the Australia Logo

### ISSUE THREAD

**Issue by rhiannareechaye** [guardian/dotcom-rendering#7447]
We have Guardian Australia's 10-year anniversary landing on May 27. We're keen to explore the feasibility of changing 'The Guardian' logo on the website accordingly - similar to what was rolled out during the G200 celebrations.

It'd be pretty light touch - very similar to the '200' that was woven into the header logo during the 200th anniversary:

![Image](https://user-images.githubusercontent.com/93542262/226420771-ad31b834-8b95-47ce-8762-fbfc0eb7f9d9.png)

The creative brief for the work is currently sitting with OLIVER (the creative studio). 'Happy path' timeline is as follows:
Creative (i.e. tweaked logo) finalised and with you by March 24

Set logo live in w/c April 24

**Comment by alinaboghiu** [comment]
Assuming we're no longer doing this since the anniversary passed
