### ISSUE TITLE
Don't show labs content on AdFree fronts

### ISSUE THREAD

**Issue by bryophyta** [guardian/dotcom-rendering#7467]
DCR currently shows Labs content when `renderAds` is false:

- [ ] Filter out Labs containers on ad free requests
- [ ] Question: Is it possible for labs cards to show up in non-labs containers? If so, presumably we need to filter those out, too.

**Comment by alinaboghiu** [comment]
resolved in https://github.com/guardian/dotcom-rendering/pull/7813
