### ISSUE TITLE
Fronts migration: release strategy for network fronts

### ISSUE THREAD

**Issue by jamesgorrie** [guardian/dotcom-rendering#7481]
Bump [`DCRFronts`](https://github.com/guardian/frontend/blob/main/common/app/experiments/Experiments.scala#L31-L38) experiment to 100%. - done

Next steps: 
- [X] create a test for network fronts specifically https://github.com/guardian/frontend/pull/26217
- [x] start with 0% so we can test in production https://github.com/guardian/frontend/pull/26246
- [x] release to 1% https://github.com/guardian/frontend/pull/26250
- [x] release to 20% https://github.com/guardian/frontend/pull/26281
- [x] release to 50% https://github.com/guardian/frontend/pull/26287
- [x] release to 100% https://github.com/guardian/frontend/pull/26291

**Comment by alinaboghiu** [comment]
CP comms here, please comment / make any suggestions:
https://docs.google.com/document/d/1mI6iJzmf-Beik4DU6va1j91l-KA7ZHOB0RD8jx86tNI/edit?usp=sharing

**Comment by mxdvl** [comment]
Not truly completed yet!

**Comment by alinaboghiu** [comment]
@arelra is checking ad parity with D&I - please let us know how this goes

**Comment by VDuczekW** [comment]
1% test has gone out today🎉

**Comment by mxdvl** [comment]
@SiAdcock reports being unable to opt out the test. Neither could I. 

https://www.theguardian.com/opt/out/dcr-network-fronts
