### ISSUE TITLE
Ad ratio is less in DCR in /uk/commentisfree

### ISSUE THREAD

**Issue by ioannakok** [guardian/dotcom-rendering#7526]
It has been reported by Commercial dev that ad ratio is consistently less in DCR in comparison to frontend in:
https://www.theguardian.com/uk/commentisfree

https://docs.google.com/spreadsheets/d/1I9Ss0RH0v4_6owyOgTxgkN8NQetCaKe6J1sQOE2THco/edit#gid=2117712738

See notes from the 5/4 Comm dev - Dotcom catch up related to the issue: https://docs.google.com/document/d/1xMlSKVtQqZFqHmKQA_MAOj1w15r2G_NbCEDbTQs_9jk/edit#heading=h.x5zqmbxf40bc

This ticket is to investigate and fix it. We are going to pair with Commercial.

**Comment by VDuczekW** [comment]
merged planned later today
