### ISSUE TITLE
Support New Cartoon Element

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#7531]
## What are cartoons?

Examples can be found here:

- https://www.theguardian.com/cartoons/archive
- https://www.theguardian.com/pictures

## What's the new cartoon element?

Tools have been working on adding support for a new cartoon element to Composer and CAPI. This new element will appear in the blocks API, and will be used to power some of the kinds of cartoons listed above.

## What do the platforms (dotcom, apps) need to do?

When Tools are ready, the platforms will need to rebuild cartoons in articles based on the new cartoon element. We should decide whether we need to do this for both DCR and AR, or just DCR. We will also have to figure out how cartoon support will work in frontend and the apps templates once this new element rolls out.

**Note:** Cartoons often appear on "picture" articles, which neither DCR nor AR have support for yet. We will need to decide whether this support is a pre-requisite for adding this new element. More information about adding support for picture articles in #4941.

**Comment by rhiannareechaye** [comment]
We've taken a look at when we could do this: https://docs.google.com/document/d/15Q1QFv3OY40kuIwOomJxuHKSbwxB18QEJLm06wJZZnU/edit

**Comment by alinaboghiu** [comment]
Done
