### ISSUE TITLE
Identify specific areas where we use identity management in DCR

### ISSUE THREAD

**Issue by jamesgorrie** [guardian/dotcom-rendering#7544]
## Sign in top bar

![Image](https://user-images.githubusercontent.com/31692/231440711-e190deb7-a1cb-49ae-92a6-daaa380d7ec0.png)

Currently the top bar [uses the `GU_U` cookie method](https://github.com/guardian/dotcom-rendering/blob/main/dotcom-rendering/src/web/components/HeaderTopBar.importable.tsx#L73-L74) to get [whether the user is signed in client side](https://github.com/guardian/dotcom-rendering/blob/main/dotcom-rendering/src/web/components/HeaderTopBarMyAccount.tsx).

---

### Live blogs

![Image](https://user-images.githubusercontent.com/31692/231442331-1666aaee-30c2-4824-a1ef-9a27520831e9.png)

[Uses the `GU_U` cookie method](https://github.com/guardian/dotcom-rendering/blob/main/dotcom-rendering/src/web/components/LiveBlogEpic.importable.tsx#L107). 

---

## Consent management platform
???

---

## Discussion

- [Uses the GU_U cookie](https://github.com/guardian/dotcom-rendering/blob/main/dotcom-rendering/src/web/components/DiscussionContainer.importable.tsx#L26)
- [To then lookup information from the discussion API](https://github.com/guardian/dotcom-rendering/blob/main/dotcom-rendering/src/web/components/DiscussionWhenSignedIn.tsx#L6-L18) @https://discussion.theguardian.com/discussion-api/profile/me?strict_sanctions_check=false

### Questions
- [ ] Who is responsible for the https://discussion.theguardian.com/discussion-api/profile/me?strict_sanctions_check=false endpoint? And how do we handle it in this new world.

**Comment by rhiannareechaye** [comment]
Closing as this was done in the Spike: https://docs.google.com/document/d/1tXWq_Cudcs6U7ZvpQhw2VGM1cMFR2DnoWB_kgGq1Pn0/edit#heading=h.le722un7883g
