### ISSUE TITLE
Crossword anagram helper alignment bug

### ISSUE THREAD

**Issue by georgeblahblah** [guardian/dotcom-rendering#7548]
For hyphenated answers, the anagram helper renders incorrectly when the cell to the left of the hyphen is populated:

![Image](https://user-images.githubusercontent.com/705427/231490307-cdbadb1d-75ab-494c-863b-57d15a41074c.png)

See https://github.com/guardian/react-crossword/commit/ac2873252bbb759df937ef01f37add115b677398 for a previous fix. It looks like `guardian/react-crossword` is only used for the Editions app

**Comment by rhiannareechaye** [comment]
We are deprioritising this ticket by 'closing a not planned' - this won't delete the ticket and it will be searchable if the issue crops up again. Unfortunately we have over 130 health tickets to address in the web team. With so many tickets we are potentially missing things that are high-impact so we're reorganising the board - if we can get through all our high-impact tickets we can re-open these lower impact ones.

**Comment by rhiannareechaye** [comment]
We are deprioritising this ticket by 'closing a not planned' - this won't delete the ticket and it will be searchable if the issue crops up again. Unfortunately we have over 130 health tickets to address in the web team. With so many tickets we are potentially missing things that are high-impact so we're reorganising the board - if we can get through all our high-impact tickets we can re-open these lower impact ones.
