### ISSUE TITLE
React 18 Upgrade: About Us

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#7569]
https://github.com/guardian/about-us

**Comment by georgeblahblah** [comment]
It looks like `source-react-components` is still on React 17. We probably need it to be upgraded to React 18 first before upgrading `about-us`. We will reach out to CSNX.

**Comment by georgeblahblah** [comment]
Because `react` is a peer dep of `source-react-components`, we can upgrade React independently, even though we will get a mismatched peer dependency warning

**Comment by rhiannareechaye** [comment]
https://github.com/guardian/about-us/pull/108 related issue

**Comment by rhiannareechaye** [comment]
We're going to look at these on Wednesday and Thursday 26th & 27th (we're going to hold all the applications till then so that we can use the new versions of the libraries)

**Comment by georgeblahblah** [comment]
Upgraded in https://github.com/guardian/about-us/pull/117, but we should wait until `@guardian/source-react-components` has been upgraded so we can remove `legacy-peer-deps` from `.npmrc` and the `resolutions` key from `package.json`.
