### ISSUE TITLE
Moving `discussion-rendering` Into DCR

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#7590]
Now that we're no longer going to be using `discussion-rendering` in AR (see #7366), the only project that's ever likely to depend on it is DCR. We could save ourselves the overhead of maintaining a separate library by pulling all the code into the DCR codebase and deprecating `discussion-rendering`.

See also: #7588

**Comment by coldlink** [comment]
https://github.com/guardian/dotcom-rendering/pull/8057
