### ISSUE TITLE
Crossword Published As `article` Rather Than `crossword` Missing From Search

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#7598]
A crossword piece published as a normal `article` rather than a `crossword` does not appear when searching by id on the crosswords search page[^1].

Examples:

- April prize crossword: https://www.theguardian.com/crosswords/2023/apr/08/easter-special-cryptic-crossword-no-29039
- Some (all?) genius crosswords: https://www.theguardian.com/crosswords/series/genius

[^1]: https://www.theguardian.com/crosswords/search

**Comment by JamieB-gu** [comment]
I believe this happens because crossword pieces have a consistent CAPI id of the form `crosswords/<crossword_type>/<crossword_id>`. That makes them easy to retrieve from CAPI, as this id can be derived given the `crossword_type` and `crossword_id`. This is how `frontend` finds them: https://github.com/guardian/frontend/blob/26b27eb4c18424c7a516efed7ac8909e68b26b79/applications/app/controllers/CrosswordsController.scala#L36

When a crossword is published as a normal article, however, it doesn't have a CAPI id of this form. It has a normal article id, which makes it harder to find given just `crossword_type` and `crossword_id`.

**Comment by rhiannareechaye** [comment]
We are deprioritising this ticket by 'closing a not planned' - this won't delete the ticket and it will be searchable if the issue crops up again. Unfortunately we have over 130 health tickets to address in the web team and we can't address them all. With so many tickets we are potentially missing things that are high-impact so we're reorganising.
