### ISSUE TITLE
`MerchandiseHighSectionSwitch` on `/uk` front

### ISSUE THREAD

**Issue by ioannakok** [guardian/dotcom-rendering#7616]
Support `MerchandiseHighSectionSwitch` that moves the merchandising high section lower on a UK front, to coincide with an ad campaign. See frontend PR that implemented it: https://github.com/guardian/frontend/pull/23677

Once this is implemented we need to make sure we're taking the switch into account in the logic that decides the merchandising high position. See [frontend logic](https://github.com/guardian/frontend/blob/main/common/app/views/support/HtmlCleaner.scala#L836-L847).

Before (switch off):

<img width="651" alt="Screenshot 2021-04-12 at 15 13 23" src="https://user-images.githubusercontent.com/7014230/114412929-7765c700-9ba5-11eb-91f0-891c2202bec7.png">

After (switch on): 

<img width="651" alt="Screenshot 2021-04-12 at 15 14 11" src="https://user-images.githubusercontent.com/7014230/114412954-7d5ba800-9ba5-11eb-891a-5f8afa9ab71b.png">

**Comment by alinaboghiu** [comment]
Ashish says we don't need to do this

**Comment by ashishpuliyel** [comment]
We don't need this functionality. We should just take the switch out.

**Comment by rhiannareechaye** [comment]
This is a small ticket
