### ISSUE TITLE
Take into account `hasPageSkin` in merchandising high logic

### ISSUE THREAD

**Issue by ioannakok** [guardian/dotcom-rendering#7620]
Once DCR [supports Page Skin Ads](https://github.com/guardian/dotcom-rendering/issues/5490) we need to make sure we're taking this into account in the logic that calculates the merchandising high position. See [frontend logic](https://github.com/guardian/frontend/blob/main/common/app/views/support/HtmlCleaner.scala#L836-L849).

**Comment by rhiannareechaye** [comment]
@arelra fyi

**Comment by arelra** [comment]
After investigation with @ioannakok we concluded the current Frontend merchandising-high logic does not do anything with the `hasPageSkin` boolean. This ticket can be closed with no further action required.
