### ISSUE TITLE
Match Report Top Tag Should Take Theme Colour On Narrow Breakpoints

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#7644]
In match reports the top tag sits on different background colours at different breakpoints: yellow on wider breakpoints and white on narrower ones. The text colour is currently a dark neutral on both backgrounds.

We'd like it to keep the dark neutral on the yellow background, but switch to a theme-specific colour when on the white background (e.g. a blue for sport articles).

Example article: https://www.theguardian.com/football/2023/apr/26/manchester-city-arsenal-premier-league-match-report

Talk to Design (@HarryFischer) if unsure which theme colours to use. Contact CP to let them know when this is done.

| Narrow | Wide |
| - | - |
| ![top-tag-narrow] | ![top-tag-wide] |

[top-tag-wide]: https://user-images.githubusercontent.com/53781962/234836820-6a39d1dd-ac1a-4fc2-b6ec-2e1ba0dfaad4.jpg
[top-tag-narrow]: https://user-images.githubusercontent.com/53781962/234836825-3b3f0578-d413-48ce-ace3-20a504518cc8.jpg

**Comment by rhiannareechaye** [comment]
Thank you for writing this up. I'm actually going to close this ticket as not planned. We have so many high impact tickets to get through. We will revisit once we get through our high-impact tickets to see when we can pick this up
