### ISSUE TITLE
[Bug]: DCR data-link-name on SubNav links is different than frontend

### ISSUE THREAD

**Issue by AshCorr** [guardian/dotcom-rendering#7651]
### What happened?

Frontend appears to use the link title to generate the data-link-name attribute whilst DCR tries to generate it from the link path.

This is the case for both Fronts and Articles

## Frontend

<img width="979" alt="image" src="https://user-images.githubusercontent.com/21217225/234941320-20193508-cd9f-47a1-ad3e-c3836ae87cbe.png">

## DCR

<img width="1041" alt="image" src="https://user-images.githubusercontent.com/21217225/234941398-b1ed00f7-5bb1-485f-ab1d-0461ce7e629f.png">

### Where is this happening?

https://www.theguardian.com/uk

### What is the impact?

Unknown

**Comment by rhiannareechaye** [comment]
Removing this from the Rota team and moving it into our bug fixes for Fronts

**Comment by rhiannareechaye** [comment]
@AshCorr I don't understand what the impact of this is for DCR - is it a bad thing? Have added to post-100% milestone for now

**Comment by AshCorr** [comment]
Can't say wether its a bad thing or a good thing! I'm not sure I know enough about how Ophan uses these data link names. Considering its been broken/different in articles for such a long time I'm thinking this probably isnt that important.
