### ISSUE TITLE
Big avatar pictures do not show on DCR

### ISSUE THREAD

**Issue by ioannakok** [guardian/dotcom-rendering#7688]
![Image](https://user-images.githubusercontent.com/19683595/236511374-b61066b3-c428-4e6d-9907-a57f3de2a75d.png)

**Comment by HarryFischer** [comment]
Is DCR on the left? I think the huge pic looks a bit off. left version feels nicer @ioannakok

**Comment by rhiannareechaye** [comment]
Closing as better in DCR
