### ISSUE TITLE
"How to listen to Podcasts" container looks off in DCR

### ISSUE THREAD

**Issue by ioannakok** [guardian/dotcom-rendering#7689]
![Image](https://user-images.githubusercontent.com/19683595/236511624-36643c4f-1179-4ec6-b070-f43762e5a70e.png)

**Comment by rhiannareechaye** [comment]
We are discussing simplifying the podcast Front - could @alinaboghiu and @AshCorr take a look at this as part of the Thrasher/Snaplink work ?
