### ISSUE TITLE
"Rights and freedom" container is missing "Supported by"

### ISSUE THREAD

**Issue by ioannakok** [guardian/dotcom-rendering#7690]
https://theguardian.com/global-development/series/rights-and-freedom

DCR on the left. The issue exists in all breakpoints

![Image](https://user-images.githubusercontent.com/19683595/236512407-6f38d507-1e44-40f6-85a1-03ff5d6b5a6f.png)

**Comment by rhiannareechaye** [comment]
Medium piece of work as you have to find out how to get the badge content from the series tag

**Comment by rhiannareechaye** [comment]
[#7850](https://github.com/guardian/dotcom-rendering/issues/7850)
