### ISSUE TITLE
Complete document about DCAR

### ISSUE THREAD

**Issue by rhiannareechaye** [guardian/dotcom-rendering#7715]
https://docs.google.com/document/d/1K2-m5r1KwgGT5KIyBl9BjmPyBEgniUd5zErhM6orhm4/edit

This doc needs to be completed by multiple teams

**Comment by georgeblahblah** [comment]
I added some comments. The doc is looking like mostly questions, but I think that gives us a good direction to prioritise and start finding the answers.
