### ISSUE TITLE
Remove the list of unsupported thrashers from `FaciaPicker`

### ISSUE THREAD

**Issue by ioannakok** [guardian/dotcom-rendering#7760]
## Non-full width thrashers

- [x] https://content.guardianapis.com/atom/interactive/interactives/thrashers/2022/12/wordiply/default,
- [x] https://content.guardianapis.com/atom/interactive/interactives/thrashers/2022/04/australian-election/default (asking CP if we can delete), 
- [x] https://content.guardianapis.com/atom/interactive/interactives/thrashers/2021/07/full-story/default,
- [x] https://content.guardianapis.com/atom/interactive/interactives/thrashers/2021/10/saved-for-later/default (width 100%) -,
@HarryFischer  FIND OUT WHO BUILT THIS
- [x] https://content.guardianapis.com/atom/interactive/interactives/thrashers/2022/12/documentaries-signup-thrasher/default,
I think this looks OK?
- [x] https://content.guardianapis.com/atom/interactive/interactives/thrashers/2021/12/100-best-footballers/default (arrow icon needs css) - DCR Team branch is `thrashers/100-best-footballers`,
- [x] https://content.guardianapis.com/atom/interactive/interactives/thrashers/2021/01/football-weekly-thrasher/thrasher (button styling missing) - DCR Team branch is `football-weekly-2021-thrasher`,
- [x] https://content.guardianapis.com/atom/interactive/interactives/2022/11/20/football-interactive-atom/knockout-full (@AshCorr is this going to be replaced by a CSTI repo version?),
- [x] https://content.guardianapis.com/atom/interactive/interactives/thrashers/2021/07/pegasus/default (text colour & width) - DCR Team banch is `thrashers/pegasus`,
- [x] https://content.guardianapis.com/atom/interactive/interactives/thrashers/2022/07/lakeside/default (link styling, width) - DCR Team branch is `lakeside-header`,
- [x] https://content.guardianapis.com/atom/interactive/interactives/thrashers/2022/07/support-guardian-thrasher/default (link button css, fix margins @HarryFischer will do this one),
- [x] https://content.guardianapis.com/atom/interactive/interactives/thrashers/2022/02/pw-uk/default (link button styles & content width @HarryFischer will do this one),
- [x] https://content.guardianapis.com/atom/interactive/interactives/thrashers/2022/11/comfort-eating-grace-dent-thrasher-no-logo/default (link button styles),
- [x] https://content.guardianapis.com/atom/interactive/interactives/thrashers/2022/02/weekend-podcast-2022/default (link button styles & content width @HarryFischer will do this one),,

### Pandora Papers
* https://github.com/guardian/dotcom-rendering/pull/7841 

- [x] https://content.guardianapis.com/atom/interactive/interactives/thrashers/2021/09/pandora-header/default

### Cost of the crown
* https://github.com/guardian/dotcom-rendering/issues/7686
- [x] https://content.guardianapis.com/atom/interactive/interactives/thrashers/2023/04/cost-of-crown/default  (fonts look weird, padding and alignment start looking weird on smaller breakpoints @HarryFischer will do this one)

### Cotton Capital 

* https://github.com/guardian/dotcom-rendering/pull/7863)

Full-width will be fixed by @HarryFischer: https://github.com/guardian/dotcom-rendering/issues/7748

- [x] https://content.guardianapis.com/atom/interactive/interactives/2022/10/tr/default-fronts-default 
- [x] https://content.guardianapis.com/atom/interactive/interactives/2022/10/tr/david-olusoga-front-default 
- [x] https://content.guardianapis.com/atom/interactive/interactives/2022/10/tr/cassandra-gooptar-front-default 
- [x] https://content.guardianapis.com/atom/interactive/interactives/2022/10/tr/gary-younge-front-default,
- [x] https://content.guardianapis.com/atom/interactive/interactives/2022/10/tr/deneen-l-brown-front-default,
- [x] https://content.guardianapis.com/atom/interactive/interactives/2022/10/tr/the-enslaved-front-default,
- [x] https://content.guardianapis.com/atom/interactive/interactives/2022/10/tr/olivette-otele-front-default,
- [x] https://content.guardianapis.com/atom/interactive/interactives/2022/10/tr/interactives-front--globe,
- [x] https://content.guardianapis.com/atom/interactive/interactives/2022/10/tr/michael-taylor-front-default,
- [x] https://content.guardianapis.com/atom/interactive/interactives/2022/10/tr/lanre-bakare-front-default,
- [x] https://content.guardianapis.com/atom/interactive/interactives/2022/10/tr/hidden-figures-front-default,
- [x] https://content.guardianapis.com/atom/interactive/interactives/2022/10/tr/johny-pitts-photo-essay-front-default,

**Comment by VDuczekW** [comment]
last remaining is AUS - Harry taking a look - but can be removed

**Comment by HarryFischer** [comment]
@VDuczekW Sorry I cant find the code for this - I think we should remove if possible

**Comment by rhiannareechaye** [comment]
I've emailed CP to ask them to delete it

**Comment by rhiannareechaye** [comment]
Closing as this ticket is done :)
