### ISSUE TITLE
Develop a light-weight custom library

### ISSUE THREAD

**Issue by rhiannareechaye** [guardian/dotcom-rendering#7786]
Okta’s current library

- OKTA has a library which enables us to tap into their authentication 
- This library is too heavy for us to bundle and send over to the end user 

Creating our own lightweight custom library 

- Identity (Mahesh) is going through the Okta library and building a custom one which will only contain functions that we in the Web team need. 

Can WebX start work without the custom library in place? 

- WebX can start working with the Okta library
- In the Spike it was fine using this existing library
- The names of the functions etc. in the custom Okta library will be the same as the general Okta one, so it should just be a name in the code that we replace when we get round to it 
- We’ll just release behind a switch with the Okta library

**Comment by coldlink** [comment]
Methods currently being used are defined here: https://docs.google.com/document/d/1tXWq_Cudcs6U7ZvpQhw2VGM1cMFR2DnoWB_kgGq1Pn0/edit#heading=h.y085vrt2h519

**Comment by coldlink** [comment]
WIP here: https://github.com/guardian/csnx/pull/588
Will continue when back from AL next week

**Comment by ShraddhaPande** [comment]
Writing tests - this is now feature complete and can be picked up to start being included in the Web Ex dev

**Comment by coldlink** [comment]
In review now: https://github.com/guardian/csnx/pull/588

**Comment by VDuczekW** [comment]
please review and make sure this is the right forward - webx pairing

**Comment by ShraddhaPande** [comment]
Just waiting for CSTI to approve and then it will be merged . Web Exp can then use it
