### ISSUE TITLE
Figure out if it's possible to have a DCAR debug build

### ISSUE THREAD

**Issue by rhiannareechaye** [guardian/dotcom-rendering#7790]
Currently there is [functionality built into the iOS live app](https://github.com/guardian/ios-live/pull/7068) to render debugging URLs.

You should be able to [follow the readme](https://github.com/guardian/ios-live#your-first-build) - but a few notes on this:

* you need to be on OSX Ventura
* you need to be on XCode 14.3.1
* clone the repo
* run `./configure`
* run `npm install`
* open `GLA/GLA.xcworkspace` in XCode
* wait for the project to build
* run in an emulator (play button on the top right of the left panel)
* run the code to enable debugging (ask)
* paste the [DCR style URL](https://www.theguardian.com/politics/2023/may/09/liz-truss-to-visit-taiwan-and-give-speech-that-could-upset-uks-china-strategy?dcr=apps) in the bar

# Note on the last step

This doesn't work. We'll need to work out with Apps why not, a small hunch is that there might be [some](https://github.com/guardian/ios-live/blob/main/GLA/GLA/Classes/ArticleSingleViewController.swift#L27C1-L33C1) [validation](https://github.com/guardian/ios-live/blob/0ba32cdfae34c73afd7c2efd869b7f165ebe2793/GLA/GLA/Classes/URL%2BExtension.swift#L44) on what URLs can be used. 

@guardian-ben - do you know if this is the case?

**Comment by JamieB-gu** [comment]
We think it should be possible to add a control for DCAR articles in the debug build. iOS and Android (Apps Experience) both have tickets to add this and will let us know when they're done.

**Comment by jamesgorrie** [comment]
Updated the comment

**Comment by VDuczekW** [comment]
James running with it

**Comment by VDuczekW** [comment]
testing to check and can be closed if it is successful

**Comment by VDuczekW** [comment]
it's done

**Comment by jamesgorrie** [comment]
This PR was the last step in getting this done:
https://github.com/guardian/ios-live/pull/7131
