### ISSUE TITLE
Broken HTML in series description of AMP articles

### ISSUE THREAD

**Issue by ParisaTork** [guardian/dotcom-rendering#7824]
Paul from User Support and Gabriel reported broken HTML in the series description of these articles:
- [ ] https://amp.theguardian.com/lifeandstyle/2023/may/26/biting-the-skin-off-my-fingers-feels-like-self-harm-but-i-cant-stop
- [ ] https://amp-theguardian-com.cdn.ampproject.org/v/s/amp.theguardian.com/money/2023/may/25/my-mothers-treasured-phone-number-of-70-years-has-been-lost

Original email title: Re: Technical Issues - I’d like to report a technical issue with your website (Case #03535202)

**Comment by rhiannareechaye** [comment]
We are deprioritising this ticket by 'closing a not planned' - this won't delete the ticket and it will be searchable if the issue crops up again. Unfortunately we have over 130 health tickets to address in the web team and we can't address them all. With so many tickets we are potentially missing things that are high-impact so we're reorganising.
