### ISSUE TITLE
Container badge should be based on series tag

### ISSUE THREAD

**Issue by alinaboghiu** [guardian/dotcom-rendering#7850]
At the moment we decide a badge based on two things: 
1. If the container display name is "This is Europe" we display the "This is Europe" badge
2. If all cards have the same sponsor we display this sponsor's badge

The first part of this logic should change and instead be based on the collection series tag. 
We should probably reproduce this logic in Frontend which maps each series tag to a badge: https://github.com/guardian/frontend/blob/main/common/app/model/Badges.scala#L28
Then we can use the series tags from a container to decide which badge to display.

**Comment by rhiannareechaye** [comment]
[#7690](https://github.com/guardian/dotcom-rendering/issues/7690)
