### ISSUE TITLE
Culture not having a colour on its section

### ISSUE THREAD

**Issue by ParisaTork** [guardian/dotcom-rendering#7854]
The Guardian readers' editor's office have reached out to us about Culture not having a colour on its section - the original info is here:

This is hard to describe so I have attached screenshots for tech support. When you go to the supplementary sections of the main page, usually those sections are highlighted by a colour bar above the title to tell you where you are.

When you click on Sports, the highlight colour above is blue. When you click on Lifestyle the highlighted colour above is pink. But when you click on the Culture page there is no bar highlighted - it goes back to highlighting the main News title highlighted in red, so at a glance you think you are on the main News page but actually you are on the Culture page.

It's just a minor annoyance, but when you go to the Culture page it should highlight that's where you are, instead of what we have now which is wrong.

![Image](https://github.com/guardian/dotcom-rendering/assets/47482049/30817a7c-d7cb-4268-a363-cd343bb6c9e5)

![Image](https://github.com/guardian/dotcom-rendering/assets/47482049/a982b689-e957-4427-8ab2-24bff50954e2)

![Image](https://github.com/guardian/dotcom-rendering/assets/47482049/0b7d9792-2a0a-49a0-8c0d-2c7140c146a9)

**Comment by OllysCoding** [comment]
PR to address this is here: https://github.com/guardian/dotcom-rendering/pull/7587
