### ISSUE TITLE
Katy's '+more film' bug in Chrome/Firefox

### ISSUE THREAD

**Issue by ParisaTork** [guardian/dotcom-rendering#7855]
Jamie & I had a session today to investigate a bug in which Katy had issues clicking on '+film' - the button doesn't expand and we couldn't see a request being sent out in the Network tab - we've tested this in multiple browsers incognito on Katy's work machine, but haven't had any success - here are screenshots below capturing this issue:

![Image](https://github.com/guardian/dotcom-rendering/assets/47482049/c77b7fcc-6270-4fd8-8de8-656a10b746c6)
![Image](https://github.com/guardian/dotcom-rendering/assets/47482049/a49d405b-9c75-4d26-b778-2d0cb3c64774)
![Image](https://github.com/guardian/dotcom-rendering/assets/47482049/4569d593-438a-44e1-bad2-6d45d3ca277a)
![Image](https://github.com/guardian/dotcom-rendering/assets/47482049/a0745c54-38ce-43bc-9790-62cfb6cd33a7)
![Image](https://github.com/guardian/dotcom-rendering/assets/47482049/c6a82f62-7b4c-4476-95e6-89125d13c644)
![Image](https://github.com/guardian/dotcom-rendering/assets/47482049/0e10bc6f-db4d-4144-9f16-5dd738744160)

**Comment by Georges-GNM** [comment]
Katy is asking her colleagues if they can replicate and will get back to us.

**Comment by alinaboghiu** [comment]
Sorry to jump in so late in the process. Did we establish whether this bug goes away if ?dcr=false is set in the url when Katy visits the culture front?

**Comment by shesah** [comment]
This seems to be a problem with Hydration and was suggested to Katy to change her laptop
