### ISSUE TITLE
Guardian Foundation custom footer

### ISSUE THREAD

**Issue by mxdvl** [guardian/dotcom-rendering#7898]
Some Guardian Foundation pages [have a custom footer](https://github.com/guardian/frontend/blob/0ab174b0b3982a68c60338130c6b68ed58b2e75c/common/app/views/fragments/footer.scala.html#L141), for example:

- https://www.theguardian.com/gnm-archive

<img width="1313" alt="image" src="https://github.com/guardian/dotcom-rendering/assets/76776/2afb9950-6a90-44f2-9f17-cd5cc9493018">

**Comment by rhiannareechaye** [comment]
Thanks for raising Max - I will 'close as not planned' so that we have a record of this (but we can't prioritise addressing right now)
