### ISSUE TITLE
Remove paid for by from cards on labs fronts

### ISSUE THREAD

**Issue by DanielCliftonGuardian** [guardian/dotcom-rendering#7921]
Currently looks like this on dcr
![Image](https://github.com/guardian/dotcom-rendering/assets/110032454/0942e825-6cd4-4491-a174-716127c6ab6f)

**Comment by alinaboghiu** [comment]
The logic to filter out these badges correctly already exists in FrontLayout but it's only being used for the labs container. We should pull it further up in the file and use it for all containers.
