### ISSUE TITLE
Image resolution

### ISSUE THREAD

**Issue by alinaboghiu** [guardian/dotcom-rendering#7941]
Dynamic package full-with image [is loaded at 700px](https://m.code.dev-theguardian.com/sublinks-test?dcr#dynamic/package-(dynamo)) wide instead of 940px in Frontend leading to a low resolution

**Comment by rhiannareechaye** [comment]
Duplicate of [Refactor image position#4822](https://github.com/guardian/dotcom-rendering/issues/4822)
