### ISSUE TITLE
Cards Bug

### ISSUE THREAD

**Issue by VDuczekW** [guardian/dotcom-rendering#7942]
![Image](https://github.com/guardian/dotcom-rendering/assets/91130034/01cf5d87-bbd0-43de-bb25-e7d83faa760b)

![Image](https://github.com/guardian/dotcom-rendering/assets/91130034/85fb301a-c7cf-46a4-9fab-b56875be7f85)

![Image](https://github.com/guardian/dotcom-rendering/assets/91130034/6c66f75b-0d78-4a44-a218-599b1a60d9be)

![Image](https://github.com/guardian/dotcom-rendering/assets/91130034/667499b5-e712-450a-b1e7-829481d13d2b)

**Comment by rhiannareechaye** [comment]
Closing as issues stated elsewhere!
