### ISSUE TITLE
Byline shows additional information on DCR

### ISSUE THREAD

**Issue by rhiannareechaye** [guardian/dotcom-rendering#7946]
(Ewan Mirray at LA Country club) 

![Image](https://github.com/guardian/dotcom-rendering/assets/93542262/88161e15-5333-4e23-93f1-67cd78964ba9)

**Comment by rhiannareechaye** [comment]
This may be correct - we're not sure so it needs to be investigated

**Comment by rhiannareechaye** [comment]
@HarryFischer do you have thoughts on this from a design perspective? Is it meant to show? DCR is on left in picture

**Comment by alinaboghiu** [comment]
in `enhaceCards` we should use `card.properties.byline` instead of `faciaCard.properties.maybeContent?.trail.byline`
