### ISSUE TITLE
Difference in topics on /food front (DCR on right)

### ISSUE THREAD

**Issue by rhiannareechaye** [guardian/dotcom-rendering#7947]
![Image](https://github.com/guardian/dotcom-rendering/assets/93542262/286bd712-980d-422e-810c-4378236260a6)

**Comment by AshCorr** [comment]
Duplicate of #7161

**Comment by rhiannareechaye** [comment]
[#7161](https://github.com/guardian/dotcom-rendering/issues/7161) this seems to be related
