### ISSUE TITLE
Card background colour on dynamic packages

### ISSUE THREAD

**Issue by mxdvl** [guardian/dotcom-rendering#7951]
When a `dynamic/package` container **has no palette applied**, but contains a boosted card, it does not get a background associated with the trail’s format and instead gets a white background. The hover styles seem fine

| Frontend      | DCR      |
|-------------|------------|
| ![frontend][] | ![dcr][] |
|           hover          |
| ![frontend-hover][] | ![dcr-hover][] |

[frontend]: https://github.com/guardian/dotcom-rendering/assets/76776/6f4e6574-3ff3-4bec-9653-2ad1e9358a71
[dcr]: https://github.com/guardian/dotcom-rendering/assets/76776/29582d41-5202-4838-b31e-bff8f8a8afeb

[frontend-hover]: https://github.com/guardian/dotcom-rendering/assets/76776/5de1bd9e-0947-410e-b758-01fa7557c88d
[dcr-hover]: https://github.com/guardian/dotcom-rendering/assets/76776/01bfa764-99ab-4b3a-af65-929154f757f5

**Comment by alinaboghiu** [comment]
What is this? sorry..

**Comment by mxdvl** [comment]
I’m struggling to reproduce this, but it did look weird when there was a `dynamic/*` container with a light blue palette. Do we want to close this and reopen when it’s used in anger?

**Comment by mxdvl** [comment]
Closed by #8020
