### ISSUE TITLE
Show More Button alignment

### ISSUE THREAD

**Issue by rhiannareechaye** [guardian/dotcom-rendering#7952]
More button alignment? 

![Image](https://github.com/guardian/dotcom-rendering/assets/93542262/4d98a9f9-446b-44a5-ba72-c93d2266685c)

**Comment by alinaboghiu** [comment]
Doesn't seem to happen on network fronts so moving to post-release bugs

**Comment by alinaboghiu** [comment]
Can't recreate this, please reopen with an example
