### ISSUE TITLE
Front line thrasher not showing at lower breakpoints

### ISSUE THREAD

**Issue by DanielCliftonGuardian** [guardian/dotcom-rendering#7970]
The thrasher appears here and seems correct at other breakpoints https://www.theguardian.com/au/environment?dcr=true

| FRONTEND      | DCR | 
| :---        |    :----:   |        
| ![Image](https://github.com/guardian/dotcom-rendering/assets/110032454/4d4a4794-33ca-41b5-8278-d435e31c0170)      | ![Image](https://github.com/guardian/dotcom-rendering/assets/110032454/bf7415f7-6cc3-44dd-8804-e39a376ebe60)       |

**Comment by AshCorr** [comment]
AU team should probably pick this up, they recently moved this thrasher from JSON.HTML to Interactive. I'll ping them this!

**Comment by rhiannareechaye** [comment]
Thanks Ash - I will close this ticket
