### ISSUE TITLE
Use parameter store for badge definitions

### ISSUE THREAD

**Issue by cemms1** [guardian/dotcom-rendering#7974]
As follow up work from https://github.com/guardian/dotcom-rendering/issues/7850, we should store badge definitions somewhere more sensible than straight in the code. Parameter store has been suggested as a possible option:

> do we plant to address this in this PR? we could  use parameter store! this would also make it easier to add badges in future

_Originally posted by @alinaboghiu in https://github.com/guardian/dotcom-rendering/pull/7963#discussion_r1235027887_

**Comment by georgeblahblah** [comment]
re Parameter Store, right now we don't need Janus credentials to run DCR locally and I think that's great. I think storing badges in Parameter Store would change that, but maybe there's a way we can have a local stub for development. Definitely worth exploring!

**Comment by rhiannareechaye** [comment]
We'll bring this up in the platform rendering meeting with the tools team

**Comment by jamesgorrie** [comment]
> we should store badge definitions somewhere more sensible than straight in the code

I agree with this sentiment, but with the aim of making it more self serve to non-engineers which
