### ISSUE TITLE
Use cutout

### ISSUE THREAD

**Issue by alinaboghiu** [guardian/dotcom-rendering#8006]
This is a control on the card in Facia tool. 

If in tag manager a large byline exists, and in the fronts tool the "use cutout" option is enabled, we need to display the larger cutout on the card.

**Comment by alinaboghiu** [comment]
We should write a story for this in storybook if there isn't one already

**Comment by ioannakok** [comment]
Closing this as we're already supporting it:

Large byline url:
https://uploads.guim.co.uk/2022/08/26/Nesrine_Malik.png

frontend:
![image](https://github.com/guardian/dotcom-rendering/assets/19683595/b9a58169-684e-4e28-a683-b117ea57058a)

DCR:
![image](https://github.com/guardian/dotcom-rendering/assets/19683595/d099771c-815e-4094-afe5-50ca3a257693)
