### ISSUE TITLE
Pillar colour highlight not displaying on current pillar front

### ISSUE THREAD

**Issue by rcrphillips** [guardian/dotcom-rendering#8007]
### What happened?

First of all: woop woop DCR fronts out in production!

The pillar highlight is defaulting to news when viewing a dcr front
![Screenshot_20230621-191939](https://github.com/guardian/dotcom-rendering/assets/2051501/2677c904-33ab-4e36-9fb3-e51096d443c0)
![Screenshot_20230621-191931](https://github.com/guardian/dotcom-rendering/assets/2051501/c1bb126a-1af6-412e-8e51-c938404e11eb)

### Where is this happening?

https://www.theguardian.com/uk/culture

**Comment by rhiannareechaye** [comment]
Thanks @rcrphillips !

**Comment by rhiannareechaye** [comment]
Closing this ticket as it was fixed by: https://github.com/guardian/dotcom-rendering/pull/7967
