### ISSUE TITLE
Facebook share on a page you manage query

### ISSUE THREAD

**Issue by DanielCliftonGuardian** [guardian/dotcom-rendering#8024]
A query came in from a user.
"Two days ago Facebook changed how it provides for sharing webpages.
The Guarding website has not kept up with the change.
The Guardian website does not support "Share on a page you manage."
This means that people who manage multiple Facebook accounts can't link Guardian sites."
Not sure if this is entirely our remit.

**Comment by rhiannareechaye** [comment]
Thanks @DanielCliftonGuardian - agree i don't think this is our remit and also we have limited capacity at the moment so I'm going to close as not planned but good for us to have a record of it
