### ISSUE TITLE
URLs in https://m.code.dev-theguardian.com/uk/lifeandstyle are duplicated

### ISSUE THREAD

**Issue by DanielCliftonGuardian** [guardian/dotcom-rendering#8027]
URLs in https://m.code.dev-theguardian.com/uk/lifeandstyle have got the root URL duplicated (i.e. `[https://m.code.dev-theguardian.com/http://www.code.dev-theguardian.com/technology/2021/oct/27/wifi-advice-techscape`](https://m.code.dev-theguardian.com/http://www.code.dev-theguardian.com/technology/2021/oct/27/wifi-advice-techscape%60)

**Comment by rhiannareechaye** [comment]
@DanielCliftonGuardian would you mind adding a bit more info to this issue? What is the problem with this?
