### ISSUE TITLE
Move `/documentaries` to new documentaries format

### ISSUE THREAD

**Issue by alinaboghiu** [guardian/dotcom-rendering#8040]
@HarryFischer is moving the https://www.theguardian.com/documentaries page to a more standard front format which should be supported by DCR

**Comment by rhiannareechaye** [comment]
Hey @HarryFischer  - just wondering if you got anywhere with moving this page to a new format?
https://www.theguardian.com/documentaries

I wonder if we just turn it into a regular front? We're about to introduce a new video container with playable videos which looks pretty nice so maybe it could use that

Context of the new container here: https://docs.google.com/document/d/1JSmc-dcisw-QVrnk9OET23sSxwd3GZHChizbUsfpZno/edit

**Comment by rhiannareechaye** [comment]
Have heard from Harry that this is being worked on and should be ready by the end of the week

**Comment by VDuczekW** [comment]
not blocked but outside of core engineering team

**Comment by HarryFischer** [comment]
This is done
