### ISSUE TITLE
Decide what to do with Email Fronts

### ISSUE THREAD

**Issue by mxdvl** [guardian/dotcom-rendering#8047]
Frontend is able to render some fronts for email–see Fronts tool /email–e.g.:

- https://www.theguardian.com/email/uk/daily
- https://www.theguardian.com/email/us/daily
- https://www.theguardian.com/email/au/daily

This logic is unfortunately not based [on a route](https://github.com/guardian/frontend/blob/bc005b5772684477ae1bb72b7efea432cca39e79/facia/conf/routes), nor a property of [`PressedPage` ](https://github.com/guardian/frontend/blob/bc005b5772684477ae1bb72b7efea432cca39e79/common/app/model/PressedPage.scala#L113), but rather simply from the fact that these pages are pressed.

We prevent these fronts from being sent to DCR by checking for [unsupported collection types](https://github.com/guardian/frontend/blob/bc005b5772684477ae1bb72b7efea432cca39e79/facia/app/services/dotcomrendering/FaciaPicker.scala#L16-L17).

We should decide what to do with these and whether ongoing support or migration is required.

**Comment by dblatcher** [comment]
I'd suggest there's no need to migrate the email-design to DCR - We do have plan to extend the [email-rendering](https://github.com/guardian/email-rendering) project to render fronts in email format and there is also some design work on-going to change the look of the current email-front templates.

**Comment by alinaboghiu** [comment]
We will probably end up moving some of these as part of https://github.com/guardian/dotcom-rendering/issues/10433
Closing this ticket since the decision is move to email-rendering
