### ISSUE TITLE
Issue with Tone Kicker on DCR Fronts

### ISSUE THREAD

**Issue by rhiannareechaye** [guardian/dotcom-rendering#8050]
The tone kicker should I believe not be there: there's a button to switch it off in the config but that's not taking effect in dcr.

See https://www.theguardian.com/uk/sport?dcr=false vs https://www.theguardian.com/uk/sport?dcr=true

Second, in DCR we shouldn't have this kicker:
![Image](https://github.com/guardian/dotcom-rendering/assets/93542262/5e4a6e37-1936-4fb6-801c-e527bd41399a)

Which isn't in the tool:
![Image](https://github.com/guardian/dotcom-rendering/assets/93542262/c6f75c10-5243-4ec1-aa86-4b1d6a777683)

clicking "Suppress tone kickers" in fronts config has no effect

**Comment by ioannakok** [comment]
Fixed by: https://github.com/guardian/dotcom-rendering/pull/8083

**Comment by ioannakok** [comment]
Also, investigated "Suppress tone kickers" - TODO: Write comment with findings
