### ISSUE TITLE
[Bug]: Play icon appearing on cards without playable main media.

### ISSUE THREAD

**Issue by DanielCliftonGuardian** [guardian/dotcom-rendering#8065]
### What happened?

Play icon appearing on cards without playable main media. Might be caused by the media being changed.
<img width="242" alt="image" src="https://github.com/guardian/dotcom-rendering/assets/110032454/ed8746ea-de7c-450f-b622-9b93d485b62c">

### Where is this happening?

https://www.theguardian.com/uk?dcr

**Comment by rhiannareechaye** [comment]
Closing as we can't replicate. We will reopen if we see it again but it's unlikely as this design has now changed.
