### ISSUE TITLE
Eyes graphic missing in Tip Us Off element

### ISSUE THREAD

**Issue by jon-kearnesLC** [guardian/dotcom-rendering#8068]
### What happened?

Eyes have gone missing on the mobile breakpoint only of the "tip us off" element on fronts. DCR example on left of screenshot, frontend example on the right:
<img width="1920" alt="image" src="https://github.com/guardian/dotcom-rendering/assets/105220197/055d3946-bb94-4d8a-bef1-f6f35018e13a">

### Where is this happening?

Fronts on the mobile breakpoint

### What is the impact?

Extremely minimal / may be an intentional design choice

**Comment by abeddow91** [comment]
This thrasher is owned by the design team and [lives here ](https://github.com/guardian/csti-interactives/blob/2fa1899ce647e41459a10090712b407de34fdcc8/thrashers/examples/secure-drop/src/thrasher/ThrasherTemplate.tsx#L40)

Spoke with @HarryFischer who confirmed this change isn't deliberate and that the eyes should show and that they will look into fixing this.

**Comment by alinaboghiu** [comment]
Won't fix
