### ISSUE TITLE
Newsletter thrasher legal text cropping at mobile breakpoint

### ISSUE THREAD

**Issue by jon-kearnesLC** [guardian/dotcom-rendering#8069]
### What happened?

Can't read the legal privacy notice of the newsletter thrasher at certain mobile breakpoints:

DCR example on the left:
<img width="1885" alt="image" src="https://github.com/guardian/dotcom-rendering/assets/105220197/4dddd80b-ab9c-4ba8-bcb1-41d0af2e2876">

### Where is this happening?

DCR fronts, newsletter thrasher

### What is the impact?

Regulatory compliance

**Comment by rhiannareechaye** [comment]
@AshCorr and @ioannakok - not sure if either of you looked at this thrasher but this seems like a bit of an issue to me. Including @dblatcher who might have some insight too? I've added it to the list which we need to do before we roll out to 50%

**Comment by dblatcher** [comment]
I think I see the issue - on DCR, the container  div that the thrasher content is being put in  has `display:flex`, so its not constraining the content to fit the space - if you change this to `display:block` or `display:contents` in the console, this makes the content wrap within the space as expected - the div I mean is highlighted in the screenshot below.

The thrashers were written with the assumption they would be within a `display:block` container, like in the frontend template. 

If there's no way to account for this in DCR container, it should be possible to adjust the code in the thrashers, but unfortunately there are about 20 instances of this thrasher design that would all need to be adjusted and redeployed from https://github.com/guardian/interactive-atom-thrasher-template . Can be done if necessary!

<img width="906" alt="Screenshot 2023-06-28 at 15 20 02" src="https://github.com/guardian/dotcom-rendering/assets/30567854/e63e0396-df1f-4fa6-8cc2-a720b19fc3bf">
