### ISSUE TITLE
"Supported By" not showing up correctly on 

### ISSUE THREAD

**Issue by AshCorr** [guardian/dotcom-rendering#8089]
When all cards in a container have branding Frontend adds a "Supported by" badge to the container, this does not seem to happen correctly in DCR.

DCR also renders all containers with the "Branding" tag as labs containers, which I'm not sure is entirely correct.

## DCR

<img width="1316" alt="image" src="https://github.com/guardian/dotcom-rendering/assets/21217225/e022b516-c274-40f4-af0f-0e36fb7c1c18">

## Frontend

<img width="1303" alt="image" src="https://github.com/guardian/dotcom-rendering/assets/21217225/71eb3bf6-804d-4801-ac35-84376f070f9f">

**Comment by rhiannareechaye** [comment]
Confirmed in planning today that @jamesgorrie will take a look at this as it's currently blocking this ticket: [#7989](https://github.com/guardian/dotcom-rendering/issues/7989)

**Comment by rhiannareechaye** [comment]
@jamesgorrie I'm just trying to understand if this ticket is a must (as discussed in planning). I think it is because I think we are branding this labs content when it isn't, but I'm just trying to confirm that

**Comment by rhiannareechaye** [comment]
As per this guide (https://www.theguardian.com/info/2016/jan/25/content-funding) we are incorrectly labelling this content, it's not Labs content as it's editorially independent - this means that we should prioritise this fix - lets discuss at standup

**Comment by rhiannareechaye** [comment]
@ioannakok we discussed this in standup, but once you're done with the bridget analytics service, would you mind picking up this ticket? (it takes priority over the other bugs)
