### ISSUE TITLE
Support kickers controls from Fronts Config tool in Most viewed container

### ISSUE THREAD

**Issue by ioannakok** [guardian/dotcom-rendering#8125]
### Context

From CP: 
Show tag kickers - makes the primary tag on the content visible ahead of the headline
Show section kickers - makes the section tag visible ahead of the headline

![Image](https://user-images.githubusercontent.com/19683595/250814815-aa170d8f-e22c-475e-97d8-dc668bcd6eb4.png)

### Behaviour

| Config | frontend | DCR |
|--------|----------|-----|
| ![image](https://github.com/guardian/dotcom-rendering/assets/19683595/dec100ea-6c56-4734-9128-5c84d21610ff) | ![image](https://github.com/guardian/dotcom-rendering/assets/19683595/3198bb8f-413a-41b8-8434-dad473b9bbb4) | ![image](https://github.com/guardian/dotcom-rendering/assets/19683595/8b582262-c97c-4c13-8cf0-feaabfe6aaf3) |
| ![image](https://github.com/guardian/dotcom-rendering/assets/19683595/c73fffdb-c883-4039-baf9-e430b37d2116) | ![image](https://github.com/guardian/dotcom-rendering/assets/19683595/40dad890-e1ce-4fff-b285-7de08d9fbe43) | ![image](https://github.com/guardian/dotcom-rendering/assets/19683595/731dc4bd-9f44-49cb-9d9c-0372e0285c6f) |
| ![image](https://github.com/guardian/dotcom-rendering/assets/19683595/fb8b43fa-7828-411a-8b89-c1e7ca1835bf) | ![image](https://github.com/guardian/dotcom-rendering/assets/19683595/aef66abf-65d6-4d2d-8e7d-fabfb029bf4d) | ![image](https://github.com/guardian/dotcom-rendering/assets/19683595/25aeeff9-5863-4f66-98d4-24beed5cd2e2) |
| ![image](https://github.com/guardian/dotcom-rendering/assets/19683595/b547cca2-583c-405d-bd0c-48a2535c36c7) | ![image](https://github.com/guardian/dotcom-rendering/assets/19683595/f3d2727e-cf4c-40bb-a1a9-d3b8c628798f) | ![image](https://github.com/guardian/dotcom-rendering/assets/19683595/5fe71f83-6f85-4cb2-aa99-e99e7d480f79) |

### Task
This ticket is to support them in the "Most viewed" container in DCR. We already support them for the rest of containers.

```[tasklist]
### Tasks
- [ ] Support show tag kickers
- [ ] Support show section kickers
```

### Note
This ticket is for the previous "Most viewed" layout. 

![image](https://github.com/guardian/dotcom-rendering/assets/19683595/878c6b86-b250-473e-8332-3a074a6cf66b)

Please discuss with Product regarding the new Most popular layout:

![image](https://github.com/guardian/dotcom-rendering/assets/19683595/e3d33215-025d-48a6-a1b4-1ff9262eb7b0)

**Comment by rhiannareechaye** [comment]
Thanks @ioannakok  - No need to do this for the new 'Most Popular' layout as this is just a test. If the test is successful then we can consider it
