### ISSUE TITLE
Make a plan to decide what to do with 'Message us' long term

### ISSUE THREAD

**Issue by rhiannareechaye** [guardian/dotcom-rendering#8152]
We have a bit of a 'hacky version' - a time limited test of the features in the ed tools codebade (it's not in the capi model) 

Rhianna and Max + tools to decide where it should sit and whether or not it should be in production

**Comment by rhiannareechaye** [comment]
Moving to EdEx health work

**Comment by alinaboghiu** [comment]
We've decided to remove this feature. Keeping this ticket so we can track removal work.
cc @JamieB-gu

**Comment by JamieB-gu** [comment]
Duplicate of #10571
