### ISSUE TITLE
Evaluate pm2 vs another process manager

### ISSUE THREAD

**Issue by cemms1** [guardian/dotcom-rendering#8180]
There have been a couple of issues raised with PM2 on Snyk:
- https://app.snyk.io/org/guardian-dotcom-n2y/project/ef273702-c5ea-4a20-80c4-fe1a2c60b735#issue-snyk:lic:npm:pm2:agent:AGPL-3.0
- https://app.snyk.io/org/guardian-dotcom-n2y/project/ef273702-c5ea-4a20-80c4-fe1a2c60b735#issue-snyk:lic:npm:pm2:AGPL-3.0

We currently use [PM2](https://pm2.keymetrics.io/) to run [DCR](https://github.com/guardian/dotcom-rendering/blob/b876fdf6cdb0bdd41f1fd564ef541059fc0fa1ec/dotcom-rendering/makefile#L65) and [AR](https://github.com/guardian/dotcom-rendering/blob/b876fdf6cdb0bdd41f1fd564ef541059fc0fa1ec/apps-rendering/cdk/lib/mobile-apps-rendering.ts#L97) in production.
This raised the question, _"Why do we use PM2? Is there a better alternative?"_

There have been some recent discussions about PM2 and running containerised node applications in chat:
- https://chat.google.com/room/AAAAag0I08g/XS3_W1IYj74
- https://chat.google.com/room/AAAAag0I08g/AQULNrpIYII

[Interestingly the Newsletters team recently changed their application to run using `systemd` instead of `pm2`.](https://github.com/guardian/newsletters-nx/pull/149)
There are some other Guardian teams using `PM2` so it would be useful to help set good standards across the department for running node apps in containers. 
_[This repo](https://github.com/guardian/backend-101-node-starter) had been set up to attempt to solve that problem_. Another idea could be to add some recommendations [here](https://github.com/guardian/recommendations).

Other useful links:
- [The PR introducing PM2 to DCR](https://github.com/guardian/dotcom-rendering/pull/52)
- [An unresolved PR to the PM2 repo highlighting licensing issues](https://github.com/Unitech/pm2/issues/5143)

**Comment by georgeblahblah** [comment]
I think our requirements for `dotcom-rendering`'s process manager are:
- run the server
- if the server process terminates, start the server again

Although PM2 can do this, it can also has a lot of additional functionality that we don't use. Also, as a dependency, it comes with its own maintenance burden of vulnerabilities.

I think using a tool like `systemd` would meet our requirements and reduce our maintenance overhead.

**Comment by rhiannareechaye** [comment]
Thanks for the detailed notes @georgeblahblah and @cemms1 - I've added this to the triage coloumn. It seems like the next step is, as George has said, 'surface this as a possible recommendation in https://github.com/guardian/recommendations'... Do we think this is 'high impact' and 'low effort'? @jamesgorrie?

**Comment by arelra** [comment]
While we don't use all the features of pm2 currently one potentially useful feature is cluster mode. This mode creates multiple processes for the app and load balances requests to each process. This is potentially beneficial if we want to vertically scale by using all the available cpus on our instances.

**Comment by rhiannareechaye** [comment]
Moving this to the backlog as (out of our non-OKR work) I don't think this takes priority (Akka + AWS stacks are more of a priority) - please shout if you don't agree with this assessment though

**Comment by arelra** [comment]
Testing pm2 cluster mode is wip: https://github.com/guardian/dotcom-rendering/pull/8789

So lets park removing it for now.

**Comment by arelra** [comment]
### Pros

- production proven process manager.
- provides resume from failure, restarts, logging, monitoring (not used currently) and cluster mode ([PR](https://github.com/guardian/dotcom-rendering/pull/8929))
    - cluster mode would utilise all the CPUs available on our instances which should reduce rendering latency

### Cons

- mo dependencies mo problems
    - CVEs although all current ones have been resolved
    - version updates are infrequent
- we don't use most of the features that pm2 offers - at least anymore.
- we have a [proposal](https://github.com/guardian/dotcom-rendering/compare/ash/Multithread?expand=1) from @AshCorr  to create our own wrapper over Node's cluster mode (which is what PM2 also abstracts).

### Strawman proposal for next steps


- go ahead with pm2's cluster mode to assess performance and any potential issues
- use the locally pm2 dependency and not the version baked into the AMI

- work on our own wrapper over Node's cluster mode which we can test using the same [load testing harness](https://github.com/guardian/dotcom-rendering/pull/8789/files#diff-0be936cb2f009b0b1374d584ffd6af952dd67da9b5f4b4434bdf42d9443b95d8) used to analyse pm2's cluster mode.
- remove pm2 if our custom version of cluster mode has no issues
