### ISSUE TITLE
Trail text not bold when it should be

### ISSUE THREAD

**Issue by ioannakok** [guardian/dotcom-rendering#8192]
Tools:

![Image](https://user-images.githubusercontent.com/19683595/251697257-92b39e00-6de0-4949-a259-a962fe656750.png)

DCR:

![Image](https://user-images.githubusercontent.com/19683595/251697331-58aa6c66-1b57-4229-bc46-f49e01286fc0.png)

DCR DOM:

![Image](https://user-images.githubusercontent.com/19683595/251697419-34e3465d-a644-4801-9740-8c624edacc98.png)

**Comment by ioannakok** [comment]
The `trailText` is set here: https://github.com/guardian/dotcom-rendering/blob/main/dotcom-rendering/src/components/Card/Card.tsx#L537-L538

`font-weight: bold` gets overriden by `font: inherit` coming from the [resets](https://github.com/guardian/csnx/blob/8a1e22c413d07c522dead9af23478264f9361acb/libs/%40guardian/source-foundations/src/utils/resets.ts#L83):

<img width="542" alt="image" src="https://github.com/guardian/dotcom-rendering/assets/19683595/ae333041-d2e5-4d09-879b-d40740207ab6">

To fix this we'll have to do what @DanielCliftonGuardian did [here](https://github.com/guardian/dotcom-rendering/pull/7956#pullrequestreview-1498599108).

**Comment by rhiannareechaye** [comment]
Closed as fixed
