### ISSUE TITLE
[User help report]: Website is consuming a lot of CPU on reader's device

### ISSUE THREAD

**Issue by ioannakok** [guardian/dotcom-rendering#8193]
This was sent by an email to user help:

> I need to disable Javascript while visiting your site since it is chewing up a fair amount of my CPU, even when I'm not interacting (scrolling, etc.)
>
> I have a hefty laptop so it's not impacting my other work but I don't want to have the fan running all the time.
>
> You have some control on your pages (and it seems to be all of them) that is cycling too frequently. If you want I'm happy to research this using Firefox's (or other's) developer tools. Just don't want to waste my time if you're not interested in fixing the issue.
>
> Thanks - copied from my clipboard:
>
> Browser Information:
Device: - Windows 10
Browser: Firefox 114.0
Window Size: 1562 x 666
Screen Size: 1728 x 972
Adblocker status: On
Cookie Information:
gu_hide_support_messaging: unset
gu_digital_subscriber: unset
gu_paying_member: unset
gu_recurring_contributor: unset
Account Information
Digital subscription end date:
Show supporter messaging: false
Content Access - member: false
Content Access - paidMember: false
Content Access - recurringContributor: true
Content Access - supporterPlus: false
Content Access - digitalPack: false
Content Access - paperSubscriber: false
Content Access - guardianWeeklySubscriber: false
Content Access - guardianPatron: false

**Comment by alinaboghiu** [comment]
No further reports
