### ISSUE TITLE
Reader Revenue and Braze banners not showing on DCR Fronts

### ISSUE THREAD

**Issue by georgeblahblah** [guardian/dotcom-rendering#8194]
These banners are implemented in the [`StickyBottomBanner`](https://github.com/guardian/dotcom-rendering/blob/main/dotcom-rendering/src/components/StickyBottomBanner.importable.tsx) component. For articles, this is placed on the layout.

We are not currently rendering the banner for Fronts, but we should do.

**Comment by rhiannareechaye** [comment]
https://github.com/guardian/dotcom-rendering/pull/8196 - this doesn't get banners rendering, but it does get the Braze messaging/cleanup code running on DCR fronts.

**Comment by rhiannareechaye** [comment]
I have asked for an update on the P&E/Supporter Rev channel

**Comment by rhiannareechaye** [comment]
Fixed by https://github.com/guardian/dotcom-rendering/pull/8215
