### ISSUE TITLE
Create testing plan

### ISSUE THREAD

**Issue by rhiannareechaye** [guardian/dotcom-rendering#8216]
Roll out  - OKTA release plan ([example](https://docs.google.com/document/d/1PisYFY-0veTGZTYaBJ4lwbMGaJzUo7o5zsIq_y_mcPM/edit) of a previous one) 
What do we need to do before any tests start? 
What checks do we want to do when we ramp out % 
Other measures that we want to do at some point (e.g. Cypress) 

James to look at the scenarios that we went through before to turn them into test cases

**Comment by VDuczekW** [comment]
who do we need to reach out to for dashboards:
Identity 
Commercial 
T&C 
Discussion 
We want a list of dashboards for us to check 

- when token refresh fails - how do we see that - at what rate do those events fail 
- exceptions logging from library? 
- create more explicit logging - please list what we are then capturing 
- Use sentry 

how do we then test - we are happy with manual testing 
we then go to 1%? - Monitor - up

**Comment by jamesgorrie** [comment]
Okta is done!
