### ISSUE TITLE
Most viewed footer layout top padding off with pageskin

### ISSUE THREAD

**Issue by DanielCliftonGuardian** [guardian/dotcom-rendering#8224]
Between leftCol and wide the top padding is off the title is overlapping this is when pageskin is present.

![Image](https://github.com/guardian/dotcom-rendering/assets/110032454/e43ac531-d8bb-48c0-b6ea-b96321780ff0)

**Comment by arelra** [comment]
If it helps - when there's a page skin we need to _not_ apply any leftCol or wide layout styling
