### ISSUE TITLE
`WeatherController` throws a lot of 5xx

### ISSUE THREAD

**Issue by ioannakok** [guardian/dotcom-rendering#8233]
After [this change](https://github.com/guardian/fastly-edge-cache/pull/1000) got deployed, we are seeing a spike in 5xx from the `WeatherController`:

From [SLI dashboard](https://metrics.gutools.co.uk/d/zM0ouzs4z/sli-dashboard-debug-view?orgId=1&var-AWSAccount=frontend&var-Service=frontend-PROD-onward-ELB)

![Image](https://user-images.githubusercontent.com/19683595/252725258-b1e9676e-7ec7-43f0-91af-83670bf81791.png)

https://logs.gutools.co.uk/s/dotcom/goto/596f1040-1ffa-11ee-8045-5554bf78223c

![Image](https://user-images.githubusercontent.com/19683595/252725808-99c418db-054b-4c89-9a52-56ab38bc1179.png)

error thrown:

![Image](https://user-images.githubusercontent.com/19683595/252725925-2d4d9c41-1905-42ec-9c5c-79b05aed4b6d.png)

from [`WeatherController`](https://github.com/guardian/frontend/blob/main/onward/app/weather/controllers/WeatherController.scala#L89-L95).

**Comment by abeddow91** [comment]
For a first response fix, we have added a fallback to get the weather from the edition
