### ISSUE TITLE
Bonzai ad pageskins are causing AU/UK homepages to appear as blank

### ISSUE THREAD

**Issue by abeddow91** [guardian/dotcom-rendering#8237]
Aus have been reporting an issue where the UK homepage from there looks blank on desktop. 
This has been difficult to replicate. 

"The issue on the Home page is inconsistent and seems to happen when switching between different editions. We havent been able to replicate the same on other index pages/article from any of the Truskin ads"

There’s an email chain on this with the subject line is “homepage is blank”. 
Initial work from central prod in Aus suggests it might be a DCR issue

The issue was first reported around 23.36 BST wed 12 July

**Issue detected in debugging - James Gorrie and Anna Beddow**

We were able to replicate this in the UK using a AU (Sydney) VPN and visiting www.theguardian.com/uk. It only seemed occur when the [`The Off Season` ad appeared](https://www.discovertasmania.com.au/off-season?utm_medium=display&utm_source=yahoo&utm_campaign=offseason_inter_aws&utm_content=beach_theguardian).

The issue is caused by a `bz-custom-container` element covering the content. Deleting this element from the DOM reveals the front content underneath. This container is specific to Bonsai Truskin ad. 

This issue has now been passed across to Ashish Puliyel, who'll be taking this forward

![Image](https://user-images.githubusercontent.com/20416599/252906883-90206c6f-4e38-4b71-8be6-0fa12f86c943.png)

![Image](https://user-images.githubusercontent.com/20416599/252904964-03816917-d462-46a0-94fc-b4ced5089fd4.png)

**Comment by arelra** [comment]
From @Amouzle 

It's an edge case where we have a UK page skin and an Australian browser goes onto the UK edition... and there is an Australia Pageskin. 

Thankfully, it can be resolved in Ad Manager - we're sending Aus the details now.

**Comment by arelra** [comment]
Closing as this will be picked up by the Aus ad ops team and Bonzai
