### ISSUE TITLE
Address branding comments from previous PR

### ISSUE THREAD

**Issue by jamesgorrie** [guardian/dotcom-rendering#8244]
On this PR https://github.com/guardian/dotcom-rendering/pull/8242

- [ ] https://github.com/guardian/dotcom-rendering/pull/8242#discussion_r1261215865
- [ ] https://github.com/guardian/dotcom-rendering/pull/8242#discussion_r1261205791
- [ ] Improve size 
- [ ] Add some padding below the image

### Size
<img width="415" alt="image" src="https://github.com/guardian/dotcom-rendering/assets/19683595/a6f978a6-c432-4c7c-a436-fc196e71f899">

### Padding

frontend:
<img width="261" alt="image" src="https://github.com/guardian/dotcom-rendering/assets/19683595/5cc48530-919c-4016-98e1-713d170f0d4c">

DCR:

<img width="280" alt="image" src="https://github.com/guardian/dotcom-rendering/assets/19683595/3339196d-b64b-4de3-9849-90e9c2cc8e37">

**Comment by alinaboghiu** [comment]
Fixed in separate PRs
