### ISSUE TITLE
AR Ads Overlapping Blocks On Deadblogs

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#8271]
For deadblogs on AR, from the desktop breakpoint and above, ads are overlapping the blocks in the timeline. Reported by @glockett, and reproducible.

For examples of deadblogs go to: https://www.theguardian.com/tone/minutebyminute

![ad-overlap](https://github.com/guardian/dotcom-rendering/assets/53781962/7910255d-03cc-4d51-b51f-cdacd9be8a14)

**Comment by alinaboghiu** [comment]
Will move to DCR 
Not sure if we have liveblog in editions so please reopen if still needed
