### ISSUE TITLE
On mobile some fronts bounce the user back to the browser when they click to "Open" in the app

### ISSUE THREAD

**Issue by ioannakok** [guardian/dotcom-rendering#8273]
Bug reported by Matthew Holmes in the WebEx chat and confirmed by @cemms1 (both using iphone 12 mini / Charlotte's on Safari on iOS 16.5.1)

Quoting Charlotte here:

Some fronts it happens for me on are:
- womens world cup 2023
- womens world cup 
- football live scores
- football fixtures
- football results
- football clubs

It doesn't happen on these fronts:
- football
- books (also can't find a non football-related front this happens on yet) 

https://github.com/guardian/dotcom-rendering/assets/19683595/8b03f2a6-7608-4fb7-a2f1-cd22fa8ae96f

**Comment by alinaboghiu** [comment]
I think this is a native issue described in this thread, which also links to their open issue:
https://groups.google.com/a/guardian.co.uk/g/dotcom.platform/c/Q-Vk8sdjHyE/m/iAJVqLHgBQAJ

closing as it should be fixed natively
