### ISSUE TITLE
Blockquote styles incorrect

### ISSUE THREAD

**Issue by groakland** [guardian/dotcom-rendering#8333]
https://mobile.guardianapis.com/rendered-items/lifeandstyle/2023/jul/07/inside-britains-tiniest-places-its-an-engineering-work-of-art-with-coffee

https://mobile.guardianapis.com/rendered-items/politics/2022/sep/06/boris-johnson-likens-himself-to-roman-cincinnatus-who-returned-as-dictator?editions

**Comment by alinaboghiu** [comment]
no longer rendering these with AR
