### ISSUE TITLE
Video play icon shifts on hover

### ISSUE THREAD

**Issue by sophie-macmillan** [guardian/dotcom-rendering#8336]
The play icon on a video card moves left and right by 1 or 2px as you hover in and out of a video card

https://user-images.githubusercontent.com/26366706/255139925-d9d52ccb-4e9a-43fa-a571-d29ac22f44fc.mov

**Comment by paperboyo** [comment]
While at it, we should [optically centre](https://medium.com/design-bridges/optical-effects-9fca82b4cd9a#f9d2) the triangle within the circle.
