### ISSUE TITLE
Women's world cup results are 3 days old

### ISSUE THREAD

**Issue by cemms1** [guardian/dotcom-rendering#8373]
The interactive/snap on this page is showing the results from three days ago: https://www.theguardian.com/football/womens-world-cup-2023
![image](https://github.com/guardian/dotcom-rendering/assets/43961396/2158f3a7-88fe-40c3-9b10-0348807ae40c)

Compared with the table on this page https://www.theguardian.com/football/womens-world-cup/overview (which is frontend-rendered)
<img width="1317" alt="image" src="https://github.com/guardian/dotcom-rendering/assets/43961396/4b8df453-2f60-4050-9f49-444c5a4c2ceb">

**Comment by jamesgorrie** [comment]
This was fixed with by following [this readme](https://github.com/guardian/csti-interactives/blob/e21765f5302b5827ef7e14e935d09a53078613bf/atoms/webex/football-atoms-collection/README.md?plain=1#L28-L41), with extras, that we will add to the internal Google Docs doc.
