### ISSUE TITLE
Use date for location of client not general edition 

### ISSUE THREAD

**Issue by cemms1** [guardian/dotcom-rendering#8378]
As a follow up from #8371, Editorial have requested that we use the "real" location of a user to get the date according to their time-zone, rather than the value for edition.

**Comment by jamesgorrie** [comment]
> Editorial have requested that we use the "real" location of a user

This wouldn't be possible as it would require us to split the cache on `region` which would be way to fragmented. We _could_ add the date async and use an endpoint similar to `/weather.json` where [we do split the cache on regional data](https://github.com/guardian/fastly-edge-cache/blob/ed2c72c9397dbed07a739b7f9756eaaea2e2a3a5/services_guardian_apps/src/main/resources/varnish/main.vcl#L257-L271), but we have seen how fraught that is, so think we **shouldn't**. 

I think the logic of frontend makes sense just to clarify this is: We choose a timezone based on edition, which is [initially set from your geolocation](https://github.com/guardian/fastly-edge-cache/blob/ed2c72c9397dbed07a739b7f9756eaaea2e2a3a5/theguardiancom/src/main/resources/varnish21/geo.vcl#L63)

Once this is done, we can decide what value we get if we want to be more specific about this.
