### ISSUE TITLE
[EPIC] What does the vendor list need to look like?

### ISSUE THREAD

**Issue by rhiannareechaye** [guardian/dotcom-rendering#8380]
2: Figure out what the native vendor list needs to look like (Emily T + James G & anyone else who wants to be involved to work through this with Data Privacy) 
The vendor lists are different. We should probably compare them and determine if things need to be moved from one to the other to support this. 
WebX to pull together a list of what technologies/vendors that are used on the web + what would we actually want to use (note there’s a problem with putting things on the cookie banner if the project hasn’t launched; we can’t put it in ahead of time for example). We need to make sure we’re asking for consent for things that are only used on articles (not on dcr in general e.g. fronts)  
If we can, we assume merging the vendor lists on apps so it covers apps+web would cover all bases 
Could be an entirely new vendor list for this purpose.

**Comment by rhiannareechaye** [comment]
https://docs.google.com/spreadsheets/d/1l8IW-56SKWgzMsHB0yyK6Z4gccEMalIEWEEJ037JQKg/edit#gid=0

**Comment by VDuczekW** [comment]
@jamesgorrie please reach out to Emily and see who is working on this piece

**Comment by VDuczekW** [comment]
Emily will put a new list together and then we can discover what we need to include - it is still unclear who will make the 'call'

**Comment by theemilyturner** [comment]
I've completed:

-list of all vendors across all
-identified those that are on web but not on app
-identified those marked as essential on web
-categorised those essential ones with what I believe we are using them for

https://docs.google.com/spreadsheets/d/1l8IW-56SKWgzMsHB0yyK6Z4gccEMalIEWEEJ037JQKg/edit#gid=1175437152

**Comment by VDuczekW** [comment]
@jamesgorrie & @JamieB-gu to review and decide next steps

**Comment by VDuczekW** [comment]
meeting scheduled for next steps

**Comment by VDuczekW** [comment]
closing this item of analysis work will be completed under #8557   @JamieB-gu, @theemilyturner @jamesgorrie
