### ISSUE TITLE
DCR for Apps - How do we serve ads in the app

### ISSUE THREAD

**Issue by rhiannareechaye** [guardian/dotcom-rendering#8381]
Make a decision about ads in apps (investigative piece with mix of engineering and business) 
Note that as per [our plan -](https://docs.google.com/presentation/d/1MgYcyU14o8rXuL7eFdTBw7Mm1wn3ptU1TluBxQNYh_o/edit#slide=id.g25870f0c6d4_1_9) we won’t get onto the ad implementation till the end of the quarter
Fundamentally we should go with what's easier and fastest to implement first, and then follow that up with the better solution commercially. At this stage I don't know if that's native or web-rendered ads.
Note from Ravi: If_ we can get consent state passing successfully from native to web then I think going fully web ads and videos is an easier path as that is what DCR does already and should mean minimal changes/specialisation for DCAR. But I defer to the team closer to DCAR.
What are the downsides of having two ways of rendering ads in the app (native for non-articles) 
We’re assuming that if we figure out option 1, we’ll be okay but we should try to validate this

**Comment by rhiannareechaye** [comment]
Hey @arelra I've been away for a bit so trying to catch up. Would you mind giving a bit of an update on this epic - did it get covered in the consent spike, do we need to set up another spike etc?

**Comment by arelra** [comment]
Hey @rhiannareechaye sure.

So far we have completed:

- a spike to prove that we can pass consent from the native layer to the web layer

We are in the process of:

- amalgamating the vendor lists which is with T&C

What is pending is deciding what level of tracking we can enable for web based ads on DCAR:

- understanding what Apple and Google's tracking prevention frameworks / policies mean for ads in the web layer on DCAR. It might mean that we have to narrow what tracking is allowed to happen on DCAR. Alex Amoui and myself are talking to Petter about this to understand the policies better.

I think its a good idea to create a spike for the 'DCAR ad tracking' work to we can (er...) track it.

**Comment by jamesgorrie** [comment]
This seems like we might need to spike this from a "web ads" POV, but we are tracking the ads work in this Epic #8744
