### ISSUE TITLE
Launch the Deeply Read A/B test on the 14th of August

### ISSUE THREAD

**Issue by rhiannareechaye** [guardian/dotcom-rendering#8396]
https://docs.google.com/document/d/1Lg4rZpprqrD52vllknsQaz7Po4MHUHj9dTGAtOk0brs/edit

- [x] Confirm that Marjan has added an A/B test to this 
- [x] Confirm that Anthony doesn't need anything before we set the test for his data analysis 
- [x] Confirm that Chris M is aware this is going live (I've already run it past him so would be good to give him a heads up) 
- [x] Let the Digieds know this is happening (I'll ask Max Walker to do this) 
- [x] Let CP know this is happening

**Comment by marjisound** [comment]
The deeply read AB test (50/50) was added through these PRs:
- https://github.com/guardian/frontend/pull/26418
- https://github.com/guardian/dotcom-rendering/pull/8439

The switch to enable the test is called `deeply-read`

When the test is enabled, the 2 variants are:
- deeplyReadVariant: Variant
- deeplyReadControl: control

**Comment by marjisound** [comment]
Details about the tracking can be found here: https://docs.google.com/document/d/1pflzKXwuEr-oh4ifOdqcCcTnDRUsY57B455Qy1j1P9o/edit

**Comment by VDuczekW** [comment]
not blocked - with Marjan - not with Web X team 'to do' - Marjan will send comms today and test on schedule to be put live on Monday

**Comment by VDuczekW** [comment]
test switched on
