### ISSUE TITLE
Fix dot navigation above left col on the carousel container for larger card carousels (eg video)

### ISSUE THREAD

**Issue by abeddow91** [guardian/dotcom-rendering#8419]
When the breakpoint is above left col, the dot navigation on carousel sits in the left col. At this point, the dot navigation has too few dots; it should reflect the number of cards in the carousel.  

This appears to be fine in all other breakpoints

**Comment by rhiannareechaye** [comment]
I'm closing this ticket as we need to prioritise other essential health tickets this q - lets rediscuss if the issue comes up again
