### ISSUE TITLE
Sections at the bottom of AMP articles are cutting off text

### ISSUE THREAD

**Issue by abeddow91** [guardian/dotcom-rendering#8420]
![Image](https://user-images.githubusercontent.com/20416599/257257088-368ca848-1ea7-478f-9c7e-26c54c830435.jpg)

https://mail.google.com/chat/#chat/space/AAAAG9rU0m0/F-A1UJEphn8 reported 31/July/23

**Comment by rhiannareechaye** [comment]
Closing as it's a replica of: https://github.com/guardian/dotcom-rendering/issues/8421
