### ISSUE TITLE
Sections at the bottom of AMP articles have the wrong font

### ISSUE THREAD

**Issue by abeddow91** [guardian/dotcom-rendering#8421]
![Image](https://user-images.githubusercontent.com/20416599/257257088-368ca848-1ea7-478f-9c7e-26c54c830435.jpg)

https://mail.google.com/chat/#chat/space/AAAAG9rU0m0/F-A1UJEphn8 reported 31/July/23

**Comment by rhiannareechaye** [comment]
Closing this ticket - as per the email in the screenshot, we are only fixing urgent amp issues

![Image](https://github.com/guardian/dotcom-rendering/assets/93542262/086a13bb-2830-4d60-874c-585d2ccb7eed)
