### ISSUE TITLE
Don't use default VPC ID

### ISSUE THREAD

**Issue by cemms1** [guardian/dotcom-rendering#8429]
We should update our infra to not use the default VPC for security reasons post #7624 

See comments on #8417 

Ref: https://github.com/guardian/recommendations/blob/636bbcf55a0bf47273ede2d70bad0ac08e448bca/AWS.md?plain=1#L44

**Comment by jamesgorrie** [comment]
[The VPC is defined in the platform project](https://github.com/guardian/platform/blob/main/provisioning/cloudformation/frontend-vpc.yaml) - so out of scope of this work.
