### ISSUE TITLE
Separate out badge from branding logic in front containers

### ISSUE THREAD

**Issue by cemms1** [guardian/dotcom-rendering#8435]
There's a `decideBadge` function used in `enhanceCollections` which adds a badge definition to each container. It considers sponsored badges to behave similarly to editorial badges, but after a [bit of investigation](https://docs.google.com/document/d/1yPCmjz33SahtVrzT-7E8Iau6hoo46YFUgLDBJJSJwJw/edit?usp=sharing), this isn't quite true.

To make this distinction between sponsored and editorial badges clear, we should ensure there is no danger of mixing them up.

This allows the commercial team to adapt paid content containers without fear of changing how badges  appear in other containers.

**Comment by jamesgorrie** [comment]
@cemms1 was this fixed here?
https://github.com/guardian/dotcom-rendering/pull/8242
