### ISSUE TITLE
H2s misbehaving on photos essays on AMP articles

### ISSUE THREAD

**Issue by abeddow91** [guardian/dotcom-rendering#8467]
bullet captions and H2 text on photo essays no longer perform correctly on mobile. The captions double up and the H2 headers don’t sit on the photos like they should. This issue may be specific to amp.theguardian which in my case is being viewed on an iPhone.

from Matt Fidler, forwarded to WebEx by Lily Smith 

![Image](https://github.com/guardian/dotcom-rendering/assets/20416599/ec8f5439-1e56-4eb1-aa6f-35db2f4b1e08)

**Comment by jamesgorrie** [comment]
Given the solution to this on DCR has to hack the source data (captions on photo essays are a hack) - we don't want to have to maintain this on the AMP project which is in maintenance mode.
