### ISSUE TITLE
Images not loading

### ISSUE THREAD

**Issue by abeddow91** [guardian/dotcom-rendering#8470]
Three reports from readers who are having trouble with images not loading properly. All of the complaints I've seen are from Mac users 
- Mac OS X 10.5.7, Safari 16.
-  MacOS 12.6.8, Safari 16.6
-  Mac OS X 12.6.7, Safari v 16.5.2

Notable that all OS' are pre 13.X (ventura).

Initially suspicions that this is todo with AVIF support on older MacOS. this should be tested in browserstack to verify (although a quick check suggests browserstack wont let you use those OS versions with safari 16)

@mxdvl did work on AVIF so might be a useful person to speak to.

@mateusz suggested if it is to do with avif, we could ask Fastly if they had any reports/put in mitigations, or, maybe, we could mitigate in VCL?

![Image](https://user-images.githubusercontent.com/20416599/258126020-d5b067ae-9e0c-49be-b5cd-5b87bb43528b.png)
![Image](https://user-images.githubusercontent.com/20416599/258126019-8aa5b315-eea3-4a42-9188-d8e03c936384.png)

**Comment by mxdvl** [comment]
Looks similar to reports in [this thread on Apple Discussions](https://discussions.apple.com/thread/254766633?answerId=254766633021)

**Comment by mxdvl** [comment]
We’ve had some reports that upgrading iOS / Safari versions seem to fix the issue, but nothing definitely conclusive yet…

There is no strong indication that this is caused by our move to AVIF, despite the strong time correlation.

**Comment by mxdvl** [comment]
We’ve disabled AVIF for Safari on macOS as of this morning. Hopefull this reduce the number of reported issues.

**Comment by mxdvl** [comment]
> We’ve disabled AVIF for Safari on macOS as of this morning. Hopefully this reduce the number of reported issues.

This did the trick… we might need to revisit in the future if we can start serving AVIF to Safari browsers again.
