### ISSUE TITLE
Sublinks don't have a big enough clickable area

### ISSUE THREAD

**Issue by sophie-macmillan** [guardian/dotcom-rendering#8490]
Pre DCR, the whole sublink part of the card linked through to the sublink (second image).

After the migration, it seems to click through to the card - not the sublink.

It's not an issue on desktop because you're clicking with a pointer, or on app because it works like in the bottom image, it's a right pain on mobile web right now.

![Image](https://user-images.githubusercontent.com/26366706/258731428-bee7cd70-c714-4047-88c7-7d810abc15c7.png)

**Comment by paperboyo** [comment]
Related to https://github.com/guardian/dotcom-rendering/issues/8425.
