### ISSUE TITLE
Video cards showing different images for signed in/out users

### ISSUE THREAD

**Issue by sophie-macmillan** [guardian/dotcom-rendering#8519]
We seem to get a trail image displaying on stories with video as main media when readers are not logged in (and viewing the front in preview), but for logged-in readers (if video is showing/playable) it seems to show a still from a video.

Screenshots below show the difference for the "Caught on Infrared" story 

**Logged in (video thumbnail)**

![Image](https://github.com/guardian/dotcom-rendering/assets/26366706/db5bc002-7bbb-43f7-8645-825e5380df25)

**Logged out (video still)**

![Image](https://github.com/guardian/dotcom-rendering/assets/26366706/bf580f1f-17d7-4269-9283-795da88dafe6)

**Comment by paperboyo** [comment]
Could it not be sign-in status, but the fact that cards are different size (large can play in situ, small – can’t). If that’s true, there is sorta-related [chat thread](https://chat.google.com/room/AAAA5nTgD0E/v5o903K-fpc) [archived space].

**Comment by paperboyo** [comment]
> Could it not be sign-in status

Most recent email report (“Video carousel titles on the front”, 22 Aug 2023, 00:19) suggest I was wrong and it indeed may be logged in state?
