### ISSUE TITLE
Expired callouts don't render on DCR

### ISSUE THREAD

**Issue by abeddow91** [guardian/dotcom-rendering#8538]
This bug was discovered through investigating #8444 

If a callout has expired, DCR *should* render a calloutExpired component.

**How do callouts work and why isn't this happening?**
When a callout is added to an article, a callout block element is stored in CAPI with a callout ID.

Frontend has a cache of campaigns which it retrieves from the targeting tool. Crucially, it only asks for active campaigns from the targeting tool.

During parsing, Frontend checks if the campaign id on the callout block element is stored in the cache. If it is, great! and we pass through a callout block element to DCR. If it isnt, the element is ignored and DCR has no idea there was ever a callout in the article. 

This is a problem as it means we never render a calloutExpired message to end users.

**Comment by abeddow91** [comment]
Possible options:

1. change the api call to return all callouts (active and expired)
This means our cache could grow indefinitely. Also, what would happen if a callout is deleted? it would still be absent without cause to the end user
2. We make a second call to the targeting tool *if* the callout is missing from the cache. This would allow us to pass additional information with the callout to the renderer eg 'expired' or 'missing' 
3. We store the active until date in CAPI and use that to validate if the callout is expired if the callout is missing from the cache. This doesn't work because updates in the targeting tool don't thread through to CAPI (which is a main reason for the cache).
4.

**Comment by rhiannareechaye** [comment]
Thanks for the detail in this ticket. Callout work is not currently prioritised in the webx team so I'm going to close this ticket for now. That being said, let's keep an eye on this, if we start to get reader feedback on it, or we start to see lots of responses to old call outs, the lets try and revisit as part of our healthwork

**Comment by rhiannareechaye** [comment]
FYI there has been a manual workaround created now ... as agreed with Matt, Caroline and Jonathan, the text below will be manually added when a callout has finished. 

```
H2 This Community callout closed on day Month Year.
Bullet point bold: You can see the article that included respondents to this callout here.  (only if appropriate)
Bullet point bold: You can contribute to open Community callouts here or Share a story here. 
```

It's not ideal to do this manually, so we'd love to come back to this issue if community becomes a priority again, or if we have time in future health weeks etc.
