### ISSUE TITLE
Migrate youtube atom to DCR

### ISSUE THREAD

**Issue by abeddow91** [guardian/dotcom-rendering#8541]
Spotted by @paperboyo on 10 aug '23.

The Youtube embed atom does not follow standard practice when it comes to images. They don’t go via fastly resizer, so they are massive, use naked Grid crops which are poorly optimised, can’t be AVIF etc, etc.

The atom is used in multiple places, on fronts in the video carousel and on playable front cards, and wherever we have embedded video in articles.

This is potentially low hanging fruit for improving load times of fronts and articles.

**Comment by arelra** [comment]
`@joecowton1` has a PR to migrate YoutubeAtom over to DCR which should allow us to use DCR's  optimised `Picture` component. It's almost complete with the exception of a storybook issue. Joe handed it over to me so I can liaise with whoever picks up this work.

https://github.com/guardian/dotcom-rendering/pull/8231

**Comment by shesah** [comment]
@AshCorr could you please split out the ticket to capture the work done for the migration?
