### ISSUE TITLE
[Bug]: Star ratings are overlapping timestamps at lower breakpoints

### ISSUE THREAD

**Issue by DanielCliftonGuardian** [guardian/dotcom-rendering#8549]
### What happened?

This is a frontend issue on tag fronts, the tag fronts have not yet been migrated to DCR and this will no longer be an issue when the work is completed and these fronts are rendered by DCR.

![Image](https://github.com/guardian/dotcom-rendering/assets/110032454/1261bb2d-33d5-472d-b636-696b18dc7496)

### Where is this happening?

https://www.theguardian.com/stage/edinburgh-festival-2023

**Comment by shesah** [comment]
Tag fronts are not in production yet but when they are, this will be resolved so for now, it's not a high priority.

**Comment by rhiannareechaye** [comment]
Closing this ticket - as Shervin says it will be resolved by tag fronts roll out
