### ISSUE TITLE
[Bug]: Preload headers not set for DCR assets and frontend assets still being downloaded

### ISSUE THREAD

**Issue by DanielCliftonGuardian** [guardian/dotcom-rendering#8550]
### What happened?

DCR fronts are still initiating downloads of frontend JavaScript ( `graun.standard` etc). This appears to be due to the absence of updated preload headers. The browser downloads frontend JavaScript on DCR fronts, and DCR assets aren't preloaded in this way. We should update the preload headers.

See https://github.com/guardian/frontend/blob/main/common/app/http/ResultWithPreconnectPreload.scala

See thread https://chat.google.com/room/AAAAG9rU0m0/tYnigeQMNbg

### Where is this happening?

https://www.theguardian.com/uk

**Comment by rhiannareechaye** [comment]
Thanks for opening the bug - I assume the impact here is one of Fronts performance. Do we think this would be a high impact ticket @georgeblahblah?

**Comment by rhiannareechaye** [comment]
Had a quick chat with James and because it's a performance related bug, we think it's best to prioritise this

**Comment by georgeblahblah** [comment]
Fixed in https://github.com/guardian/dotcom-rendering/pull/8657 and https://github.com/guardian/frontend/pull/26523
