### ISSUE TITLE
Productionise the passing the apps consent in to dcr rendered articles

### ISSUE THREAD

**Issue by VDuczekW** [guardian/dotcom-rendering#8555]
Isolated demo has been done now we need to bring it into DCR
 - in principle it works 
 - but unknown how long - it is complicated - it either works and swiftly implemented or a lot of tinkering
Olli is going to circulate docs and add here

**Comment by VDuczekW** [comment]
not blocked - but WebX not actively working on this - it is with T&C

**Comment by shesah** [comment]
Closing this ticket - The T&C team have some work to do on this and then that may create some work for us around consent in App on DCR, which we can create new tickets for.
