### ISSUE TITLE
optimisation: Phases >1 (CDK)

### ISSUE THREAD

**Issue by ParisaTork** [guardian/dotcom-rendering#8556]
Phase 1 of the CDK Migration (#7614) was a 1:1 migration and will allow us to work more effectively on improving our infrastructure since the incidents (https://github.com/guardian/frontend/issues/26335, #8351,  #8345). In this process, we (@cemms1, @DanielCliftonGuardian and I) noticed some optimisations that we can make. This issue formalises all of them in one place, so we can refer to it later when we undergo further phases:

- [ ] [Changing CIDRs](https://github.com/guardian/dotcom-rendering/pull/8417#discussion_r1282221773), so EC2 instances are launched in different subnets
- [ ] Adopting a pattern rather than constructs
- [ ] [Adopting a user data construct](https://github.com/guardian/dotcom-rendering/pull/8507#discussion_r1286988283) - wonderfully suggested by @DanielCliftonGuardian 
- [x] Refactoring S3 bucket names (completed by @cemms1 [here](https://github.com/guardian/dotcom-rendering/pull/8526))
- [ ] [Renaming the app](https://github.com/guardian/dotcom-rendering/pull/8428#discussion_r1282914400)
- [ ] [Cleaning up policies](https://github.com/guardian/dotcom-rendering/pull/8495#discussion_r1286906741)
- [ ] [Adopting ALBs](https://github.com/guardian/dotcom-rendering/pull/8501#discussion_r1290986750)
- [ ] More parametrisation of values (all) e.g. [here](https://github.com/guardian/dotcom-rendering/pull/8507/files#r1286950320)
- [ ] Adopting target tracking, rather than simple scaling [here](https://github.com/guardian/dotcom-rendering/pull/8512) and [here](https://github.com/guardian/dotcom-rendering/pull/8514#discussion_r1290984739)

**Comment by ioannakok** [comment]
Closing this ticket as the work has been split to other tickets. See:
* https://github.com/guardian/dotcom-rendering/issues/9374
* https://github.com/guardian/dotcom-rendering/issues/9310
* https://github.com/guardian/dotcom-rendering/issues/9320
* https://github.com/guardian/platform/issues/1545
