### ISSUE TITLE
Update apps vendor list with new web vendors

### ISSUE THREAD

**Issue by VDuczekW** [guardian/dotcom-rendering#8557]
I've completed:

-list of all vendors across all platforms
-identified those that are on web but not on app
-identified those marked as essential on web
-categorised those essential ones with what I believe we are using them for

https://docs.google.com/spreadsheets/d/1l8IW-56SKWgzMsHB0yyK6Z4gccEMalIEWEEJ037JQKg/edit#gid=1175437152

see Spike work on [[EPIC] What does the vendor list need to look like?#8380](https://github.com/guardian/dotcom-rendering/issues/8380)

**Comment by VDuczekW** [comment]
#8380

**Comment by VDuczekW** [comment]
to create tickets from the spreadsheet

**Comment by rhiannareechaye** [comment]
Hey @VDuczekW and @JamieB-gu should this become an EPIC with tasks from the spreadsheet? Happy to set this up if that helps

**Comment by jamesgorrie** [comment]
Closing in favour of https://github.com/guardian/dotcom-rendering/issues/8569
