### ISSUE TITLE
Dropcap Misalignment In Apps

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#8595]
The top of the dropcap should be aligned with the x-height of the text (the top of the letters "a", "c", "e" etc.):

![dropcap-misalignment](https://github.com/guardian/dotcom-rendering/assets/53781962/0b3dc87d-5e28-4d3b-ac77-419b52bbb537)

Speak to @HarryFischer for more guidance and a design review. The code governing this can be found here: https://github.com/guardian/dotcom-rendering/blob/628ef0d51324a50407f2b4582c9c8135b79002e4/apps-rendering/src/components/Paragraph/index.tsx#L51-L71

**Comment by rhiannareechaye** [comment]
Thanks for raising this ticket - since it's AR I'll close it as we should be prioritising DCR for Apps, but good to have the record of the issue if it comes up again
