### ISSUE TITLE
Ophan Heatmap causes Slideshows to overlap on fronts

### ISSUE THREAD

**Issue by AshCorr** [guardian/dotcom-rendering#8599]
<img width="716" alt="image" src="https://github.com/guardian/dotcom-rendering/assets/21217225/661170e3-c97b-4252-9e60-38a8f5810dbf">

As seen on https://www.theguardian.com/uk?heatmap=show

It seems like Ophan causes the first image loaded to be taller so it ends up peeking out under the rest of the images on a Slideshow

**Comment by rhiannareechaye** [comment]
Thanks for raising ash - I think for now lets deprioritise this issue in favour of the teamcity and cdk work that needs to be done, but good to have a record, and if it comes up again we should fix it

**Comment by georgeblahblah** [comment]
Similar reports of the same issue received on 22/08/2023.
