### ISSUE TITLE
Empty rich link causes DCR to error when rendering liveblogs

### ISSUE THREAD

**Issue by AshCorr** [guardian/dotcom-rendering#8678]
On the 25th Aug, 2023 [this liveblog](https://www.theguardian.com/world/live/2023/aug/25/russia-ukraine-war-live-updates-ukrainian-drones-launched-over-crimea-says-russia-us-to-train-f-16-pilots-in-october) had an abnormal rich link inserted into one of its blocks which caused DCR to error when attempting to render it.

## Invalid Liveblog Richlink

![image](https://github.com/guardian/dotcom-rendering/assets/21217225/cb522c90-dbc6-4440-97b3-73aa52d0013e)

## Resulting error

https://logs.gutools.co.uk/s/dotcom/app/discover#/doc/50201630-bd0f-11e9-92b3-f10623802d36/logstash-frontend-2023.08.25?id=OR5_LYoBA6ZvXZ0XvFDu (ta @Georges-GNM for finding it)

<img width="1207" alt="image" src="https://github.com/guardian/dotcom-rendering/assets/21217225/1cdf1202-506f-4f1a-9c2d-d2ab51201c79">

## Outcome

It seems like the invalid rich link might have had an empty `url` property which we tried to parse here https://github.com/guardian/dotcom-rendering/blob/main/dotcom-rendering/src/components/RichLinkComponent.importable.tsx#L51

the `URL` constructor throws an error if it tries to parse an invalid URL, we should try to catch this error or use a better way of getting the pathname from a URL.

**Comment by mxdvl** [comment]
Worth noting that [a falsy `url` will also prevent `useApi` from making a call](https://swr.vercel.app/docs/conditional-fetching), so it’s perfectly valid and probably ideal to return `undefined` from `buildUrl` when an error is thrown.

https://github.com/guardian/dotcom-rendering/blob/f07f66745e3b9736e89a44b70616cf7c6997cd4a/dotcom-rendering/src/components/RichLinkComponent.importable.tsx#L47-L53

**Comment by rhiannareechaye** [comment]
Nice work on the investigation and speedy fix. Lets bring this into planning later today but my thoughts are that while there is an element of risk in leaving this issue open to happening again, it's only happened once since DCR began rendering liveblogs which was maybe 18 months ago? Therefore I think the risk is so compared to our other priorities (DCR for Apps, DevX initiatives, Europe Edition, Deeply Read) this should be 'closed' as not planned, and addressed if it comes up again

**Comment by mxdvl** [comment]
The fix is only adding two small lines:

```ts
 const buildUrl: (element: RichLinkBlockElement, ajaxUrl: string) => string = ( 
 	element, 
 	ajaxUrl, 
 ) => { 
 	try {  
 		const path = new URL(element.url).pathname; 
 		return `${ajaxUrl}/embed/card${path}.json?dcr=true`; 
 	} catch (_) {
 		return undefined;
 	}
 }; 
```

**Comment by rhiannareechaye** [comment]
@mxdvl from our planning discussion i think the time-sink concern is more about being able to test the fix

**Comment by rhiannareechaye** [comment]
Closing as we don't have capacity to pick this up right now
