### ISSUE TITLE
Fronts: blogs with main media video show incorrect video

### ISSUE THREAD

**Issue by georgeblahblah** [guardian/dotcom-rendering#8679]
Live/dead blogs with a video main media can show a different video (from the same blog) on Fronts, instead of the one chosen as main media.

This is because we take the poster image from the media atom at index 0, instead of the media atom selected as main media:

https://github.com/guardian/dotcom-rendering/blob/a94ce73d8839ed44cb1b84147c9276262e2c9653/dotcom-rendering/src/model/enhanceCards.ts#L372-L375

### Adopt Frontend's approach

Frontend handles this by parsing the card's `properties.maybeContent.fields.main` property to extract the `gu-atom[data-atom-id]` attribute. It uses this value to look up the correct atom from the card's `properties.maybeContent.elements.mediaAtoms` array.

As in other places, we could use JSDOM to parse the HTML string. However, the `enhanceCards` module is used both client & server-side - JSDOM is not available client-side. We could 

- refactor `enhanceCards` to support different behaviour client/server side.
- calculate a new field in Frontend, passing this to DCR

## Useful info
- [Discovery doc](https://docs.google.com/document/d/1t22ImwEAVizOpWnv85oSQUmmNoVNC3pQ_cGTR2T3nWs/edit)

**Comment by JamieB-gu** [comment]
It looks like this problem was wider than just liveblogs: https://github.com/guardian/dotcom-rendering/issues/8733#issuecomment-1705539185
