### ISSUE TITLE
Give a gallery card in Dynamic Package the colour palette if in first slot

### ISSUE THREAD

**Issue by HarryFischer** [guardian/dotcom-rendering#8697]
https://preview.gutools.co.uk/design/uk?dcr#testt

![Image](https://user-images.githubusercontent.com/20658471/264317925-cfcbc699-666d-46de-8915-3b40ce33ff06.png)

If a gallery is in slot 1 of a Dynamic Package it displays white text on white background. Digi Eds want to start using this on the 'In pictures' container on UK front. Can we update to use the same card style as a normal gallery card. Like this:
![Image](https://user-images.githubusercontent.com/20658471/264318591-c6227653-6bf1-48c0-93ba-52bb3d7912a3.png)

**Comment by rhiannareechaye** [comment]
We can't pick this up at the moment as we have so much on our backlog, but we'll add it to our list for when we look at optimising articles and fronts from January next year
