### ISSUE TITLE
Article JS size increase

### ISSUE THREAD

**Issue by DanielCliftonGuardian** [guardian/dotcom-rendering#8734]
### What happened?

Article JS size appears to have jumped 80kb/15% on Tuesday 29th August.

![image](https://github.com/guardian/dotcom-rendering/assets/110032454/468f8a45-8102-4568-8d19-4bf500ca707f)

Possibly caused by this https://github.com/guardian/dotcom-rendering/commit/141b51e0a840e1d779a97f4d9057cd26ed110493

**Comment by georgeblahblah** [comment]
Done in https://github.com/guardian/dotcom-rendering/pull/8763
