### ISSUE TITLE
Web ads for Apps

### ISSUE THREAD

**Issue by jamesgorrie** [guardian/dotcom-rendering#8752]

**Comment by arelra** [comment]
Investigation in to how we can implement web ads on DCAR here:
https://docs.google.com/document/d/15qvzi623q63-yakSloSb-u8howOOVJfYnnUxdq0Lc7A/edit

**Comment by arelra** [comment]
We will render ads natively for now - so not on the web. As described in the document above there are issues with ATT and the current web stack which may load ads that perform tracking.
