### ISSUE TITLE
Implement Sub-Meta Design Change On AR

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#8769]
The new designs are here: https://github.com/guardian/dotcom-rendering/issues/7389#issuecomment-1653748826

We either implement the change on AR or wait for the rollout of DCR for apps to cover it via #8768.

**Comment by rhiannareechaye** [comment]
I'm going to close this as not planned and suggest that we wait for the rollout of DCR for Apps - ideally we don't do any work in the legacy platforms
