### ISSUE TITLE
Implement Sub-Meta Design Change On Frontend

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#8771]
The new designs are here: https://github.com/guardian/dotcom-rendering/issues/7389#issuecomment-1653748826

We either implement the change on frontend or wait for the rollout of DCR for dotcom to cover it via #8768.

**Comment by rhiannareechaye** [comment]
I'm going to close this as not planned and suggest that we wait for the rollout of DCR for Dotcom - ideally we don't do any work in the legacy platforms. We will be looking at Fronts/Articles etc. from a UX perspective from January 2024 so I'd recommend we revisit this then and focus on getting DCR for Apps over the line
