### ISSUE TITLE
Live Rugby Data On Sportblogs

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#8799]
When a sportblog (sport liveblog) covers a particular football or cricket match, we have the ability to incorporate live data from PA, as seen here:

- https://www.theguardian.com/football/live/2023/sep/03/arsenal-v-manchester-united-liverpool-v-aston-villa-and-more-premier-league-live-updates
- https://www.theguardian.com/sport/live/2023/sep/08/england-v-new-zealand-first-mens-one-day-international-live

We'd like to consider whether we can do something similar for rugby on dotcom and apps articles. We have had support for rugby data on sportblogs at certain times in the past (see https://github.com/guardian/frontend/pull/21832 for an example), but this functionality no longer works.

```[tasklist]
- [ ] Decide whether we'd like to (or even can) reuse the existing code in frontend to retrieve rugby data from PA
- [ ] Decide, in conjunction with Editorial, what data we'd like to display on sportblogs (scores, match stats etc.)
- [ ] Figure out how to surface that data client-side for DCR
- [ ] Build new UI on DCR to display the data
- [ ] Figure out how to introduce support for apps (which, unlike dotcom, haven't had support in the past)
```

See #4758 and https://github.com/guardian/frontend/pull/24977 for examples of how some of this was done for cricket on DCR.

**Comment by rhiannareechaye** [comment]
I spoke to Matt and confirmed that it's not something we can prioritise for this year so I'm going to close this ticket as not planned, however i expect we'll need to resurrect it for the next rugby tournament
