### ISSUE TITLE
Text around sponsor badge poor contrast

### ISSUE THREAD

**Issue by DanielCliftonGuardian** [guardian/dotcom-rendering#8806]
![image](https://github.com/guardian/dotcom-rendering/assets/110032454/283da7e6-e2ff-4b3d-a87a-0e9c2d9e6365)

Seen on the au front [https://www.theguardian.com/au](https://www.theguardian.com/au)

**Comment by rhiannareechaye** [comment]
@ioannakok is this a replica of something that you fixed?

**Comment by ioannakok** [comment]
@rhiannareechaye Yes, sort of! I think this one is for the contrast but since the badge shouldn't have been there in the first place (fixed in https://github.com/guardian/dotcom-rendering/pull/8818) I'm closing this ticket and if something similar happens again we can revisit!
