### ISSUE TITLE
DCAR: Font interception in Android

### ISSUE THREAD

**Issue by georgeblahblah** [guardian/dotcom-rendering#8814]
The Android app intercepts HTTP requests to load fonts when loading Apps Rendering articles, in order to serve the font files directly from cache. This mechanism picks up URLs from MAPI. Apps articles rendered by DCAR will not have MAPI font URLs, meaning the intercept mechanism won't work and fonts won't be served from cache. This could break offline reading.

**Comment by abeddow91** [comment]
This is currently being investigated by @robksmith from the Android team

**Comment by abeddow91** [comment]
This is blocked from a webex perspective whilst the Android native devs look into this. A session on 28th sept found the cause of this issue to be a missing [access-control-allow-origin header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin). Its suspected that this header gets dropped after the fonts get intercepted.
