### ISSUE TITLE
Hide the badge from the cards in paid fronts

### ISSUE THREAD

**Issue by ioannakok** [guardian/dotcom-rendering#8827]
| DCR | frontend |
|-----|----------|
| <img width="1692" alt="image" src="https://github.com/guardian/dotcom-rendering/assets/19683595/837e3d72-ac6e-4bbb-92cb-1b6872facfce"> | <img width="1692" alt="image" src="https://github.com/guardian/dotcom-rendering/assets/19683595/cee6db1d-7242-4f8b-87ae-cb93e5b33a66"> |

**Comment by alinaboghiu** [comment]
this has been fixed
