### ISSUE TITLE
GA Tracking issue

### ISSUE THREAD

**Issue by rhiannareechaye** [guardian/dotcom-rendering#8837]
All details in this doc: https://docs.google.com/document/d/1xgSeshUun3agWTyU5u3FOGZPXIj5VmOL0Qs-0SQFGUQ/edit#heading=h.16zry08c2xbh

We should look at this, but when I'm not sure. I will add it to our list of things to dicuss in planning, but moving to the backlog for now 
```[tasklist]
### Tasks
- [ ] https://github.com/guardian/ophan/issues/5579
```

**Comment by shesah** [comment]
This needs to be picked up by the Ophan team

**Comment by alinaboghiu** [comment]
Since this is now with Pageview Data Working Group I don't think there's anything for us to do in this team
