### ISSUE TITLE
Audit cookie consent (before using third parties)

### ISSUE THREAD

**Issue by rhiannareechaye** [guardian/dotcom-rendering#8838]
It’s critical that we’re all extremely careful about data privacy and consent. Every third party that we integrate with and send user data to, or make client-side requests to, must be listed in SourcePoint, our Consent Management Platform.

To assess in which category a vendor belongs you should work with our Data Privacy team on the specific use cases with exact data that will be transferred or processed.

For all our users, we need a [lawful basis for processing](https://ico.org.uk/for-organisations/uk-gdpr-guidance-and-resources/lawful-basis/a-guide-to-lawful-basis/) personal data (see [what is personal data](https://docs.google.com/document/d/1wXsshs7GKzVdQhO57-QR6RZDFV2ZySPeHjqTvxfceZk/edit)) and we need either consent or an exemption [to store any data on a user device](https://ico.org.uk/for-organisations/direct-marketing-and-privacy-and-electronic-communications/guide-to-pecr/guidance-on-the-use-of-cookies-and-similar-technologies/what-are-the-rules-on-cookies-and-similar-technologies/) or access local storage (for instance cookies).

A vendor may be assessed for a specific purpose as strictly essential, which means that it is strictly essential from the user’s perspective.

This means:

Data Privacy has assessed that we can use use [strictly necessary exemption](https://ico.org.uk/for-organisations/direct-marketing-and-privacy-and-electronic-communications/guide-to-pecr/guidance-on-the-use-of-cookies-and-similar-technologies/what-are-the-rules-on-cookies-and-similar-technologies/#rules9) to store data or access local storage on user device  
Data Privacy has assessed that we do not require consent as the lawful basis for processing the personal data (or there is no use of personal data)

If that is the case they should be listed in the very short list of ‘essential’ vendors in the CMP. Even though we do not require consent for these ‘essential’ vendors, we must still identify them on the cookie banner. Please don’t assume, and take a moment to check that it is!

If that is not the case, the code that integrates them should always check to make sure that the user has given their consent for that purpose before initialising the vendor script or making any requests to the service.

- [ ] Check the third parties/vendors that your team uses, are [listed](https://docs.google.com/spreadsheets/d/1ujtHflyHS3ZBb6Xk9VL_2YnwnEv7v_g3q7gwIT9J5WI/edit#gid=0) on the CMP/Cookie Banner
- [ ] Check whether the way we use them matches what we have listed
Are they essential to the functioning of the service from a user's perspective?
If so, have we listed them as an essential vendor?
If not, are the purposes that we have listed them as, on the cookie banner, correct? (If you are not sure, please reach out and we can review with you.)
Are we listing the same vendor differently on different platforms? 
- [ ] If you haven't already, please also check out our review list of Essential [cookies ](https://docs.google.com/spreadsheets/d/1i4oqkWvbFJuazgbUHLP2LE6Bxzpeexcy4-idvTp7aac/edit#gid=123556787)- a different but complementary activity we've been looking at this quarter.

**Comment by mxdvl** [comment]
# First party usage

## Local Storage
- `gu.prefs.container-states`: used to know which containers are hidden in [`ShowHideContainer`](https://github.com/guardian/dotcom-rendering/blob/522ac56159f1eb5d3aad9ba5a6a055a86dd947b8/dotcom-rendering/src/components/ShowHideContainers.importable.tsx#L21)
- `gu.prefs.accessibility.flashing-elements`: used to disable flashing elements such as [`PulsingDot`](https://github.com/guardian/dotcom-rendering/blob/522ac56159f1eb5d3aad9ba5a6a055a86dd947b8/dotcom-rendering/src/components/PulsingDot.importable.tsx#L44)
- `gu.prefs.lightbox-hideinfo`: used to determine the user’s preference for Lighbox captions in [`LightboxJavascript`](https://github.com/guardian/dotcom-rendering/blob/e0fdd9ae15727e61cc2558c4e49512eea5ee8e37/dotcom-rendering/src/components/LightboxJavascript.importable.tsx)
- `gu.prefs.discussion.*` save preferences related to discussions layout in [`Comments`](https://github.com/guardian/dotcom-rendering/blob/e0fdd9ae15727e61cc2558c4e49512eea5ee8e37/dotcom-rendering/src/components/Discussion/Comments.ts)
  - `gu.prefs.discussion.threading` whether to show "collapsed", "expanded" or "threaded"
  - `gu.prefs.discussion.pagesize` wether to show 10, 25 or a 100 comments per page
  - `gu.prefs.discussion.order` wether to show “newest”, “oldest” or “recommendations”
  - `gu.prefs.discussion.mutes` remember the list of muted comments for a user
- `gu.history.*` used for number of articles read by a user in [`articleCountOptOut`](https://github.com/guardian/dotcom-rendering/blob/e0fdd9ae15727e61cc2558c4e49512eea5ee8e37/dotcom-rendering/src/components/marketing/lib/articleCountOptOut.ts#L13-L15)
  - `gu.history.dailyArticleCount`
  - `gu.history.weeklyArticleCount`
  - `gu.history.articleCountsThisWeek`
- `gu.alreadyVisited` count of number of pages seen by a user
- … (To be continued)

## Cookies
- `gu_article_count_opt_out` opts out of article count, valid for 90 days in [`articleCountOptOut.ts`](https://github.com/guardian/dotcom-rendering/blob/e0fdd9ae15727e61cc2558c4e49512eea5ee8e37/dotcom-rendering/src/components/marketing/lib/articleCountOptOut.ts#L8-L11)

### Dev Tools
- `gu.geo.override` used by developers to force themselves into a different geolocation/country. Not exposed to regular users

### Supporter Rev
- `gu.prefs.engagementBannerLastClosedAt`
- `gu.prefs.subscriptionBannerLastClosedAt`
- `gu.prefs.signInBannerLastClosedAt`
- `gu.contributions.views`
- `gu.prefs.sign-in-gate`
- `gate-dismissed-count-*-*`

**Comment by ashishpuliyel** [comment]
Amazing piece of work!

**Comment by mxdvl** [comment]
We should use `@guardian/libs` storage everywhere to ensure we can ensure all usage is consented:
- #10052

**Comment by ioannakok** [comment]
Closing for now but let's review again in Q1. @shesah will set up a calendar reminder (once a quarter)
