### ISSUE TITLE
Surpress the EU modal if a similar Supporter Revenue banner 

### ISSUE THREAD

**Issue by AshCorr** [guardian/dotcom-rendering#8846]
or alternatively surpress Supporter Revenue banners if the EU modal is going to appear. Currently both can appear at the same time which looks like this

<img width="2052" alt="image" src="https://github.com/guardian/dotcom-rendering/assets/21217225/825743fd-12a6-48c3-a6b1-ae6f0e81f28a">

I personally find this to be a lot of things the user has to dismiss in order to get to our content, but it may not be an issue. @AshCorr to check with Supporter Revenue.

**Comment by alinaboghiu** [comment]
I think we've removed this modal altogether so closing this ticket.
