### ISSUE TITLE
Most viewed is out of date on articles

### ISSUE THREAD

**Issue by abeddow91** [guardian/dotcom-rendering#8898]
The most viewed component is showing out of date content on articles. It is displaying the correct content on Fronts. 

All content doesnt seem to have updated since friday 22 septemeber

This was reported on Rota Sun 24th Sept

**Comment by abeddow91** [comment]
fixed by https://github.com/guardian/frontend/pull/26606

**Comment by paperboyo** [comment]
Closed as indicated fixed. Please reopen if necessary.
