### ISSUE TITLE
No badge showing in "Rights and freedom" page

### ISSUE THREAD

**Issue by ioannakok** [guardian/dotcom-rendering#8908]
https://www.theguardian.com/global-development/series/rights-and-freedom

### DCR
![image](https://github.com/guardian/dotcom-rendering/assets/19683595/d8c613e3-c23a-4572-be52-d54f00423009)

### frontend
![image](https://github.com/guardian/dotcom-rendering/assets/19683595/8b65c693-6cd6-4150-ae1b-e2fdad283656)

**Comment by shesah** [comment]
This is being picked up by the commercial team. ticket here:
