### ISSUE TITLE
Filter articles in MAPI for the Beta launch

### ISSUE THREAD

**Issue by georgeblahblah** [guardian/dotcom-rendering#8964]
MAPI is responsible for telling the app whether a given article can be rendered with DCR, AR or if it should be rendered by the embedded templates.

We can use information about the requested content to determine a given platform's support for that content. MAPI can indicate that some content is supported by DCR, or AR, or neither (but not both). Currently, we don't use details of the request to help determine support.

This ticket is to represent support for DCR articles in beta. Currently, we currently support articles that meet the following criteria:

- no discussion
- no media atoms
- standard layout
- no newsletter embed
- is not one of DCR's unsupported article types (gallery, picture, audio, video)

it might be that there are other properties which are not supported. These should become clear during the beta test.

**Comment by rhiannareechaye** [comment]
Linking the release plan ticket here as an FYI: https://github.com/guardian/dotcom-rendering/issues/8750
