### ISSUE TITLE
Understand our current 'state of play' for readers

### ISSUE THREAD

**Issue by rhiannareechaye** [guardian/dotcom-rendering#8977]
We need to understand what our readers see when they look at Sports pages. 

We have regular articles about Sports competitions, but what we're interested in are the more custom pages. 

Lets start with Football as that has the most variants. 

For football: 
What is a regular article experience 
What is a liveblog experience 
What is a deadblog experience 

Then take a look at these custom pages
- [Live scores](https://www.theguardian.com/football/live)
- [Tables](https://www.theguardian.com/football/tables)
- [Fixtures](https://www.theguardian.com/football/fixtures) 
- [Results](https://www.theguardian.com/football/results) 
- [Competitions](https://www.theguardian.com/football/competitions) 
- [Clubs](https://www.theguardian.com/football/teams)

Could we get screenshots of all these pages - do you have any thoughts of glaring UX issues? Could we see what this looks like on a mobile phone? 

What about the Olympics? 
- What is a regular article experience 
- What is a liveblog experience 
- What is a deadblog experience 
- What about custom pages? I found[ this one](https://www.theguardian.com/sport/ng-interactive/2021/aug/06/tokyo-2020-olympics-full-medal-table
- )

If we can get some screenshots of these things (we don't need to do all sports yet, maybe just the olympics and football as a starting point) - then we can start to see any glaring UX issues 

Paste your findings in [this doc](https://docs.google.com/presentation/d/1eCQwcTlZjrTNhtMrWOomvwnWXDwMniJXWYJ3nz7ke98/edit#slide=id.g2820a3de5a0_0_123)

**Comment by rhiannareechaye** [comment]
Due date for this is 20th of Oct

**Comment by mxdvl** [comment]
@Francesca-osei & @shesah is this done? Can we close this issue?
