### ISSUE TITLE
Understand the competitor landscape for 'Sports Pages'

### ISSUE THREAD

**Issue by rhiannareechaye** [guardian/dotcom-rendering#8979]
It would be great to see what our competitors are doing in the same space, e.g. for all the Football pages, what is the BBC doing? Again totally up to you where you store this work, but again it needs to be done and read to send out by 20th of October

Remember to add links to the doc [here](url)

**Comment by mxdvl** [comment]
@Francesca-osei & @shesah is this done? Can we close this issue?
