### ISSUE TITLE
Understand our Editorial goals and desires for Sports Pages

### ISSUE THREAD

**Issue by rhiannareechaye** [guardian/dotcom-rendering#8981]
Calvin (the PM on Content Pipelines) will be gathering some insights from our Editorial team around what they envisage for Sports Pages. 

All insights to be gathered into [this doc](https://docs.google.com/presentation/d/1eCQwcTlZjrTNhtMrWOomvwnWXDwMniJXWYJ3nz7ke98/edit#slide=id.g2820a3de5a0_0_158)

**Comment by mxdvl** [comment]
@shesah to catch-up with UX

**Comment by Francesca-osei** [comment]
Calvin presented the insights from the editorial team in the Sports workshop. 
The team will go through the ideas that came out of the session so they are ready if we decide to work on sports in January.
