### ISSUE TITLE
Understand the design team's goals & desires for Sports Pages

### ISSUE THREAD

**Issue by rhiannareechaye** [guardian/dotcom-rendering#8982]
We know that the design team already have some ideas about these pages + since Alex is covering the Apps Experience work, it would be helpful to have their thoughts on next steps for these areas. We definitely don't need final designs, just a rough idea so that the engineering and product teams can start making assessments of how to sequence things. 

The empty doc [here](https://docs.google.com/presentation/d/1eCQwcTlZjrTNhtMrWOomvwnWXDwMniJXWYJ3nz7ke98/edit#slide=id.g2826bdebb7e_0_0) is to put these thoughts into - again it's fine for it to just be links to figma files etc. 

I will assign this ticket to Calvin as he can make sure the designs are in place!

**Comment by JamieB-gu** [comment]
@shesah @Francesca-osei catching up with rest of discovery team soon

**Comment by Francesca-osei** [comment]
We have a session scheduled in for Monday to look over the ideas that have come out of the session.
