### ISSUE TITLE
Missing the vertical rules between cards

### ISSUE THREAD

**Issue by alinaboghiu** [guardian/dotcom-rendering#9048]
when 3 cards sit on a row they are missing the vertical rules

![Image](https://github.com/guardian/dotcom-rendering/assets/1229808/100b2bad-339a-4a8c-b566-42496e335e7b)

**Comment by abeddow91** [comment]
Testing on a code Fronts suggests these lines do appear across all breakpoints

![Image](https://github.com/guardian/dotcom-rendering/assets/20416599/1b1cd3e0-9dc6-42aa-be07-f21bbfb04f7a)


Closing as this is not replicable and the original container no longer exists
