### ISSUE TITLE
Fronts: hidden containers un-hiding on back navigation, can't re-hide

### ISSUE THREAD

**Issue by georgeblahblah** [guardian/dotcom-rendering#9076]
## Steps to reproduce

1. Hide a container
2. Navigate to an article
3. Navigate back
4. See the hidden container is un-hidden
5. Try to hide the container again. It does not hide.

We have had reports of this on Firefox and Chrome (including Android).

## Firefox 

https://github.com/guardian/dotcom-rendering/assets/705427/02e345be-fb12-409b-8542-b90ef3a99e74

## Chrome 

https://github.com/guardian/dotcom-rendering/assets/705427/0708aff2-f3ce-4188-ae78-7a4be21bc2f8

**Comment by paperboyo** [comment]
Thanks! I can also repro in Chrome 116 Incognito without Teleporter (present, but disallowed in Incognito). Actually, just by reloading the page after Hiding a container (sic!), so not sure related to Teleporter.
