### ISSUE TITLE
Update the colours of Design Tags 

### ISSUE THREAD

**Issue by cemms1** [guardian/dotcom-rendering#9084]
Ensure colours are `pillar.400` versions for light mode (`pillar.500` for dark mode)

e.g.
<img width="535" alt="Screenshot 2023-10-11 at 16 20 36" src="https://github.com/guardian/dotcom-rendering/assets/1229808/823961fd-12b3-46f2-89ca-03f73667e284">

**Comment by JamieB-gu** [comment]
Closing this as designs aren't finalised yet. When they are it will be tracked by #9254.
