### ISSUE TITLE
Disable Ophan tracking in the webview

### ISSUE THREAD

**Issue by alinaboghiu** [guardian/dotcom-rendering#9085]
DCR for Apps should not send any tracking data to Ophan. All tracking should be handled natively instead. 

We should disable tracker.js and make sure this doesn't run in the webview.

**Comment by georgeblahblah** [comment]
Possible steps:

* Exclude `ophan-tracker-js` from the apps bundle in Webpack
* Refactor call-sites of `getOphan` to check if Rendering Target is Web before calling `getOpha`n

**Comment by ioannakok** [comment]
Re-opening as #9137 was only the first PR. 2nd one will follow
