### ISSUE TITLE
[Bug]: Pull quote obscures caption on Showcase article

### ISSUE THREAD

**Issue by cemms1** [guardian/dotcom-rendering#9088]
Pull quote obscures caption on this Showcase article:
https://www.theguardian.com/artanddesign/2023/oct/10/hiroshi-sugimoto-review-japan-great-faker-hayward

<img width="935" alt="image" src="https://github.com/guardian/dotcom-rendering/assets/43961396/f51e90ff-088c-41de-9957-80d3ff2aa580">

**Comment by ioannakok** [comment]
This is a user error. We shouldn't put pullquotes this close to images.
