### ISSUE TITLE
Liveblog Alert Notifications

### ISSUE THREAD

**Issue by georgeblahblah** [guardian/dotcom-rendering#9103]
### Taken from #8786: 
> Something the apps support is signing up to alerts (notifications) for changes to a specific liveblog. We will want to replicate this behaviour for the apps version of DCR liveblogs. We may be able to draw on the UI changes that were made to accommodate this feature in AR in #3543, but this design differs from how the alert button currently looks in the apps, so it would be best to ask Design about which to use. It may be that we need to add a new Bridget service to handle this, or we may be able to reuse the existing `Notifications` service.

## Design input needed

**Design input needed** for how the notification subscribe button will appear when you can _also_ get notifications for the live blog author.

| Native templates | DCAR current | 
| ---------------- | ------------ |
| ![templates1] | ![dcar1]|
| ![templates2] | ![dcar2]

[templates1]: https://github.com/guardian/dotcom-rendering/assets/43961396/9709ca61-292e-4eb3-81ef-8e5fce438193
[templates2]: https://github.com/guardian/dotcom-rendering/assets/43961396/98267471-9325-46d4-bc88-8d0f3f93e815
[dcar1]: https://github.com/guardian/dotcom-rendering/assets/43961396/147161db-137d-446d-842b-a26c0dd2d3a6
[dcar2]: https://github.com/guardian/dotcom-rendering/assets/43961396/27c8361c-f9e6-4fae-8d4c-651b087af102

**Comment by benwuersching** [comment]
@cemms1 Can we catch up on this, please? I don't exactly understand what the design issue is.

**Comment by domlander** [comment]
Blocked as waiting for apps team to investigate what data to send via Bridget to enable notifications

https://chat.google.com/room/AAAAehVq1H0/kbPZWCBC09w/SqBHh1W9qgQ?cls=10

**Comment by domlander** [comment]
Blocked until I can get into the office and use a device for testing

**Comment by domlander** [comment]
Liveblog notifications failed testing. I think we need help from the apps team to ensure that notifications can work on their side: https://github.com/guardian/dotcom-rendering/issues/12287#issuecomment-2334097514

**Comment by domlander** [comment]
Blocked until liveblogs go to Beta. This is currently waiting on [12313 - Support all elements that can appear in liveblogs](https://github.com/guardian/dotcom-rendering/issues/12313)

**Comment by domlander** [comment]
How to test notifications are working?
- There are devices in the office that are available for use. [This spreadsheet](https://docs.google.com/spreadsheets/d/1Ytg4gi4TKJwhDf5mPpnf-FwdUNKhrunnxIKSM8zt-4g/edit?gid=802619498#gid=802619498) keeps track of what's available and is used for signing devices in and out. 
- Ensure that you're using a beta build of the app
- Test both iOS and Android
- Ask the Apps team if you need help
