### ISSUE TITLE
'show caption' text is visible (should be visually hidden)

### ISSUE THREAD

**Issue by gidsg** [guardian/dotcom-rendering#911]
# steps to reproduce
go to https://amp.theguardian.com/gnm-archive/2019/nov/06/from-new-media-to-guardian-unlimited-records-of-the-guardians-first-years-online on iOS safari

# actual results
'show caption' text is visible on top of icon
![IMG_1652](https://user-images.githubusercontent.com/1764158/68334685-0f1ed600-00d3-11ea-92e4-8fe278b81cfe.png)

# expected results
'show caption' text is visually hidden
CC @nicl @SiAdcock

**Comment by SiAdcock** [comment]
Wow, thanks so much @gidsg! Hope all is cool with you
