### ISSUE TITLE
Pass Edition From The App To Frontend

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#9130]
Existing web behaviour: 

**Cookies**
GU_geo_country = is set by Fastly 
GU_EDITION = set manually by the edition dropdown

**Headers** 
Frontend uses this header to determine edition: 
X-Gu-Edition = Based on the GU_EDITION cookie if set or GU_geo_country 

We need to make sure that when an article is rendered in the app via webView, the correct header information is transmitted to Frontend: 

**Option 1**: set existing GU_EDITION cookie in the vebview (requires native change because the native layer need to pass this on as part of its request) - we don't know if this is possible, need to investigate if this way we can set the X-Gu-Edition header correctly

**Option 2**: reuse the _edition parameter, include this in the response from MAPI so that when the app fectches the article it will include this parameter - we would need to change Fastly because this parameter is only available in the ajax domain - Frontend is already looking for _edition and is using it as highest precedence 

**Option 3**: editionalise paths in articles (same as we do in apps rendering) - we'd need to update the controllers in Frontend

**Comment by ioannakok** [comment]
Example of adding a route. Changes in:
* [frontend](https://github.com/guardian/frontend/pull/25876/files#diff-3eae0983c3869596a893ee3558830e95419f13d9065c964b81c5eb5659fe2497R14)
* [platform](https://github.com/guardian/platform/pull/1515)

**Comment by mxdvl** [comment]
We went for **Option 4** in https://github.com/guardian/fastly-edge-cache/pull/1031
