### ISSUE TITLE
Remove sign in link from AMP pages

### ISSUE THREAD

**Issue by alinaboghiu** [guardian/dotcom-rendering#9134]
From User Help email: 

"We would like to know if there's a possibility of removing the sign in link on the AMP version of the webpage, or to have it redirect to the desktop/mobile fully rendered page? We do see readers confused when trying to sign in on articles via the Google news feed or any other AMP pipeline."

**Comment by mxdvl** [comment]
Discussing with @guardian/identity as we believe fixing the redirect would be ideal as we do not want to prevent people who want to sign in from doing so.

Thread: https://chat.google.com/room/AAAAFdv9gK8/zxHDBTNrK7w/

**Comment by shesah** [comment]
Identity issue - closing ticket
