### ISSUE TITLE
Confusing Sign In Behaviour On AMP Articles

### ISSUE THREAD

**Issue by georgeblahblah** [guardian/dotcom-rendering#9135]
User Help have raised that users find the Sign In flow from AMP pages confusing.

Currently, users can sign in from AMP from the menu:

![image](https://github.com/guardian/dotcom-rendering/assets/705427/c9426dc8-7d34-4c90-ae15-a7dd22a2eaf1)

Following this link takes them to Identity's sign in page. Once successfully signed in, they are redirected to the AMP article which does not reflect their sign in status - the menu still has an option to Sign In, but not Manage My Account.

## Questions

* Should we remove the sign in link from the menu on AMP pages?
* Following a successful sign in, should we redirect to the non-AMP version of the article?

**Comment by shesah** [comment]
This should be looked at by the identity team rather than WebEx
