### ISSUE TITLE
Update Node To 18.18.2 In Containerfile

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#9140]
It wasn't possible to do in #9132 as the docker images were not yet available.

**Comment by mxdvl** [comment]
It looks like [the 18.18.2 version is now available](https://hub.docker.com/_/node/tags?page=1&name=18.18.2)!

It’s probably [following the merge in the offical docker repo](https://github.com/docker-library/official-images/pull/15545#event-10667440562).
