### ISSUE TITLE
[Bug]: DCR fronts don’t take hidden containers into account when navigating back to fronts

### ISSUE THREAD

**Issue by paperboyo** [guardian/dotcom-rendering#9147]
### What happened?

Unlike `dcr=false` DCR doesn’t go back to the exact the same scroll position on a front when navigating back when hidden containers are involved. It should take the height of hidden containers into account when calculating scroll position just as frontend does. Preferably without any delay (although frontend does have a delay).

Steps:
1. Hide some container(s) on a front (Sport and Rugby, obviously)
2. Scroll below hidden containers, to eg. https://www.theguardian.com/europe#in-pictures
3. Click on a story in In pictures
4. Click history back

Actual result: you are going back to a position higher than you started from in pt. 3

Expected result: you should go back the exact scroll position from pt. 3   

### Where is this happening?

Any DCR front with hidden containers

### What is the impact?

Trivial. But sad. Frontend [always made sure](https://github.com/guardian/frontend/issues/3170) readers are never lost and navigation is predictable.

Always be better, never worse.

**Comment by shesah** [comment]
We believe this is fixed. @paperboyo please reopen if you see this again.

**Comment by paperboyo** [comment]
Yep, seems fixed, thanks @shesah!
