### ISSUE TITLE
Babel critical vulnerability

### ISSUE THREAD

**Issue by alinaboghiu** [guardian/dotcom-rendering#9153]
From DevX email: 

Dependabot has [alerted](https://github.com/guardian/csnx/security/dependabot/12) us to a critical vulnerability in the @babel/traverse package which is included in the following Guardian packages:
 - [@guardian/source-react-components](https://www.npmjs.com/package/@guardian/source-react-components)
 - [@guardian/source-react-components-development-kitchen](https://www.npmjs.com/package/@guardian/source-react-components-development-kitchen)
 - [@guardian/atoms-rendering ](https://www.npmjs.com/package/@guardian/atoms-rendering)

We've now updated to @babel/traverse@7.23.2 in each of these packages as recommended. We strongly suggest you update to the latest versions of the above packages as soon as possible.

Snyk has highlighted the presence of @babel/traverse in a number of other projects across the Guardian - please check if this affects you.

**Comment by alinaboghiu** [comment]
@georgeblahblah ok to close this?

**Comment by ioannakok** [comment]
Fixed in Snyk mob session
