### ISSUE TITLE
Standfirst: Authoritative, `ArticleDisplay.Immersive`

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#9188]
## Requirements

The list of formats that should have an "authoritative immersive" standfirst design must be both `ArticleDisplay.Immersive` and the following `ArticleDesign`s:

- `ArticleDesign.Obituary`
- `ArticleDesign.Comment`
- `ArticleDesign.Editorial`
- `ArticleDesign.Letters`

**Comment by ioannakok** [comment]
Covered by #9256
