### ISSUE TITLE
Standfirst: Neutral/Soft, `ArticleDisplay.Immersive`

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#9192]
## Requirements

The list of formats that should have an "neutral/soft immersive" standfirst design must be both `ArticleDisplay.Immersive` and the following `ArticleDesign`s:

- `ArticleDesign.Standard`
- `ArticleDesign.Profile`
- `ArticleDesign.Explainer`
- `ArticleDesign.Timeline`
- `ArticleDesign.LiveBlog`
- `ArticleDesign.DeadBlog`
- `ArticleDesign.Analysis`
- `ArticleDesign.Feature`
- `ArticleDesign.Interview`
- `ArticleDesign.Recipe`
- `ArticleDesign.Review`

**Comment by ioannakok** [comment]
Covered by #9272 and #9276
