### ISSUE TITLE
Dropcap: Authoritative

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#9198]
## Requirements

The list of formats that should have an "authoritative" dropcap design are as follows.

If `ArticleDisplay.Immersive` then the following `ArticleDesign`s:

- `ArticleDesign.Obituary`
- `ArticleDesign.Comment`
- `ArticleDesign.Editorial`
- `ArticleDesign.Letters`

else:

- `ArticleDesign.Comment`

**Comment by ioannakok** [comment]
Covered by #9194
