### ISSUE TITLE
Measure ad ratio and revenue in DCAR

### ISSUE THREAD

**Issue by alinaboghiu** [guardian/dotcom-rendering#9220]
We need to make sure ad ratio and revenue is the same in DCAR and AR.

After talking to Yen and Zoyah we came up with these next steps: 
- [x] introduce a new RP (rendering platform) parameter in the ad targeting parameters that are then recorded in the pageview table (https://github.com/guardian/commercial-shared/pull/56, https://github.com/guardian/mobile-apps-api/pull/2867)
- [ ] since the targeting params only appear when there are ads we should also introduce this data into the `experience` column in the page view data, so we can measure that ads appear on articles at the same rate
- [ ] introduce an simple random A/B test in MAPI. This can start at a high percentage e.g. 50% since the risk or reducing ad revenue is low

**Comment by alinaboghiu** [comment]
@JamieB-gu do we still want to merge this PR? https://github.com/guardian/dotcom-rendering/pull/8962
And if so would we want some king of ad parity measurement in place before we do?

**Comment by alinaboghiu** [comment]
@arelra if you have any time to help with this let me know and we can catch up

**Comment by arelra** [comment]
@alinaboghiu happy to help! I think we'd need a way to distinguish bewteen ar and dcar in the targeting that gets sent to GAM. I am not sure what apps does currently but on web we use the targeting property `rp (rendering platform)` to distinguish between DCR and Frontend so I think we could extend this to dcar and apps if not already there. We'll need D&I support too for the analysis. cc @Amouzle

**Comment by alinaboghiu** [comment]
- we will not A/B test ad ratio between DCAR and AR
- we will not populate the pageview.experiences column from DCAR or AR 
 
because we trust DCAR (it's not a new platform, it's been trialed and tested etc.)
