### ISSUE TITLE
Align the Support the Guardian button

### ISSUE THREAD

**Issue by alinaboghiu** [guardian/dotcom-rendering#9252]
Background: https://github.com/guardian/dotcom-rendering/issues/7393
Figma: https://www.figma.com/file/R5kfAuzgovB4lVlCKKyCww/DCAR-Anomalies-and-App-preferences?type=design&node-id=1-2&mode=design&t=G3EWbsT4bPgaXyVQ-0

- [ ] check if SR have approved the above designs - @georgeblahblah is asking
- [ ] ensure the agreed designs are implemented (if SR are happy with the above then we don't need to do anything)

**Comment by ajbreuer** [comment]
![Image](https://github.com/guardian/dotcom-rendering/assets/1144827/5a04462a-02fe-4843-9341-0d5b7879c247)

Dark mode now added to the design

**Comment by alinaboghiu** [comment]
Moving to planned as we marked it as required for first prod release

**Comment by alinaboghiu** [comment]
SR are ok with the design being inconsistent. 
So as part of this ticket we should implement the blue design ^
