### ISSUE TITLE
Football tool generates json.html thrashers?

### ISSUE THREAD

**Issue by alinaboghiu** [guardian/dotcom-rendering#9258]
It's possible that fixtures generated with this tool are not supported by DCR:
https://frontend.code.dev-gutools.co.uk/admin/football/fronts

Email thread here: https://groups.google.com/a/guardian.co.uk/g/dotcom.platform/c/eYmeZeo1YVc/m/ctqWbR4VAQAJ

**Comment by alinaboghiu** [comment]
It doesn't seem possible to generate the euro 2024 fixtures with this tool. 
And the one that broke the Europe front has been removed so I cannot check. 
Chatting to CP on Monday to see if they can help me recreate.

**Comment by ioannakok** [comment]
Next step: Chat with people who generate `json.html` thrashers
