### ISSUE TITLE
Blockquotes: Soft/Neutral/Authoritative

### ISSUE THREAD

**Issue by sophie-macmillan** [guardian/dotcom-rendering#9300]
This captures pullquotes that have an "neutral/soft/authorative" style. These changes should go out together (either in a single PR, or a single feature switch) to create a consistent design update. The list of tasks is here for quick reference and full descriptions can be found below.

https://www.figma.com/file/xPr2tZZger7pszcO075tAQ/New-Formats---April-23?type=design&node-id=2002-32607&mode=design&t=fQ2u2Xgcc2ZTmwVT-4

```[tasklist]
### Tasks
- [x] BlockQuote: Clear
- [x] BlockQuote: Stand Out
```

<details>
<summary>

## Blockquote, Clear

</summary>

The list of formats that should have an "soft/neutral/authoritative" clear blockqoute design must be the following `ArticleDesign`s:

- `ArticleDesign.Obituary`
- `ArticleDesign.Standard`
- `ArticleDesign.Profile`
- `ArticleDesign.Explainer`
- `ArticleDesign.Timeline`

### All breakpoints

* font: GuardianText
* font-size: 17px
* font-weight: regular Italic
* lightmode font colour: neutral[7]
* darkmode font colour: neutral[60]
* lightmode svg colour: neutral[46]
* darkmode svg colour: neutral[60]
* spacing above: 14px
* spacing below: 14px
* spacing between svg and text: 4px

Using Source, the typography API call would be:

```ts
${textSans.medium({ fontWeight: 'regular', fontStyle: 'italic', lineHeight: 'loose' })};
```

and colours from `palette.neutral`.

</details>

<details>
<summary>

## Blockquote, Standout

</summary>

The list of formats that should have an "soft/neutral/authoritative" standout blockquote design must be the following `ArticleDesign`s:

- `ArticleDesign.Comment`
- `ArticleDesign.Editorial`
- `ArticleDesign.LiveBlog`
- `ArticleDesign.DeadBlog`
- `ArticleDesign.Analysis`
- `ArticleDesign.Feature`
- `ArticleDesign.Interview`
- `ArticleDesign.Recipe`
- `ArticleDesign.Review`

### All breakpoints

* font: GuardianText
* font-size: 17px
* font-weight: regular Italic
* lightmode font colour: neutral[7]
* darkmode font colour: neutral[60]
* lightmode svg colour: pillar colour 200 (colour applies to the quotemark only - not the text)
* darkmode svg colour: pillar colour 500 if not available (default to neutral[46]) (colour applies to the quotemark only - not the text)
* spacing above: 14px
* spacing below: 14px
* spacing between svg and text: 4px

Using Source, the typography API call would be:

```ts
${textSans.medium({ fontWeight: 'regular', fontStyle: 'italic', lineHeight: 'loose' })};
```

and colours from `palette.neutral` and an example of the colour change would be:

```
const styles = css`
  color: ${palette.news[200]};
`;
```

</details>

**Comment by ioannakok** [comment]
Closed by: https://github.com/guardian/dotcom-rendering/pull/9312
