### ISSUE TITLE
Review DCR Scaling Policy

### ISSUE THREAD

**Issue by ioannakok** [guardian/dotcom-rendering#9311]
Ticket created from https://github.com/guardian/dotcom-rendering/issues/8345#issuecomment-1647502598

This ticket is to: 
1. Experiment with alternative solutions on the DCR scaling policy 
2. Review the metric upon which we want to base our scaling on. 

### DCR Scaling Policy

DCR is currently using Simple Scaling Policy[^1]. AWS have [essentially deprecated this style of scaling](https://docs.aws.amazon.com/autoscaling/ec2/userguide/ec2-auto-scaling-scaling-cooldowns.html) and are promoting their alternative solutions as a best practice:

![image](https://github.com/guardian/dotcom-rendering/assets/19683595/c5484b40-49f8-456c-8794-18f274b0f848)

Do we want to consider adopting one of the [other alternatives](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-autoscaling-scalingpolicy.html#cfn-autoscaling-scalingpolicy-policytyp)?

Some examples in other Guardian repos:
* [`TargetTrackingScaling`](https://github.com/guardian/dotcom-rendering/blob/207f8430c01f7c050a922f66d50a3a47142ed049/apps-rendering/cdk/lib/__snapshots__/mobile-apps-rendering.test.ts.snap#L145C31-L145C31) in AR
* [`StepScaling`](https://github.com/guardian/ophan/blob/a46d118b0ba16a96ebbebbfcae7e93cc5599b42c/cdk/lib/avro-logger.ts#L138C15-L165) in Ophan

### DCR Scaling Policy Metric

We're currently scaling based on latency:

https://github.com/guardian/dotcom-rendering/blob/83927738d0a45719cd156b7fb756feaa2267155d/dotcom-rendering/cdk/lib/dotcom-rendering.ts#L296-L301

and scaling up by doubling our capacity every 10 minutes:

https://github.com/guardian/dotcom-rendering/blob/83927738d0a45719cd156b7fb756feaa2267155d/dotcom-rendering/cdk/lib/dotcom-rendering.ts#L272-L277

whilst scaling down by removing an instance once every 2 minutes:

https://github.com/guardian/dotcom-rendering/blob/83927738d0a45719cd156b7fb756feaa2267155d/dotcom-rendering/cdk/lib/dotcom-rendering.ts#L278-L283

Do we want to consider other scaling strategies? Apps-rendering, for example, via `guardian/cdk`, scales based on a target CPU utilisation:

https://github.com/guardian/dotcom-rendering/blob/e234547e28cb1071b83c526fdbae7df5c361f522/apps-rendering/cdk/lib/mobile-apps-rendering.ts#L104-L106

[^1]: [Simple scaling is the default](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-autoscaling-scalingpolicy.html#cfn-autoscaling-scalingpolicy-policytype), so if `PolicyType` is unspecified, `SimpleScaling` is used.
```[tasklist]
### Tasks
- [ ] https://github.com/guardian/dotcom-rendering/issues/10273
```

**Comment by ioannakok** [comment]
Progress so far: https://docs.google.com/document/d/1FjDANYnddGrB3JnXdMjoHnie2kB7fL3MgJachCVZHVg/edit

**Comment by arelra** [comment]
Re-opening here:
https://github.com/guardian/dotcom-rendering/pull/11715

**Comment by arelra** [comment]
Completed by:
https://github.com/guardian/dotcom-rendering/pull/11837
https://github.com/guardian/dotcom-rendering/pull/11928
