### ISSUE TITLE
Review ASG Sizes

### ISSUE THREAD

**Issue by ioannakok** [guardian/dotcom-rendering#9322]
We're currently using a minimum of 15 and a maximum of 60 instances in production:

https://github.com/guardian/dotcom-rendering/blob/e234547e28cb1071b83c526fdbae7df5c361f522/dotcom-rendering/cloudformation.yml#L72-L78

Do these limits allow enough headroom for our additional traffic, scaling requirements, and RiffRaff deploys?

**Comment by ioannakok** [comment]
PR that reduced `minCapacity` to 27 was merged: https://github.com/guardian/dotcom-rendering/pull/9369

**Comment by ioannakok** [comment]
Progress so far: https://docs.google.com/document/d/1FjDANYnddGrB3JnXdMjoHnie2kB7fL3MgJachCVZHVg/edit

**Comment by alinaboghiu** [comment]
https://github.com/guardian/dotcom-rendering/blob/main/dotcom-rendering/docs/architecture/029-scaling-policy-decision-record.md
