### ISSUE TITLE
Newsletter sign up form failing

### ISSUE THREAD

**Issue by cemms1** [guardian/dotcom-rendering#9523]
There are some **non-editorial** newsletters in the newsletters response. These are marked as paused due to being marketing newsletters rather than editorial newsletters.

There have been reported issues for signing up to newsletters using the old embeds. These embeds are only shown on old articles and old sign up pages.

**Comment by shesah** [comment]
We discussed this in triage - we are not quite sure which team it sits with and is probably one for discussion with EH - @ashishpuliyel . @cemms1 to flesh out the ticket soon
