### ISSUE TITLE
Update Twitter logo to X logo

### ISSUE THREAD

**Issue by abeddow91** [guardian/dotcom-rendering#9524]
There has been a request to change Twitter logo to the updated 'X'
Could someone create a ticket please?

svg here:
https://www.figma.com/file/a5cq2VFJRmLccYn1Ra6sG1/X-logo-svg?type=design&node-id=0%3A1&mode=design&t=HjhBprTrbxayOs7l-1

This ticket should also check with design if the icon needs to be added to source first.

**Comment by mxdvl** [comment]
I think we should just stick with the Unicode character: 𝕏

**Comment by HarryFischer** [comment]
⚠  Please leave as is for now
