### ISSUE TITLE
Labs front has strange styling when signed in

### ISSUE THREAD

**Issue by cemms1** [guardian/dotcom-rendering#9530]
Signed in (DCR):
<img width="1304" alt="image" src="https://github.com/guardian/dotcom-rendering/assets/43961396/5dcf4600-cd4b-49d0-85e9-d0742e566c54">

Signed out (DCR):
<img width="1316" alt="image" src="https://github.com/guardian/dotcom-rendering/assets/43961396/50494196-c6cb-476b-a064-05bc2a7dd707">

Signed in (frontend):
<img width="1318" alt="image" src="https://github.com/guardian/dotcom-rendering/assets/43961396/312077ea-ad53-400a-bb71-eab44326d420">

**Comment by mxdvl** [comment]
Seen on https://www.theguardian.com/guardian-labs

I think that the [logic to show `LabsSection` should **not** rely on `renderAds`](https://github.com/guardian/dotcom-rendering/blob/6b1c27d42c6019a7423c75fa322d6fce794da23d/dotcom-rendering/src/layouts/FrontLayout.tsx#L462)
