### ISSUE TITLE
Fix `most-read.json?_edition=EUR&dcr=true` endpoint

### ISSUE THREAD

**Issue by ioannakok** [guardian/dotcom-rendering#9553]
It is currently broken. It can be hit in the following edge case: A reader 
1. Is in the Europe edition
2. Visits an article without a section

https://github.com/guardian/dotcom-rendering/blob/2ef128c0251187cf5cb910c4d8ea9f8f939658f5/dotcom-rendering/src/components/MostViewedFooterData.importable.tsx#L31-L33

We haven't found an article yet that does not have a section so this is not likely to affect many readers.

**Comment by arelra** [comment]
Original post from Mariot:

https://chat.google.com/room/AAAAG9rU0m0/q8w3fX4P1Ao/

**Comment by ioannakok** [comment]
1. DCR [makes a request](https://github.com/guardian/dotcom-rendering/blob/61a6c51e9cc57f1f04cad70ef569c0efe752cd18/dotcom-rendering/src/components/MostViewedFooterData.importable.tsx#L34 ) to https://api.nextgen.guardianapps.co.uk/most-read/[sectionId].json?_edition=EUR&dcr=true
2. Request hits [/most-read/*path.json](https://github.com/guardian/frontend/blob/main/onward/conf/routes#L30) in onward app
3. The controller [fetches the most popular content from the `MostPopularAgent`](https://github.com/guardian/frontend/blob/main/onward/app/controllers/MostPopularController.scala#L55).
4. The `MostPopularAgent` [refreshes its cache with most viewed data](https://github.com/guardian/frontend/blob/85fccaf6d3489c972437afe5a28074e5733eece8/onward/app/feed/MostPopularAgent.scala#L98) from CAPI. 
5. We pass the edition 

https://github.com/guardian/frontend/blob/85fccaf6d3489c972437afe5a28074e5733eece8/onward/app/feed/MostPopularAgent.scala#L81-L87

**Comment by ioannakok** [comment]
[26830](https://github.com/guardian/frontend/pull/26830)
