### ISSUE TITLE
"Suppress related content" not working

### ISSUE THREAD

**Issue by ioannakok** [guardian/dotcom-rendering#9554]
See discussion [here](https://groups.google.com/a/guardian.co.uk/g/dotcom.platform/c/_7n2xslyPYQ)

Go to Composer > Furniture tab (top left corner) > Scroll down to the Filters

<img width="400" src="https://github.com/guardian/dotcom-rendering/assets/19683595/61d42065-fedb-4799-9687-7493bb993965">

"Suppress related content" doesn't seem to be working

**Comment by shesah** [comment]
don't think we will investigate this further as the original issue was resolved via an Ophan solution and this issue is not deemed a priority
