### ISSUE TITLE
Use Partner Code in calls to Accuweather $$$

### ISSUE THREAD

**Issue by alinaboghiu** [guardian/dotcom-rendering#9561]
From the email thread: 

"As part of your API Account with linking opportunities, we are happy to share your authorized Partner Code with our APIs. When used properly, your Partner Code will help appropriately attribute your end-user-directed traffic on AccuWeather.com. 

Partner Code: web_guardian_adc

[Quick Start Guide](http://apidev.accuweather.com/developers/api-quick-start-guides)

[Examples](http://apidev.accuweather.com/developers/partner-code)

Please review the Quick Start Guide and noted examples to see how to properly append your assigned partner code to the “Deep Links” provided in specific API responses."

**Comment by shesah** [comment]
@alinaboghiu we are not what this is and why we need to do it (what is the value?) is it a requirement by Accuweather or is it a nice to have that would give us some additional functionality?

**Comment by shesah** [comment]
One we can discuss with the team in a planning session to understand effort.
