### ISSUE TITLE
Support darkmode on the auto filter button bank

### ISSUE THREAD

**Issue by abeddow91** [guardian/dotcom-rendering#9572]
Current filter appearance:

| Light mode | Dark mode |
| ---------- | --------- |
| ![light] | ![dark] |

[dark]: https://github.com/guardian/dotcom-rendering/assets/43961396/ee95556a-189c-48e6-8b1e-4ecbcbdc6434
[light]: https://github.com/guardian/dotcom-rendering/assets/43961396/a0b938eb-f2a9-4a51-b374-e274ea271985

Need designs for dark mode

**Comment by abeddow91** [comment]
@HarryFischer to provide designs as this component was previously web only

**Comment by JamieB-gu** [comment]
Closing in favour of #12025.
