### ISSUE TITLE
Darkmode - Liveblog rich links

### ISSUE THREAD

**Issue by sophie-macmillan** [guardian/dotcom-rendering#9622]
Note: Liveblogs are not currently a priority

**Cards**
| AR | DCAR |
|--------|--------|
| <img width="700" alt="image" src="https://github.com/guardian/dotcom-rendering/assets/26366706/81a03ffe-4e52-4441-85f6-f2996db5b237"> | <img width="700" alt="image" src="https://github.com/guardian/dotcom-rendering/assets/26366706/f2635c81-15c1-4e26-b142-cd87142fd4d9"> |

**Comment by JamieB-gu** [comment]
Fixed in #9683.
