### ISSUE TITLE
We should only show the related content at the bottom of Apps articles in DCAR

### ISSUE THREAD

**Issue by sophie-macmillan** [guardian/dotcom-rendering#9631]
Apps Rendering only has the related content and the apps footer rendered
<img width="847" alt="image" src="https://github.com/guardian/dotcom-rendering/assets/26366706/bcb4ce56-5d6b-4eb9-97f1-e7aefa262dfe">

DCAR renders a bunch of stuff - most of which doesn't support dark mode
<img width="466" alt="image" src="https://github.com/guardian/dotcom-rendering/assets/26366706/ab4fec6e-f21a-4328-8811-2d3c1d98acc2">

**Comment by alinaboghiu** [comment]
I think we do want the extra content 
The latest designs should be the ones on this alignment card:  https://github.com/guardian/dotcom-rendering/issues/7390
