### ISSUE TITLE
Comments being cut off before the end

### ISSUE THREAD

**Issue by cemms1** [guardian/dotcom-rendering#9655]
There have been a number of reported issues with comments recently, where users are seemingly typing out long paragraphs which are being truncated after being submitted.

Here are some examples of this:
- https://www.theguardian.com/commentisfree/2023/nov/24/tories-power-grabs-government-britain-voters#comment-165479036
- https://www.theguardian.com/commentisfree/2023/nov/18/it-galls-the-french-but-english-has-become-europe-cultural-lingua-franca#comment-165393529
- https://www.theguardian.com/politics/live/2023/jul/20/byelections-conservatives-labour-rishi-sunak-keir-starmer-uk-politics-latest-news#comment-163623840

It is not known exactly why this happens and as such we cannot know whether it is a platform (web/apps) issue or an API (identity) issue.

[Email thread here](https://groups.google.com/a/guardian.co.uk/g/dotcom.platform/c/mKRNS_K45Qo)

**Comment by mxdvl** [comment]
Unable to reproduce… @georgeblahblah to edit this comment with more details!
