### ISSUE TITLE
Dark mode - Visual review of articles pre beta release

### ISSUE THREAD

**Issue by cemms1** [guardian/dotcom-rendering#9708]
Before releasing dark mode to beta, we should double check the whole page for a selection of DCAR articles and compare to web (for light mode comparison) and AR (for dark mode comparison)

We should raise tickets to address any major differences.

**Comment by ioannakok** [comment]
Went through [these articles](https://docs.google.com/document/d/10TDt7mVf4vhE5FHE0UfwwzYf8hrFFOAjIKISiLWUVKk/edit). Tasks have been added in #9110
