### ISSUE TITLE
Darkmode - Byline with multiple authors

### ISSUE THREAD

**Issue by ioannakok** [guardian/dotcom-rendering#9728]
word "and" should also be pillar.500

![image](https://github.com/guardian/dotcom-rendering/assets/19683595/a84883f7-6ae0-42cf-9e9a-4e54c1b7b335)

example article: https://www.theguardian.com/world/2020/may/07/revealed-the-secret-report-that-gave-ministers-warning-of-care-home-coronavirus-crisis

![image](https://github.com/guardian/dotcom-rendering/assets/19683595/ea39a48d-1e9c-43a7-a75d-e52db8053016)

https://www.theguardian.com/world/2020/mar/28/life-after-coronavirus-panic-buying-cocaine-drug-dealer-spaceman-therapist

**Comment by JamieB-gu** [comment]
This is what AR does. We're going to leave as is for dark mode beta release, but @HarryFischer please shout if you would like this changed at some point.
