### ISSUE TITLE
DarkMode - InteractiveAtomBlockElement

### ISSUE THREAD

**Issue by ioannakok** [guardian/dotcom-rendering#9738]
![image](https://github.com/guardian/dotcom-rendering/assets/19683595/0337a589-4a92-42ac-9bef-01e63b798e5c)

https://www.theguardian.com/world/2020/mar/31/view-from-nhs-staff-in-frontline-of-battle-against-coronavirus

![image](https://github.com/guardian/dotcom-rendering/assets/19683595/f60bf8e4-d416-4eb6-876f-bc42ae0498c6)

https://www.theguardian.com/world/2022/mar/17/russias-war-in-ukraine-complete-guide-in-maps-video-and-pictures

**Comment by JamieB-gu** [comment]
Fixed in #10212
