### ISSUE TITLE
Vertical slideshow: Currently looks broken in both AR and DCAR

### ISSUE THREAD

**Issue by ioannakok** [guardian/dotcom-rendering#9747]
https://www.theguardian.com/world/2020/sep/22/datablog-scale-200000-coronavirus-deaths-us
https://mobile.guardianapis.com/uk/rendered-items/world/2020/sep/22/datablog-scale-200000-coronavirus-deaths-us
https://www.theguardian.com/world/2020/sep/22/datablog-scale-200000-coronavirus-deaths-us?dcr=apps

#### DCR
<img width="1575" alt="image" src="https://github.com/guardian/dotcom-rendering/assets/19683595/a3234891-16cd-4929-96f4-c13af55d5100">

#### AR
<img width="1322" alt="image" src="https://github.com/guardian/dotcom-rendering/assets/19683595/b6255336-034a-4f26-88ca-d67cec82a0bf">

#### DCAR
<img width="1429" alt="image" src="https://github.com/guardian/dotcom-rendering/assets/19683595/7f248326-be82-4f3d-a3f1-0704f3077f0c">

**Comment by shesah** [comment]
Interactive atoms will be fix by scrolly articles

**Comment by shesah** [comment]
#9545 will fix ads being hidden problem. and we will try and deprecate interactive elements in the long term
