### ISSUE TITLE
Article text overflowing into ad

### ISSUE THREAD

**Issue by sophie-macmillan** [guardian/dotcom-rendering#9793]
We had the following report of the article text overflowing onto the ad in chrome.
I've asked for more details about browser version and device as I couldn't recreate this

https://www.theguardian.com/world/2023/dec/05/israel-faces-difficult-second-phase-of-war-with-fighting-in-north-and-south-gaza

![Image](https://github.com/guardian/dotcom-rendering/assets/26366706/6055b216-87f2-42e2-ae54-41ea6b3d491f)

**Comment by alinaboghiu** [comment]
Can't reproduce, please reopen with steps to reproduce if still an issue
