### ISSUE TITLE
DCR Deploy Failures

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#9846]
Several deploys have failed over the last few days due to `WaitForStabilization` check timeouts: the ELB has been a few instances short of the ASG by the time the timeout limit is reached.

**Comment by JamieB-gu** [comment]
A short term fix to prevent failures while we debug the issue might be to tweak the `secondsToWait` or `warmupGrace` autoscaling parameters, as suggested by @akash1810

**Comment by alinaboghiu** [comment]
Is there a way to identify the instance that is being considered unhealthy / not yet healthy? Perhaps the cloud init logs on that instance could shed some light

**Comment by arelra** [comment]
I've compared the current server bundle size to the size a month ago.

There is a small increase of ~300kB from 11.2MB to 11.5MB which might slow down instantiation slightly but it's not an increase that is immediately concerning.

The startup times reported in the syslog don't look concerning either:
```
Dec 12 15:08:46 ip-10-248-141-137 cloud-init[1262]: starting PROD server...
Dec 12 15:08:46 ip-10-248-141-137 cloud-init[1262]: NODE_ENV=production node dist/server.js
Dec 12 15:08:48 ip-10-248-141-137 cloud-init[1262]: Started production server on port 9000
Dec 12 15:08:48 ip-10-248-141-137 cloud-init[1262]: ready

```

**Comment by JamieB-gu** [comment]
- [ ] Get cloud init logs shipped to ELK
- [ ] Find out what's happened to DCR's application logs
- [ ] Find out how long it takes between instance startup and application startup (CloudWatch metrics or log lines? Maybe use SDK to check launch time and compare to current time)
- [ ] Look for patterns. Availability zone? Is it the only app in the account suffering from this? What about CODE?

**Comment by akash1810** [comment]
> Maybe use SDK to check instance launch time and compare to current time

The launch time might be available in the [instance metadata endpoint](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instancedata-data-retrieval.html). This'll mean we wouldn't need to make an outgoing call to AWS, and add the relevant IAM permissions too.

**Comment by JamieB-gu** [comment]
It seems the same problem has now started to affect AR (ELB/ASG mismatch), despite it being a different application that doesn't share much in the way of code with DCR (aside from having similar dependencies).

**Comment by abeddow91** [comment]
@alinaboghiu to continue this discussion in the engineering channel to work out next steps.

**Comment by JamieB-gu** [comment]
Temporary mitigation in #9992.

**Comment by alinaboghiu** [comment]
We suspect it could be one of the AMI patches (possibly related cloud-init lib). We're hoping the next cloud-init patch will fix it. But we've not done anything, we're just monitoring.

**Comment by ioannakok** [comment]
[Related message](https://chat.google.com/room/AAAAPTsU18A/nn404_wnPqY/) by @cemms1 in chat

**Comment by shesah** [comment]
need to pair up with @arelra and/or @ashishpuliyel
