### ISSUE TITLE
Byline Job Titles Incorrectly Appearing On The Same Line

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#9876]
On analysis articles, if the piece only has a single contributor, the byline is meant to include the name of the author on one line and the job title (if present) on another. However, in some cases they're both appearing on the same line, one after another.

| | Piece | Screenshot |
| - | - | - |
| Correct | https://www.theguardian.com/environment/2023/dec/13/what-the-cop28-agreement-says-and-what-it-means | ![byline] |
| Incorrect | https://www.theguardian.com/environment/2023/dec/11/the-climate-crisis-will-amplify-the-uks-existing-health-inequalities | ![byline-inline] |
| Incorrect | https://www.theguardian.com/australia-news/2023/dec/13/labor-gaza-ceasefire-policy-stance-un | ![byline-inline-2] |

[byline-inline]: https://github.com/guardian/dotcom-rendering/assets/53781962/55cb2044-9d8d-460e-adcd-d39773f3f440
[byline]: https://github.com/guardian/dotcom-rendering/assets/53781962/78640549-9b96-4ece-9ea4-9f71649e4344
[byline-inline-2]: https://github.com/guardian/dotcom-rendering/assets/53781962/66445620-a8c5-4ea6-8224-23d206fcb713

## Why?

The styles that wrap the job title onto a new line can be found here:

https://github.com/guardian/dotcom-rendering/blob/9905ceb642bb20c2c6c21c92129e269c46fd994f/dotcom-rendering/src/components/HeadlineByline.tsx#L104-L107

and are applied here only if the piece has a single contributor:

https://github.com/guardian/dotcom-rendering/blob/9905ceb642bb20c2c6c21c92129e269c46fd994f/dotcom-rendering/src/components/HeadlineByline.tsx#L208-L209

However, the current logic says a piece only has a single contributor if the byline does not include the word "and":

https://github.com/guardian/dotcom-rendering/blob/9905ceb642bb20c2c6c21c92129e269c46fd994f/dotcom-rendering/src/lib/byline.ts#L16-L19

The examples above have the word "and" in the job title:

- "Health and inequalities correspondent"
- "Foreign affairs and defence correspondent"

so this logic assumes there's more than one contributor, the additional styles do not get applied, and the name and job title appear on the same line.

## Possible Solution

AR doesn't suffer from the same problem because it uses CAPI's `bylineHtml` field, which tends to separate the different parts of the byline into different elements.

https://github.com/guardian/dotcom-rendering/blob/9905ceb642bb20c2c6c21c92129e269c46fd994f/apps-rendering/src/components/Byline/Byline.defaults.tsx#L83-L87

DCR doesn't currently have access to this version of the byline because it's not passed through from `frontend`. One option would be to update the frontend models to include this and use it instead.

**Comment by paperboyo** [comment]
DCAR should defo get access to much betterer `bylineHtml`. But not sure everything can be 100% sorted (?):

<img width="315" alt="image" src="https://github.com/guardian/dotcom-rendering/assets/6032869/750dd7af-8912-4a73-ad15-8870e02c062a">

[[URL](https://www.theguardian.com/world/2023/dec/12/donald-tusk-vision-progressive-poland-heart-of-eu)]

Central Production will be helpful (as always!) in knowing about and finding all the possible values for that field…

**Comment by georgeblahblah** [comment]
An example of a byline with two contributors: https://www.theguardian.com/uk-news/2024/apr/03/levelling-up-what-has-the-government-spent-and-where

**Comment by georgeblahblah** [comment]
I think the data model we get from CAPI (even if we pass the Byline HTML field to DCR) doesn't support a full solution to this issue, because any solution just exposes a different edge case. Given this is fairly low impact I'm inclined to close it.

The variants of byline/contributor combinations I've discovered are:

1 Sole contributor (`<a>A Name</a>`)
1 Sole contributor w/ job (`<a>A Name</a> Health and wellness correspondent`)
1 Multiple contributor (`<a>A Name</a> and <a>Another Name</a>`)
1 Contributor + byline (`<a>A Name</a> and Another Name`)
1 Byline (`A Name`)
1 Multiple byline (`A Name and Another Name`)
1 I do not know if it's possible to have a byline (but not be a contributor) and a "job" e.g `A Name Health and wellness correspondent`
